adobe/spectrum-web-components

- packages/top-nav/src/TopNav.ts
- packages/top-nav/src/TopNavItem.ts
- packages/top-nav/test/top-nav.test.ts
Add label recalculation in Top Nav Item to match Tab so that indicator can be updated as needed.
- fixes #2500
1. Go [here](https://top-nav--spectrum-web-components.netlify.app/storybook/?path=/story/top-nav--selected)
2. Inspect the Top Nav Item with the content "Page 3"
3. Change its `innerHTML`
4. See that the indicator is updated.
1. Go here
2. Do this …
> fix(top-nav): match indicator management strategy from Tabs

- .circleci/config.yml
- packages/table/src/Table.ts
- packages/table/src/TableBody.ts
- packages/table/src/table-body.css
- packages/table/src/table.css
- packages/table/test/table.test.ts
- packages/table/test/virtualized-table.test.ts
- test/visual/test.ts
- use Mutation Observer over Resize Observer as most Tables don't actually resize
- add extra delay to the tests to ensure we test the after render context
- test styled Tables
- remove the default `overlay: auto` when not measuring in such a way as the scroll
- update VRT cache
- store a VRT cache against the revision number ALWAYS (help establish a cache on flaky subjects)
- remove the Table Body clearing code, it spun up an error in the tests
- refs #290
1. It's tests, mainly
-   [ ] If my change required …
> Table Testing Updates

- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay-trigger-sync.test.ts
- packages/overlay/test/overlay-trigger.test.ts
- packages/picker/test/index.ts
Move `Escape` listener to `keydown` to match native `<modal>` interaction.
- fixes #1844
1. With updated unit tests.
> fix(overlay): move "escape" listener to "keydown"

- packages/number-field/src/NumberField.ts
- packages/slider/src/Slider.ts
- packages/slider/test/slider-editable.test.ts
- fixes #2543
1. Go to Storybook, to editable slider: https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/slider--editable
2. Click the number input field, and mouse scroll to change the value
3. Slider on the left of the number input is inert
1. Go to Documentation site, to editable slider: https://chitiga-daniel-editable-slider-fix--spectrum-web-components.netlify.app/components/slider/
2. Click the number input field, and mouse scroll to change the value
3. Slider on the left of the number input is changing according to the value inside the number input
-   [ ] Breaking change (fix or feature …
> Fix Slider component scroll number-field to update the slider value

- .circleci/config.yml
- packages/tabs/README.md
- packages/tabs/package.json
- packages/tabs/src/Tabs.ts
- packages/tabs/src/tabs.css
- packages/tabs/stories/tabs.stories.ts
- projects/documentation/src/components/styles.css
- add support for `quiet`, `compact`, and `emphasized` to the `direction="vertical|vertical-right"` variants
- update stories to include this
- update documentation to include this
- fixes #2552
1. VRTs
> fix(tabs): add "quiet", "compact", and "emphasized" "direction=vertical"

- .circleci/config.yml
- packages/bundle/elements.ts
- packages/dialog/dialog-base.md
- packages/dialog/exports.json
- packages/dialog/package.json
- packages/dialog/sp-dialog-base.ts
- packages/dialog/src/DialogBase.ts
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/stories/dialog-base.stories.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/stories/dialog.stories.ts
- packages/dialog/stories/index.ts
- packages/dialog/test/dialog-base.test.ts
- packages/dialog/test/dialog-wrapper.test.ts
- packages/modal/src/modal.css
- packages/theme/README.md
- projects/story-decorator/src/StoryDecorator.ts
- test/visual/test.ts
- web-test-runner.utils.js
Abstract a Dialog Base element down from the Dialog Wrapper element.
- accepts a slotted `<sp-dialog>` element
- cedes management of button content to consuming developers
- surfaces as `renderDialog` method that is `protected` for easier extending
I've not yet written documentation for this, wanted to get thoughts on what might be useful there before I did.
- fixes #1864
1. Go [here](https://dialog-base--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-base--slotted)
2. See that the `<sp-dialog>` content is not locked within the shadow root of the `<sp-dialog-base>` element as it is in the `<sp-dialog-wrapper>` element …
> Abstract down a Dialog Base for more flexible Dialog patterns

- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/test/overlay-trigger-hover.test.ts
- packages/tooltip/src/Tooltip.ts
- packages/tooltip/test/tooltip.test.ts
Due to https://bugs.chromium.org/p/chromium/issues/detail?id=1363632 we need to use JS to manage pointer events and their interaction between the trigger and the content of an overlay, particularly when that content is a tooltip.
TODO:
- fixes #2573
1. Go [here](https://tooltip-enter--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--default)
2. Slowly enter the button with your pointer device from the bottom center, see that the tooltip is opened correctly.
1. Go [here](https://tooltip-enter--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tooltip--self-managed&args=placement:bottom;offset:0)
2. Close the tooltip
3. Slowly enter the button with your pointer device from the bottom center, see that …
> fix: special case the possibility of leaving an overlay trigger by entering its overlay content

- .circleci/config.yml
- packages/styles/tokens/express/global-vars.css
- packages/styles/tokens/spectrum/global-vars.css
- packages/switch/README.md
- packages/switch/package.json
- packages/switch/src/Switch.ts
- packages/switch/src/spectrum-config.js
- packages/switch/src/spectrum-switch.css
- packages/switch/stories/switch-sizes.stories.ts
- packages/switch/stories/switch.stories.ts
- scripts/spectrum-tokens.js
- web-test-runner.config.js
- yarn.lock
Adds a beta version of the new Switch component.
Uses beta release, hold for full release.
CSS JIra. https://jira.corp.adobe.com/browse/CSS-100 Implement%20Switch%20Core%20Tokens
CSS-100) #1496
https://github.com/adobe/spectrum-css/pull/1496 feat(switch)!: migrating switch to core-tokens (CSS-42, CSS-100) #1496
Core Tokens migration in Spectrum CSS.
Also breaking change as we are adding t-shirt sizing as well. 
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] Chore (minor updates related to the tooling or maintenance of the …
> refactor(switch): use core tokens

- .circleci/config.yml
- packages/search/src/search.css
- packages/search/stories/search.stories.ts
Update the end of line padding to prevent the text from falling behind the clear button when typing a long search term.
- fixes #2574
1. Go [here](https://206c63a096c098a7218cbf9156aae66f--spectrum-web-components.netlify.app/review/)
2. Review the addition across themes.
- …
> fix(search): prevent overflow content from going behind clear button

- tools/grid/src/Grid.ts
- tools/grid/src/GridController.ts
- tools/grid/stories/grid.stories.ts
Support customization of `padding` in the Grid
Note:
The Storybook won't responsively update when the `padding` is changed in the UI due to https://github.com/lit/lit/issues/3285, but update `gap` and previously send `padding` updates will take.
- fixes #2554
1. Go [here](https://grid-padding--spectrum-web-components.netlify.app/storybook/?path=/story/grid--sized)
2. Update `gap` and `padding` in the Story UI
3. See above note about responsivity... …
> fix: add support for "padding" attribute

- packages/dialog/src/Dialog.ts
- packages/dialog/test/dialog.test.ts
Ensure that late added content does not accidentally receive already applied IDs when associating it to its parent `sp-dialog` element.
- fixes #2486
1. Go [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/12976/workflows/25d21100-1c1d-41bb-aa2f-85f6a9f4ad6d)
2. See that the new test passes
- …
> fix: prevent reuse of applied IDs when associating Dialogs to their content

- packages/button/src/ButtonBase.ts
- packages/card/src/Card.ts
- packages/menu/src/MenuItem.ts
Ensure all `pointerup` listeners are matched with a `pointercancel` listener in case the visitor proceeds to scroll while the pointer is down.
1. Go [here](https://pointercancel--spectrum-web-components.netlify.app/) on iOS
2. Open one of the theme pickers
3. Touch on of the Menu Items and "swipe"
4. You'll see the page scroll (captured for fixing in #2536)
5. Lift your finger on a part of the page that IS NOT the Menu Item you started on
6. See that the "active" (looks a little like hover) state is removed.
7. Compare to [production](https://opensource.adobe.com/spectrum-web-components/index.html)
-   [x] My code follows …
> fix: match "pointerup" listeners with "pointercancel" for full coverage

- projects/documentation/scripts/build-search-index.js
Prevent non-project package inclusion in the autocomplete list for search.
1. Go [here](https://docs-search--spectrum-web-components.netlify.app/)
2. Type "doc" into the search interface
3. See that "Prettier" and "Glob" are not offered as options in the auto complete.
- …
> docs: exclude non-project readmes from docs search

- README.md
- package.json
- scripts/update-spectrum-css.js
By default, use semver to upgrade spectrum-css (^5.0.0 -> 5.0.1, but ^5.0.0 !-> 6.0.0).
- https://github.com/adobe/spectrum-web-components/pull/2643
Non-breaking changes can be done regularly & perhaps even automated, whereas human intervention is normally required for breaking changes.
- Run `yarn update:spectrum-css` on main
- See that it provides breaking updates to many components
- Run `yarn update:spectrum-css:nonbreaking` on this branch
- See that it only updates 'card' and 'tabs', which are the only non-breaking css changes
- Run `yarn update:spectrum-css` on this branch
- See that it has the same behavior as main (update everything to latest)
-   [ ] …
> add semver resolution to update-spectrum-css script

- packages/theme/src/Theme.ts
Don't let `theme="express"` express a Dev Mode warning incorrectly. Previously, we were looking for `express-express` instead of `express`.
1. Run `yarn storybook` locally
2. Switch the the `express` theme
3. See that Dev Mode doesn't warn you about missing Theme modules
- …
> fix: correct theme calculation for triggering warnings

- packages/iconset/README.md
- packages/iconset/src/iconset.ts
- packages/iconset/test/iconset.test.ts
Begin deprecating Iconsets:
- https://opensource.adobe.com/spectrum-web-components/components/iconset/
- https://opensource.adobe.com/spectrum-web-components/components/icons/
This will post deprecation notices to Dev Mode and the docs site in advance of removing these packages in favor of UI Icons and Workflow Icons. This also points to a longer term need to productionize the work going into #2407 or similar so that it is more clear how downstream projects can make/manage/deliver their own icon content.
Begin removal of contradictory packages/documentation to ease consumption of the library. cc: @e111077 …
> docs: begin Iconset deprecation process

- .circleci/config.yml
- packages/action-button/README.md
- packages/action-button/src/ActionButton.ts
- packages/action-button/src/action-button.css
- packages/action-button/src/spectrum-action-button.css
- packages/action-button/src/spectrum-config.js
- packages/action-button/stories/action-button-black-quiet.stories.ts
- packages/action-button/stories/action-button-black.stories.ts
- packages/action-button/stories/action-button-emphasized-quiet.stories.ts
- packages/action-button/stories/action-button-emphasized.stories.ts
- packages/action-button/stories/action-button-quiet.stories.ts
- packages/action-button/stories/action-button-standard.stories.ts
- packages/action-button/stories/action-button-white-quiet.stories.ts
- packages/action-button/stories/action-button-white.stories.ts
Adds `size="xs"` to `<sp-action-button>`.
1. Go [here](https://action-button-xs--spectrum-web-components.netlify.app/components/action-button/#sizes)
2. See that there are `size="xs"` buttons
1. Go [here](https://action-button-xs--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-button-static-black-quiet--xs)
2. Visit all of the Action Button variants
3. See that there are `size="xs"` buttons.
- …
> fix(action-button): add support for XS t-shirt size

- packages/number-field/src/NumberField.ts
- packages/number-field/test/helpers.ts
- packages/number-field/test/inputs.test.ts
- packages/number-field/test/number-field.test.ts
- packages/slider/src/SliderHandle.ts
- packages/slider/test/slider.test.ts
- packages/theme/src/Theme.ts
- tools/reactive-controllers/package.json
- tools/reactive-controllers/src/LanguageResolution.ts
- tools/reactive-controllers/test/helpers.ts
- centralize language resolution tooling for reuse
- ensure the use of `unsubscribe` rather than event based contract nullification so that memory can be correctly released
1. The tests pass
1. Go [here](https://resolved-language--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--default)
2. Duplicate the Slider in the story a bunch of times within the `<sp-story-decorator>` element
3. Find the `<sp-theme>` element within the Decorator
4. Check the value of `_contextConsumers.size` on the Theme element
5. Delete some of the `<sp-slider>` elements. 
6. See that `_contextConsumers.size` has decreased by the number of Slider you have deleted
-   [x] I have signed …
> fix: convert the langage resolution workflow to a Reactive Controller

- .circleci/config.yml
- packages/action-menu/stories/action-menu.stories.ts
- packages/menu/src/menu.css
Correct width application to `sp-menu` elements when opened within `sp-action-menu`s.
- fixes #2555
1. Go [here](https://7d851870bc1c12eade17f759b2dbb828--spectrum-web-components.netlify.app/review/#ActionMenuStories/groups.png)
2. Review the VRT updates/additions
-   [x] All …
> fix(menu): ensure that Groups in Action Menus are rendered with the correct width

- .circleci/config.yml
- packages/overlay/stories/overlay.stories.ts
- test/visual/create.js
- test/visual/test.ts
Adds new configuration to a story that allows it to be skipped at VRT time:
```
export const story = () => html`...`;
story.swc_vrt = {
skip: true,
};
```
- fixes #2611
Not all stories are exciting enough to capture as VRTs.
1. Go [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/13303/workflows/850b9511-fbd8-421d-947e-db95ec783ec9/jobs/228666)
2. See that the VRT output is one less image than previously.
-   [x] Tooling …
> test: allow Stories to be skipped at VRT time

- .circleci/config.yml
- packages/picker/src/picker.css
Prevent icons in the Picker trigger from appearing too high vertically.
- fixes #2649
1. Go [here](https://icon-picker--spectrum-web-components.netlify.app/storybook/?path=/story/picker--icons)
2. See the icon is vertically centered
1. Go [here](https://icon-picker--spectrum-web-components.netlify.app/storybook/?path=/story/picker--icons-only)
2. See the icon is vertically centered
1. Go [here](https://icon-picker--spectrum-web-components.netlify.app/storybook/?path=/story/picker--icons-none)
2. See there is no icon
-   [ ] …
> fix: style icons in Picker correctly

- .circleci/config.yml
- packages/dialog/src/DialogBase.ts
- packages/dialog/test/dialog-base.test.ts
- packages/dialog/test/dialog-wrapper.test.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay-trigger-hover.test.ts
- packages/shared/src/focusable.ts
- packages/tray/src/Tray.ts
- test/visual/test.ts
- prevent N number of `Escape` pressed or "close" button clicks from breaking the overlay that is being managed by those interactions
- ensure "open" animations are being run in Firefox
- turn tests in this are back on for Firefox
- refactor work workflows for simplicity
- remove test time workaround for multiple overlay open/closes
- fixes #2646
1. Go [here](https://double-close--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-base--slotted)
2. Once the dialog is open, quickly press `Escape` N number of times.
3. See that the dialog is closed
4. Click the "Toggle Dialog" button
5. See that the dialog is opened.
6. Repeat 2-5 N number of times.
1. Go [here](https://double-close--spectrum-web-components.netlify.app/storybook/?pat …
> fix: correct the relationship between overlayWillCloseCallback and phased animations

- packages/split-view/src/split-view.css
Allow un-canceled touch interaction in mobile.
@pfulton I know this was a contribution to CSS, but this feels like an addition that could be made there to support more users of your output?
1. Go [here](https://split-view--spectrum-web-components.netlify.app/storybook/?path=/story/split-view--horizontal-resizable) in a Chrome touch environment, can be emulated by Dev Tools
2. Drag the split view handle
3. See that the handle moves continuously
-   [x] I …
> fix(split-view): prevent touch-action on handle for delivery in mobile

- .circleci/config.yml
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/field-label/package.json
- packages/field-label/src/field-label.css
- packages/field-label/src/spectrum-field-label.css
- packages/field-label/stories/field-label.stories.ts
- packages/styles/express/core-global.css
- scripts/spectrum-tokens.js
- yarn.lock
Adds a beta version of the migrated FieldLabel component.
Uses beta release, hold for full release.
CSS: https://github.com/adobe/spectrum-css/pull/1476 feat(fieldlabel)!: core-tokens implementation (CSS-102) #1476
Jira: https://jira.corp.adobe.com/browse/CSS-102 
-
CSS Core-tokens migration
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] I have signed the [Adobe Open Source …
> refactor(field-label): use core tokens

- .circleci/config.yml
- packages/swatch/package.json
- packages/swatch/src/spectrum-swatch-group.css
- packages/swatch/src/spectrum-swatch.css
- scripts/spectrum-tokens.js
- yarn.lock
- Swatch group density swatch gap differences e.g. 
There are unexpected changes in SWC due to HTML and CSS changes to the Swatch component in CSS including:
- `is-image` class for transparent backgrounds on Image, Gradient, and Mixed Value swatches
- selected swatch states do not work on all variants in SWC (I have not investigated this yet)
- Swatch border relies on hardcoded tokens.
Here is one example:
I hard coded this token since I couldn't find one to use: https://github.com/adobe/spectrum-css/pull/1501/files#diff-cc50ec1bfa218207591ac782352b4f5894b71d81450b2c74fa9004ca1dfca665R22
-
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] New feature (non-breaking change which adds …
> refactor(swatch): use core tokens

- .circleci/config.yml
- packages/slider/src/SliderHandle.ts
- packages/slider/test/slider.test.ts
When not supplied, value will now be set to halfway between min and max as opposed to `10` as it has been previously.
- fixes #1788
1. Go [here](https://slider-default--spectrum-web-components.netlify.app/components/slider/#standard)
2. See the default value of the documented sliders is `50` and not `10`.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)> …
> feat(slider): update "value" default to match browser native range input

- packages/color-area/src/ColorArea.ts
Announce deprecation of the `label` attribute/property in Color Area
- refs #1802
1. Run Storybook locally
2. Visit https://localhost:8000/?path=/story/color-area--default
3. Inspect the `sp-color-area` element
4. Give it a `label` attribute, e.g. `label="Special label"`
5. See the Dev Mode warning.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/ …
> chore: deprecate the "label" property

- packages/number-field/src/NumberField.ts
Allow `.` button in iPhone virtual keyboard.
This leveraged the `resolvedOptions` of the Number Formatter, as seen in https://github.com/adobe/react-spectrum/blob/7cebb4eea31f383f1eec06cc53a7909f8736f66a/packages/%40react-aria/numberfield/src/useNumberField.ts#L148-L149, which seems to default to `3` if not set. Does this precipitate adding information around this to the documentation so that consumers know how to actively manage this keyboard input? cc: @wyanghz1
- fixes #2674
1. On an iPhone
2. Go [here](https://number-field-decimal--spectrum-web-components.netlify.app/components/slider/#editable)
3. Attempt to edit the text of the slider input
4. See that the `.` key is present
-   [x] I have signed the …
> fix: correct the origin on "maximumFractionDigits" when deciding "inputMode"

- .circleci/config.yml
- packages/badge/README.md
- packages/badge/package.json
- packages/badge/src/Badge.ts
- packages/badge/src/badge.css
- packages/badge/src/spectrum-badge.css
- packages/badge/src/spectrum-config.js
- packages/badge/stories/badge.stories.ts
- packages/badge/test/badge.test.ts
- packages/styles/express/spectrum-scale-large.css
- packages/styles/express/spectrum-scale-medium.css
- packages/styles/spectrum-scale-large.css
- packages/styles/spectrum-scale-medium.css
- scripts/spectrum-tokens.js
- yarn.lock
This updates the Badge component to use core tokens
Uses beta release. Hold for full release.
-
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] I have …
> refactor(badge): use core tokens

- tools/styles/README.md
While working on another issue, I noticed that the import statement for the package was for npm instead of yarn, and I noticed a few typos that I wanted to fix. I also added commas because I love them.  …
> docs[styles]: correct typos and update import statement

- packages/tabs/src/Tabs.ts
- packages/tabs/src/tabs.css
On Safari, the tab offsetLeft and offsetTop were not working properly. This fix instead calculates the tab indicator position based off its location relative to the `sp-tabs` wrapping component.
#2629
-
Tab indicators were not behaving properly on Safari.
Verified my changes by opening the storybook on both Safari and Chrome. Ran unit tests.
-   [x] My code follows the …
> fix: tab indicator positioning

- tools/shared/src/like-anchor.ts
I couldn't remember whether or not `[label]` was applied visually, & a reminder from the docs would have helped.
-   [X] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-component …
> docs: note that LikeAnchor .label is not visually presented

- packages/overlay/src/overlay-stack.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-trigger-hover-click.test.ts
Prevent clicks within ancestor overlays from closing those ancestor overlays.
- fixes #2693
1. Go [here](https://overlay-stack-mangement--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--deep)
2. Click the first buttons to open the Popover
3. Hover the first button in the Popover to open the Tooltip
4. Click the button associated to the Tooltip
5. See that the Popover is still open …
> fix: keep parent overlays open when not closing child hover overlays

- .circleci/config.yml
- packages/slider/src/slider.css
- packages/slider/stories/slider.stories.ts
Allows sliders not to change width when their label takes up their entire width and then have subsequent value changes.
1. Go [here](https://slider-editable--spectrum-web-components.netlify.app/storybook/?path=/story/slider--in-popover)
2. Change the value of the slider
3. See its width not change.
-   [x] I have added …
> fix(slider): add less visually effectacious style to the slider output when editable

- packages/number-field/src/NumberField.ts
- packages/slider/src/SliderHandle.ts
- packages/slider/stories/slider.stories.ts
- tools/reactive-controllers/src/LanguageResolution.ts
- Language Resolver: ensure language resolution updates are responsive to the element owning the language resolver
- Number Field: normalize device specific input to page specific language when using the iOS `decimal` keyboard
- Add a demo
- fixes #2709 
International usage
*Docs Site*:
1. using iOS
2. region set to `Romania`
3. Go to https://language-resolution-fix--spectrum-web-components.netlify.app/components/number-field/
4. Open dev tools and change lang attribute in `<html>` to `ro-RO`
- We do not current bind to non-custom element sources of language reactively, so this will not change the language of the SWC content in the page. We could take a separate feature request to do so in an opt in manner. For now, I'll list the expected behavior based no today's feature set, and then …
> fix: ensure reactivity of resolved language

- .circleci/config.yml
- packages/dialog/dialog-wrapper.md
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/test/dialog-wrapper.test.ts
DialogWrapper shouldn't show a divider if there's no headline
fixes #2699
3 new unit tests. visual confirmation of expected behavior using storybook.
See Storybook cases:
DialogWrapper:Wrapper With Headline
DialogWrapper:Wrapper With Headline No Divider
DialogWrapper:Wrapper No Headline
-   [ ] If my change required …
> fix(dialog): don't show DialogWrapper divider when there's no headline

- packages/field-label/package.json
- packages/field-label/src/FieldLabel.ts
- packages/field-label/test/field-label.test.ts
- tools/reactive-controllers/README.md
- tools/reactive-controllers/element-resolution.md
- tools/reactive-controllers/package.json
- tools/reactive-controllers/src/ElementResolution.ts
- tools/reactive-controllers/test/element-resolution.test.ts
- add some test coverage ignore markers
- add the Element Resolution Controller
- resolves an element in the same DOM tree from a selector
- always resolve the first element of that selector regardless of DOM/attribute mutations
- applies the controller to Field Label which previously has a one shot element resolution method
Prepares this functionality to be leveraged in overlay trigger interactions
1. Go [here](https://element-resolver--spectrum-web-components.netlify.app/storybook/?path=/story/field-label--standard)
2. Futz with the DOM and attributes of the story dom
3. Change the `for` value on the Field Label
4. Change the `id` value on the Textfield
5. Move the Textfield around
6. Add/remove a different Textfield with the same ID
7. See that the element …
> Add element resolver for keeping a live reference to an element in the same DOM tree

- packages/link/README.md
Swap docs to `static` from `over-background`.
> docs: update link docs to "static" from "over-background"

- projects/documentation/package.json
- projects/documentation/scripts/copy-component-docs.js
Rebuild docs site on README.md change while viewing docs site locally.
- fixes #2730
1. Run the docs site locally
2. Change some content in a README.md file
3. See the changes happen live while the docs site is running.
-   [ ] I have added tests to cover my …
> docs: watch README while running docs site locally

- projects/documentation/content/index.md
- projects/documentation/src/components/styles.css
Add accessibility content to the home page of the documentation site:
> **Accessible by default**
> Developed with existing and emerging browser specifications in mind to deliver/maintain a quality experience whether using a screen reader, keyboard navigation, and/or high contrast colors.
- fixes #2615 
-   [ ] Documentation …
> docs: add a11y information

- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
- projects/documentation/src/components/side-nav-search.ts
With the advent of the `popover` attribute, the `popover` property appears to reflect, so in preparation, let's rename some properties so that we don't accidentally create a popover when we don't need/want one.
1. Go [here](https://popover-prepare--spectrum-web-components.netlify.app/) in a browser with the "Experimental Web Platform features" flag turned on
2. Open a Picker/the search nav in the docs site
3. See that it opens as expected
4. Previously this would attempt to open a popover
-   [ ] If my …
> refactor: prepare for the presence of the "popover" attribute/property in the platform

- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/active-overlay.css
- packages/tray/src/tray.css
Reduce manual measurement of the layout by leveraging `dvh` with a fallback to `vh`.
- fixes #2772
1. Go [here](https://overlay-container--spectrum-web-components.netlify.app/components/dialog-wrapper/)
2. Make the browser very short
3. Open the overlay in the docs content
4. Expand the hight of the browser
5. See that the overlay remains centered, vertically
1. Go [here](https://overlay-container--spectrum-web-components.netlify.app/), in iOS
2. Play with the Pickers and the Dialogs to make sure they display correctly …
> fix: leverage "dvh" rather than measured screen height

- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/stories/overlay.stories.ts
Allow `Overlay.update` to be reacted to without closing the overlay.
- fixes #2766
1. Go [here](https://overlay-update--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--updating)
2. Open the overlay
3. Update the trigger location
4. See that across multiple moves that overlay is NOT closed
-   [ ] I have …
> fix: ensure Overlay.update bypasses the auto close mechanism

- projects/documentation/src/components/code-example.ts
Ensure theme specific style application in code samples.
- fixes #2793
1. Go [here](https://docs-code-themes--spectrum-web-components.netlify.app/)
2. See the code sample highlighting
3. Switch the theme color
4. See the code sample highlighting
5. Experience being able to read the code in all themes.
-   [ ] I have added …
> docs: correct application of themed code styling

- packages/table/exports.json
- packages/table/package.json
`packages/table/exports.json` was missing the export for `elements.js`. This PR adds `elements.js` to [packages/table/export.json](https://github.com/adobe/spectrum-web-components/commit/30015b83d18d63498f17f9fea703bb4c39d06f59#diff-5312b5edfc776cff2fecce8f948a39efe2020fbeb289df251fa15ccc753ff6a4R3).
none.
When using `<sp-table>` and trying to `import '@spectrum-web-components/table/elements.js'` you will get `Missing "./elements" export in "@spectrum-web-components/table" package`
It has not been tested. I'm not familiar with the codebase and not sure how to test. Would appreciate it someone could double check my work. 🙏 
-   [ ] Breaking change (fix or feature …
> Add missing "elements.js" export for sp-table component.

- .storybook/theme.js
- projects/story-decorator/package.json
- projects/story-decorator/src/StoryDecorator.ts
Loosen theme application in Storybook so that by default the Manager UI and the Story UI can display the OS native color theme (e.g. dark mode).
1. Go [here](https://themed-storybook--spectrum-web-components.netlify.app/storybook/?path=/story/accordion--default)
2. See that the theme matches your OS settings
3. Change your OS settings to not dark/light mode as appropriate
4. Reload
5. See that the theme matches the new OS settings
-   [x] Something fun...? …
> docs: make storybook themed

- .circleci/config.yml
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/active-overlay.css
Position overlays with `fixed` rather than `absolute`, which ensures that `margin` on the `body` doesn't interact negatively with the `roundByDPR` calculations.
- prepares for #2764 which also requires `fixed` positioning
- fixes #2803
1. CI passes
1. Go [here](https://overlay-body-margin--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--replace)
2. Remove the `padding` from the `sp-theme` element.
3. Remove the `margin: 0;` rule on the `body` element.
4. Open the overlay in the story
5. See that the overlay is visible and not displayed off screen.
-   [ ] If my …
> Overlay body margin

- projects/documentation/package.json
- projects/documentation/scripts/build-search-index.js
- projects/documentation/src/components/search-index.ts
Allow for the search interface to work for all package types, guides, and help pages.
1. Go [here](https://search-tools--spectrum-web-components.netlify.app/)
2. Search for `base`
3. Choose the "Base" auto complete
4. See that the correct docs page opens: https://search-tools--spectrum-web-components.netlify.app/tools/base/
1. Go [here](https://search-tools--spectrum-web-components.netlify.app/)
2. Search for `luck`
3. Choose the "Getting Started" auto complete
4. See that the correct docs page opens: https://search-tools--spectrum-web-components.netlify.app/getting-started/
-   [x] docs
-   [x] If my …
> docs: differentiate between "components" and "tools" when generating search index

- tools/styles/exports.json
- tools/styles/package.json
Still waiting for the publication to propagate at https://jspm.dev/npm:@spectrum-web-components/styles@0.22.1-style.28 and/or https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hcCguSE0uKSrN1S1PTdJNzs8tyM9LzSsp1i8uqcxJLXYw0DMy0jPUBfP0jCwAL2hwmD4A but this appears to revert the change in v0.15.1 of the `styles` package that caused it to stop building in JSPM. The publication has been stuck on v0.15.0 which has yet to introduce any of the Core Tokens work that we've released throughout the fall.
- fixes #2802 (theoretically)
1. This is mainly to support the internal build process in JSPM, but when it's ready, we can review at https://jspm.dev/npm:@spectrum-web-components/styles@0.22.1-style.28 and/or https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hcCguSE0uKSrN1S1PTdJNzs8tyM9L …
> build(styles): update package export listing

- projects/documentation/e2e/published.spec.ts
Unskip smoke tests now that all recent updates to the Documentation site live.
> test: unskip smoke tests

- packages/sidenav/src/SidenavItem.ts
- projects/documentation/.eleventy.cjs
- projects/documentation/content/_includes/partials/sidenav.njk
- projects/documentation/scripts/component-template-parts.js
- projects/documentation/scripts/copy-component-docs.js
- projects/documentation/src/components/styles.css
- group multiple docs pages for the same package under the package itself rather than as sibling pages
- autofocus the current page in the SideNav at page load
- fixes #2411
1. Go [here](https://docs-groups-autofocus--spectrum-web-components.netlify.app/components/tab/)
2. See that the `Tab` navigation item is both visible on load and focused
1. Go [here](https://docs-groups-autofocus--spectrum-web-components.netlify.app/components/slider-handle/)
2. See that the `Slider Handle` navigation is both visible on load and focused
-   [x] Docs
-   [x] If my change required a change to the documentation, I …
> Group docs pages by package name, autofocus the current page in the Side Nav

- .circleci/config.yml
- packages/overlay/package.json
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/active-overlay.css
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-update.test.ts
- yarn.lock
When dispatching `sp-update-overlays` the expectation is the the size AND position of Overlays is updated. This change ensures that size rules applied as part of previous layout application passes is _removed_ before the update workflow is reentered.
- fixes #2813
1. Go [here](https://sp-update-overlays--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--accordion)
2. Open the Overlay
3. Toggle open Accordion Items until the overlay fills the vertical height of the viewport
4. See that it is updated to fill the viewport but never overflows the viewport.
-  [ ] _Test case 2_
1. Go [here](https://studio.webcomponents.dev/edit/1YZCcOq4PMMLIJVekDBk/src/index.ts?branch=overlay%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories)
2. See how the size wasn't …
> Make "sp-update-overlays" work from a clean render

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
When interacting with a Number Field via the `wheel` event, ensure that a `change` event is dispatched, to ensure batched listening is successful. Do so by waiting 100ms after the last `input` event is fired to fire a `change` event. Timing here seems pretty flexible, and I could be convinced of a shorter debounce, but this feels like a good balance between firing the `change` and not firing it all the time, as the `wheel` event could be stop and start and allows for breaks in the interaction.
- fixes #2867 
1. Go [here](https://number-field-change--spectrum-web-components.netlify.app/storybook/index.html?path=/story/number-field--default)
2. Interact with the Number Field with the `wheel` event
3. Check the "Actions" Tab in the Storybook interface
4. See that a …
> fix: ensure "wheel" interactions lead to a "change" event

- .circleci/config.yml
- packages/swatch/src/SwatchGroup.ts
- packages/swatch/stories/swatch-group.stories.ts
- packages/swatch/test/swatch-group.test.ts
- test/visual/test.ts
When `sp-swatch-group` has `selects="single"`, selected `sp-swatch` children no longer loose their selection when being clicked subsequent times.
- fixes #2812
1. Go [here](https://swatch-single--spectrum-web-components.netlify.app/storybook/?path=/story/swatch-group--selects-single)
2. Click `yellow-500`, the selected Swatch
3. See that the Swatch is not _deselected_ and the `selected` values …
> Manage Swatch Group selection correction when "selects=single"

- projects/documentation/e2e/published.spec.ts
Prevent smoke test failures like: https://github.com/adobe/spectrum-web-components/actions/runs/3991273424
We should be able to Smoke Test the preview site to prevent this in the future, but keeping production and preview in sync in a productive way could be trouble.
Searching titles are more resilient, but are technically subject the same in production failures we're seeing right now.
> test: update smoke test for new content

- .circleci/config.yml
- packages/table/src/table-body.css
- packages/table/stories/table-elements.stories.ts
- packages/table/stories/table-virtualized.stories.ts
There was a bug that didn't allow the table to be resized past 120px. Adding flex-grow to the CSS file now makes this possible. 
- fixes https://github.com/adobe/spectrum-web-components/issues/2864
-   Visually tested
- Passes all other tests
-   [ ] If my change required a change to the documentation, I have updated …
> table: allow resizing of table body

- package.json
- packages/tabs/src/Tabs.ts
- packages/tabs/src/tabs.css
- packages/top-nav/src/TopNav.ts
Scales tab indicators from a 100px base instead of a 1px base to avoid rounding & rendering errors.
- https://github.com/adobe/spectrum-web-components/issues/2884
Fixes a rendering issue in horizontal tabs, vertical tabs, and TopNav.
-   [ ] All automated tests pass
-   [ ] Vertical tabs
1. Go to https://opensource.adobe.com/spectrum-web-components/components/tabs/#vertical-tabs
2. Scale your viewport to 140%
3. Select tabs & see the incorrect indicator sizes
4. Go to https://hloftis-fix-2884--spectrum-web-components.netlify.app/components/tabs/#vertical-tabs
5. Scale your viewport to 140%
6. Select tabs & see the correct indicator sizes
-   [ ] TopNav
1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/iframe.html?id=top-nav--default&viewMode=story&args=#page-3
2. …
> fix(tabs): correct indicator size by scaling from 100px

- .circleci/config.yml
- packages/dialog/package.json
- packages/dialog/src/spectrum-dialog.css
- yarn.lock
Take latest Spectrum CSS Dialog package. Changes some padding and sizing to allow for content in the dialog to not be clipped.
1. Go [here](https://dialog-update--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-wrapped--tooltips)
2. Tab focus the first Button in the Dialog
3. See that its Focus Ring is not clipped on the top or left edge …
> chore: use latest CSS dependency for dialog

- packages/menu/src/MenuItem.ts
- packages/menu/stories/menu-item.disconnected.stories.ts
Conditionally query into `shadowRoot` for `itemChildren` content so that disconnected elements do not throw errors.
- fixes #2872 
1. Go [here](https://disconnected-menu-item--spectrum-web-components.netlify.app/storybook/?path=/story/menu-item-disconnected--disconnected-child-items)
2. Click "Switch Views"
3. See that errors are not thrown.
4. Do it again.
5. And again! …
> fix: prepare for querying child items while disconnected

- .circleci/config.yml
- packages/toast/README.md
- packages/toast/stories/toast.stories.ts
The Core Tokens update moved the `white/black` values out of `variant` and into `static` and this allows for consumption of the Toast pattern to better follow the Spectrum guidelines outlined in https://opensource.adobe.com/spectrum-css/toast.html
- fix #2289
1. Go [here](https://toast-buttons--spectrum-web-components.netlify.app/components/toast/#with-actions)
2. See that the outline of the button is more subdued rather than solid white.
-   [ ] Docs …
> docs: use correct Button settings within the toast docs

- .circleci/config.yml
- packages/button/src/button.css
Correct the icon position when the icon is a `position`ed element and is effected by `inset` rules.
1. Go [here](https://b4fb3e0be6d62dce954792067c78fe05--spectrum-web-components.netlify.app/review/)
2. See diff.
> Override errant `inset` rules on Button icons.

- .circleci/config.yml
- packages/button/src/Button.ts
- packages/button/test/button.test.ts
Accidentally removed this functionality as part of last weeks Core Tokens updates for Button 🙈 
1. Go [here](https://2e3cd5a9d50bafd54620be656239428d--spectrum-web-components.netlify.app/review/)
2. See that all the Buttons go back to `variant="accent"` by default.
-   [x] …
> HOT FIX! Revert faulty button variant management.

- projects/documentation/package.json
- yarn.lock
Slim down our dependencies with the latest version of 11ty! This should only effect our [docs site output](https://eleventy--spectrum-web-components.netlify.app/), while simplifying our dependencies and install time 🥳  …
> chore: use latest eleventy version

- packages/tooltip/stories/tooltip.stories.ts
Update the story so that it's open by default so we can compare the VRTs to the new updated tooltip. Also added a control for it in the story. 
-
For overlay v2 
-   Ran tests locally
- Checked storybook …
> chore(tooltip): update selfManaged story to be open by default

- packages/avatar/src/Avatar.ts
- packages/avatar/test/avatar.test.ts
Ensure the "focusable" Avatars resolve a `focusElement` so that they don't throw an error when provided a `tabindex`.
1. Go [here](https://avatar-error--spectrum-web-components.netlify.app/storybook/?path=/story/avatar--size-100)
2. Inspect the Avatar
3. Give it a `tabindex` attribute or `tabIndex` property
4. See that no errors are thrown.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING. …
> fix(avatar): ensure there is ALWAYS a focusElement

- projects/documentation/.eleventy.cjs
- projects/documentation/scripts/build-ts.js
We missed the "code splitting" setting in our transition to `esbuild` and it bloated out first site load on mobile from 58kb to 99.5kb. This puts turns it back on and slims down our first load, again.
1. Go [here](https://docs-build--spectrum-web-components.netlify.app/)
2. See the JS that loads when you run the site in Mobile with all _default_ theme options …
> docs: use code splitting in the JS output

- package.json
- projects/example-project-rollup/package.json
- yarn.lock
Fix the CI build failure plaguing all of our branches after the Playwright docker image updated its version of Node.
> chore: manage deps for build stability

- packages/button/README.md
We should update the docs to reflect the latest changes in the Button API that deprecates variant="white" and variant="black" in favor of using static="white" and static="black" respectively.
#2948 
-
The docs should reflect our best practices and should not include deprecated usages.
1. Go here
2. Do this
1. Go here
2. Do this …
> fix: docs button variant usage

- packages/link/src/Link.ts
Missing type definition for `quiet` property in Link component cause typescript compile error
N/A
User need type definition to use `quiet` property of Link component in a typescript project.
1. Go here
2. Do this
1. Go here
2. Do this
Current API:
API doc change after this PR:
-   [x] My code follows the code style of this …
> fix(link): add the missing quiet property to Link component

- README.md
- patches/lru-cache+6.0.0.patch
Apply a noop patch to the `set` method of the `lru-cache` package so that `@web/dev-server` won't hang when `@web/test-runner` is leveraged on ARM based macOS.
1. Clone locally on an ARM based mac.
2. Run tests
3. See that they finish without hanging (failure in at least one Firefox test locally is not unexpected 😬) …
> chore: patch lru-cache for local testing on ARM based macOS

- cem-react-wrapper.config.js
- custom-elements-manifest.config.js
- package.json
- scripts/cem-plugin-react-wrapper.js
Fixed two issues in this PR.
1. React wrapper generation should exclude the new project - `custom-vars-viewer`
2. [overlay](https://github.com/adobe/spectrum-web-components/tree/main/packages/overlay) component is special.
Two customer element declaration file names do not follow the naming convention. [overlay-trigger.ts](https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/overlay-trigger.ts) and [active-overlay.ts](https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/active-overlay.ts). They should both have prefix `sp-`. This will cause the generated customer-elements.json miss two customer element declaration information and the react wrapper miss two file import statements.
-
1. Go here
2. Do this
-   [ ] _Test case …
> fix(@swc-react/overlay): cem file glob cause one customer element info were omitted

- .circleci/config.yml
- web-test-runner.config.ci-chromium-flags.js
- web-test-runner.utils.js
Add speculative unit testing to CI in advance of leveraging experimental features in the Overlay API rewrite.
1. It's tests: https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/14797/workflows/27d26608-26a0-4a51-bbf4-7f95c8929a48/jobs/287465
2. They ran without failing
-   [x] Tests …
> test: add unit test pass to CI with --enable-experimental-web-platform-features flag

- .circleci/config.yml
- packages/color-area/package.json
- packages/color-area/src/spectrum-color-area.css
- packages/color-area/test/color-area.test.ts
- scripts/spectrum-tokens.js
- yarn.lock
Migrates ColorArea to the core tokens system. Hold for full release. 
Jira Ticket [CSS 190](https://jira.corp.adobe.com/browse/CSS-190)
- Token Migration
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] If my change required a change to the documentation, I have updated …
> chore(color-area): use core tokens

- .circleci/config.yml
- packages/table/src/table-row.css
- projects/documentation/package.json
- projects/documentation/scripts/component-template-parts.js
- projects/documentation/src/components.ts
- projects/documentation/src/components/layout.css
- projects/documentation/src/components/styles.css
Dog food the `<sp-table>` elements in the API tables for the docs site.
1. Go [here](https://docs-api-2--spectrum-web-components.netlify.app/)
2. Visit your favorite component
3. Checkout it's API table
4. Scale the width of the browser up and down.
5. See that content can always be viewed, whether by default or by horizontal scroll.
6. Confirm that forced line breaks are not overly distracting from API communication
-   [x] Docs and self component usage …
> docs: use sp-table in docs site

- projects/documentation/src/components/layout.css
- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/settings.ts
- projects/documentation/src/components/styles.css
Require even less JS over the wire for the initial page load/render by moving theme options into a right side nav.
1. Go [here](https://docs-mobile--spectrum-web-components.netlify.app/)
2. Size the browser from large to small and see that the layout works in a predictable way at all width.
3. Visit in an incognito window with the dev tools set to "mobile" so you get the default mobile view on a clean cache
4. Open the options panel on the left and see that you can change the theme settings.
-   [x] Docs
- …
> docs: sequester themeing from main UI in mobile

- packages/action-button/src/spectrum-action-button.css
- packages/action-button/src/spectrum-config.v2.js
- packages/button/src/spectrum-button.css
- packages/button/src/spectrum-config.v2.js
- packages/checkbox/src/spectrum-checkbox.css
- packages/clear-button/src/spectrum-clear-button.css
- packages/clear-button/src/spectrum-config.v2.js
- packages/close-button/src/spectrum-close-button.css
- packages/close-button/src/spectrum-config.v2.js
- packages/dropzone/src/spectrum-dropzone.css
- packages/number-field/src/spectrum-config.v2.js
- packages/number-field/src/spectrum-number-field.css
- packages/radio/src/spectrum-radio.css
- packages/switch/src/spectrum-switch.css
- packages/tabs/src/spectrum-config.v2.js
- packages/tabs/src/spectrum-tabs.css
- tasks/process-spectrum.js
- revisit default hoisting
- realize that selector is no longer functional
- remove non-functional selectors
> fix: prevent default hoisting of custom pseudo elements

- .circleci/config.yml
- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/stories/index.ts
- packages/action-menu/test/index.ts
- packages/card/README.md
- packages/card/stories/card.stories.ts
- packages/card/test/card.test.ts
- packages/picker/src/Picker.ts
- packages/top-nav/README.md
- packages/top-nav/stories/top-nav.stories.ts
* Modified `PickerBase` to no longer force divergent behavior on `quiet` attribute in `sizePopover`, moved this logic down into `Picker`.
* Modified `ActionMenu` to reflect its `quiet` property down onto the internal action-button, and no longer force its value to true.
NOTE: This is a breaking change, as the default behavior for `sp-action-menu` will now be noisy rathern than quiet.
Fixes #3040 
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not …
> fix: sets action-menu quiet to false by default, fixes #3040

- .circleci/config.yml
- packages/action-button/package.json
- packages/action-button/src/ActionButton.ts
- packages/action-button/src/action-button.css
- packages/action-button/src/spectrum-action-button.css
- packages/action-button/test/benchmark/basic-test.ts
- packages/button/package.json
- packages/button/src/Button.ts
- packages/button/src/ButtonBase.ts
- packages/button/src/StyledButton.ts
- packages/button/src/button-base.css
- packages/button/src/button.css
- packages/button/src/spectrum-button.css
- packages/button/test/benchmark/test-basic.ts
- packages/split-button/src/SplitButton.ts
- yarn.lock
Didn't actually need to be on the new processing, as no selectors were effected, but this update accepts a refactor of the Spectrum CSS output to allow for Button and Action Button to require less JS intervention in their layout increasing their render performance.
- closes #2914 
- fixes #2975
1. Go [here](https://lightning-buttons--spectrum-web-components.netlify.app/storybook/?path=/story/action-button-static-black-quiet--xl)
2. See that Action Buttons display as before
1. Go [here](https://lightning-buttons--spectrum-web-components.netlify.app/storybook/?path=/story/button-accent-fill--default)
2. See that Buttons display as before
-   [ ] Performance refactor …
> perf: accept new Spectrum CSS featuring simpler DOM structure

- .circleci/config.yml
- packages/number-field/stories/number-field.stories.ts
- tools/theme/src/Theme.ts
- `stopPropagation()` on language context events
- demo using local language data on individual components
1. Go [here](https://local-custom-lang--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--german-decimals)
2. See that the decimal is `,` because German
1. Go [here](https://local-custom-lang--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--german-decimals)
2. Find the `<sp-theme>` wrapping the `<sp-number-field>`
3. Find the `lang` to `en-US`
4. See that the decimal is `.` because English
- …
> fix(theme): stop language resolution propagation and demo using local languages

- packages/checkbox/src/Checkbox.ts
- packages/split-view/src/SplitView.ts
It looks like the customer-elements.json for `Checkbox` component hasn't mentioned  its `change` event.
N/A
There is no `change` event declaration in customer-elements.json which cause @swc-react/checkbox component is unable to support `change` event callback.
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] My code follows …
> chore(checkbox): declare change event in customer-elements.json

- packages/radio/src/spectrum-config.js
- packages/radio/src/spectrum-radio.css
Ensure "focus" styles for Radio only display at `:focus-visible`
- fixes #2998
1. Go [here](https://radio-focus--spectrum-web-components.netlify.app/components/radio/#sizes)
2. Click a Radio button
3. See that _visible_ focus isn't given to the element
4. Use an arrow key to focus another Radio button
5. See that it is given visible focus
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md …
> fix(radio): process :focus and :focus-visible

- projects/documentation/.eleventy.cjs
- projects/documentation/content/_includes/partials/sidenav.njk
Ensure that subpages of the Tools documentation groups and displayed as such.
- fixes #3054 
1. Go [here](https://tools-docs--spectrum-web-components.netlify.app/tools/reactive-controllers/)
2. See that `Element Resolution`, `Match Media` and `Roving Tab Index` are all accessible as sub pages in the navigation.
-   [x] Docs
-   [x] …
> docs: ensure that subpages for tools packages are included

- packages/radio/src/RadioGroup.ts
- packages/radio/test/radio-group.test.ts
This PR proposes a fix for issue #3074, where the RadioGroup component's 'selected' property does not work correctly when used in a React application with a React wrapper.
After analyzing the code, it appears that the following lines can be removed, as the same logic is covered by the subsequent validateRadios() function call:
```
if (!selectedRadio) {
this.selected = '';
} else {
```
Removing these lines should improve the accuracy of the DOM query within validateRadios(), as it ensures that updateComplete has occurred. This change aims to resolve the issue with the initial state of the default selected radio button when using the RadioGroup component with a React wrapper in a React application.
-
1. Go here
2. Do this
1. Go here
2. Do this
- …
> fix(radio): initialize the radiogroup component correctly

- .circleci/config.yml
- packages/swatch/src/swatch.css
- packages/swatch/stories/swatch.stories.ts
Update "color" application so that it can accept gradient information.
- https://github.com/adobe/spectrum-css/issues/1460
1. Go [here](https://swatch-gradient--spectrum-web-components.netlify.app/storybook/?path=/story/swatch--gradient)
2. See that the Swatch displays with a gradient
-   [x] feature …
> feat: support non-flat "color" application

- package.json
- packages/action-button/test/action-button.test.ts
- tools/shared/src/focusable.ts
Ensure the toggling `disabled` OFF will return the `tabindex` to its previous value. Specifically, make sure that `-1` is returned to `-1`.
*To do:*
- TK
1. Go [here](https://focusable-tabindex--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-button--icon-size-overridden)
2. Inspect the Action Button
3. Set its `tabindex` to `-1` in the HTML
4. Apply the `disabled` attribute
5. See that its `tabindex` stays `-1`
6. Remove the `disabled` attribute
7. See that its `tabindex` stays `-1`
1. Go to other elements that leverage the `focusable` base class
2. Do similar testing.
- …
> fix: manage "tabindex" when toggling "disabled"

- packages/color-area/src/ColorArea.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/number-field/src/NumberField.ts
- packages/slider/src/Slider.ts
Add `pointerleave` to all `streamingListener` usage with pointer events to ensure that in cases where `pointercancel` is not fired the stream is broken.
It would be nice to have a test for this, but it's really a quirk of the browser and while I could manually fire the events that lead to this situation, I'm not sure that it would actually be guaranteeing anything that an actual consumer of the element would encounter.
- fixes #3112 
- fixes #2103 (@hunterloftis I think I need a mouse to test whether this is "fixed" instead of "refs", can you support here?)
- fixes #3002 
1. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--default) or [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html …
> fix: ensure streamingListener ends even if pointercancel not fired

- .circleci/config.yml
- packages/dropzone/src/dropzone.css
- packages/illustrated-message/README.md
- packages/illustrated-message/package.json
- packages/illustrated-message/src/spectrum-config.js
- packages/illustrated-message/src/spectrum-illustratedmessage.css
- packages/illustrated-message/stories/illustrated-message.stories.ts
- packages/illustrated-message/test/benchmark/test-basic.ts
- packages/illustrated-message/test/illustrated-message.test.ts
- scripts/spectrum-tokens.js
- tools/styles/express/spectrum-core-global.css
- yarn.lock
**Core token migration**
Updates version of spectrum CSS illustratedmessage to the latest v6 version that has the core token migration.
**Also: removes "cta" variant**
The CTA variant is no longer necessary, as it provides no unique styles. It has been removed in the spectrum CSS component. This variant was at a previous point in time differing only in whether the description text was italic or not. The more recent versions (including [current 0.9.14 illustrated-message SWC](https://opensource.adobe.com/spectrum-css/illustratedmessage.html)) as dictated by design and tokens, have a normal font-style by default.
[spectrum-css PR 1699](https://github.com/adobe/spectrum-css/pull/1699)
- Ran `yarn test` to make sure tests for `illustrated-message` still passed.
- Compared with VRTs. Notes in …
> refactor(illustrated-message): core tokens update

- packages/slider/src/slider.css
- tools/styles/express/spectrum-core-global.css
While we don't have a more precise timeline for #2905, fast forward some of the fixes therein.
- fixes #2918
- fixes #2917
1. Go [here](https://slider-ff--spectrum-web-components.netlify.app/storybook/?path=/story/slider--default)
2. See the `cursor: pointer` when hovering the track with you mouse
3. See the animation when interacting with the handle.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CO …
> fix: fast forward changes in #2905

- packages/tags/src/spectrum-config.js
- packages/tags/src/spectrum-tags.css
Ensure there is a source for the `spectrum-tags.css` output.
- fixes #2977
> refactor: connect spectrum-tags.css to a source

- packages/overlay/test/index.ts
This uses mocha's test state (`this.foo`) instead of shared closures over `let testDiv` etc, allowing us to run the tests in isolation. A nice side-effect is that it can also delete `afterEach` since cleanup is no longer necessary between tests.
> chore: stop sharing references in overlay tests

- .circleci/config.yml
As per https://github.com/google/wireit/issues/71 the Wireit cache can grow... _forever_. This negates the caching benefits in CircleCI when you need to load/save many MB of data after a couple of weeks of leveraging the cache. This PR creates a parameter that can be passed the build so that when pointed to someting other than the default the cache will not get loaded and the install workflow will create a new cache from scratch. It is possible to inject a parameter as part of a chron based triggering of a CircleCI, so I've scheduled a weekly run that creates a new cache so that we can benefit from the speed of the caching _generally_ without allowing the cache to grow to large. If at some point the issue in question is addressed and there is a "wireit-native" cache management strategy, …
> ci: create an empty cache by including extra key data when loading cache

- package.json
Clean up race condition that could initiate the types build before all of the TS files are present.
> build: ensure icons before running types

- web-test-runner.config.ci.js
- web-test-runner.config.js
- add a new test group for the `overlay-api`, so that all Overlay relative code can be tested as together
- move retries into CI, only
> test: add "overlay-api" group to test suite

- lerna.json
- projects/example-project-webpack/package.json
In order to publish all the packages at 0.x, none of the packages can be 1.x
> chore: wind example project back to 0-version for unified publishing

- packages/icon/src/Icon.ts
- packages/icon/stories/icon.stories.ts
- packages/icon/test/icon.test.ts
Adding support for error API within the icon component
Added error API support for icon component having invalid src passed, in such case the component will announce an `Event("error")` which can be handled by parent component
-
Added a test case …
> feat(icon): image src invalid error api

- packages/meter/src/Meter.ts
- packages/meter/test/meter.test.ts
- packages/progress-bar/src/ProgressBar.ts
- packages/progress-bar/test/progress-bar.test.ts
Update % delivery in `<sp-meter>` and `<sp-progress-bar>` to be internationalized.
cc: @tranjanessa  
- fixes #3166
1. Go [here](https://meter--spectrum-web-components.netlify.app/storybook/?path=/story/meter--side-label)
2. Detach and reattach the `<sp-meter>` element from the DOM (this is required because the Storybook timing is faulty and the language resolution doesn't always attach). I usually do this by highlighting the element in the Elements tab of DevTools and pressing `Delete` then `Command + Z`.
3. Find the `<sp-theme>` element.
4. Apply the `lang` attribute with a value of `ar-sa`
5. See that the % delivery is chagned
1. Go [here](https://meter--spectrum-web-components.netlify.app/storybook/?path=/story/progress-bar--label)
2. Detach …
> fix(meter,progress-bar): add i18n to progress delivery

- .circleci/config.yml
- packages/button/src/ButtonBase.ts
- packages/button/src/button-base.css
- packages/button/src/button.css
- packages/tooltip/stories/tooltip.stories.ts
- tools/shared/src/observe-slot-text.ts
Can we make buttons smarter about consuming Tooltips in advance of the new Overlay API?
1. Go [here](https://button-slots--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--self-managed-icon-only)
2. Ensure the top button (with Tooltip) and bottom button (without Tooltip) display the same visually
1. Go [here](https://3f739bdefe5cf6e781e59c351b81bef0--spectrum-web-components.netlify.app/review/)
2. See that the VRTs only fail on the addition of a new story. …
> refactor: prepare label/tooltip styles for Overlay refactor

- packages/button/src/ButtonBase.ts
- packages/button/test/button.test.ts
- packages/swatch/src/Swatch.ts
- packages/tags/src/Tag.ts
- tools/shared/src/focusable.ts
Ensure that `Focusable` extensions that start `disabled` will return to `tabindex=0` when `disabled` is removed.
- fixes #3200 
1. Go [here](https://focusable-tabindex--spectrum-web-components.netlify.app/storybook/?path=/story/button-black-outline--default)
2. Inspect the Button in the middle that is disabled.
3. See that it's `tabindex` is `-1`
4. Set `$0.disabled = false`
5. See that the `tabindex` updates to `0`. …
> fix(shared): allow "disabled" first to return to "tabindex=0" in "focusable"

- packages/overlay/src/overlay-stack.ts
In the code, `trappingInited` is set to true in the `initTabTrapping` method but when shadow root is not found on the `body` we should ideally stop the trapping. If we don't set this flag to false, it will result in an exception [here](https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/src/overlay-stack.ts#L189) in the above scenario. 
The overlay code is being revamped and this bug fix might not make sense in the new code but this will be helpful for integrating SWC with UXP. 
-
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] Breaking change (fix or feature that would cause existing …
> Fix(overlay): stop the tab trapping if shadow root is not found

- custom-elements-manifest.config.js
- package.json
- projects/css-custom-vars-viewer/package.json
- yarn.lock
Moving element registrations into `defineElement` altered the contents of our CEM output. This ensures element registering files in CEM look like:
```
{
"kind": "javascript-module",
"path": "sp-button.js",
"declarations": [],
"exports": [
{
"kind": "custom-element-definition",
"name": "sp-button",
"declaration": {
"name": "Button",
"module": "/src/Button.js"
}
}
]
},
```
and _NOT_ this:
```
{
"kind": "javascript-module",
"path": "sp-button.js",
"declarations": [],
"exports": []
},
```
1. Take the branch your local machine
2. Run `yarn`
3. Run `yarn custom-element-json`
4. See that the contents of `packages/button/custom-elements-manifest.json` has the expanded listing outlined above.
-   [x] Chore (minor updates related to the tooling or maintenance of the …
> fix: process "defineElement()" to CEM files

- packages/radio/README.md
- packages/radio/src/Radio.ts
- packages/radio/src/spectrum-config.js
- packages/radio/stories/radio.stories.ts
Remove references to no longer supported 'label below' feature for radio component.
Closes #2976.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CON …
> docs(radio): remove label below

- RELEASE_PROCESS.md
- `git clean -dfx` removes the need to `rm -rf` anything.
- most actions work even outside of the Node version requirements, but make sure you're on something expected before running the release.
> docs: prune release process

- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
Fixes spelling error in `aria-label` attribute for the Picker's "Dismiss" button and updates tests.
#3240 
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob …
> fix(picker): #3240 [Bug][a11y]: Picker "Dismiss" button has invalid aria-label attribute name

- packages/dialog/src/DialogBase.ts
- packages/dialog/src/DialogWrapper.ts
- packages/menu/src/MenuGroup.ts
- packages/table/src/Table.ts
We are from UXP team, We are working on [swc-wrappers ](https://git.corp.adobe.com/torq/swc-uxp-wrappers/, ) UXP.
We are facing issue while writing UXP wrapper for DialogBase, DialogWrapper, MenuGroup and Table.
Please find below findings for DialogBase Example.
```
import {
CSSResultArray,
html,
PropertyValues,
SpectrumElement,
TemplateResult,
} from '@spectrum-web-components/base';
import { property } from '@spectrum-web-components/base/src/decorators.js';
import '@spectrum-web-components/underlay/sp-underlay.js';
import '@spectrum-web-components/button/sp-button.js';
import '../sp-dialog.js';  -> sp-dialog.js importing from local path
```
In DialogBase.ts code is importing sp-dialog.js from local path. This is causing reregistration sp-dialog us while implementing UXP Wrapper for …
> updating paths to be package imports

- packages/slider/test/slider.test.ts
- packages/split-view/test/split-view.test.ts
- tools/base/src/streaming-listener.ts
Use `requestAnimationFrame` based limiting to dispatch "streamed" events in a more performance manner
- fixes #3226
- refs #3186
1. Go [here](https://slider-input--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--default)
2. Reduce your CPU and parallel hardware usage your browser's dev tools
3. Interact with the slider a lot at once, very quickly
4. See that the handle sticks pretty close to your mouse
5. Compare to [production](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--default) with the same browser settings
-   [x] My code follows the code …
> fix(base): ensure streaming listener "streams" on the animation frame

- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/overlay/src/overlay-stack.ts
Reverts the work in https://github.com/adobe/spectrum-web-components/pull/3188 and sets a VRT that will alert us to further regression in the future.
When @benjamind is able to provide an update repro for #3187 then we can look at another approach to address his situation using this test as a guide.
1. Go [here](https://regression--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-wrapped--wrapper-labeled-hero)
2. See that the `<sp-button>` in the top left, behind the dialog is visible.
3. If you inspect the `#shadow-root` on the `<body>` element, you can inspect `<div id="actual">` and revert the CSS calc for `min-height: calc(100dvh - var(--swc-body-margins-block, 0px));` to be `min-height: calc(100dvh - var(--swc-body-margins-block, 0));` to …
> fix(overlay): ensure CSS calcs resolve to the expected measurement value

- .circleci/config.yml
- packages/search/package.json
- packages/search/src/spectrum-search.css
- scripts/spectrum-tokens.js
- tools/styles/express/spectrum-core-global.css
- tools/styles/spectrum-core-global.css
- tools/styles/spectrum-scale-large.css
- tools/styles/spectrum-scale-medium.css
- tools/styles/tokens/express/global-vars.css
- tools/styles/tokens/spectrum/global-vars.css
- yarn.lock
Update to use the 6.0 version of Spectrum CSS 'search', which has migrated the component to use core tokens.
[Spectrum CSS PR 1761](https://github.com/adobe/spectrum-css/pull/1761)
Requires PR #2920 for Textfield to be merged in first, before this can be finalized. The CSS overrides here apply to the updated CSS used in Textfield.
VRT comparisons; notes in PR comments.
And looking at preview links for Storybook and the docs site in Chrome and Firefox.
-   [x] …
> refactor(search): core tokens update

- packages/number-field/README.md
Minor change to doc to pass axe-core.
Adds a label to an unlabeled field and an id to a field where it was missing
fixes #3275
-   [x] Run Doc page
1. Go to Doc Page for sp-number-field
2. Run axe Dev tools
3. ensure there are no unlabeled form field errors
-   [x] If my change required a change to the documentation, …
> docs: add labels to sp-number-field documentation

- .circleci/config.yml
- packages/checkbox/src/Checkbox.ts
- packages/checkbox/stories/checkbox.stories.ts
- packages/checkbox/test/checkbox.test.ts
- packages/menu/src/Menu.ts
- packages/menu/src/MenuGroup.ts
- packages/split-view/src/SplitView.ts
- yarn.lock
- update axe-core version and respond to test failures
- correct `indeterminate` values for Checkboxes
- correct role/aria attribute application in Menu Groups
- apply `valuenow`, thought I'm not 100% sure why, to SplitView
- fixes #3266
1. Go [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/16000/workflows/27506cb2-99dc-49d9-9b54-22cf02164c6c/jobs/336229/tests#failed-test-0)
2. See test failures
1. Go [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/16002/workflows/8c63a347-64f5-4fc8-89c6-fc9ec94600a8/jobs/336327)
2. See them not fail
-   [x] I have signed the [Adobe …
> chore: use latest axe-core

- packages/checkbox/src/Checkbox.ts
- packages/checkbox/src/CheckboxBase.ts
- packages/checkbox/stories/checkbox.stories.ts
- packages/checkbox/test/checkbox.test.ts
- packages/switch/test/switch.test.ts
Automated testing tools like aXe throw a conformance error when an aria-checked attribute is assigned to an HTMLInputElement element, because we should be using the native HTML checked attribute or the indeterminate property.
We should set the [HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) object's indeterminate property via JavaScript (it cannot be set using an HTML attribute).
#3266 
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] Chore (minor updates related to the tooling or maintenance …
> fix(checkbox): [a11y] use indeterminate property rather than aria-checked="mixed" #3266

- .circleci/config.yml
- package.json
- packages/number-field/src/number-field.css
- packages/slider/src/slider.css
- packages/textfield/src/textfield.css
- packages/textfield/test/textfield.test.ts
- yarn.lock
Resolve a couple of incongruities between Spectrum CSS and SWC width application in Number Field, Text Field, and editable Slider elements.
1. Go [here](https://number-field-width--spectrum-web-components.netlify.app/storybook/?path=/story/slider--editable)
2. Compare to [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--editable) …
> fix(number-field): simplify width management

- .circleci/config.yml
- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/src/color-slider.css
- packages/color-slider/test/color-slider.test.ts
Use `inset-block-*` and `inset-inline-*` and fix RTL orientation
- #3301 
Also, see conversation here: https://github.com/adobe/spectrum-web-components/pull/3293#pullrequestreview-1470103325
ColorSlider should be oriented correctly for right to left languages and the behavior of arrow keys should be oriented right to left.
1. Go to https://opensource.adobe.com/spectrum-web-components/components/color-slider/#default
2. Change the Direction to RTL
3. Tab or click to set focus to the first ColorSlider on the page.
4. Notice that the ColorSlider gradient remains oriented left to right
5. Use left or right arrow keys to change the value.
6. Notice that the handle moves in the opposite direction as one would expect.
-   [ ] New feature …
> fix(color-slider): [Bug][a11y] orientation is incorrect for RTL languages #3301

- package.json
- yarn.lock
Chromedriver was updated to 114 in the repo, but github tachometer has a dependency on `ubuntu-latest` which is creating a version mismatch with Chrome. See bug ticket [here](https://github.com/actions/runner-images/issues/7699). This is causing the tachometer results to fail on Chrome. Rolling back the release until the bug is fixed.
-
Want PRs to be green :) 
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] I …
> chore: roll back chromedriver due to incompatibility

- packages/menu/src/Menu.ts
- packages/menu/src/MenuItem.ts
Global Events were holding onto DOM trees and showing up in chromes DetachedElement retainer chains. Use per instance events instead of reusing the
Fixes https://github.com/adobe/spectrum-web-components/issues/3164
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] If my …
> fix(menu): #3164 plug memory leak with gobal events

- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/test/color-slider.test.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/color-wheel/test/color-wheel.test.ts
`<sp-color-slider>` and `<sp-color-wheel>` should render the focused style when they first receive focus, tabbing into the document of iframe.
fixes #3278 
fixes #3279 
For ColorSlider:
1. Open https://opensource.adobe.com/spectrum-web-components/components/color-slider/#default
2. Hover over and mouse click to set focus on the "#" sign next to the heading reading "Default."
3. Press Tab key once to set focus to the "#" link with href="#default".
4. Then press Tab a second time to move focus to the ColorSlider example rendered below.
5. Notice that the ColorSlider handle does not change, by growing in size, to display focus.
6. If you press Esc or an Arrow key to change the value, the focused style will render.
Repeat for ColorWheel:
1. Open …
> fix(color-slider,color-wheel): fail to render focused style when first receiving focus #3278

- packages/radio/README.md
The `sp-radio-group` should be labeled by the `sp-field-label`.
Documentation examples at https://opensource.adobe.com/spectrum-web-components/components/radio/#help-text: The `<sp-field-label>` uses the `for` attribute with an IDREF that is used as the `is` attribute on the `<sp-radio-group>`. is should be `id`.
- fixes #3351 
1. Go here
2. Do this
1. Go here
2. Do this …
> chore(radio): fix radio documentation usage of sp-field-label[for] and sp-radio-group[id] #3351 

- packages/tooltip/README.md
- packages/tooltip/src/Tooltip.ts
Provide a brief explanation of a currently-undocumented API that we recommend as a best practice.
- https://github.com/adobe/spectrum-web-components/issues/1436
- resolves https://github.com/adobe/spectrum-web-components/issues/2924
User questions
-   [X] If my change required a change to the documentation, I have …
> docs(tooltip): document self-managed API

- packages/action-button/src/action-button.css
- packages/action-group/src/ActionGroup.ts
- packages/action-group/test/action-group.test.ts
I’m trying to use `sp-action-group` component with `sp-action-button` as child components. When I try to select/click one of the `sp-action-button`, it calls [handleClick](https://github.com/adobe/spectrum-web-components/blob/main/packages/action-group/src/ActionGroup.ts#L171) event. Here, `event.target` is always `span` instead of parent `sp-action-button`. And, because of that `target.value` is always `undefined` and returns and does nothing. 
Technical detail: Retargeting is not occuring because the event occurs on a slotted element inside action button, that physically lives in the light DOM. And because of that event.target is always `span` instead of `sp-action-button`. To fix that, we used [event.composedPath()](https://javascript.info/shadow-dom-events#bubbling-event-composedpath) …
> fix(action-group): fixes action group click event which was not selecting action button when they are child elements of action group

- .circleci/config.yml
- tools/theme/src/express/theme-dark.css
- tools/theme/src/express/theme-light.css
- tools/theme/src/theme-dark.css
- tools/theme/src/theme-darkest.css
- tools/theme/src/theme-light.css
- tools/theme/src/theme-lightest.css
Some of the files within the Spectrum CSS core tokens packages weren't being imported to be used in the `theme` tools, even though we are importing them in the `styles` tools. Added imports for these files so that we can consume these custom variables, as well.
Missing import 
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] …
> chore(theme): include custom var css files in theme imports

- packages/slider/src/HandleController.ts
- packages/slider/src/Slider.ts
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider.test.ts
- #3340 
The aria-valuetext attribute on the input[type="range"] element within the SliderHandle in the Slider shadowDom should include the _forcedUnit for units not included in Intl.NumberFormatOptions, like px or pc.
-   [ ] If my change required a change to the documentation, I have updated the documentation in …
> fix(slider): slider input aria-valuetext omits formatOptions for unit #3340

- packages/table/package.json
Include missing dependency on `@lit-labs/observers`
> fix(table): include all dependencies, @lit-labs/observers was missing

- .circleci/config.yml
- .vscode/settings.json
- packages/number-field/README.md
- packages/number-field/src/NumberField.ts
- packages/number-field/src/number-field.css
- packages/number-field/src/spectrum-config.js
- packages/number-field/src/spectrum-number-field.css
- packages/number-field/stories/number-field-sizes.stories.ts
- packages/number-field/test/number-field.test.ts
- packages/search/README.md
- packages/search/src/Search.ts
- packages/search/src/search.css
- packages/search/src/spectrum-config.js
- packages/search/src/spectrum-search.css
- packages/search/stories/search-sizes.stories.ts
- packages/textfield/README.md
- packages/textfield/src/Textfield.ts
- packages/textfield/src/spectrum-config.js
- packages/textfield/src/spectrum-textfield.css
- packages/textfield/stories/textarea-sizes.stories.ts
- packages/textfield/stories/textfield-sizes.stories.ts
- packages/textfield/textarea.md
Add t-shirt sizing to Number Field, Search, Textfield and subsequently "text area".
Normally this would be "breaking", but in this instance the Spectrum CSS source allows for delivering the pattern _without_ a t-shirt size listing meaning that all consumers should be able to update and continue to deliver their content as they had previously. …
> fix(number-field,search,textfield): add t-shirt sizes

- packages/action-button/src/ActionButton.ts
- packages/action-button/test/action-button.test.ts
- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/test/index.ts
- packages/picker/src/Picker.ts
- packages/split-button/src/SplitButton.ts
- packages/split-button/test/index.ts
There are several small issues with ActionMenu accessibility implementation that require changes to ActionButton and Picker as well.
1. `sp-action-button` within shadowDOM for  `sp-action-menu` includes `aria-pressed` in addition to `aria-expanded` state, which is overkill.
Possible solution would be to change:
https://github.com/adobe/spectrum-web-components/blob/c820757885bf4b000cacd84b54a0df618df72bd4/packages/action-button/src/ActionButton.ts#L213
to 
```ts
const canBePressed = 
isButton && 
(this.selected || this.toggles) && 
!(this.hasAttribute('aria-haspopup') && this.hasAttribute('aria-expanded'));
```
So that we don't add `aria-pressed` to popup buttons that have `aria-expanded` state.
2. `sp-action-button` within shadowDOM for  `sp-action-menu` should only include …
> fix(action-menu): [Bug][a11y]: ActionMenu implementation includes incorrect aria-* attributes #3259

- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/test/color-slider.test.ts
- #3303
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTR …
> fix(color-slider): sp-color-slider fails to announce new value on change after keydown #3303

- packages/swatch/swatch-group.md
> docs: spelling fix in swatch-group docs

- .circleci/config.yml
- packages/tabs/package.json
- packages/tabs/src/spectrum-config.js
- packages/tabs/src/spectrum-tab.css
- packages/tabs/src/spectrum-tabs-sizes.css
- packages/tabs/src/spectrum-tabs.css
- packages/tabs/src/tab.css
- packages/tabs/src/tabs-overflow.css
- packages/tabs/src/tabs.css
- packages/tabs/stories/tabs.stories.ts
- packages/top-nav/src/top-nav-item.css
- scripts/spectrum-tokens.js
- tools/styles/express/spectrum-core-global.css
- tools/styles/spectrum-core-global.css
- tools/styles/tokens/express/global-vars.css
- tools/styles/tokens/spectrum/global-vars.css
- yarn.lock
This updates the Tabs component to use the new version of Spectrum tokens. 
- #3255 
Part of our effort to migrate all Spectrum components to the new tokens.
- Horizontal Tabs height has decreased by 2px
- Icon size went down by 2px in width (ex: 18px to 16px for Medium) …
> feat(tabs): update to use core tokens

- projects/example-project-webpack/src/index.html
- projects/example-project-webpack/src/index.js
We've apparently not followed up on the Webpack example for quite some time. It didn't include file extensions that have been required for a while.
- fixes #3420
1. `cd` into the webpack example directory
2. run `yarn build`
3. run `npx servor dist`
4. ensure you get no errors
5. ensure you get a page that loads in the browser …
> build: correct webpack examples

- .circleci/config.yml
- packages/tooltip/stories/tooltip.stories.ts
Prep Tooltip testing in for delivery changes in subsequent work, e.g. Overlay V2!
1. Go [here](https://2e798b0e2c9927efdde9c7275b32b474--spectrum-web-components.netlify.app/review/)
2. See the that Tooltip has a really long piece of text
-   [x] I have added tests …
> test: use long tooltip content in VRTs

- packages/textfield/src/textfield.css
fixes [#3432](https://github.com/adobe/spectrum-web-components/issues/3432)
I changed some conditions in textfield.css file so that while styling "grows" and "quite" property does not interfere/
-
Now the textarea with properties "grows" and "quite" is properly functioning when focused.
using dev tools
1. Go here
2. Do this
1. Go here
2. Do this
https://github.com/adobe/spectrum-web-components/assets/32033946/e14f52a5-ba42-4360-9595-23f47bba298c
-   [ x] Bug fix (non-breaking change which fixes an issue)
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, …
> fix(textfield): textarea-issue-3432

- .circleci/config.yml
- packages/action-bar/README.md
- packages/action-bar/package.json
- packages/action-bar/src/ActionBar.ts
- packages/action-bar/src/action-bar.css
- packages/action-bar/src/spectrum-action-bar.css
- packages/action-bar/src/spectrum-config.js
- packages/action-bar/stories/action-bar.stories.ts
- packages/action-bar/tsconfig.json
- packages/action-button/src/ActionButton.ts
- packages/action-button/src/spectrum-action-button.css
- packages/action-button/src/spectrum-config.js
- packages/action-button/stories/index.ts
- packages/action-button/tsconfig.json
- packages/action-group/src/ActionGroup.ts
- packages/button/src/CloseButton.ts
- packages/button/tsconfig.json
- packages/close-button/src/spectrum-close-button.css
- packages/close-button/src/spectrum-config.js
- packages/icon/src/IconBase.ts
- scripts/spectrum-tokens.js
- test/testing-helpers.ts
- tsconfig-all.json
- yarn.lock
Changes expected DOM structure from:
```html
<sp-action-bar open>
<sp-checkbox indeterminate>228 Selected</sp-checkbox>
<sp-action-group quiet>
<sp-action-button label="Edit">
<sp-icon-edit slot="icon"></sp-icon-edit>
</sp-action-button>
<sp-action-button label="More">
<sp-icon-more slot="icon"></sp-icon-more>
</sp-action-button>
</sp-action-group>
</sp-action-bar>
```
to
```html
<sp-action-bar open>
2 selected
<sp-action-button slot="buttons" label="Edit">
<sp-icon-edit slot="icon"></sp-icon-edit>
</sp-action-button>
<sp-action-button slot="buttons" label="More">
<sp-icon-more slot="icon"></sp-icon-more>
</sp-action-button>
</sp-action-bar>
```
- replaces the "select" functionality of the Checkbox with a Close Button
- removes the need for an Action Group, which allows for the Action Bar …
> refactor(action-bar): use core tokens

- .circleci/config.yml
- packages/textfield/src/Textfield.ts
- packages/textfield/src/textfield.css
- packages/textfield/stories/textarea.stories.ts
- packages/textfield/textarea.md
- projects/story-decorator/src/StoryDecorator.ts
Allow `<sp-textfield multiline quiet>` to actively accept the `grows` attribute. At some point in the past, style delivery in this area blocked this from delivering correctly, but some combination of time and/or Core Tokens have unlocked this feature.
1. Go [here](https://textarea-quiet-grows--spectrum-web-components.netlify.app/components/textarea/#grows)
2. See that the `quiet` Textfield (the furthest right) now takes the full height of its content.
3. Type additional content and see that the visible area grows
4. Delete content and see that the visible area shrinks
1. Go [here](https://textarea-quiet-grows--spectrum-web-components.netlify.app/storybook/index.html?path=/story/textarea--grows-quiet)
2. See that the Textfield now takes the full …
> fix(textfield): add support for [grows] when [multiline][quiet]

- packages/field-label/src/FieldLabel.ts
- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
- packages/textfield/src/Textfield.ts
Updated the Number field increase/decrease buttons to use the number fields label as part of their label text
Previously the number field increase/decrease buttons were using hardcoded labels as Increment/Decrement but now with this update buttons label text would use the number-field-label text as a part of it to give more context and clarity.
So for
```
<sp-field-label for="units">Package width</sp-field-label>
<sp-number-field
id="units"
style="width: 200px"
value="4"
format-options='{
"style": "unit",
"unit": "inch",
"unitDisplay": "long"
}'
></sp-number-field>
````
The buttons would have their labels as "Increase Package width" and "Decrease Package Width".
- fixes #3273 
1. Go here
2. Do this
1. Go here
2. Do this
-   [x ] Bug fix …
> fix(number-field): update button label to use number-field-labels as part of the text

- tools/reactive-controllers/element-resolution.md
Fix some typos in element resolution docs.
N/A
-
N/A
N/A
-   [ ] I …
> docs: fix element resolution typo

- packages/split-button/src/SplitButton.ts
- packages/split-button/test/index.ts
Fixes #3305
Changes the label for the more button from static text to a reference to the sibling button element
#3305
-
1. Go to https://jnurthen-issue3305--spectrum-web-components.netlify.app/components/split-button/
2. Inspect the more part of the split button and look at the Accessible Name in Dev tools
3. Note that it should be the same as the accessible name of the button part of the split button
-   [x] I have signed the [Adobe …
> fix: sp-split-button more button label

- packages/tabs/src/Tabs.ts
- packages/tabs/test/tabs.test.ts
- tools/reactive-controllers/src/FocusGroup.ts
Updated the logic to accept event code on arrow key press in TabGroup.ts allowing users to use both ArrowLeft and ArrowUp keys interchangeably (same for ArrowDown and ArrowRight)
fixes #3263 
Currently a screen reader user would have to guess the orientation to figure out which arrow keys will work to navigate to the next or previous Tab since we can't rely on screen readers announcing the tablist orientation.
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] Chore (minor updates related to the tooling or maintenance of the …
> fix(tabs): allow bi-directional arrow key navigation in both orientations

- packages/swatch/src/SwatchGroup.ts
- packages/swatch/stories/swatch-group.stories.ts
- packages/swatch/stories/swatch-sizes.stories.ts
- packages/swatch/stories/swatch.stories.ts
- packages/swatch/test/swatch-group.test.ts
- packages/swatch/test/swatch.test.ts
Removed mixed-value attribute from swatch if swatch group selects !== 'multiple'
- https://github.com/adobe/spectrum-web-components/issues/3458
Chrome, Accessibility tree
1. Go here
2. Do this
1. Go here
2. Do this …
> fix(swatch): warn when mixed-value used with selects !== 'multiple'

- packages/textfield/src/Textfield.ts
- packages/textfield/test/textfield.test.ts
When a textfield is marked as invalid, we should mark the title as an empty string to prevent non-intended text from appearing in the the DOM
- fixes #3099
Fixes Adobe Express internal issue
Changes were tested in the storybook environment
1. Go to the default page for TextField in storybook
2. Hover over the invalid field
3. Notice that you no longer get the system level text: "Please match the requested format"
-   [x] I have signed …
> fix(textfield): set "title" when textfield is invalid

- .circleci/config.yml
- packages/action-menu/README.md
- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/stories/index.ts
Tooltip for ActionMenu
https://github.com/adobe/spectrum-web-components/issues/2916
-
1. Go here
2. Do this
1. Go here
2. Do this …
> fix(action-menu): add a slot for Tooltip content

- .circleci/config.yml
- packages/toast/src/toast.css
- packages/toast/stories/toast.stories.ts
Switches `sp-toast` to use the same behavior as `sp-tooltip` for controlling visibility with the `[open]` attribute. This switches from `display: none` to `visibility:hidden` which means the element now has size when hidden allowing the overlay behavior to properly measure it and therefore position it.
#3510 
-
Fixes the placement in overlays.
Added storybook to cover this case, and tested locally in Chrome. …
> fix(toast): switches toast[open] to use visibility hidden to fix overlay handling

- package.json
- tasks/ts-tools.js
- yarn.lock
- use latest esbuild
- correct config to build dev and prod with the same settings
- update the wireit config to rerun TS compilation when the scripts that do that work are updated
1. The tests ran and passed
2. The VRTs ran and passed
3. The docs site built and is usable: https://esbuild--spectrum-web-components.netlify.app/ …
> chore: use latest esbuild

- package.json
The wrong path here was causing the file to _sometimes_ get cleaned up by Wireit and leave changes at CI time....
> chore: correct cache path

- .circleci/config.yml
- packages/action-group/src/ActionGroup.ts
- packages/action-group/stories/action-group-tooltip.stories.ts
- packages/action-group/stories/action-group.stories.ts
- packages/action-group/test/action-group.test.ts
Prevent selection management from happening in an Action Group that does not have `selects` after the first management when `selected` is acquired from the initial merging of `selected` and the DOM provided by the consumer.
Due to the Mutation Observer and the reparenting that happens in the Overlay API you could falsely construct a selection from the last selection AND the next selection without this gate.
1. Added a new test and a new story.
2. [Story](https://action-group-selection--spectrum-web-components.netlify.app/storybook/?path=/story/action-group-tooltips--controlled)
3. [Test](https://github.com/adobe/spectrum-web-components/pull/3529/files#diff-c7346234f129e6f42044c0dab13aa3c69a97010a58c078bb4bd10466bce543f5)
-   [x] Bug fix (non-breaking change which …
> fix(action-group): separate first selection management from later selection management

- packages/overlay/overlay-trigger.md
Clarified use of `type="modal"` and `placement="none"` to ensure underlay covers entire viewport.
-   [X] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CON …
> docs: outline usage of placement="none"

- projects/documentation/content/_includes/partials/logo.njk
- projects/documentation/src/components/adobe-logo.ts
- projects/documentation/src/components/layout.css
- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/side-nav.css
- projects/documentation/src/components/side-nav.ts
- projects/documentation/src/components/styles.css
Make it so responsive side-nav and settings overlays are modal and can be closed using the Escape key.
- #3428 
1. Go here
2. Do this
1. Go here
2. Do this
- …
> docs: responsive side-nav and settings overlays should be modal and keyboard accessible #3428

- projects/documentation/e2e/published.spec.ts
- projects/documentation/src/components/layout.ts
Smoke test didn't get update with the Overlay API changes.
There were some JS errors in the docs site.
1. Go [here](https://smoke-test--spectrum-web-components.netlify.app/)
2. See that there are no errors in the JS console
1. Go [here](https://github.com/adobe/spectrum-web-components/actions/runs/5941219386)
2. Make sure the smoke tests passed …
> docs: update smoke test and focus managment

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/test/index.ts
- packages/picker/src/Picker.ts
- packages/split-button/src/SplitButton.ts
- packages/split-button/test/index.ts
Some event listeners in Picker were not correctly bound in its class extensions Action Menu and Split Button. This caused their respective Menu to stay open when clicking to close them.
Correctly binds the event listeners to the derivative classes.
1. Go [here](https://action-menu-overlay--spectrum-web-components.netlify.app/storybook/?path=/story/split-button-accent-field--s)
2. Click on a "carat"
3. See that the Menu opens
4. Click the "carat" again
5. See that the Menu closes
1. Go [here](https://action-menu-overlay--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--default)
2. Click the Action Button
3. See that the Menu opens
4. Click the Action Button again
5. See that the Menu closes
-   [x] Bug fix (non-breaking …
> fix(action-menu,split-button): ensure toggling the Menu closed completes

- packages/radio/README.md
Updated documentation for radio button to show proper usage of an invalid radio group. Additionally, directed readers to read more about help text. Also, opened [equivalent PR to CSS project](https://github.com/adobe/spectrum-css/pull/2104).
Issue #3005 
Clearer documentation is always good.
Documentation only change.
-   [X] My code follows the code style of this …
> docs: improves documentation for invalid selections in radio groups

- package.json
- yarn.lock
Fast forward Chromedriver update in #3561 so that CI can run again
1. GitHub CI (perf tests) should run and pass
> chore: use latest chromedriver

- packages/table/package.json
- yarn.lock
Seems that maybe the build cache in CI was hiding the lack of alignment here from us 😞 
Bumped some dependencies that are used in multiple places, and massaged some shared dependencies with `resolutions` to clean up the lock a bit.
1. CI no longer fails
-   [ ] I …
> chore: massage dependency versions

- tools/reactive-controllers/test/element-resolution.test.ts
- tools/reactive-controllers/test/match-media.test.ts
The "responds to media changes" test has been flaky as of late: https://app.circleci.com/insights/github/adobe/spectrum-web-components/workflows/build/tests this attempts to resolve that with some extra frame between configuration and tests.
Also, I discovered that the test name was used in multiple locations, so I corrected the non-related test to have a more accurate name.
1. CI stability increases? …
> test: update timing and naming for clarity and stability

- packages/radio/src/RadioGroup.ts
- packages/radio/test/radio-group.test.ts
Added onChange trigger when radio buttons are navigated via keyboard in a radio-group
- https://github.com/adobe/spectrum-web-components/issues/3262
1. Go here
2. Do this
1. Go here
2. Do this …
> fix(radio-group): onChange event not triggering on keyboard navigation

- packages/action-group/stories/action-group-tooltip.stories.ts
- packages/action-menu/stories/index.ts
- packages/badge/src/Badge.ts
- packages/card/src/Card.ts
- packages/dialog/src/DialogBase.ts
- packages/dialog/src/DialogWrapper.ts
- packages/field-label/src/FieldLabel.ts
- packages/menu/src/MenuItem.ts
- packages/meter/src/Meter.ts
- packages/number-field/src/NumberField.ts
- packages/picker-button/stories/index.ts
- packages/progress-bar/src/ProgressBar.ts
- packages/search/src/Search.ts
- packages/sidenav/src/SidenavItem.ts
- packages/slider/src/Slider.ts
- packages/split-view/src/SplitView.ts
- packages/table/src/Table.ts
- packages/table/src/TableHeadCell.ts
- packages/tabs/src/Tab.ts
- packages/tags/src/Tag.ts
- packages/tooltip/stories/tooltip.stories.ts
As mentioned in the lit doc:
Prefer using nothing over other falsy values as it provides a consistent behavior between various expression binding contexts. 
Replaced empty html`` tag with nothing
doc: https://lit.dev/docs/api/templates/#nothing
-
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] My code follows the code style …
> refactor: replace html`` with nothing

- packages/overlay/README.md
Document the impact on https://bugs.webkit.org/show_bug.cgi?id=160953 on our overlay fallbacks
-   [X] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRI …
> docs(overlay): Overlay clipping in Safari (bug 160953)

- .circleci/config.yml
- packages/dialog/src/Dialog.ts
- packages/dialog/stories/dialog.stories.ts
Recalculate scroll/tabindex presence at slotchange + style application time to ensure scrolling is available. Previous calculation would only happen at resize time, which can be prevented by placing the Dialog in a sized container.
- fixes #3073
1. Go [here](https://dialog-scrolling--spectrum-web-components.netlify.app/storybook/?path=/story/dialog--forced-scrolling)
2. See that scrolling is possible in the Dialog content …
> fix(dialog): include tab order management at slotchange time

- packages/table/README.md
- projects/documentation/src/components/code-example.ts
- don't rewrite HTML to the page after the first time (`code-example` isn't recycled, so this should be fine in our context)
- lazily init the Table demos by the availability of `code-example` AND `sp-table`
1. Go [here](https://table-docs--spectrum-web-components.netlify.app/components/table/)
2. See that the Virtualized table demos load
3. Switch the color theme
4. See that the Virtualized table demos are still live …
> docs: ensure table loads

- .circleci/config.yml
- packages/slider/README.md
- packages/slider/src/HandleController.ts
- packages/slider/src/SliderHandle.ts
- packages/slider/stories/slider.stories.ts
Ensure the Slider displays correctly by default when a `value` attribute is not provided.
- fixes #2940
- fixes #3118
1. Go [here](https://slider-track--spectrum-web-components.netlify.app/storybook/?path=/story/slider--minimal-dom)
2. See the track is visible
3. Inspect the element, see that not `value` attribute is present …
> fix(slider): ensure first render when no "value" is supplied

- packages/number-field/src/NumberField.ts
- packages/number-field/stories/number-field.stories.ts
- packages/textfield/src/Textfield.ts
Current implementation: Intercepts IME-based keystrokes and replaces them with their single-byte cousin. 
This change: Accepts all keystrokes until the component is blurred (loses focus), then converts all IME-based characters into their single-byte cousins. 
- https://github.com/adobe/spectrum-web-components/issues/2269
Fix Number Field issues with certain Input Method Editor (IME) input types.
- All existing tests pass
- Manual testing of both IME and non-IME cases
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled …
> fix(number-field): correct composition entry of multi-byte numbers

- packages/asset/README.md
- packages/avatar/README.md
- packages/avatar/test/avatar.test.ts
- packages/dialog/README.md
- packages/tags/README.md
- packages/thumbnail/README.md
- tools/styles/tokens/global-vars.css
- tools/styles/tokens/large-vars.css
- tools/styles/tokens/medium-vars.css
- tools/styles/tokens/spectrum/custom-large-vars.css
- tools/styles/tokens/spectrum/custom-medium-vars.css
Update all broken place.dog images to picsum.photos
- fixes #3585
1. Go to the Asset, Avatar, Dialog, Tags, or Thumbnail pages in the docs
2. See that images on the page actually load. …
> docs: move to picsum.photos instead of place.dog

- .circleci/config.yml
- packages/sidenav/src/SidenavItem.ts
- packages/sidenav/stories/sidenav.stories.ts
"Revert" work that accidentally removed the `<slot>` that accepted label text.
- fixes #3557
1. Go [here](https://sidenav-labels--spectrum-web-components.netlify.app/storybook/?path=/story/sidenav--multilevel-slotted)
2. See that the labels display as expected
3. Expectation can be divided from [here](https://sidenav-labels--spectrum-web-components.netlify.app/storybook/?path=/story/sidenav--multilevel) …
> fix(sidenav): reintroduce support for slotted label content

- .circleci/config.yml
- packages/picker/src/Picker.ts
- packages/tray/package.json
- packages/tray/src/tray.css
- tools/styles/package.json
- tools/styles/tokens/global-vars.css
- tools/styles/tokens/large-vars.css
- tools/styles/tokens/medium-vars.css
- tools/styles/tokens/spectrum/custom-large-vars.css
- tools/styles/tokens/spectrum/custom-medium-vars.css
- yarn.lock
Picker accidentally passed `placement` to its overlay, even when in mobile, where it should be opening a Tray without positioning.
Catch an out of date style application in Tray.
Update some associated dependencies across the style ecosystem.
1. Go [here](https://picker-mobile--spectrum-web-components.netlify.app/storybook/iframe.html?id=picker--default&args=&viewMode=story)
2. Use a mobile device or emulator
3. Open the Picker
4. See that it opens in a Tray …
> fix(picker): ensure the Menu opens in a Tray on mobile

- packages/table/src/Table.ts
- packages/table/test/table.test.ts
Implemented TypeScript's optional chaining (question mark operator) for safer access to the **tableHead** property. This ensures that nullish values are gracefully handled, especially since the Lit Element's async update doesn't guarantee its presence in React runtime.
[DTT-1780](https://jira.corp.adobe.com/browse/DTT-1780)
-
The change was necessitated by observations where the asynchronous updates in Lit Element did not guarantee the tableHead property's presence in React runtime, leading to potential runtime errors.
Unable to provide a test case because it is race condition issue which was only reproducible in a special env(My local dev instance and sometimes during the VRT testing) 
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] Bug fix …
> chore: enhanced robustness of table component in react runtime

- package.json
- packages/icons-ui/bin/build.js
- packages/icons-ui/package.json
- packages/icons-workflow/bin/build.js
- packages/icons-workflow/package.json
- scripts/cem-plugin-react-wrapper.js
- yarn.lock
Not sure why this started to fail at `get-ready` time, but normalizing to `fast-glob` which we use most other places seems to do the trick!
1. run `yarn`
2. don't get failures
-   [x] All new and existing tests …
> chore: switch to fast-glob from glob

- tools/base/exports.json
- tools/base/package.json
- tools/base/src/directive.ts
Add an export so that items from `lit/directive.js` can be imported through `@spectrum-web-components/base`
-
1. Go here
2. Do this
1. Go here
2. Do this
- …
> feat(base): add re-export of lit/directive.js

- .circleci/config.yml
Don't let wireit build from a cache that it doesn't own. That allows stale date in the cache created by the run that perpetuates across future runs and branches.
> ci: stop using a fallback wireit cache

- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/VirtualTrigger.ts
- packages/overlay/src/loader.ts
Remove some circular dependencies from the Overlay class architecture.
- fixes #3563
1. All of the tests pass
2. Not sure how to test the fail context, however.
> fix(overlay): reduce circular dependencies

- .circleci/config.yml
- packages/action-menu/README.md
- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/stories/action-menu.stories.ts
- tools/shared/src/observe-slot-presence.ts
Add slot-based API for delivering a Action Menu without an icon in its Action Button
- fixes #2557 
1. Go [here](https://action-menu-label-only--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--label-only)
2. See it in _action_ 😉 
-   [x] All …
> Deliver Action Menu without an Icon

- .circleci/config.yml
- packages/field-label/package.json
- packages/slider/README.md
- packages/slider/package.json
- packages/slider/src/Slider.ts
- packages/slider/src/slider.css
- packages/slider/src/spectrum-config.js
- packages/slider/src/spectrum-slider.css
- packages/slider/stories/slider-sizes.stories.ts
- packages/slider/stories/slider.stories.ts
- yarn.lock
Add the `s`, `m`, `l`, and `xl` t-shirt sizing to the `<sp-slider>` element.
- size applies to all slider handle/field-label/number-field shadow and light DOM children on the slider and is not customizable
- updated placement of number-field in the overall layout
- removed local margin/padding applications
Correct color delivery of disabled value label.
**TO DO**
1. Go [here](https://sized-slider--spectrum-web-components.netlify.app/storybook/?path=/story/slider-sizes--xl-editable)
2. Review the new "Sizes" section of the "Slider" stories
-   [x] If my change …
> fix(slider): add t-shirt sizing

- .circleci/config.yml
- packages/color-handle/package.json
- packages/color-handle/src/color-handle.css
- packages/color-slider/package.json
- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/src/color-slider.css
- packages/color-slider/src/spectrum-color-slider.css
- packages/color-slider/test/color-slider.test.ts
- yarn.lock
1. This changes the color-slider component to use the new version in spectrum CSS that has migrated to core tokens.
2. Applies SWC opacity checkerboard tools class to the component.
[CSS PR](https://github.com/adobe/spectrum-css/pull/1924)
-   [x] Confirm any differences in VRTs
-   [x] Confirm that examples function and look as intended, given expected VRT differences
-   [x] Confirm that it looks correct in RTL and that the gradient is reversed
-   [x] I …
> feat(color-slider): migrate to core tokens

- packages/color-loupe/src/ColorLoupe.ts
- tools/opacity-checkerboard/README.md
- Updated docs around opacity-checkerboard inclusion order and fixed a path that was wrong there
- Updated order of styles in only component I found where the checkerboard styles were after the component styles
Related to some discussion around an open issue around inclusion order in Spectrum CSS, and thoughts around doc updates when I was integrating opacity-checkerboard with ColorSlider.
-   [ ] _Make sure ColorLoupe visuals have not changed_
-   [ ] _Review [updated docs](https://checkerboard-inclusion-order--spectrum-web-components.netlify.app/tools/opacity-checkerboard/) for opacity-checkerboard_
-   [ ] Breaking change (fix or feature that would cause …
> fix: opacity checkerboard inclusion order

- packages/overlay/src/OverlayPopover.ts
When manually closing a Overlay that leverages `popover`, wait till the Overlay has left top-layer before measuring its position.
1. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/overlay--complex-modal)
2. Once the Picker is all the way open, click the Picker to close it
3. See the Menu jump down and to the right
4. This sometimes requires the Animations speed to be turned down to 25 or 10% in order to see.
1. Go [here](https://overlay-close-position--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--complex-modal)
2. Once the Picker is all the way open, click the Picker to close it
3. See the Menu DOES NOT jump down and to the right
4. This sometimes requires the Animations …
> fix(overlay): ensure position when closing overlays over the top-layer

- .circleci/config.yml
- packages/menu/src/Menu.ts
- packages/menu/stories/index.ts
- packages/menu/stories/menu-group.stories.ts
- packages/menu/test/menu-group.test.ts
Allow `<sp-menu>` to coalesce slotted content across multiple composed slots, across multiple Menu Groups, into its Menu Items cache.
- fixes #3647
1. Go [here](https://deep-slotted-items--spectrum-web-components.netlify.app/storybook/?path=/story/menu-group--complex-slotted)
2. See that the tab focus enters the group and the arrow based focus group includes all of the Menu Items …
> fix(menu): manage deeply slotted menu items and initial focus

- .circleci/config.yml
- packages/overlay/src/OverlayDialog.ts
- packages/overlay/src/OverlayNoPopover.ts
- packages/overlay/src/OverlayPopover.ts
- packages/overlay/stories/overlay-element.stories.ts
- packages/overlay/test/overlay-element.test.ts
Adds ability for the Overlay to pass focus focus to a root element in the Overlay rather than only child content.
- fixes #3640
1. Go [here](https://receives-focus--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--receives-focus)
2. See that focus is on the link by default when the overlay is first opened …
> fix(overlay): allow "receives-focus" to target the root of an overlay

- .circleci/config.yml
- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/stories/index.ts
- packages/overlay/src/Overlay.ts
- packages/picker/src/Picker.ts
- packages/picker/stories/picker.stories.ts
- packages/picker/test/index.ts
- packages/split-button/src/SplitButton.ts
Add `tooltip` slot to `<sp-picker>` and `<sp-split-button>`. Prepare for #3596 with better ID referencing.
- fixes #3629
1. Go [here](https://picker-tooltip--spectrum-web-components.netlify.app/storybook/?path=/story/picker--tooltip)
2. See that the Tooltip on the Picker opens/closes
3. See that it _only_ does so when hovering/focusing the main "picker" button.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-compo …
> fix(picker,split-button): include "tooltip" slot in the main button

- package.json
- yarn.lock
Rollback to `lerna@6.x` so we can continue to use the existing workflow for publishing `@swc-react` packages.
1. Load the branch locally
2. Run `yarn`
3. Run `yarn build:react` (builds react wrappers, which are `.gitignore`d)
4. Run `yarn lerna list`
5. See that `@swc-react` packages are included
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/mai …
> build: use older lerna so @swc-react packages can be published

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
If you type in a number larger than the max attribute and press "return", it should change the number to the max.
i.e. The value inside the number-field should update on pressing "return" however right now it only happens when the input is blurred out.
- #3000
If you type in a number larger than the max attribute and press "return", it doesn't always change the number. However, the number is always changed when the input is blurred. In addition, the number is never changed when format-options is used, and the number is only changed the first time you press "return" even without format-options.
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] New feature (non-breaking change which adds …
> bug(number-field): update number-field value on pressing "enter"

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
Number field was not correctly handling negative numbers when step was a floating point number
-
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] I have …
> fix(number-field): negative numbers handled

- packages/action-menu/stories/action-menu.stories.ts
- packages/menu/src/Menu.ts
- packages/menu/stories/menu.stories.ts
- packages/menu/test/menu.test.ts
- test/plugins/browser.ts
- test/plugins/grant-permissions-plugin.ts
- web-test-runner.config.js
- web-test-runner.utils.js
Remove an asynchronous break in the call stack between `click` and `change` so that `navigator.clipboard.copyText()` can be safely called during the `change` event.
Test this.
- permissions can be added to Chrome
- flags can be set in Firefox
- Safari does not seem to have testing support in the version of Playwright we're leveragng
Demonstrate it in a handful of stories.
- [menu](https://direct-change--spectrum-web-components.netlify.app/storybook/?path=/story/menu--single-select)
- [action menu](https://direct-change--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--label-only)
- fixes #3687 
- @rickharris to reconfirm in his local Safari
1. Go [here](https://direct-change--spectrum-web-components.netlify.app/storybook/?path=/story/menu--singl …
> fix(menu): allow `change` events to be direct

- packages/action-button/src/ActionButton.ts
- packages/action-group/src/ActionGroup.ts
- packages/action-group/test/action-group.test.ts
Action button change events should bubble and be composed to match behavior with other SWC components which fire change events such as `sp-switch` and `sp-checkbox`
- #3615 
1. Go here
2. Do this
1. Go here
2. Do this …
> feat(action-button): allow change events to bubble and pierce shadowdom

- packages/tags/test/tags.test.ts
- tools/reactive-controllers/src/FocusGroup.ts
- tools/reactive-controllers/src/RovingTabindex.ts
Test focus management in deletable Tags.
Ensure MO is bound to Focus Group items after a rAF when clearing the cache.
Ensure MO is bound to Focus Group items after an update when connecting the host.
- fixes #3590
1. Go [here](https://westbrook-grid--spectrum-web-components.netlify.app/tools/grid/)
2. See that the page loads/scrolls/is interactive and doesn't crash
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-component …
> refactor(reactive-controllers): update attach and post clear cache update timings

- packages/alert-dialog/package.json
- packages/alert-dialog/src/AlertDialog.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/test/dialog-wrapper.test.ts
- test/testing-helpers.ts
Measure content length with a Resize Observer rather than the `resize` event. Allow late loading of hero images to trigger recalculation of content lengths that could enable scrolling and tab stop application.
- fixes #3613
1. Go [here](https://dialog-hero--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-wrapped--lazy-hero)
2. See that the lazily applied hero image causes the content area to scale down and force a scrollbar.
-   [x] I …
> fix(alert-dialog): use resize observer in place of page resize event for content measurement work

- .circleci/config.yml
- packages/slider/src/HandleController.ts
- packages/slider/stories/slider.stories.ts
Make sure the focus loupe of the Slider handle does not fall behind the slider track in the Express theme.
- fixes #3688
1. Go [here](https://slider-handle--spectrum-web-components.netlify.app/storybook/?path=/story/slider--autofocus&sp_theme=express)
2. See that the _right_ edge of the focus loupe is over the right track. …
> fix(slider): ensure z-index in Express theme

- package.json
Ensure publications with no breaking changes (`0.x.0`) still include ALL packages, so that the unified version can be installed by consumers.
1. Open the branch locally
2. Run `yarn lerna-publish`
3. See that all packages are listed.
4. Press `n` and `control + c` to escape the action
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTI …
> build: ensure publication of non-breaking changes includes ALL packages

- packages/overlay/src/Overlay.ts
- packages/overlay/test/overlay-trigger-hover.test.ts
- packages/overlay/test/overlay.test.ts
A timer based approach to allowing hover content to persist so that a user can hover over it. 
- fixes #3366 
Blocks Coachmark PR and Rich Tooltip PR. This also matches the expected behaviour for tooltips outlined by [WACG](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role).
-   [ ] _Before_
1. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/tooltip--overlaid-top)
2. Hover over any of the trigger elements
3. Attempt to hover over a tooltip
4. See that it is not possible! 
5. You can also try the same test [here](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/overlay--click-and-hover-targets)
-   [ ] _After_
1. Go [here](https://halsema-overlay-hover-handler--spectrum-web-components.netlify.a …
> fix(overlay): allow overlay to persist on hover

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
- packages/slider/test/index.ts
- packages/slider/test/slider.test.ts
- test/testing-helpers.ts
Refactor `change` event dispatching so that setting the `value` from the outside does not trigger a `change` event.
- fixes #3720
1. Go [here](https://slider-events--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--editable)
2. Slide the slider
3. See that only one `change` event is dispatched per interaction
4. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--editable) for comparison.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this …
> fix(number-field): prevent over excited "change" events

- .github/workflows/test.yml
- package.json
- yarn.lock
Actually, remove it, for now. We'll likely need to add it back, later, but we need to get over the Node 16 => 18 hump first.
Testing in #3721, passed!
> chore: update chromedriver

- tools/grid/src/Grid.ts
- tools/grid/test/grid-memory.test.ts
- web-test-runner.config.js
- web-test-runner.utils.js
Rendering a `lit-html` template with `render()` without caching it's root part means that you can't inform it when the template is connected to the DOM or not. This connection state is required to ensure clean up can happen to any of the template directives that might be leveraged therein. If the Virtualize template directive does not get disconnected it can leak references to the items it had previously rendered to the DOM.
Cache a reference to the "grid part" in the Grid element for the DOM that would otherwise have been rendered to the render root and managed directly by `LitElement`. Manage the connected state of this cached part.
- fixes #3707
1. Follow the steps in https://github.com/adobe/spectrum-web-components/issues/3707#issuecomment-1754719002
-   [x] Bug …
> fix(grid): plug a mememory leak from the render process

- packages/table/src/TableRow.ts
- packages/table/test/table-selects.test.ts
- packages/top-nav/src/TopNav.ts
- packages/top-nav/stories/top-nav.stories.ts
- packages/top-nav/test/top-nav.test.ts
- manage `role` in Top Nav
- manage `aria-selected` in Table Row
- fixes #3401
- fixes #3397
1. Go [here](https://role-management--spectrum-web-components.netlify.app/storybook/?path=/story/top-nav--default)
2. Turn on screen reader
3. See that the Top nav element is announced as "navigation"
4. You can also toggle the `label` attribute to a value and see that it is used as well.
1. Go [here](https://role-management--spectrum-web-components.netlify.app/storybook/?path=/story/table--selects-single)
2. See that the selected row has the `aria-selected="true"` value and that others have `aria-selected="false"` …
> Updated aria attribute management in Top Nav and Table

- .circleci/config.yml
- packages/overlay/package.json
- packages/overlay/src/Overlay.ts
- packages/overlay/src/topLayerOverTransforms.ts
- packages/overlay/stories/overlay-element.stories.ts
- packages/overlay/test/overlay-trigger-click.test.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
- packages/overlay/test/overlay-v1.test.ts
- packages/overlay/test/overlay.test.ts
- packages/picker/stories/picker.stories.ts
- packages/status-light/package.json
- packages/status-light/src/spectrum-status-light.css
- storybook/main.js
- test/testing-helpers-a11y.ts
- tools/grid/stories/grid.stories.ts
- web-test-runner.config.js
- yarn.lock
- support Overlays over `will-change`
- support Overlays over `backdrop-filter`
- support Overlays over containers with `margin-{inline|block}-start`
- remove so obsessive caching in storybook
- correct the location of long press helper content
- fixes #3710
1. Go [here](https://overlay-over-transforms--spectrum-web-components.netlify.app/storybook/?path=/story/picker--open)
2. See that the Menu is open in the correct location
3. This change adds a `backdrop-filter` to the story context, which also runs into the default margin on `<fieldset>`
1. Go [here](https://overlay-over-transforms--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--modal)
2. See that the Popover is open in the correct location
3. This change adds a …
> Overlay over transforms

- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/stories/overlay-element.stories.ts
- packages/overlay/test/overlay-trigger-click.test.ts
This PR adds the `delay` capability back to `overlay-trigger`
Adding back the capability of delayed overlays.
Inside storybook created a button with a delayed tooltip through overlay-trigger.
Called the Overlay.open() method to test backwards compatibility.
-   [ ] If my …
> fix: add delay to overlay-trigger

- .circleci/config.yml
- web-test-runner.config.js
- run ff and webkit unit tests in parallel
- chromium builds test coverage which is difficult to merge at the end of the process so exclude it from this
- split lint/analyze/check for changes step into its own job
> ci: attempt firefox texts in parallel

- packages/field-group/src/FieldGroup.ts
Apply role when none provided
- fixes #3362
1. Go [here](https://focus-group-role--spectrum-web-components.netlify.app/storybook/index.html?path=/story/field-group--horizontal)
2. See that the Field Group has a `role` attribute
-   [x] All new and existing tests …
> fix(field-group): apply role when none present

- packages/tags/src/Tag.ts
- packages/tags/test/tag.test.ts
Make the `delete` event cancelable for the `sp-tag` element.
- fixes #3777  …
> fix(tags): make the 'delete' event cancelable

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
Fixing the displayed value of sp-number-field on arrow keys and on scroll interactions.
https://github.com/adobe/spectrum-web-components/issues/3753
It improves the user experience by showing in real time the changing value.
1. Go to number-field storybook
2. Click on the number field to focus it
3. Tap the ArrowUp/ArrowDown key or scroll
4. See that the value updates in real time
In the first part of the video you can see the behaviour while I'm scrolling with focus on number field, while the second part shows what happens when tapping the ArrowUp/ArrowDown keys.
https://github.com/adobe/spectrum-web-components/assets/67201262/3d4270ce-5c02-487b-b1d4-066b62aa1e96
-   [ ] New feature (non-breaking change …
> fix(number-field): update display value on scroll and arrow up/down

- packages/overlay/src/OverlayStack.ts
- packages/overlay/test/overlay-element.test.ts
Persist `<sp-overlay type="manual">` elements through interaction that occur outside of their subtree, as is documented/expected/etc but was missed... 😞 
- fixes #3702
1. Go [here](https://manual-overlay--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--click&args=type:manual)
2. Ensure "type" is set to "manual" in the story controls
3. Open the overlay
4. Click outside of it
5. See that it does not close …
> fix(overlay): ensure manual overlays persist through interactions outside of their subtree

- .github/dependabot.yml
There seems to be a lot of value in more frequent alignment with Spectrum CSS releases for components already built in SWC. Adding a separate set of configurations for Spectrum CSS allows the appropriate labels be applied and the PRs be assigned to the Spectrum Engineering crew to review & provide feedback.
As we move into a more rapid update cycle, this will help us see those changes show up in SWC in real-time.
-   [N/A] If my change required a change to the documentation, I have updated the documentation in this pull request. …
> chore: custom Spectrum CSS dependabot settings

- packages/overlay/README.md
- packages/overlay/overlay-trigger.md
The clearest description of the Overlay's `type` attribute is hidden away in the Imperative API docs, which feels counterintuitive since we discourage using the imperative API. I added it to the overlay's README and also changed the order of the content in `overlay-trigger` so that the installation stuff is at the top like the other components. 
-
Clarity! 
1. Go [here](https://halsema-overlay-docs--spectrum-web-components.netlify.app/components/overlay/#type)
2. See that the types section has been added. Compare to [main](https://opensource.adobe.com/spectrum-web-components/components/overlay/#api)
1. Go [here](https://halsema-overlay-docs--spectrum-web-components.netlify.app/components/overlay-trigger/)
2. See that the usage information is now …
> docs(overlay): add types to overlay documentation

- tools/grid/stories/grid.stories.ts
Expand demo code to include responsive card widths.
> docs(grid): expand sized demo to include responsive sizes

- .circleci/config.yml
- packages/slider/src/slider.css
- packages/slider/stories/slider.stories.ts
Fixed track alignment in editable `sp-slider` with label-visibility="none"
- #3812
slider line of sp-slider is not aligned in centre of the value input box when we dont have the label for slider (label-visibility="none" in sp-slider)
1. Go here
2. Do this
1. Go here
2. Do this
Before - 
After - 
-   [x] My code follows the code …
> fix(slider): align editable slider when no label provided

- packages/tooltip/README.md
Expand https://opensource.adobe.com/spectrum-web-components/components/tooltip/#self-managed-overlays to include information about a focusable element, as per the Dev Mode warning and the discussion in https://github.com/adobe/spectrum-web-components/discussions/3781#discussioncomment-7504620
Extended `self-managed` tooltip documentation to include an example of how to use tooltip for non-interactive elements by wrapping them with an interactive element and added notes about why the current pattern is supported the way it is.
- #3787
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] Breaking change (fix or feature that …
> chore(tooltip): extend tooltip self-managed documentation

- packages/action-bar/src/ActionBar.ts
- packages/button/src/Button.ts
- packages/overlay/test/index.ts
- packages/overlay/test/overlay-update.test.ts
- packages/sidenav/test/sidenav.test.ts
- packages/slider/src/HandleController.ts
- projects/documentation/src/components/layout.ts
- projects/documentation/src/utils/templates.ts
- tools/base/src/sizedMixin.ts
- tools/base/test/define-element.test.ts
- tools/shared/src/focusable.ts
Fast forward changes needed to be compliant with `lit@3.0` so that consumers could choose to force that dependency as needed. This also opens the door for an interstitial step wherein we depend on `^2 || ^3` if needed by consuming projects for a period of time.
- refs #3773
- refs #3209
1. Tests pass
-   [x] All new …
> refactor: prepare for lit@3.0 usage

- packages/overlay/src/Overlay.ts
- packages/overlay/stories/overlay-element.stories.ts
- packages/overlay/stories/overlay-story-components.ts
- clean up event bindings before binding.
- merge multiple possible calls to `manageTriggerElement()` into a single call
- fixes #3795
1. Go [here](https://do-pointer-leave--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--transient-hover)
2. Trigger the tooltip on the button
3. Click the button to trigger the popover
4. Move the mouse out of the button
5. See that no error in thrown in the console …
> fix(overlay): ensure events are only bound once

- tools/base/src/directives.ts
Added the `join` and `unsafeHTML` exports to the list of directives we use from `lit/directives' in order to support libraries that don't consume lit. like uec. 
-
Remove unnecessary dependency from my Rich tooltip PR that would be required if we don't have these imports :-)
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] My …
> chore(base): add join and unsafeHTML to directive imports

- .circleci/config.yml
- packages/picker/src/Picker.ts
- packages/picker/stories/picker.stories.ts
`type=auto` was taking up the root dialog component as its parent and rendering the `sp-tray` considering dialog as its root instead of the DOM.
- https://github.com/adobe/spectrum-web-components/issues/3834
Do this:
1. Add the below code in `picker.stories.ts` and try to emulate it in a iphone simulatorwith `xcode`.
```
<overlay-trigger type="modal" open="click">
<div slot="click-content" role="dialog">
<sp-underlay style="z-index: 10000;"></sp-underlay>
<div style="  position: fixed;top: 50%;left: 50%;transform: translate(-50%, -50%);z-index: 10001; background-color: yellow; padding: 20px">
<div style="display: flex; flex-direction: column; gap: 40px">
<sp-picker id="picker-m" size="m" label="Selection type" ${spreadProps(args)}> …
```
> chore(picker): fix for overlaid picker in mobile

- packages/tabs/src/tabs.css
Use a more complete value for `overflow`, `auto hidden`, to prevent overflow scrolling in touch environments.
I'm not sure how one might do a regression test on this sort of thing, but maybe we don't need to? 
- fixes #3813
1. Go [here](https://opensource.adobe.com/spectrum-web-components/components/tabs-overflow/#example)
2. In an actual iOS device, maybe an emulator would be enough, but I didn't try
3. See that the Tabs will scroll up/down as well as left/right, even if they always go back to root
1. Go [here](https://overflow-tabs-scrolling--spectrum-web-components.netlify.app/components/tabs-overflow/#example)
2. In the same device
3. See that the Tabs will NO LONGER scroll up/down
- …
> fix(tabs): prevent vertical scrolling in overflow tabs

- projects/documentation/content/guides/generating-components.md
Add missing step in package creation.
- fixes #3462
1. Go [here](https://new-package-docs--spectrum-web-components.netlify.app/guides/generating-components/)
2. See the new content
-   [x] Docs update
> docs: include missing step in adding a new package

- .circleci/config.yml
- packages/slider/src/HandleController.ts
- packages/slider/src/Slider.ts
- packages/slider/src/spectrum-config.js
- packages/slider/src/spectrum-slider.css
Added DOM changes to bring in the handleContainer and trackContainer
- fixes https://github.com/adobe/spectrum-web-components/issues/2990
- fixes https://github.com/adobe/spectrum-web-components/issues/3536
- fixes #3862
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] …
> chore(slider): slider handle alignment fix

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
Validate limits more regularly to prevent slippage and ensure the value stays within them.
- fixes #3827
1. Go [here](https://number-field-limits--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--min-max)
2. Use the `ArrowDown` key until the Number Field hits `0`, the min value
3. See that the value does not go below that value
1. Go [here](https://number-field-limits--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--min-max)
2. Set the value to 254
3. use the `ArrowUp` key until the Number Field hits `255`, the max value
4. See that the value does not go above that
See other use cases in #3827 …
> fix(number-field): validate min/max in more contexts

- packages/action-menu/stories/action-menu.stories.ts
- packages/menu/src/Menu.ts
- packages/menu/test/menu-group.test.ts
- packages/menu/test/menu-selects.test.ts
- packages/menu/test/submenu.test.ts
Ensure that Menu Items contained within Menu Groups can be navigated to via the arrow keys and selected via the space bar.
- fixes #3686
1. Go [here](https://menu-group-navigation--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--groups)
2. Use the Arrow Keys to navigate through the Menu Items
3. Use the Space key to select one
4. See that the selection is reported in the Actions tab of Storybook …
> fix(menu): support navigating to and selecting Menu Items in Menu Groups

- packages/action-menu/stories/action-menu-sizes.stories.ts
- packages/action-menu/stories/action-menu.stories.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/stories/index.ts
- packages/overlay/stories/index.ts
- packages/picker/stories/picker.stories.ts
- packages/popover/stories/popover.stories.ts
- packages/split-button/stories/split-button-primary-field.stories.ts
- packages/split-button/stories/split-button-primary-more.stories.ts
- packages/split-button/stories/split-button-secondary-field.stories.ts
- packages/split-button/stories/split-button-secondary-more.stories.ts
Simplify waiting for a single `sp-opened` event before allow for a VRT to happen.
1. It is tests, the tests go green in CI.
> docs: refactor story decorator usage to normalize a single Overlay helper

- packages/tooltip/src/Tooltip.ts
- packages/tooltip/stories/tooltip.stories.ts
Allow self-managed Tooltip elements to accept `delayed` and/or `disabled` as boolean attributes.
This work is demonstrated for manual testing in Storybook.
1. Go [here](https://tooltip-delay-disabled--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--self-managed&args=open:!false;disabled:!true)
2. Toggle on `delayed`
3. Attempt to activate the Tooltip
4. See that it is _delayed_
1. Go [here](https://tooltip-delay-disabled--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--self-managed&args=open:!false;disabled:!true)
2. Toggle on `disabled`
3. Attempt to activate the Tooltip
4. See that it will not activate
-   [x] I have signed the [Adobe …
> fix(tooltip): surface "delayed" and "disabled" functionality

- packages/picker/src/Picker.ts
- packages/picker/src/picker.css
Load dependencies, even lazily, before allowing the Menu to be displayed open in a Picker
1. Go [here](https://picker-dependencies--spectrum-web-components.netlify.app/)
2. Make your browser less than 960px wide
3. Refresh the page (at this point it can be helpful to reduce connection and processor resources to ensure delay in content delivery)
4. Open the "options" menu in the top right
5. Open a picker
6. See that there wasn't a flash of non-upgraded layout …
> fix(picker): prevent the Menu opening until required dependencies are loaded

- projects/documentation/src/components/layout.ts
Picker is off centre in docs site, so I removed `placement` attribute since it seems to be unneeded. 
- fixes #3885 
1. Go to [the docs site](https://opensource.adobe.com/spectrum-web-components/)
2. Make your browser less than 960px wide
3. Open the "options" menu in the top right
4. Open a picker
5. See that the overlay is not aligned with the picker
1. Go to [the branch docs site](https://halsema-picker-docs-fix--spectrum-web-components.netlify.app/)
2. Make your browser less than 960px wide
3. Open the "options" menu in the top right
4. Open a picker
5. See that the overlay is aligned with the picker
-   [ ] Breaking …
> docs: remove placement attribute from theme controls

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/test/index.ts
- packages/picker/package.json
- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
- packages/picker/tsconfig.json
- packages/tooltip/src/Tooltip.ts
Ensure reasonability of Tooltip state when Menu is open.
This came up while addressing #3596. This change fast forwards the work that was needed to make that happen.
1. Go [here](https://picker-tooltip-management--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--tooltip-description-and-placement)
2. Hover over the Action Menu
3. See the Tooltip open
4. Click the Action Menu
5. See the Menu open and Tooltip close
6. Focus away from the Menu
7. See the Menu close and the Tooltip _stay_ closed …
> fix(picker): force close slotted Tooltip elements with disabled when Menu openes

- package.json
- packages/icon/package.json
- packages/icons-ui/package.json
As part of a clean-up effort, Spectrum CSS is moving SVG processing for the UI icons library out of the @spectrum-css/icon styles package and into it's own @adobe/spectrum-css-ui-icons package.
This draft PR was tested against a linked local version and was successful. Once we release the new package on npm, we can migrate this to ready to review.
-   [ ] _Validate no regressions in ui icons_
1. Set up a local `yarn link` for the ui-icons folder
2. Updated SWC references from @spectrum-css/icon to @adobe/spectrum-css-ui-icons
3. Run the build and validate the results
-   [x] My code …
> chore(icons,icons-ui): fetch icons from new @spectrum-css/ui-icons package

- .circleci/config.yml
- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/test/index.ts
- packages/menu/test/submenu.test.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/overlay.css
- packages/overlay/test/overlay-trigger-longpress.test.ts
- packages/overlay/test/overlay-update.test.ts
- packages/tooltip/src/Tooltip.ts
- packages/tooltip/src/tooltip.css
- packages/tooltip/stories/tooltip.stories.ts
- packages/tooltip/test/tooltip.test.ts
- yarn.lock
- Prevent unopened Overlay content from existing on the Tab order
- Prevent unopened Overlay content form existing outside of its parent element causing drag image issues
- Correct order of attribute/property application in Overlay Trigger to support
- Add dependency load management to Tooltip
- Update test to support
- fixes #3872
- fixes #3761
1. Go [here](https://overlay-visibility--spectrum-web-components.netlify.app/components/overlay-trigger/#click-content-only)
2. With VoiceOver running, navigate to focus the Overlay Trigger button in the "Click content only" example.
3. Press Tab key to advance to the next focusable control.
4. **_FAIL STATE:_** The VoiceOver cursor disappears and VoiceOver announces "dialog, with 4 items, I understand, button", which is the …
> fix(overlay): move closed overlays to "display: none"

- .circleci/config.yml
- packages/overlay/src/topLayerOverTransforms.ts
- packages/overlay/stories/overlay-element.stories.ts
Expand rules processing for overlay over new layer calculations to include `container-type`.
- fixes #3874 
- refs #3718
1. Go [here](https://overlay-container-type--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--longpress)
2. See that the overlay is in the right place
3. Inspect the overlay to see it has a parent with `container-type: size;` …
> fix(overlay): support positioning overlays within parents leveraging container-type rules

- .circleci/config.yml
- packages/overlay/src/Overlay.ts
- packages/overlay/src/PlacementController.ts
- packages/overlay/stories/overlay-element.stories.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
- packages/overlay/test/overlay-update.test.ts
- test/testing-helpers.ts
Remove the need for `Overlay.update()` by binding multiple `autoUpdate` listeners with different settings.
- clean up consumption of `<sp-popover>` in Overlay Element stories
- fixes #3809
1. Go [here](https://overlay-update--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--accordion)
2. Open the overlay
3. Open various Accordion Items
4. See that through it all the size of the overlay is updated …
> fix(overlay): automatically reposition overlay when the contents resize

- .circleci/config.yml
- packages/combobox/src/Combobox.ts
- packages/combobox/src/ComboboxItem.ts
- packages/combobox/test/combobox.test.ts
- packages/combobox/test/index.ts
- correct some out of date tests
- skip some tests to be addressed in future tasks
- update golden image cache
- refs #478 
1. It is tests and more of them pass, or we skip ones we'll address later.
-   [x] All new …
> test(combobox): get more tests passing and skip tests that will be visited in future work

- packages/top-nav/src/TopNav.ts
- packages/top-nav/stories/top-nav.stories.ts
Add `ignore-url-parts` attribute and `ignoreURLParts` property that accept a space separated list of things to remove from the URL when comparing for the "selected" item in a Top Nav. Values of `hash` and `search` are currently supported.
This makes it so that consumers can opt-in to which part of the URL they would like their "selected" Top Nav Item to be matched against.
- fixes #1983
1. Go [here](https://top-nav-search--spectrum-web-components.netlify.app/storybook/iframe.html?id=top-nav--selected&viewMode=story#test)
2. See that the selected item in the Top Nav does not include the `search` params in its `href`. …
> fix(top-nav): allow consumers to "ignore-url-parts" or "search" or "hash"

- .circleci/config.yml
- packages/combobox/src/Combobox.ts
- packages/combobox/stories/combobox.stories.ts
- packages/combobox/test/combobox.data.test.ts
- packages/combobox/test/combobox.test.ts
Allow an `<sp-tooltip>` to be addressed to the `tooltip` slot of an `<sp-combobox>`.
It doesn't look 100% accessible at current, but we'll revisit that aspect in the a11y audit coming up for this element.
1. Go [here](https://combobox-tooltip--spectrum-web-components.netlify.app/storybook/?path=/story/combobox--with-tooltip)
2. Hover in and out of the Combobox
3. See the Tooltip open/close …
> fix(combobox): add support for external tooltip elements

- packages/overlay/README.md
- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/OverlayDialog.ts
- packages/overlay/src/OverlayNoPopover.ts
- packages/overlay/src/OverlayPopover.ts
- packages/overlay/src/overlay-types.ts
- packages/overlay/test/overlay-element.test.ts
While bubbling `sp-opened` and `sp-closed` events can be tracked to their source via the `event.composedPath()[0]` API, when these events are not bubbling they are a notification of something that happened elsewhere and it is difficult to resolve where in fact that work happened/is happening. This adds an `overlay` property to the events dispatched with type `sp-opened` and `sp-closed`.
While this moves from a `CustomEvent` to an `extends Event {}` implementation, I am attempting to reduce breaks/type collisions by leaving the data previously available on these events in the `detail` property and adding only the `overlay` property to the class of the new event. The previous values could be duplicated to the class as well, for simpler consumption in the future, if that felt appropriatel. …
> fix(overlay): surface "overlay" property to "sp-opened" and "sp-closed" events

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/src/action-menu.css
- packages/action-menu/test/index.ts
- packages/menu/src/Menu.ts
- packages/menu/test/menu-selects.test.ts
- packages/menu/test/submenu.test.ts
- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
- packages/split-button/src/SplitButton.ts
- packages/split-button/src/split-button.css
- packages/split-button/test/index.ts
- test/testing-helpers.ts
Support opening the element's Menu and selecting one of its Menu Items with a single pointer button interaction.
- fixes #2966
1. Go [here](https://picker-interaction--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
2. Make sure the Action Menu is closed
3. Pointerdown on the Action Button
4. See that the Menu opens
5. With the pointer STILL DOWN move to a Menu Item in the _second_ fly out Menu
6. Release the pointer
7. See that all of the correct "selections" were made
1. Go [here](https://picker-interaction--spectrum-web-components.netlify.app/storybook/?path=/story/picker--default)
2. Pointerdown on the Picker
3. Keep it down
4. See that the Menu opened
5. Move to a Menu Item
6. Release the pointer
7. See …
> fix(picker,action-menu,split- button): update interaction model

- .vscode/extensions.json
- .vscode/settings.json
- packages/picker/README.md
- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
Added dev mode warnings for missing label for sp-picker, along with a test and updated documentation that elaborates more on the different methods of labelling the element.
Also, added .vscode linting so that if an import is missing in a file, vscode will tell you! :) 
-
Better a11y contract. Prepares for Combobox. Better dev experience.
-   Unit tests.
-   [ ] My code …
> (picker): add devmode warnings for missing `label` attribute

- packages/combobox/src/Combobox.ts
When there is autocomplete of some kind the 'selection' is displayed by filtering the list or so, which leaves only `autocomplete='none'` usage as benefiting from the selected item UI.
1. Go [here](https://combobox-selects--spectrum-web-components.netlify.app/storybook/?path=/story/combobox--kerning-light-dom)
2. See that the Menu, when opened, displays empty padding to the start end of the inline direction
3. Select a value via pointer or typing
4. See that that value is given an selected ✅
-   [x] If my change required a change to the documentation, I have updated …
> fix(combobox): allow intern Menu to hold a selection when autocomplete === "none"

- scripts/spectrum-tokens.js
Spectrum-css have removed the empty css theme files from their project and thus during our css-build step we cannot always expect to get all the theme files. 
All I did is simply add a check if the corresponding theme file exists or not in our `spectrum-tokens.js` script
1. All existing tests are passing and we are able to build the project without any errors …
> fix: added checks before building a theme

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/stories/index.ts
- packages/menu/src/Menu.ts
- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
- packages/split-button/src/SplitButton.ts
- projects/documentation/package.json
While #3935 updated the interaction model of Picker, Action Menu, and Split Button, it accidentally disabled interaction with the keyboard and screen reader. This adds them back with a test to support.
Side benefits:
- clean up doc site build config so that it doesn't loop so often
- add some event tracking to the Action Menu storybook
- `preventDefault()` the `Arrow*` events that open `<sp-picker>`
- `preventDefault()` the `Space` events that select Menu Items
- refactor some naming for clarity
**Note:**
Listed as a `chore(picker):` as it corrects a `fix(picker):` that has yet to be released.
- refs #3956
1. Go [here](https://picker-spacebar--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-menu--default)
2. Tab to the Action Menu
3. Press …
> chore(picker): return "click" listening

- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/stories/index.ts
- packages/action-menu/test/index.ts
- packages/overlay/package.json
- packages/overlay/src/Overlay.ts
- packages/overlay/src/PlacementController.ts
- yarn.lock
Clear styling applied when positioning after an Overlay is closed again so that previous measurements do not negatively effect subsequent positioning.
~If you can think of a non-manual test for this, I'm all ears.~
- fixes #3955
1. Go [here](https://repeat-placement--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--icon-only&args=align:end)
2. Open/close the Action Menu repreatedly
3. See that at no point does the Menu flow off the edge of the page
-   [ ] If my change required a change to the documentation, I have updated the documentation in …
> fix(overlay): clean position data on close

- packages/combobox/src/Combobox.ts
- packages/combobox/test/combobox-a11y.test.ts
Fulfil the accessibility contract for a combobox with tooltip by adding the "tooltip" as something that works for `aria-describedby` and wrote a test to make sure the description is linked to the combobox's tooltip.
-
Manually tested, unit tests
1. Go here
2. Turn on screen reader
3. Tab into combobox
4. See that the combobox is described by not only the label, but also the tooltip text.
5. Also look at the accessibility tab and see it's got a description, too, that matches the tooltip's text.
-   [x] Chore (minor updates related to the tooling or …
> test(combobox): fulfil accessibility contract

- packages/switch/src/Switch.ts
Expect Switch component onChange to trigger an event
added change event listener to api
- #3970 
OnChange does not trigger an event after migrating from SWC 0.11.11 to 0.40.2 
-   I have verified the change by building react-swc components using `yarn build:react` …
> switch: added change event listener to api

- tools/theme/src/Theme.ts
- tools/theme/test/theme.test.ts
In https://github.com/adobe/spectrum-web-components/issues/3574 most components were updated to expose a static property for the version number. However, theme doesn't extend the same base so this value isn't available in that case. This PR addresses that by using the same approach for Theme.
- fixes #3976 
To align theme with other components
Tested in Storybook and unit test.
N/A …
> fix: expose version property on theme

- packages/combobox/stories/combobox.stories.ts
This verifies that the value of `<sp-combobox>` can be controlled by its container, and demonstrates how.
> docs(combobox): add story demonstrating controlled-component usage

- .circleci/config.yml
- packages/combobox/src/Combobox.ts
- packages/combobox/src/combobox.css
- packages/combobox/stories/combobox.stories.ts
- packages/textfield/src/Textfield.ts
- packages/textfield/src/textfield.css
- projects/documentation/scripts/component-template-parts.js
- expand on API descriptions in Textfield
- add support for `[disabled]` and `[readonly]
- cover these states in Storybook
1. Go [here](https://combobox-api-table--spectrum-web-components.netlify.app/storybook/?path=/story/combobox--disabled)
2. See what a `disabled` Combobox looks like
1. Go [here](https://combobox-api-table--spectrum-web-components.netlify.app/storybook/?path=/story/combobox--readonly)
2. See what a `readonly` …
> API Tables and additional VRT coverage

- packages/combobox/src/Combobox.ts
- packages/combobox/test/combobox.test.ts
- packages/combobox/test/index.ts
correct value to itemText interchange when something is "selected"
1. Go [here](https://combobox-types--spectrum-web-components.netlify.app/storybook/index.html?path=/story/combobox--default)
2. Type `al` into the Combobox
3. See that "Albania" does not get selected
1. Go [here](https://combobox-types--spectrum-web-components.netlify.app/storybook/index.html?path=/story/combobox--default)
2. Type `Afghanistan` into the Combobox
3. See that "Afghanistan" is selected …
> fix(combobox): correct value to itemText interchange when something is "selected"

- .circleci/config.yml
- packages/slider/src/Slider.ts
- packages/slider/src/slider.css
- packages/slider/stories/slider.stories.ts
Update the application of `fill-start` to ensure the delivery of "gradient" sliders.
- fixes #3992
1. Go [here](https://slider-gradient--spectrum-web-components.netlify.app/storybook/?path=/story/slider--gradient)
2. See that the gradient smoothly crosses the full expanse of the slider track
1. Go [here](https://slider-gradient--spectrum-web-components.netlify.app/storybook/?path=/story/slider--fill-start-with-value)
2. Make sure the fills are visible and that they all start from expected positions along the track
1. Go [here](https://slider-gradient--spectrum-web-components.netlify.app/storybook/?path=/story/slider--three-handles-complex)
2. Make sure the fills are visible and that they all start from expected positions …
> fix(slider): reimplement gradient slider track application

- packages/top-nav/src/top-nav-item.css
- packages/top-nav/test/top-nav.test.ts
Swap margin for padding to allow clicks across the full area of the Top Nav Item to interact with the `<a>` element internal to its shadow DOM.
1. Go [here](https://top-nav-updates--spectrum-web-components.netlify.app/storybook/iframe.html?args=&id=top-nav--default&viewMode=story#page-4)
2. Select any of the Top Nav Items
3. See that the visual selection and URL change
4. Click any of the Top Nav Items at the top and bottom extremes of the item (when the 👆🏼 first displays as the cursor)
5. See that the visual selection and URL change
-   [ ] If my change required a …
> chore(top-nav): clean up CSS implementation for user interactions

- .circleci/config.yml
- tools/theme/src/express/theme-dark.css
- tools/theme/src/express/theme-light.css
Custom Spectrum Tokens are required as a baseline for Express to be delivered correctly.
- prepend Custom Spectrum Tokens to the light and dark colors stops in the Express theme.
- fixes #3933
1. Go [here](https://express-custom-tokens--spectrum-web-components.netlify.app/storybook/?path=/story/menu--default&sp_theme=express)
2. Confirm the page loaded in the Express theme
3. See that when hovered the Menu Item background color changes
-   [x] I have …
> fix(theme): include custom Spectrum color tokens in Express color tokens

- .circleci/config.yml
- packages/button/src/CloseButton.ts
Implement _only_ the `large` Close Button instead of only the `default` Close button in support of usage in Dialog elements and in preparation for S2 where there will ONLY be "large", which kind of makes it default, right? 😉 
- fixes #3939
1. Go [here](https://4cd0782161a090690773055cd29cdfde--spectrum-web-components.netlify.app/review/)
2. See all the patterns this updates: Action Bar, Dialog, Toast …
> fix(button): use larger icons in Close Button

- packages/combobox/src/Combobox.ts
- packages/combobox/test/benchmark/basic-test.ts
- packages/combobox/test/benchmark/light-dom-test.ts
- packages/combobox/test/combobox-a11y.test.ts
- packages/combobox/test/combobox.data.test.ts
- packages/combobox/test/combobox.test.ts
- packages/combobox/test/helpers.ts
- packages/combobox/test/index.ts
- segregate dependencies that are not available at benchmark compare time
- lazily instantiate the Menu Items that fill the Combobox UI
1. Go [here](https://combobox-benchmark--spectrum-web-components.netlify.app/storybook/?path=/story/combobox--default)
2. See that the Combobox performs as expected
1. Take this branch
2. See that benchmark tests can be run against the combobox
-   [x] Performance update
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-compon …
> perf(combobox): prevent initial list render and update tests to prove that reduces render time

- package.json
- packages/accordion/stories/accordion.stories.ts
- packages/accordion/stories/args.ts
- packages/accordion/stories/template.ts
- packages/action-bar/stories/action-bar.stories.ts
- packages/action-bar/stories/args.ts
- packages/action-bar/stories/template.ts
- packages/button/stories/index.ts
- packages/button/stories/template.ts
- packages/card/src/card.css
- packages/iconset/package.json
- projects/documentation/.eleventy.js
- projects/documentation/.gitignore
- projects/documentation/content/_data/site.js
- projects/documentation/content/_includes/component.njk
- projects/documentation/content/_includes/partials/demo.njk
- projects/documentation/package.json
- projects/documentation/scripts/copy-component-docs.js
- projects/documentation/scripts/gather-spectrum-urls.js
- projects/documentation/scripts/gather-wcd-urls.js
- projects/documentation/src/components.ts
- projects/documentation/src/components/demo-container.css
- projects/documentation/src/components/demo-container.ts
- projects/documentation/src/components/styles.css
- projects/documentation/src/utils/posthtml-spectrum-docs-markdown.js
- projects/documentation/web-dev-server.config.js
- rollup.checksize.js
- test/tsconfig.json
- yarn.lock
Update docs content to show a demo of the component under documentation at the beginning of the page.
- update to 11ty @ 3.0 (a pre-release version) so that ESM can be used across all of the data files in the build process
- structure the demo to build from `*/stories/args.ts` and `*/stories/template.ts` files
- hide NPM, minzipped and "Try it on" links from each README.md
- add webcomponents.dev and Spectrum spec URLs to documentation build data
- power the listings of the above data with scripts to scrape it from README.md files or metadata.yml files
- prepare various variants of the component page
- component + demo + variables (features all three new sections)
- component + demo (does not include the "controls" section)
- component only (features only the Cards, which are dynamic to …
> docs: place demos at the top of each docs page

- .circleci/config.yml
- packages/popover/src/popover.css
Correct the tip size for the Popover element when positioned to the left/right of something
- fix #4011
1. Go [here](https://popover-tip--spectrum-web-components.netlify.app/storybook/?path=/story/popover--dialog-right)
2. See the tip be correctly sized
1. Go [here](https://popover-tip--spectrum-web-components.netlify.app/storybook/?path=/story/popover--overlaid-left)
2. See the tip be correctly sized …
> fix(popover): correct tip delivery size

- packages/dialog/src/DialogBase.ts
- packages/tray/src/Tray.ts
- packages/underlay/src/Underlay.ts
- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/side-nav.ts
Relying on `click` directly means that patterns that open an Overlay on `pointerdown`, like `<sp-picker>`, could inadvertently close the Overlay as part of that initial interaction.
1. Go [here](https://picker-mobile--spectrum-web-components.netlify.app/)
2. Use a mobile device, emulator, or Dev Tools to mock the mobile context
3. Open one of the theme Pickers
4. See that it stays open. …
> fix(underlay): dispatch a "close" event rather than relying naively on "click"

- .github/lighthouse/lighthouse-config.js
- .github/workflows/test.yml
- tasks/build-lighthouse-comment.js
- tasks/build-preview-urls-comment.js
- tasks/build-tachometer-comment.js
- build the test URL, rather than extract it from other functionality
- add a comparison to `main`
- go from there
1. At some point the lighthouse results pre/post a PR should display in a comment below...
-   [x] …
> ci: expand lighthouse usage and reporting

- packages/menu/src/MenuGroup.ts
- packages/menu/src/MenuItem.ts
- packages/overlay/src/Overlay.ts
- packages/split-view/src/SplitView.ts
- tools/shared/package.json
- tools/shared/src/random-id.ts
- tools/shared/test/random-id.test.ts
Replace HTTPS-only `crypto.randomUUID` with `crypto.getRandomValues`, generating equivalent output (an 8-character hex string).
Allows SWC to run without errors in HTTP contexts.
- All existing tests pass
- Added a test to validate the shape of the ID
- Added a test to validate the speed of ID generation
-   [X] If …
> fix: support generating random IDs outside of secure contexts

- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/settings.ts
- clear the critical load path in mobile of as much JS as possible
1. Go [here](https://docs-loading--spectrum-web-components.netlify.app/)
2. In mobile
3. See that less JS is loaded than in [latest](https://opensource.adobe.com/spectrum-web-components) or [main](https://main--spectrum-web-components.netlify.app/)
1. Go [here](https://docs-loading--spectrum-web-components.netlify.app/)
2. In mobile
3. See that all of the page content is still accessible
-   [x] Research …
> docs: refactor the page load pattern

- .circleci/config.yml
- packages/picker/src/Picker.ts
- packages/picker/src/picker.css
- packages/picker/stories/args.ts
- packages/picker/stories/picker.stories.ts
- packages/picker/stories/template.ts
- packages/picker/test/index.ts
- prevent `[disabled]` Picker from opening
- test to confirm
- add `[disabled]` story to confirm
- expand to leverage `template.ts` and `args.ts` to populate interactive documentation page
- fixes #4033
1. Go [here](https://picker-disabled--spectrum-web-components.netlify.app/components/picker/)
2. Toggle the demo at the top of the page to `disabled===true`
3. Attempt to open the picker by clicking on it.
4. See that it does not open …
> fix(picker): correct implementation of "disabled", expand stories and documentation

- .github/workflows/test.yml
Process branch to slug, so that more branch names can be tested.
We'll want to expand to some level of support for the super long branches (which get hashed) at some point, but baby steps.
> ci: slugify URLs in lighthouse testing

- .circleci/config.yml
- packages/menu/src/menu-item.css
- packages/menu/stories/submenu.stories.ts
A local fix for this visual bug until Spectrum CSS is able to get back to fixing this for us. The chevron wasn't turning to the disabled colour if its menu item is disabled. Now, it does! 
fixes #3659
PSWeb fix request
-   VRTs
Before: 
After (see Queens):
-   [x] If my change required a change to the documentation, …
> fix(menu): correct disabled menu item's chevron to appropriate colour

- .circleci/config.yml
- packages/textfield/src/Textfield.ts
- packages/textfield/src/textfield.css
- packages/textfield/stories/textfield.stories.ts
Prevent negative outcomes for used that leverage `grows` but not `multiline`.
`multiline` was previously document as a requirement, but clarify the effect _both_ attributes as having only vertical sizing effects.
- fixed #2862
1. Go [here](https://textfield-grows-only--spectrum-web-components.netlify.app/storybook/?path=/story/textfield--grows-only)
2. See the magic in action …
> fix(textfield): clearly mark/support "multiline" as a requirement of "grows"

- .circleci/config.yml
- packages/button/stories/index.ts
- packages/button/stories/template.ts
- packages/progress-circle/src/progress-circle.css
- projects/story-decorator/src/StoryDecorator.ts
At some point (likely with the new Core Tokens for Icon) the sizing of the Progress Circle for pending Buttons was broken.
- correct sizing
- update Progress Circle to leverage animation tokens
- move progress button custom property into "Reduce Motion" override at story time so it can be included in VRTs
- update VRTs
1. Go [here](https://progress-circle-size--spectrum-web-components.netlify.app/storybook/?path=/story/button-accent-fill-pending--m)
2. See that the Progress Circle displays after 1 second
3. Switch on "Reduce Motion"
4. Navigate to the "L" size story for these pending buttons
5. See that the Progress Circle display immediately
6. See that all Progress Circles are contains _within_ their respective Buttons
-   [x] Bug fix (non-breaking change which …
> fix(progress-circle): ensure size can be applied to non-"size" attribute bearing elements

- .github/dependabot.yml
Adds a monthly task to check for updates to github actions used in the project.
Less frequently, the actions being used get a version bump. This will ensure the project receives notification of and the opportunity to incorporate those updated actions.
-   [N/A] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [N/A] I have added tests to …
> chore: add GH action updates to dependabot

- .circleci/config.yml
- packages/top-nav/src/top-nav-item.css
Update focus loupe to trigger on `:focu-visible` on the internal `<a>` element rather that `:focus-within` of the `:host` so that the loupe only occurs on "keyboard input".
1. Go [here](https://top-nav-focus-visible--spectrum-web-components.netlify.app/components/top-nav/#example)
2. Click the items in the example Top Nav
3. See that the "indicator" moves to "feature" the clicked item, but there is no "focus loupe" present
1. Go [here](https://top-nav-focus-visible--spectrum-web-components.netlify.app/components/top-nav/#example)
2. Click an item in the example Top Nav
3. Use `Tab` or `Shift+Tab` to move focus to an alternate Item
4. See that the "focus loupe" is present
5. Press `Enter`
6. See that the "indicator" move to "feature" the item and …
> fix(top-nav): focus loupe on :focus-visible only

- packages/overlay/package.json
- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/ClickController.ts
- packages/overlay/src/HoverController.ts
- packages/overlay/src/InteractionController.ts
- packages/overlay/src/LongpressController.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/OverlayNoPopover.ts
Refactor Overlay interactions into strategies. This could reduce the negatives in #3550 in that it duplicated so much brittle/nuanced code.
- refs #3549 
- fixes #4088 
1. Go [here](https://overlay-strategy--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--modal)
2. Test the actual interaction with each of the Overlay Element types
3. See that they work the same as before
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/m …
> refactor(overlay): move interaction management to a strategy pattern

- projects/documentation/content/_includes/layout.njk
- projects/documentation/content/_includes/partials/meta-info.njk
Update content order in the docs site's header for performance suggestion from https://rviscomi.github.io/capo.js/
> docs: use capo.js to tune header content order

- .circleci/config.yml
- packages/menu/src/menu-item.css
- packages/menu/stories/menu.stories.ts
My last fix didn't include a fix for `slot="value"`children of menu items. I added some stories for `<sp-menu-item>`s with "value" slots, and disabled another menu item in a story for VRT reasons. 
- fixes #4094 
-  VRTs (see the difference [here](https://06795ee380eceec0826525c5f4390cc8--spectrum-web-components.netlify.app/review/#MenuItemStories/valueSlot.png))
Before:
After (live in [this PR's storyboo](https://halsema-disabled-menu-items--spectrum-web-components.netlify.app/storybook/?path=/story/menu--menu-with-value-slots)k): 
-   [ ] Chore (minor updates related to the …
> fix(menu): fix css for `disabled` "value" slots in menu items

- packages/overlay/src/OverlayStack.ts
- packages/overlay/test/overlay-element.test.ts
Polyfill the behavior of `popover="manual"` for browsers that do not yet support it.
- fixes #4119
1. Go [here](https://manual-overlay--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--click&args=type:manual)
2. See that the `type` is actually set at "manual", if not reapply it in the Storybook Controls
3. Open the Overlay
4. See that clicking away from the Overlay does not close it
5. See that pressing escape does not close the Overlay
-   [ ] If my change required a change to the documentation, I have updated the documentation in this …
> fix(overlay): ensure "manual" Overlays ignore "light dismiss" when [popover] is not supported

- packages/combobox/src/Combobox.ts
- packages/overlay/package.json
- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/OverlayDialog.ts
- packages/overlay/src/OverlayNoPopover.ts
- packages/overlay/src/OverlayPopover.ts
- packages/overlay/src/slottable-request-event.ts
- packages/overlay/test/overlay-element.test.ts
Surface as yet unused `slottable-request` event infrastructure to unlock in situ testing of some theoretical performance optimizations. Use `chore` in the commit so that this change doesn't appear on the change log.
- refs #3549 
1. Namely checkout the tests that run, but know this is an experimental feature that could be removed or changed at any time. …
> chore(overlay): add "slottable-request" events to the very beginning/end of the Overlay lifecycle

- .circleci/config.yml
- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/OverlayDialog.ts
- packages/overlay/src/OverlayNoPopover.ts
- packages/overlay/src/OverlayPopover.ts
- packages/overlay/src/overlay.css
- packages/overlay/test/index.ts
- packages/overlay/test/overlay-trigger-extended.test.ts
- packages/picker/stories/picker.stories.ts
- test/testing-helpers.ts
Currently when the browser closers an Overlay for us, it will fall off of the `#top-layer` immediately and allow the Overlay content to paint behind standard page content while its close animation is playing.
`transition-behavior`, in association with the `overlay` property, allows the content to stay on the `#top-layer` through the course of the animation.
*TO DO*
1. Go [here](https://transition-behavior--spectrum-web-components.netlify.app/storybook/?path=/story/picker--open) (Currently Chromium only, [more info](https://developer.mozilla.org/en-US/docs/Web/CSS/overlay))
2. Open the Picker (it should be by default)
3. Click away from the Menu, so the Picker closes
4. See that the Menu does not appear "behind" the second Picker while its close animation plays
- …
> fix(overlay): leverage "transition-behavior" to persist top-layer content while closing

- packages/overlay/package.json
- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/ClickController.ts
- packages/overlay/src/HoverController.ts
- packages/overlay/src/InteractionController.ts
- packages/overlay/src/LongpressController.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/index.ts
- packages/overlay/src/overlay-trigger-directive.ts
- packages/overlay/src/overlay-types.ts
- packages/overlay/stories/overlay-directive.stories.ts
- packages/overlay/stories/overlay-element.stories.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/benchmark/directive-test.ts
- packages/overlay/test/benchmark/element-test.ts
- packages/overlay/test/benchmark/lazy-test.ts
- packages/overlay/test/overlay-directive.test.ts
- packages/overlay/test/overlay-element.test.ts
- packages/overlay/test/overlay-trigger-directive.test.ts
- packages/tooltip/package.json
- packages/tooltip/src/tooltip-directive.ts
- packages/tooltip/stories/tooltip-directive.stories.ts
- packages/tooltip/test/benchmark/test-directive.ts
- packages/tooltip/test/tooltip-directive.test.ts
- projects/story-decorator/src/StoryDecorator.ts
Directives, demos, and tests for lazily rendering Overlay content.
This prepares for an initial pre-release for use in major consuming clients for testing purposes.
*EVERYTHING HERE IS EXPERIMENTAL!*
We're looking at pre-releasing this to `latest` and then revisit after some testing for documentation/announcement.
_Known issues:_
- directives do not orchestrate with each other, so using more than one on the same trigger is not currently suggested
- lazily populating an `<sp-overlay>` should be _roughly_ as performant as the directive, but not currently sure why there's a performance delta between the two (this lead to some gaming of the class structure that could technically be reverted)
- I'm not super happy with this argument shape or the defaults it represents:
```
triggerInteraction: …
```
> chore(overlay, tooltip): v0 directive for Overlay v2 testing

- packages/card/README.md
- packages/card/stories/card.stories.ts
- packages/coachmark/README.md
- packages/menu/stories/submenu.stories.ts
- packages/overlay/stories/overlay-element.stories.ts
Updated SWC component READMEs and stories that include the action menu as part of examples with an expected action menu label to demonstrate accessible examples [aligning with existing SWC action menu documentation:](https://opensource.adobe.com/spectrum-web-components/components/action-menu/#no-visible-label)
> "The visible label that is be provided via the default <slot> interface can be ommitted in preference of an icon only interface. In this context be sure that the <sp-action-menu> continued to be accessible to screen readers by applying the label attribute. This will apply an aria-label attribute of the same value to the <button> element that toggles the menu list.".
- fixes https://github.com/adobe/spectrum-web-components/issues/3388
Provides consumers of SWC with accessible usage …
> docs(action-menu): include action menu label in stories and READMEs

- packages/split-view/src/SplitView.ts
- packages/split-view/test/split-view.test.ts
Bug: https://github.com/adobe/spectrum-web-components/issues/3811
Adjusting the logic such that the label allows for a custom label, if it is defined
I have updated the label constant to consider this.label if it is defined. To test this out, I gave label the value of Resizable Split View Custom Label and ran on Storybook to verify that if label is defined, it overrides the default. See video:
https://github.com/adobe/spectrum-web-components/assets/55859693/e60be647-299a-4fa4-9838-0911eaa580b0
-
-   [x] Storybook 
1. Give label a string value (manually)
2. Launch storybook 
3. Verify through the debugger console that the label is set to the custom label
-   [x] Unit tests
1. label gets set when specified on split-view
-   [ ] New …
> fix: [split-view]: update label attribute to be customizable

- packages/dialog/dialog-wrapper.md
- packages/dialog/src/Dialog.ts
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/stories/dialog.stories.ts
- packages/dialog/test/dialog-wrapper.test.ts
- packages/dialog/test/dialog.test.ts
dialog-wrapper has several labels for customization. This PR introduces a new attribute `dismiss-label` for `dialog-wrapper` and `dialog`. It allows the string passed in to be used as the `label` for `dialog-wrapper` and `dialog`.
- Added new property `dismissLabel` and attribute `dismiss-label` to `dialog-wrapper` and `dialog`. Default is ``.
- `dismiss-label` will be used as the `sp-close-button`'s `label` prop. 
- Updated all related `dialog-wrapper` and `dialog` stories to pass in `dismiss-label = 'Close'`.
- Updated 2 unit tests to check that the `dismiss-label` set in the stories trickles down to the `aria-label` of the components.
- Updated `dialog-wrapper` readme with new `dismiss-label`.
https://github.com/adobe/spectrum-web-components/issues/3375 …
> feat(dialog-wrapper): add dismiss-label attribute for the close button's label

- .circleci/config.yml
- CONTRIBUTING.md
- tools/bundle/package.json
- tools/bundle/tsconfig.json
- tools/truncated/.npmignore
- tools/truncated/README.md
- tools/truncated/exports.json
- tools/truncated/package.json
- tools/truncated/sp-truncated.ts
- tools/truncated/src/Truncated.ts
- tools/truncated/src/index.ts
- tools/truncated/src/truncated.css
- tools/truncated/stories/truncated.stories.ts
- tools/truncated/test/benchmark/basic-test.ts
- tools/truncated/test/truncated.test.ts
- tools/truncated/tsconfig.json
- tsconfig-all.json
To succesfully implement the [Breadcrumbs](https://github.com/adobe/spectrum-web-components/discussions/4100) component we would require the truncated element from UEC. We copied the component in SWC so we do not create a new dependency to UEC. 
https://github.com/adobe/spectrum-web-components/discussions/4100
1. Opened storybook 
2. Hover over truncated elements
3. The tooltip appears.
-   [x] _Test case 2_
1.  Opened storybook 
2. Hover over non-truncated elements
3. The tooltip should not appear …
> Truncated element

- .circleci/config.yml
- CONTRIBUTING.md
- tools/bundle/package.json
- tools/bundle/tsconfig.json
- tools/truncated/.npmignore
- tools/truncated/README.md
- tools/truncated/exports.json
- tools/truncated/package.json
- tools/truncated/sp-truncated.ts
- tools/truncated/src/Truncated.ts
- tools/truncated/src/index.ts
- tools/truncated/src/truncated.css
- tools/truncated/stories/truncated.stories.ts
- tools/truncated/test/benchmark/basic-test.ts
- tools/truncated/test/truncated.test.ts
- tools/truncated/tsconfig.json
- tsconfig-all.json
To succesfully implement the [Breadcrumbs](https://github.com/adobe/spectrum-web-components/discussions/4100) component we would require the truncated element from UEC. We copied the component in SWC so we do not create a new dependency to UEC. 
https://github.com/adobe/spectrum-web-components/discussions/4100
1. Opened storybook 
2. Hover over truncated elements
3. The tooltip appears.
-   [x] _Test case 2_
1.  Opened storybook 
2. Hover over non-truncated elements
3. The tooltip should not appear …
> fix(truncated): add truncated package

- .circleci/config.yml
- packages/checkbox/README.md
- packages/checkbox/src/CheckboxMixin.ts
- packages/checkbox/stories/checkbox.stories.ts
- packages/checkbox/test/checkbox.test.ts
- packages/table/README.md
- packages/table/src/Table.ts
- packages/table/src/TableCell.ts
- packages/table/src/TableCheckboxCell.ts
- packages/table/src/table-cell.css
- packages/table/stories/table-elements.stories.ts
- packages/table/test/table.test.ts
The PR implements the following changes
- add `rowheader` role for `<sp-table-cell>`
- tables with `single` or `multiple` select will now have an `aria-label` attribute for the checkboxes in the table. There is an english default string for checkboxes that select a row is **Select** and for the checkbox selecting all rows the default is **Select All**
- The string that will be used for the checkboxes can be provided for the `<sp-table>` element and `<sp-table-cell>` supports an attribute to allow an explicit override for that row. This is intended for clients to support a localized version for the checkbox
- Clients can provide a localized version for **Select All** checkbox string for `<sp-table>` component
This fix addresses
- #3394
- #3396 
Screen Readers were unable to distinguish the …
> fix(table): adding missing aria-labels

- packages/tabs/src/TabsOverflow.ts
- packages/tabs/tabs-overflow.md
- packages/tabs/test/tabs-overflow.test.ts
`<sp-tab-overflow>` is an optional add-on to the Tabs component that adds a [<] and [>] button to help scroll, if there are so many tabs that they overflow off the page. These buttons are currently Keyboard-Navigable, and capture tab focus before the TabGroup itself. 
These buttons should be removed from keyboard navigation for the following reasons:
- Keyboard navigators can already use their arrow keys to navigate through the entire TabGroup
- Every time keyboard navigation enters the TabGroup component, it will always initially focus the very first Tab, regardless of whether it is currently rendered on or off the page. 
Therefore, it is superfluous to have these buttons part of the tab navigation journey.
In addition, these buttons were not labeled. This PR gives them default …
> fix(tab-overflow): improve tab navigation experience and support custom aria labels

- packages/menu/src/Menu.ts
- packages/picker/src/Picker.ts
- allow Picker to open/close in tabled devices
- this is also a workaround, the longer tail work here would be to make an Interaction Strategy specifically for Picker so this was much nicer to read and reason about, however it _seems_ to correct the issue (I've only use Chrome to emulate) without changing the interaction pattern
- also, hard to test, we need to revisit whether we can fake the mobile context in unit tests, somehow...
- Allow keyboard interaction after pointer interactions with Menu Items
- probably could use a test? setting this for discussion first, and then can come back to that tomorrow if desired
- fixes #4132
- fixes #4107
- fixes #4150
1. Go [here](https://picker-tablet--spectrum-web-components.netlify.app/storybook/?path=/story/picker--default) …
> Various Picker Fixes

- packages/progress-bar/src/ProgressBar.ts
- packages/progress-bar/test/progress-bar.test.ts
- packages/progress-circle/src/ProgressCircle.ts
- packages/progress-circle/test/progress-circle.test.ts
Following @Westbrook's suggestion, remove `aria-label` when it matches the previously set (and now empty) `label`. This allows an `aria-label` to remain when it is set independently of the label, but correctly removes an `aria-label` when its corresponding `label` is removed.
- fixes https://github.com/adobe/spectrum-web-components/issues/4151
We are unable to set an `aria-label` for `sp-progress-bar` or `sp-progress-circle` because it gets removed when `label` is not set. This lets us set an `aria-label` appropriately to meet accessibility standards.
I tested adding and removing `label` and `aria-label` attributes in the storybooks for the affected components:
-   [ ] Component should support `aria-label`
1. Add `aria-label` to component without `label`
2. Observe `aria-label` in DOM as …
> fix(progress-bar, progress-circle): remove aria-label only if set by label and label is empty

- .circleci/config.yml
- packages/badge/README.md
- packages/badge/src/Badge.ts
- packages/badge/src/spectrum-badge.css
- packages/badge/src/spectrum-config.js
- packages/badge/stories/badge.stories.ts
Updated the `--mod-badge-background-color-default` override for `seafoam,indigo,purple,fuchsia,magenta,yellow` non semantic variants property which should be
```
--mod-badge-background-color-seafoam
--mod-badge-background-color-indigo
--mod-badge-background-color-purple
--mod-badge-background-color-fuchsia
--mod-badge-background-color-magenta
--mod-badge-background-color-yellow
```
-
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact …
> docs(badge): updated non semantics docs for mod override

- .github/workflows/publish.yml
- projects/documentation/rollup.config.js
I swear we used to publish a `.nojekyll` manually, but apparently not for sometime. Add the flag to do so from `gh-pages`.
Also, prevent file hash output from allowing files that start with `_` which also seems to trigger [this issue](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/), somehow.
1. Go [here](https://opensource.adobe.com/spectrum-web-components/components/color-field/)
2. See that the docs site works.
3. NOTE: I manually ran this code locally after the docs site broke during the most recent publication
-   [x] My code follows the …
> ci: ensure that gh-pages deployment has both .nojekyll and no preceeding __ in filenames

- .circleci/config.yml
- packages/picker/src/spectrum-config.js
- packages/picker/src/spectrum-picker.css
- packages/picker/stories/picker.stories.ts
- packages/picker/stories/template.ts
Seems like the problem is that the CSS for the quiet variant of the `sp-picker` was not correctly processed:
```
:host([open]) #button:not(.spectrum-Picker--quiet) {
```
observe the `spectrum-Picker--quiet` class which should be translated to the HTML quiet attribute.
I added some more processing rules in the `spectrum-config` which should take care of that. Let me know if there is a better config to use for this.
Also, in the storybook, the `sp-label-field` should have the same size as the `sp-picker`, or else it looks weird and the `sp-picker` climbs over the `sp-label-field`. I adjusted the stories to pass the `size` attribute to the `sp-label-field` as well, if present.
- fixes https://github.com/adobe/spectrum-web-components/issues/4166
Solves a CSS bug in the `Picker` component when …
> fix(picker): correctly process the CSS for the quiet hover effect

- packages/action-group/src/ActionGroup.ts
- packages/action-group/test/action-group.test.ts
- packages/button/src/button-base.css
- force Button content to be `pointer-events: none` so that the host can be the target for all click interactions, particularly ones leading to selection
- ensure the Action Group can manage selection state through multiple slots
1. See that added Action Group tests handle "icons" that are not managed by SWC and therefor do not prevent their own `pointer-events`
1. See that added Action Group tests handle selection through multiple slots; on of their own and own of their parent's
-   [x] If my change required a change to the documentation, I …
> Selection management fixes

- packages/banner/package.json
- packages/quick-actions/package.json
- packages/split-button/package.json
- projects/documentation/content/_includes/partials/deprecation.njk
- projects/documentation/scripts/copy-component-docs.js
- tools/theme/package.json
- tools/theme/src/Theme.ts
Deprecation warning for color lightest and darkest
-
1. Go here
2. Do this
1. Go here
2. Do this …
> deprecation: color lightest and darkest

- .circleci/config.yml
- package.json
- packages/combobox/test/combobox-a11y.test.ts
- packages/picker/test/index.ts
- test/testing-helpers.ts
- tools/grid/src/GridController.ts
- yarn.lock
Updates to the latest Playwright.
- moves one static method out of a class
- restructures some test processes to support catching when macOS webkit and linux webkit no longer diverge with each other or other browsers
> chore: use latest Playwright

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/test/action-menu-directive.test.ts
- packages/action-menu/test/benchmark/test-directive.ts
- packages/action-menu/test/benchmark/test-lazy.ts
- packages/action-menu/test/benchmark/test-open-close-directive.ts
- packages/action-menu/test/benchmark/test-open-close.ts
- packages/action-menu/test/index.ts
- packages/overlay/package.json
- packages/overlay/src/HoverController.ts
- packages/overlay/src/OverlayStack.ts
- packages/overlay/src/overlay-trigger-directive.ts
- packages/overlay/src/slottable-request-directive.ts
- packages/overlay/src/slottable-request-event.ts
- packages/overlay/stories/overlay-directive.stories.ts
- packages/overlay/test/benchmark/directive-test.ts
- packages/overlay/test/benchmark/lazy-test.ts
- packages/overlay/test/overlay-directive.test.ts
- packages/overlay/test/overlay-element.test.ts
- packages/overlay/test/overlay-lifecycle.test.ts
- packages/overlay/test/overlay-trigger-hover-click.test.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
- packages/tooltip/src/Tooltip.ts
- packages/tooltip/src/tooltip-directive.ts
- packages/tooltip/stories/tooltip-directive.stories.ts
- packages/tooltip/test/benchmark/test-element.ts
- packages/tooltip/test/benchmark/test-lazy.ts
- test/benchmark/cli.ts
- allow `open` as a flag in the Overlay directives
- abstract `slottable-request` down for use with non-Overlay elements
- prioritize non-`type="hint"` Overlays on the same trigger
- expand options for performance testing specific files
- clean up performance test files
- add `slottable-request` and associated testing to the Action Menu
1. Go [here](https://slottable-action-menu--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--decorated)
2. Open and close the menu
3. See that it works roughly like it did before
1. Go [here](https://slottable-action-menu--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-directive--default)
2. See that toggling `open` in the Controls pane opens and closes the Popover
-   [ …
> Expand `slottable-request` usage and APIs

- packages/table/src/Table.ts
- packages/table/stories/table-virtualized.stories.ts
The `sp-table` component can be virtualized, which only renders table rows that are currently visible in the viewport, which helps with performance on large tables. However, this can trip up screenreaders, which only detect and announce the rendered rows, and not the true size of the table. `aria-rowcount` is a screenreader attribute which announces the true unvirtualized size of the table.
This PR implements the automatic application of `aria-rowcount` for virtualized tables. 
- fixes #3393 
Accuracy and efficacy of screenreader accessibility.
-   [x] Run storybook - Table > Virtualized > [Any of these]
1. Inspect the `sp-table` element
2. Observe that the `aria-rowcount` value is correct.
-   [x] Visit docs site - Table > Virtualized
1. Inspect the `sp-table` element
2. Observe that the …
> fix(table): Add aria-rowcount to virtualized tables

- packages/overlay/src/Overlay.ts
The `SlottableRequestEvent` gets interpreted by CEM incorrectly and fails the React build when attempting to make a release. This ignores the automatic processing of the event and places it manually in the JSDocs.
1. Run `build:react`
2. See that the process completes.
- …
> build: exclude erroneously interpreted event dispatch from CEM management

- .circleci/config.yml
- package.json
- packages/action-button/src/spectrum-action-button.css
- packages/action-button/src/spectrum-config.js
- packages/button/src/ButtonBase.ts
- packages/button/src/spectrum-button.css
- packages/button/src/spectrum-config.js
- packages/button/test/button.test.ts
- packages/checkbox/src/spectrum-checkbox.css
- packages/checkbox/src/spectrum-config.js
- packages/clear-button/src/spectrum-clear-button.css
- packages/clear-button/src/spectrum-config.js
- packages/close-button/src/spectrum-close-button.css
- packages/close-button/src/spectrum-config.js
- packages/infield-button/src/spectrum-config.js
- packages/infield-button/src/spectrum-infield-button.css
- packages/menu/src/MenuItem.ts
- packages/menu/src/spectrum-config.js
- packages/menu/src/spectrum-menu-item.css
- packages/picker-button/src/spectrum-config.js
- packages/picker-button/src/spectrum-picker-button.css
- packages/tags/src/spectrum-config.js
- packages/tags/src/spectrum-tag.css
- packages/tags/src/tag.css
- yarn.lock
Use natively applied `:active` when possible.
- this should not change the end user behavior in any way
- a small (though likely not noticeable) KB and runtime benefit will be present
- refs #4007
1. Go [here](https://native-active--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
2. See that the synthetic `[active]` continues to be applied
1. Go [here](https://native-active--spectrum-web-components.netlify.app/storybook/?path=/story/button-accent-fill--default)
2. In a non-`:hover` supporting context
3. See that pressing the button applies the `:active` state
-   [x] My code follows the code style of this …
> refactor: prefer native :active when possible

- packages/picker/src/Picker.ts
- packages/tooltip/package.json
- packages/tooltip/src/Tooltip.ts
- tools/reactive-controllers/dependency-manager.md
- tools/reactive-controllers/match-media.md
- tools/reactive-controllers/package.json
- tools/reactive-controllers/src/DependencyManger.ts
- tools/reactive-controllers/test/dependency-manager.test.ts
Add, document, and test the `DependencyManagerController` which tracks when supplied custom elements are fully registered to the page.
Refactor Picker and Tooltip to use the `DependencyManagerController` to manage their dependencies.
- fixes #3900
Deduplication.
1. See the test
1. See that Picker and Tooltip work as expected in storybook
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-compone …
> Dependency Manager reactive controller

- packages/menu/package.json
- packages/menu/src/MenuItem.ts
- packages/menu/test/menu.test.ts
Use Dependency Manager Controller in Menu Item to prevent early opening of submenus.
1. Go [here](https://manage-menu-item--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu-submenu--submenu)
2. See that the submenus open as expected
-   [x] Refactor to shared code
> refactor(menu): leverage dependency management in Menu Item for submenus

- packages/action-menu/stories/action-menu.stories.ts
- packages/menu/src/MenuItem.ts
- packages/menu/test/submenu.test.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/test/overlay-trigger-hover.test.ts
- packages/tooltip/test/tooltip-directive.test.ts
Expand use of `slottable-request` based laziness to support submenus.
1. Go [here](https://submenu-directive--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--directive)
2. See that the submenu can be activated with the mouse or the keyboard
3. When using the keyboard confirm that the "visible focus" returns to the submenu host, not the first menu item in the parent menu …
> chore(menu): support delivering submenus via directives

- packages/accordion/test/accordion-memory.test.ts
- packages/action-bar/test/action-bar-memory.test.ts
- packages/action-group/test/action-group-memory.test.ts
- packages/action-menu/test/action-menu-memory.test.ts
- packages/alert-dialog/test/alert-dialog-memory.test.ts
- packages/asset/test/asset-memory.test.ts
- packages/avatar/test/avatar-memory.test.ts
- packages/badge/test/badge-memory.test.ts
- packages/button-group/test/button-group-memory.test.ts
- packages/button/test/button-memory.test.ts
- packages/card/test/card-memory.test.ts
- packages/menu/test/menu-memory.test.ts
- test/testing-helpers.ts
- tools/grid/test/grid-memory.test.ts
The objective of this RFC is to propose a standardised approach for adding memory tests to each package in the component library using [Chrome's Performance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measureUserAgentSpecificMemory), specifically the `measureUserAgentSpecificMemory()` method.
refs #3722
Memory leaks in web applications can lead to performance issues and degraded user experience. By adding memory tests to each package in the component library, we can proactively identify and fix potential memory leaks, ensuring the overall stability and performance of the library.
1. The memory tests will be implemented using the `measureUserAgentSpecificMemory()` method from the Chrome Performance API.
2. The memory test for each package will consist of the following …
> performance: added memory tests in packages

- packages/action-group/test/action-group.test.ts
- packages/button/test/button.test.ts
- packages/top-nav/test/top-nav.test.ts
- test/benchmark/bench-runner.html
- test/benchmark/cli.ts
- test/benchmark/helpers.ts
- tools/shared/src/focusable.ts
- Leveraging non-static promises can cause faulty timing in `updateComplete` callbacks.
- Only delaying `updateComplete` when `autofocus` is true accelerated the render of the majority of focusable elements
- add the `end` or `-e` flag to the benchmark suite that accepts `updateComplete` (the default) or `paint` which waits till the browser paints before ending the performance measurement
The `paint` timing of `focusable` element can be pushed back for the active `requestAnimationFrame`, we shouldn't charge every element that fee at render time.
1. Go [here](https://perf-refactor--spectrum-web-components.netlify.app/storybook/?path=/story/button-accent-fill--default)
2. See that the element renders as expected
1. Review the timing of the tests
- …
> fix(shared): ensure the "updateComplete" in Focusable is stable

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/stories/action-menu.stories.ts
- packages/picker/src/Picker.ts
Bind `slottable-request` events before properties that could trigger them.
1. I've not been able to recreate this in library, but toggling `open` to `true` will trigger a `slottable-request`, and if the event binding for that hasn't already been made ancestor elements that should dispatch the same will not be informed.
- …
> chore(picker): update event bind timing

- packages/combobox/package.json
Normalize `package.json` in Combobox to ensure the correct files are published to NPM and that the correct files are listed as "sideeffectful" in bundles.
- fixes #4243
1. Go [here](https://github.com/adobe/spectrum-web-components/blob/main/packages/color-field/package.json)
2. See the `package.json` of one of our most recently generated packages
3. Compare that to the file changed in the PR
4. See if there is anything missing …
> fix(combobox): correct package.json listings

- projects/documentation/scripts/build-ts.js
Ensure we only get one copy of lit in the docs build.
> docs: externalize lit in the build

- package.json
- packages/overlay/package.json
- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/ClickController.ts
- packages/overlay/src/HoverController.ts
- packages/overlay/src/InteractionController.ts
- packages/overlay/src/LongpressController.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/overlay-trigger-directive.ts
- packages/overlay/src/slottable-request-directive.ts
- packages/overlay/src/strategies.ts
- tasks/ts-tools.js
Allow an interaction controller to be created without requiring the presence of an Overlay
1. Go [here](https://docs-with-overlay--spectrum-web-components.netlify.app/)
2. In mobile
3. See that when you open the Settings Panel or Side Nav the Overlay code is lazily loaded …
> refactor(overlay): make interaction controllers more lazy

- packages/overlay/package.json
- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/OverlayDialog.ts
- packages/overlay/src/OverlayNoPopover.ts
- packages/overlay/src/OverlayPopover.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/events.ts
- packages/overlay/src/overlay-trigger-directive.ts
- projects/documentation/src/components/layout.css
- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/settings.ts
- projects/documentation/src/components/side-nav.ts
1. Move from custom `inert` based left/right navigation UI to use the trigger directive
1. Go [here](https://docs-with-overlay--spectrum-web-components.netlify.app/)
3. In mobile screen sizes (less than `960px`)
4. See that the left hand navigation opens/closes
5. See that the right hand options panel opens/closes
1. Go [here](https://docs-with-overlay--spectrum-web-components.netlify.app/)
3. In mobile screen sizes (less than `960px`)
4. See that the Overlay code is only loaded when opening the settings panel, side nav, or Picker. …
> docs: refactor navigation and settings UI to leverage trigger directive

- packages/overlay/src/Overlay.ts
- projects/documentation/src/components/side-nav-search.ts
- in Overlay, prevent `receivesFocus="false"` elements from returning focus when closed as they'll have never received focus
- in Docs, leverage `manuallyKeepOpen()` directly being we're not consuming an Interaction Controller there
1. Go [here](https://docs-search--spectrum-web-components.netlify.app/)
2. Start searching for `too`
3. See that the Search Overlay opens
4. Click away from the Search Field and Overlay
5. See that the Search Overlay closes
6. Click back on the Search Field while the value is still `too`
7. See that the Search Overlay opens
-   [ ] If my …
> docs: manage search overlay

- .circleci/config.yml
- packages/combobox/README.md
- packages/combobox/src/spectrum-combobox.css
- packages/combobox/src/spectrum-config.js
- packages/combobox/stories/combobox.stories.ts
This PR aims to fix a misalignment for the "Invalid" icon inside the combobox.
- https://github.com/adobe/spectrum-web-components/issues/4330
See https://github.com/adobe/spectrum-web-components/issues/4330 for more details.
**Disclaimer**: While this looks OK now for default state, for `quiet` state the layout is still a little bit broken. This seems to be due to `sp-picker-button` which no longer has the `quiet` styles. I propose to fix this in a different PR, since it seems to be a different issue and it affects a different component as well.
1. Go [here](https://rocss-invalid-combobox--spectrum-web-components.netlify.app/storybook/?path=/story/combobox--invalid)
2. Open the "Invalid" story and compare it against [Spectrum …
> fix(combobox): process styles for invalid state

- package.json
- projects/documentation/rollup.config.js
- yarn.lock
The font URL in the preload for the public docs site is overlay branded and doesn't point to actual files.
> docs: ensure that fonts are pointed to in the right place

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
This PR addresses an issue where large numbers were being incorrectly formatted or rounded in the valueFormatter of the component. The problem was occurring due to the default behavior of the NumberFormatter which was using grouping for large numbers. This caused values greater than 1000 to be formatted incorrectly.
Added the `useGrouping: false` option to the NumberFormatter instantiation in the valueFormatter method.
This change ensures that large numbers are formatted without grouping, preventing the rounding or truncation issues observed previously.
- #4415 
This fix improves the accuracy of number formatting for large numbers in the component, ensuring that they are displayed correctly to the user.
Tested the fix with various large numbers and confirmed that they are now formatted …
> fix(number-field): handles values greater than 1000

- packages/checkbox/src/CheckboxMixin.ts
- packages/overlay/src/InteractionController.ts
- packages/overlay/src/slottable-request-directive.ts
- tools/base/package.json
- tools/base/src/async-directive.ts
Fixing issue with various lit imports introduced in 0.42.3 release.
Both Checkbox and Overlay included imports directly from lit while neither package has lit as a direct dependency. Moving these imports to pull from base as this seems to be the established standard. 
- https://github.com/adobe/spectrum-web-components/issues/4407
Unable to install the latest release without needing to add additional dependencies. 
Successfully builds
-   [X] I have signed the …
> fix(base): move lit imports to base

- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
Picker would publish a false positive on non-accessible consumption of its API. This corrects that.
1. Open the branch locally.
2. Run Storybook
3. See that there are not Picker Dev Mode messages in the console
> chore(picker): ensure dev mode is run after external labelling may have been applied

- packages/overlay/src/OverlayStack.ts
- packages/overlay/stories/overlay-element.stories.ts
- packages/overlay/test/overlay-element.test.ts
- packages/slider/src/HandleController.ts
First, the `pointerdownPath` was being persisted past the subsequent `pointerup` event, in some cases, causing the Overlay Stack to act in a strange way
Second, the `pointerdown` event was being prevented in Slider so that it would not populate a new `pointerdownPath` over the stale value, causing the Overlay to close.
- fixes #4406
1. Go [here](https://overlay-slider--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--with-slider)
2. Open the Overlay
3. Click on the _track_ of the Slider to change its value
4. See that the Overlay is not closed
-   [x] My code follows the code style of this …
> fix(slider,overlay): ensure that pointer events in Slider are handled as expected in Overlay

- .circleci/config.yml
- packages/color-area/src/ColorArea.ts
- packages/color-handle/src/ColorHandle.ts
- packages/color-slider/src/ColorSlider.ts
- packages/swatch/src/Swatch.ts
- web-test-runner.config.js
- web-test-runner.utils.js
Separate unit and memory tests for CI time efficiencies.
@Rajdeepc @TarunAdobe it looks like we were previously skipping all of the memory tests in CI, because CI runs against non-memory tooling Chrome by default which skips those tests. This move puts the memory tests back into the workflow and four of them seem to be failing. Would yall prefer to work against this branch or to see them skipped herein so you can PR them back on, in a passing state, in individual PRs, later?
I'll also test whether we can run memory tests with concurrency in this setup.
1. [Go to CI](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/21745/workflows/c6de2dcf-9667-44dc-916d-baf2663a04f7)
2. See that [test-chromium](https://app.circleci.com/pipelines/github/adobe/spe …
> ci: run unit and memory tests separately

- packages/action-bar/src/ActionBar.ts
For older browser and UXP, we have to rely on focus-visible polyfill to match behaviour with the modern browser where the corresponding pseudo-selector is supported.
fixes https://github.com/adobe/spectrum-web-components/issues/4279
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] My code follows the code style of this …
> fix(action-bar): include focus-visible polyfilling

- packages/button/test/button.test.ts
- packages/progress-circle/test/progress-circle.test.ts
- packages/thumbnail/test/thumbnail.test.ts
- packages/underlay/test/underlay.test.ts
This PR adds more tests to SWC components in order to improve the overall code coverage across the library. 
The simple criteria that I'm following here is to have a >95% code coverage for every component.
Recently we have added a lot of `Dev Mode` warnings for in our library but didn't add respective tests for that which caused the ci to fail in main. 
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] I have …
> add more tests to improve code coverage across the library

- packages/coachmark/src/Coachmark.ts
- packages/overlay/src/overlay-trigger-directive.ts
Fixing issue with various lit imports introduced in 0.42.3 release.
Similar to https://github.com/adobe/spectrum-web-components/pull/4416 but found a few more issues that didn't show up on install but did show up when trying to upgrade. I looked at adding a `import/no-unresolved` eslint rule but ran into a few issues but we should probably look at doing this in the future. 
Both Coachmark and Overlay included imports directly from lit while neither package has lit as a direct dependency. Moving these imports to pull from base as this seems to be the established standard.
- https://github.com/adobe/spectrum-web-components/issues/4454
Unable to use the latest release without needing to add additional dependencies.
- Addressing all the various issues in error report
- Code search for any …
> fix(coachmark,overlay): adjust imports of overlay and coachmark

- packages/overlay/src/overlay-trigger-directive.ts
Ensure the `lit-html` renderer shares the same `host` between the Overlay Trigger Directive's `ElementPart` and the content it renders.
- fixes #4471
1. Go [here](https://overlay-tigger-host--spectrum-web-components.netlify.app/)
2. In a mobile context
3. Open the Site Settings menu with the Gear Icon
4. Choose a different theme "System"
5. Close the Site Settings menu
6. See that the "System" was applied
7. Open the Site Settings menu again
8. See that the new "System" persists in the selection UI
-   [x] If my change required a change to the documentation, I have …
> fix(overlay): persist "host" in directive rendered Overlay content

- projects/templates/plop-templates/args.ts.hbs
- projects/templates/plop-templates/stories.ts.hbs
- projects/templates/plop-templates/template.ts.hbs
- projects/templates/plop-templates/test.ts.hbs
- projects/templates/plopfile.js
Split `package.stories.ts` into `args.ts`, `template.ts` and `package.stories.ts` in order to support automatically forwarding Storybook content into the documentation site when generating new packages.
- refs #1822
1. Take the branch onto your local device
2. Use `yarn new-package` to generate a new component
3. I used `inline-alert` and `inlinealert` as my test answers
4. Manually manage the fact that CSS has allowed canary releases onto its `latest` channel by updating the version in the generated package JSON for `@spectrum-css/inlinealert` to [`^8.1.0`](https://www.npmjs.com/package/@spectrum-css/inlinealert/v/8.1.0).
5. Run `yarn` again.
6. Run `yarn storybook`
7. See that the "new package" is included in storybook
8. Run `yarn docs:start`
9. See that the …
> build: expand templating to support #1822 by default

- .github/dependabot.yml
Ensure Dependabot notifies people on the project when opening new pRs.
> ci: notify the swc maintainers team when creating dependabot PRs

- packages/overlay/src/HoverController.ts
- packages/tooltip/test/tooltip.test.ts
`type="hint"` Overlays should query their `target` not the `document.activeElement` when deciding whether there is `:focus-visible` enough for them to open.
fixes #4482 
1. Go [here](https://tooltip-trigger--spectrum-web-components.netlify.app/components/tooltip/#self-managed-overlays)
2. `Tab` into a button with a self managed Tooltip
3. See that the Tooltip actual opens …
> fix(overlay): ensure hint Overlays within shadow roots open as expected

- packages/overlay/slottable-request.md
- packages/overlay/trigger-directive.md
- packages/tooltip/directive.md
Begin directive documentation
1. Go to the branch docs preview
2. Visit the docs additions for:
- Slottable Requests
- The `trigger()` directive
- The `tooltip()` directive
3. See that they make sense for a consumer …
> docs(overlay,tooltip): document directive usage

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
- packages/textfield/src/Textfield.ts
Keyboard based focus of Number Fields with units should _select_ all of the available content.
- fixes #3282
1. Go [here](https://number-field-selection--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--pixels)
2. Use `Tab` to focus the Number Field, see that all of the content is selected
1. Go [here](https://number-field-selection--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--pixels)
2. Click to focus the Number Field
3. See that there is no selection in the Number Field
-   [ ] If my change …
> fix(number-field): select full value when using Tab to enter a field with a unit

- scripts/generate-tokens-wrapper.js
Removing duplicate code from `generate-tokens-wrapper.js`
-
1. Go here
2. Do this
1. Go here
2. Do this …
> fix: duplicate code to empty global-vars before generating

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
Number-field was not respecting other locales than 'en'.
- #4483 
The function `convertValueToNumber` was not receiving correct input when locale was anything other than 'en'.
In function `stepBy` earlier we were doing `this.inputElement.value = value.toString();` which was not respecting locales.
Thus to respect locales we are now formating the value like this `this.inputElement.value = this.numberFormatter.format(value);`
I wrote some tests in `Number-field.test.ts`
Test [here](https://bug-number-field-not-respecting-locale--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--german-decimals)
-   [ ] Breaking change (fix or feature that would …
> fix(number-field): updated number field to respect all locales 

- projects/documentation/content/_includes/partials/demo.njk
- projects/documentation/src/components.ts
Added the check to include type of `radio`, `text` and `number` in documentation site
- https://github.com/adobe/spectrum-web-components/pull/4285#issuecomment-2122172875
The above types are not rendered on the documentation site due to a global declaration of picker type. This is bifurcated to include types `radio,text,number`
-   [ ] documentation site
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] I have signed the [Adobe Open …
> chore(docs): updated demo examples nunjucks template to include all types of args

- .circleci/config.yml
- packages/search/README.md
- packages/search/src/Search.ts
- packages/search/stories/search.stories.ts
- packages/search/test/search.test.ts
The current implementation uses `type="search"` on the input element, causing the search value to be cleared whenever the `ESC` key is pressed. This default behavior is not always desirable.
To provide an API that allows users to determine whether the search value should be retained when the `ESC` key is pressed. This will be achieved through a new property `holdValueOnEscape`.
Property Introduction: A new Boolean property `holdValueOnEscape` is introduced. When set to `true`, the `type `attribute of the input element is set to `'text'`, preventing the default behavior of clearing the input value on `ESC`.
Default Behavior: By default, `holdValueOnEscape` is true, ensuring the value is retained when `ESC` is pressed.
Conditionally Setting Type: In the `firstUpdated` lifecycle method, the …
> chore(search): added logic to hold search value on escape

- .circleci/config.yml
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/stories/overlay.stories.ts
Currently if we use a slotted button content in `sp-dialog-wrapper`, the focus is moving in inside a `overlay-trigger` since we don't bring in `receivesFocus` from overlay. Adding `receivesFocus` makes sure that the focus can be switched off inside the dialog components
- #4562
1. Go [here](https://bug-overlay-trigger-receivesfocus--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--modal-no-focus)
2. Click on Open
3. Press ESC and close the Dialog
4. Click or Press Enter
5. See there is no focus on any element
-   [ ] Chore (minor …
> chore(overlay): overlay-trigger adds receives focus attribute

- packages/number-field/src/number-field.css
Adds two more `--mod-*` tokens as per https://github.com/adobe/spectrum-web-components/issues/4527
`--mod-textfield-border-width`
and
`--mod-textfield-border-color`.
I did not add a mod token for `--spectrum-textfield-corner-radius` because the focus outline would look weird if you modify this CSS property.
- https://github.com/adobe/spectrum-web-components/issues/4527
Consumers are able to override border's width and color when `hide-stepper` is true.
1. Go [here](https://rocss-4527--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--hide-stepper)
2. Open the developer console and define `--mod-textfield-border-width` and `--mod-textfield-border-color` on the `sp-number-field` component
3. The changes should be visible on the component.
-   [ ] …
> feat(number-field): add missing `--mod-*` tokens

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
Updated the special `convertValueToNumber` case for iPhones to correctly identify user's intent of using a decimal point.
Also changed the `,` or `.` that's being replaced with the website language specific decimal character from the first occurrence left-to-right to right-to-left. (e.g. for 1,234,56 previously the value would've been 1.23456, now it is 1,234.56 to better reflect user's intent).
(for history discussions see https://github.com/adobe/spectrum-web-components/pull/4552)
- https://github.com/adobe/spectrum-web-components/issues/4531
This solves the problem of a comma used as a separator in the number-field being interpreted as a decimal point when the user didn't want that. These changes came as a necessity since iOS keyboard shows either `,` or `.` based on device's settings. …
> fix(number-field): multiple separators use-cases in decimal inputs in iOS devices

- projects/documentation/src/components/copy-to-clipboard.ts
`extractNodeCustomElements` method which runs over the copied node text and finds out the custom lit elements starting with `sp-`
`generateImportStatements` returns the created import statements of the elements which returns
```js
const fullCopiedText = `${importStatements}\n${node.textContent}`;
```
- https://github.com/adobe/spectrum-web-components/issues/2291
- https://github.com/adobe/spectrum-web-components/issues/3517
-   [x] Copy to clipboard of code snippets with dependencies
1. Go [here](https://docs-copy-paste--spectrum-web-components.netlify.app/components/accordion/#example)
2. Click on "Copy to Clipboard" button
3. Paste it on any notepad
4. See how the dependencies are imported with the code snippet
-   [ ] Copy to clipboard for only dependencies
1. Go …
> chore: updated copy functionality to include element imports

- .circleci/config.yml
- packages/dropzone/README.md
- packages/dropzone/src/Dropzone.ts
- packages/dropzone/src/spectrum-config.js
- packages/dropzone/src/spectrum-dropzone.css
- packages/dropzone/stories/dropzone.stories.ts
- packages/dropzone/test/dropzone.test.ts
There is a new design for the dropzone component when it is in a "filled state". This PR adds this functionality to the component and respective documentation.
- https://github.com/adobe/spectrum-web-components/issues/3232
Catching up the implementation with the most up to date designs.
-   [x] _Check the new `filled` state_
1. Go to [Storybook](https://feat-filled-dropzone--spectrum-web-components.netlify.app/storybook/?path=/story/dropzone--filled)
2. Toggle the `isFilled` control.
-   [ ] _Added integration test for the `filled` attribute_
-   [ ] Chore (minor updates …
> feat: add filled state to dropzone component

- tsconfig-all.json
Missing Contextual Help from `tsconfig-all.json`, therefore types are not being published with the package.
- #4648
see #4648
1. In this repo run `yarn install`
2. Check out `node_modules/spectrum-web-components/contextual-help`
3. See that `sp-contextual-help.d.ts` exists. …
> fix(contextual-help): export typings

- packages/color-area/src/ColorArea.ts
- packages/color-area/test/color-area.test.ts
- packages/contextual-help/src/ContextualHelp.ts
- packages/contextual-help/test/contextual-help.test.ts
- packages/thumbnail/test/thumbnail.test.ts
Added some tests to improve code coverage
-
-   [x] I have added …
> chore(color-area, thumbnail): added some tests

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
This PR resolves an issue in Safari where multi-byte characters were being improperly converted, resulting in `NaN` and updates the function responsible for triggering the `change` event to ensure it behaves consistently across all supported browsers.
- fixes https://github.com/adobe/spectrum-web-components/issues/4579
`sp-number-field` + Safari + IME were in need of some love.
-   [ ] Storybook actions
1. Open the Safari browser
2. Go to the deployed/locahost `/storybook/index.html?path=/story/number-field--default`
3. In your system settings, select "Japanese" as the IME
4. Type any number in the `sp-number-field` component
5. Observe the `actions` tab on `Enter` keypress and `blur` for the expected behaviour
-   [x] Did it …
> fix(number-field): update IME change detection

- packages/number-field/README.md
Expand `number-field` doc.
- #4109
Currently, removing the number in the number field leaves the number field blank. It would be nice if the number field could repopulate to either the previous value, or the default value (ex. 0).
-   [x] If my change required a change to the documentation, I have updated the …
> chore(number-field): added default-value example to the doc site

- packages/menu/menu-item.md
- packages/menu/src/Menu.ts
- packages/menu/stories/submenu.stories.ts
- packages/menu/test/submenu.test.ts
Allow using non-menu-item components as submenu.
- #4456
Using arbitrary components as submenu items and clicking them produces the TypeError:
Cannot read properties of undefined (reading 'selectionRoot') in Menu.handlePointerBasedSelection
-   Added a test and it passed.
-   [x] …
> fix(menu): allow menu-item to support arbitrary element as the submenu root

- packages/combobox/src/Combobox.ts
- packages/combobox/test/combobox.test.ts
When a user selects a value in sp-combobox and afterwards opens the menu list of values, they expect to see a checkmark before the selected value (default menu behavior).
- #4711
Triggering the menu-open with mouse doesn't show a selected menu-item at all, only if cursor-down is used (and focus is thrown to menu-item), checkmark will be visible when menu-items are focussed and user cycles through values with cursor keys.
1. Go here
2. Do this
-   [ ] Chore (minor …
> fix(combobox): update selected item state in menu

- .eslintrc.json
- package.json
- tools/.eslintrc.json
- tools/theme/src/Theme.ts
- tools/theme/test/theme-devmode.test.ts
- yarn.lock
Add file extensions to the refactored imports in the `sp-theme` component and respective `eslint` rule to avoid running into this problem in the future. Original refactor PR: https://github.com/adobe/spectrum-web-components/pull/4743
- [SWC-486](https://jira.corp.adobe.com/browse/SWC-486)
This was breaking consumers, where some vitest configurations were not correctly resolving the files without extensions. While there might be an alternative solution, involving further tinkering with consumers configurations (e.g., tinkering and trying out different TypeScript module resolutions), this is the lowest effort path forward for all teams.
Also, I am considering this a bug-fix because it goes against our convention and status-quo.
Tried running the `yarn lint:ts` command to capture the errors: …
> fix(theme): add file extension to Theme imports and respective eslint rule

- packages/breadcrumbs/src/BreadcrumbItem.ts
- packages/breadcrumbs/test/breadcrumbs.test.ts
Due to `undefined` href attribute, breadcrumb items without hrefs would not trigger change events on keyboard Enter press.
I added a similar fix which is used for `sp-sidenav-item`, which is a placeholder href value.
Fix for #4733
1. Go [here](https://4733--spectrum-web-components.netlify.app/storybook/?path=/story/breadcrumbs--default)
2. Using the keyboard, navigate through the breadcrumb items and press "Enter"
3. In the "Actions" addon, you should see the change event was triggered.
-   [ ] Did it pass in Mobile? - N/A
-   [ ] Did it pass in iPad? - N/A
-   [ ] Breaking change (fix or feature that would …
> fix(breadcrumbs): trigger change event on breadcrumbs via keyboard

- packages/number-field/src/number-field-overrides.css
- packages/number-field/src/number-field.css
- packages/number-field/src/spectrum-config.js
Added the missing `spectrum-Stepper--sizeM` conversion to the `number-field` config and add the missing `--spectrum-stepper-width` definition (that affects both the `no size` and `size-m` variants).
- https://jira.corp.adobe.com/browse/SWC-518
Before:
After: …
> fix(number-field): add missing stepper conversion config and variable definition

- packages/search/src/Search.ts
Updated `sp-icon-magnify` from SearchBar to `sp-icon-search` to maintain compatibility between three themes
- N/A
`sp-icon-magnify` is defaulting to DefaultIcon in S2 which is a bad UX for documentation site.
1. Go here
2. Do this
1. Go here
2. Do this
-   [ ] I have signed the [Adobe Open Source …
> fix: add icon-search for s1 and s2

- packages/coachmark/coach-indicator.md
- packages/coachmark/src/CoachIndicator.ts
- packages/coachmark/stories/coach-indicator-static.stories.ts
- packages/coachmark/test/coach-indicator.test.ts
Removed the `sp-coach-indicator` "variant" and "static" attributes, along with all associated references and dependencies.
- Task: [SWC-302](https://jira.corp.adobe.com/browse/SWC-302)
- Subtask: [SWC-448](https://jira.corp.adobe.com/browse/SWC-448)
For the upcoming 1.0.0 release of Spectrum Web Components, we will remove the deprecated components and features.
-   [x] My …
> chore: remove 'variant' and 'static' attributes from coach indicator

- packages/dialog/test/dialog-wrapper.test.ts
- packages/table/test/helpers.ts
- packages/tray/test/tray.test.ts
- tools/theme/README.md
There were some forgotten instances of `system='classic'`. This PR updates them! …
> chore: rename system 'classic' to 'spectrum'

- packages/calendar/src/Calendar.ts
- packages/calendar/test/calendar.test.ts
- packages/calendar/test/helpers.ts
- packages/date-time-picker/src/DateTimePicker.ts
- packages/date-time-picker/src/date-time-picker.css
- packages/date-time-picker/src/segments/DateTimeSegments.ts
- packages/date-time-picker/src/segments/SegmentsFactory.ts
- packages/date-time-picker/stories/date-time-picker.stories.ts
- packages/date-time-picker/test/date-time-picker.test.ts
- packages/date-time-picker/test/helpers.ts
Previously, the DateTimePicker had a property named `timeGranularity`. This PR changes its name to `precision` and adds the `day` option to `hour | minute | second`. 
The image below explains the different interactions between the precision property and the most specific type of the date value props (min, max or value). 
_A few examples:_
If there is a date value prop (`min`, `max` or `value`) provided, the default precision will change to accomodate said prop. For example, if `CalendarDate` is provided but the precision isn't, the default precision will be `day`. If the type provided is `CalendarDateTime` or `ZonedDateTime`, the default precision will be `minute`.
If the precision is provided by the consumer it shouldn't be overridden. etc.
> [!NOTE]  
> _These will all be included in …
> feat(date-time-picker): added precision and value interactions

- .circleci/config.yml
- packages/calendar/package.json
- packages/calendar/test/calendar.test.ts
- packages/calendar/test/helpers.ts
- packages/date-time-picker/package.json
- packages/date-time-picker/src/DateTimePicker.ts
- packages/date-time-picker/src/helpers.ts
- packages/date-time-picker/src/segments/DateTimeSegments.ts
- packages/date-time-picker/src/segments/SegmentsFactory.ts
- packages/date-time-picker/src/segments/SegmentsFormatter.ts
- packages/date-time-picker/stories/date-time-picker.stories.ts
- packages/date-time-picker/test/date-time-picker.test.ts
- packages/date-time-picker/test/helpers.ts
This PR adds the `input` event to the DateTimePicker and updates the `change` event dispatching. This also takes care of the `invalid` state triggering in different scenarios. 
- Input event dispatches
- when the segment's value change through user inputs (type-in, increment/decrement, deletion)
- Change event dispatches
- when all the segments have a value for the first time (the value gets defined)
- when the value changes are committed on a fully defined date (Space/Enter or when the component loses focus)
- the first time when a segment is being deleted from a fully defined date
- the value is changed using the Calendar
- Invalid 
- triggers when an incomplete date is committed
- triggers when a non-compliant date is committed
- untriggers when a fully defined date is committed
- …
> feat(date-time-picker): events and invalid triggering

- .github/ISSUE_TEMPLATE/s2_report.yaml
I made a template for bug reports for SWC 1.0. The "I checked for existing issues" checkbox might be overkill, but I want people to make sure they're not filing duplicate bugs. There's probably a nicer way to "suggest" this instead of making them check a box lol, so I'm open to hearing your thoughts.
This way, we don't need to add a separate label to our existing bugs and will keep everything nice and neat :^)  …
> chore: create s2 bug report template

- .circleci/config.yml
- packages/icons-ui/stories/icons-ui.stories.ts
- packages/icons-workflow/stories/icons-workflow.stories.ts
- packages/iconset/stories/icons-demo.ts
Updated `icons-demo` class to filter workflow icons only.
Our [Doc site](https://opensource.adobe.com/spectrum-web-components/components/icons-ui/) was not showing ui-icons.
Fix the storybook and doc site examples for ui-icons.
-   Go [here](https://ttomar-icons-ui-devsite--spectrum-web-components.netlify.app/components/icons-ui/) and scroll down to see the ui-icons being displayed correctly. …
> chore: update icons-demo to filter only workflow icons

- packages/accordion/src/accordion-item.css
- tasks/build-preview-urls-comment.js
Removed `lightest` and `darkest` from our preview urls comment.
`lightest` and `darkest` are deprecated and we don't test them in our VRTs, so I removed them from our preview urls comment.
-  Manually messed up the css and tested that the preview urls didn't contain `lightest` and `darkest`
-   [x] If my change …
> chore: removed lightest and darkest from preview url

- .circleci/config.yml
Incremented the version prefix (`v3c` to `v4c` and `v3b` to `v4b`). This way, CircleCI will treat this as an entirely new cache. The previous caches will still be stored but will no longer be used for builds with the updated key prefix, effectively “clearing” the cache for the new runs.
We observed a specific issue where the transitive dependency `@spectrum-css/preview` would fail to resolve correctly on CircleCI, even though it worked locally. This suggested that an outdated or corrupted cache on CircleCI might be causing the problem. Since CircleCI caches dependencies based on a key (including the `yarn.lock` checksum), old or incompatible versions can persist in the cache, leading to the errors we were seeing.
If the check `test-chromium` succeeds, it means this worked!
-   [ ] Bug fix …
> chore: invalidate CircleCI cache

- packages/action-group/src/ActionGroup.ts
- packages/action-group/test/action-group.test.ts
Added a guard to the `manageButtons` function in the `ActionGroup` component to handle cases where `slotElement` is `null`. This prevents potential runtime errors when the `MutationObserver` triggers `manageButtons` before the component is fully rendered.
- [SWC-595](https://jira.corp.adobe.com/browse/SWC-595)
We have gotten reports from customers that they were seeing this error under some circumstances:
Adding this `null` check allows the component to handle this scenario gracefully.
-   [x] _Added a test case in action-group.test.ts_
To check it is not evergreen, comment out the newly added safeguard clause.
-   [ ] Breaking change (fix or feature that would …
> fix(action-group): add null check for slotElement in manageButtons

- tools/styles/package.json
`@spectrum-web-components/styles` currently does not declare a `lit` dependency which may cause compile errors to consumers downstream.
This fixes it. …
> chore: add lit dependency to styles

- tools/reactive-controllers/README.md
- tools/reactive-controllers/package.json
- tools/reactive-controllers/pending-state.md
Added missing `sp-progress-circle` dependency to the `reactive-controllers` package. This dependency is being used in the `pending-state` controller.
- Missing Dependency.
Missing dependencies cause errors for our consumers.
- …
> chore(reactive-controllers): add missing progress-circle dependency

- packages/combobox/test/combobox.test.ts
- packages/combobox/test/helpers.ts
- packages/overlay/src/Overlay.ts
- packages/overlay/src/PlacementController.ts
- packages/overlay/src/overlay.css
Overlay needs a `display: flex` applied so that the children render correctly when they overflow the view height and can scroll. 
Resolves overflow and scrolling issues on Firefox and Safari for the following components:
- Overlay
- Combobox
- ActionMenu
- Menu
- Menu with Submenu
- Picker
- https://jira.corp.adobe.com/browse/SWC-609
This allows users on Firefox and Safari to scroll and access all children in an overlay 
1. In Firefox open each component listed above in storybook
2. Make the viewport short
3. Content within should scroll and the container should be within the margins
1. In Safari open each component listed above in storybook
2. Make the viewport short
3. Content within should scroll and the container should be within the margins …
> fix(overlay): overlay scroll in safari and firefox

- .circleci/config.yml
- packages/calendar/src/Calendar.ts
- packages/calendar/src/calendar.css
- packages/calendar/src/spectrum-calendar.css
- packages/calendar/src/spectrum-config.js
- packages/calendar/src/types.ts
- packages/calendar/test/calendar.test.ts
- packages/calendar/test/helpers.ts
- packages/date-time-picker/src/DateTimePicker.ts
- packages/date-time-picker/src/helpers.ts
- packages/date-time-picker/src/segments/EditableSegment.ts
- packages/date-time-picker/src/segments/SegmentsFactory.ts
- packages/date-time-picker/src/segments/date/DaySegment.ts
- packages/date-time-picker/src/segments/date/MonthSegment.ts
- packages/date-time-picker/src/segments/date/YearSegment.ts
- packages/date-time-picker/src/segments/time/DayPeriodSegment.ts
- packages/date-time-picker/src/segments/time/HourSegment.ts
- packages/date-time-picker/src/segments/time/MinuteSegment.ts
- packages/date-time-picker/src/segments/time/SecondSegment.ts
- packages/date-time-picker/src/types.ts
- packages/date-time-picker/stories/date-time-picker.stories.ts
This PR aims to offer screen reader support for the most common use-cases of these components.
- Announces when a date is selected
- Announces when the month is changed
- Announces when the user navigates using Arrows or VO + Arrows
- Announces the month and year when going into the component
- Announces the type of action on previous/next month buttons
- New `labels` property to override english-default labels
- Announces the current focused segment as a stepper with the correct type translated according to the locale ('year'/'month' etc.)
- Announces if the current focused segment is Empty
- Announces the new value of the segment when it gets changed 
- Announces the type of button 'Calendar'
- Announces the spelled out date value (or 'Empty') when going into the component
- New …
> feat: screen reader support for Calendar and DateTimePicker

- packages/calendar/README.md
- packages/calendar/src/Calendar.ts
- packages/calendar/src/types.ts
- packages/calendar/stories/calendar.stories.ts
- packages/calendar/test/helpers.ts
- packages/date-time-picker/README.md
- packages/date-time-picker/package.json
- packages/date-time-picker/src/DateTimePicker.ts
- packages/date-time-picker/src/helpers.ts
- packages/date-time-picker/src/types.ts
- packages/date-time-picker/stories/date-time-picker.stories.ts
- packages/date-time-picker/test/date-time-picker.test.ts
- packages/date-time-picker/test/helpers.ts
- projects/story-decorator/decorator.ts
- projects/story-decorator/src/StoryDecorator.ts
- storybook/preview.js
Updating the documentation of the new components: Calendar and DateTimePicker according to implemented features for the initial release.
Also, the storybook was updated to include the locale picker using the chromatic globals settings.
- https://github.com/adobe/spectrum-web-components/issues/2559
- https://github.com/adobe/spectrum-web-components/issues/2560
Ease of use.
Main changes has been tested in Storybook and on the local docs server.
-   [x] I have …
> docs: updated documentation for Calendar and DateTimePicker components

- .github/workflows/coveralls.yml
- web-test-runner.config.js
- web-test-runner.utils.js
This PR addresses a temporary issue with the Playwright version mismatch in the Coveralls workflow caused by the recent upgrade of Playwright to 1.49.0. This happens because `@web/test-runner-playwright `expects an older browser binary (`chromium-1117`), but the newer version of Playwright downloads `chromium-1148`.
Longer term fix can involve bypassing the web-test-runner browser configs and accessing the Playwright binaries directly.
- Follow up from https://github.com/adobe/spectrum-web-components/pull/5005
The Playwright version mismatch is currently breaking the Coveralls workflow with the error:
Executable doesn't exist at `/home/runner/.cache/ms-playwright/chromium-1117/chrome-linux/chrome`.
I added a new `playwrightLauncher` configuration: "coverallsChromium". This explicitly sets …
> build: fixing coveralls

- storybook/preview.js
update the storybook build to apply `spectrum-two` theme correctly
- storybook was not updating to `spectrum-two` theme on selection
Storybook was not working and I was confused as to why spectrum-two and spectrum-one looked exactly the same!
1. Go [here](https://ttomar-storybook--spectrum-web-components.netlify.app/storybook/)
2. Toggle the theme between s1, s2 and express.
3. Verify that the theme actually changes now.
-   [x] I have …
> build: fix the storybook theme select

- packages/button-group/src/ButtonGroup.ts
- packages/button-group/test/button-group.test.ts
- tools/base/test/sizedMixin.test.ts
Makes `sp-button-group` react to changes in `size` attribute.
- https://github.com/adobe/spectrum-web-components/issues/5030
https://github.com/adobe/spectrum-web-components/issues/5030
1. Go [here](https://rocss-5030--spectrum-web-components.netlify.app/storybook/?path=/story/button-group--buttons)
2. Using the Controls Addon, change the size
3. Observe the component reacts to the change accordingly …
> feat(sp-button-group): sp-button-group react to size updates

- .circleci/config.yml
With the introduction of Yarn 4, we need to update the build steps for deploying our documentation website in CI. This PR [aligns the implementation](https://github.com/adobe/spectrum-web-components/pull/5010/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R209-R219) with the changes already merged for deploying the documentation website and Storybook previews in each PR.
Did you know? We automatically deploy a beta documentation website every time we merge to `main`.
You can visit it here: [https://beta–spectrum-web-components.netlify.app/](https://beta--spectrum-web-components.netlify.app/)
Without this fix, the beta documentation website won’t be deployed.
-   [ ] New feature (non-breaking change …
> chore: simplify beta docs deployment steps

- packages/tooltip/src/tooltip.css
This PR will fix two things - 
1.  #4803 ([Bug][Firefox]: Long tooltip text results in tooltip offset to the left )
2. Long tooltip was updating the trigger element width in Safari.
I've replaced the `inline-size: max-content;` to `white-space: initial;
max-width: var(--spectrum-tooltip-max-inline-size);` to make sure firefox is supported.
- #4803 
Delivering tooltip consistently across all browsers.
-   Tooltip Delivery Testing
-  Open [this link](https://ttomar-tooltip-positioning--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--self-managed&globals=color:dark) in Firefox
- Open [this link](https://ttomar-tooltip-positioning--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--self-managed&globals=color:dark) in Safari
- Open [this …
> fix(tooltip): make tooltip delivery consistent across all browsers

- packages/overlay/src/AbstractOverlay.ts
- packages/overlay/src/OverlayDialog.ts
- packages/picker/stories/picker.stories.ts
Stop the click events to reach the element below tray when we open a picker in iOS <17
- fixes #5042
* Prevents the event leaking out of the dialog to the element below it.
* This is a workaround for a bug in iOS <17 where the event leaks out of the dialog to the element below it. 
- Go [here](https://picker-background-click--spectrum-web-components.netlify.app/storybook/?path=/story/picker--background-click-test&globals=color:dark) in iOS<17 
-   Manually Tested. See the attached Video below for before and After:
[screen-capture.webm](https://github.com/user-attachments/assets/57520995-d025-4042-8c00-988df3519ddf)
[screen-capture (1).webm](https://github.com/user-attachments/assets/d5b9d014-e866-4ece-b496-f260a780247b)
- …
> fix(picker): stop the click events from reaching the elements below picker-tray

- .github/workflows/chromatic-vrt.yml
Workflow action for Chromatic was using an outdated workflow that did not include the custom element assets being moved into the storybook directory. This fixes that.
-   [x] Build
-   [n/a] I have added tests to cover my changes.
-   [n/a] All new and existing tests passed. …
> build: fix chromatic build workflow github actions

- .circleci/config.yml
- packages/action-menu/stories/action-menu.stories.ts
- packages/picker/src/InteractionController.ts
- packages/picker/src/Picker.ts
- packages/picker/stories/picker.stories.ts
Fixes an incorrect hardcoded placement value (`"bottom"`) in `this.overlay.placement`, which was mistakenly introduced while prototyping and made its way to production. This ensures that the placement is correctly derived from `this.host.placement`, maintaining expected behavior for dropdowns in components like ActionMenu, Picker, etc.
Also changed the attribute reflection to adhere to our pattern (`"forcepopover"` -> `"force-popover"`).
- [SWC-644](https://jira.corp.adobe.com/browse/SWC-644)
In https://github.com/adobe/spectrum-web-components/pull/5041, the `forcePopover` feature was introduced to render a popover instead of a tray on mobile. However, the placement was mistakenly set to `"bottom"` instead of using `this.host.placement` (which defaults to `"bottom-start"` in Picker.ts). …
> fix(overlay): derive popover placement from host in interaction controller

- .github/workflows/beta-release.yml
- package.json
We want `beta` release artifacts to be 1:1 with those in `latest`, so we need to add the `prelerna-publish` command which generates the `custom-elements.json` manifests and runs the script to verify the build artifacts.
Without this, the manifests do not get published.
You can see the build artifacts of a beta test release here: https://www.npmjs.com/package/@spectrum-web-components/button/v/1.2.0-beta.3?activeTab=code
And you can see the action run here: https://github.com/adobe/spectrum-web-components/actions/runs/13309656501/job/37168759349?pr=5094
-   [x] Chore (minor …
> chore: add prelerna-publish to beta releases

- .circleci/config.yml
- packages/slider/src/Slider.ts
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider.test.ts
This PR addresses a Safari-specific issue where slider labels would disappear when a related hover-overlay is triggered and the user moves the pointer away from the slider. The problem was occurring both when using the `label` attribute and when using the default slot for text labels.
The fix ensures that the label element remain visible in the DOM regardless of hover state changes, which prevents Safari's hover state behavior from causing the disappearing label issue.
Additionally, this PR marks the default slot as deprecated, because we don't need two APIs for doing the same thing, so we want to encourage users to use the label property instead of the slot for text labels.
- [SWC-694](https://jira.corp.adobe.com/browse/SWC-694)
- Fixes …
> fix(slider): make label not disappear when using overlays in Safari

- packages/dialog/src/Dialog.ts
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/test/dialog.test.ts
- projects/documentation/content/migrations/2024-10-31 (1.0.0).md
The `error` property was not properly deprecated with a full migration plan in place. This has caused confusion and false sense of urgency for consumers to migrate. We are removing it to eliminate those pain points for consumers while we take a deep look at our dialogs and patterns. 
- resolves https://github.com/adobe/spectrum-web-components/issues/4935
reduce confusion and false urgency
1. Go to dialog error story
2. don't see a deprecation warning
1. Go to dialog-wrapper error story
2. don't see a deprecation warning
-   [ ] …
> fix(dialog, dialog-wrapper): remove dialog error property deprecation

- packages/menu/test/submenu.test.ts
- storybook/preview.js
Dependencies load versions of Typescript that do not support the `with` assertion for file types that was introduced in V5.3.0.
- resolves #5183
- Make Storybook work locally
1. Pull branch
2. run `yarn storybook`
3. Check there's no error message for the custom-element-manifest.json
-   [X] Did it pass in Desktop?
-   [X] I have signed the [Adobe Open Source …
> chore: fix storybook preview runtime error + flaky tests

- .changeset/moody-points-speak.md
- packages/menu/src/Menu.ts
- packages/menu/test/menu.test.ts
- Mouse click, arrow keys, and mouseover should set the focused item.
- The visual focus is based on the focused item.
- If the keyboard last set the focus but the mouse is still over the menu, there will be an item with focus styling and an item with hover styling.
- #5180
Currently users are not able to mouseover to open submenus and set selected items.
-   [ ] Using your mouse...
1. Go to https://nikkimk-fix-submenu-mouseover--spectrumwc.netlify.app/storybook/index.html?path=/story/action-menu--submenu
2. Click on action menu
3. Select item with submenu
4. Notice that focus styling follows the mouse
5. Reopen action menu again
6. See correct item is focused
- …
> fix(menu): focuson mouseover

- .github/dependabot.yml
This PR updates .github/dependabot.yml to set open-pull-requests-limit: 0, effectively preventing Dependabot from opening new version bump PRs while keeping security updates active.
- Reduce noise from unnecessary dependency update PRs.
Stop automatic version bump PRs while still allowing security alerts.
-   [ ] Verified that security updates remain active.
-   [ ] Confirmed that no existing PRs are affected by this change.
-   [x] I have signed the [Adobe …
> ci: stop dependabot PRs for cutoff

- packages/radio/README.md
- packages/radio/radio-group.md
Separating the radio and radio-group docs so that each one has its own API section
-
Review [radio docs](https://nikkimk-a11y-docs-radio-group--spectrum-w-c.netlify.app/components/radio/)
-  [ ] Are the docs specific to and accurate for `<sp-radio>`?
-  [ ] Do the docs examples give enough context to test for accessibility?
-  [ ] Do the docs examples and text provide information on how to use the component accessibly?
-  [ ] If the component is to be used in the context of another component, do the examples include how that component is used accessibly in that context?
-  [ ] Are the docs headings logical and consistent across these components? (You can use the [WAVE browser extension's](https://wave.webaim.org/extension/) **Structure** tab to review heading structure.)
Review …
> docs(radio-group): split radio-group docs from radio docs

- package.json
- yarn.config.cjs
- yarn.lock
[Yarn constraints](https://yarnpkg.com/features/constraints) allow enforcement of rules across workspaces in a project.
This update does not apply the constraints, but rather defines them so they can be reported. We can do a separate PR to apply the updates via: `yarn constraints --fix`.
This update adds package.json standardization rules such as:
- If no license is listed, use Apache-2.0 which is the standard for Adobe open source projects
- Expects author to be "Adobe"
- Sets the correct repository details, including accurately reflecting the directory location
For non-component packages, this update expects packages:
- To use a default set of keywords ('design-system', 'spectrum', 'adobe', 'adobe-spectrum', 'web components', 'web-components', 'lit-element', 'lit-html')
- If no homepage …
> chore: add basic project constraints

- renovate.json
Adding a [postUpgradeTask](https://docs.renovatebot.com/configuration-options/#postupgradetasks) to the renovate workflow, we give it the opportunity to generate and commit the processed assets when the @spectrum-css packages are updated.
This update is a step toward having renovate automatically generate dependency updates for SWC without manual developer intervention or initiative.
Some enhancements we can explore in the future but don't block this current update.
- fileFilters: seems valuable to be more explicit here about what file updates are allowed
- Once constraints are added, we should probably run the `yarn constraints --fix` command here as well
- Can these commands be customized to only run for certain types of package updates?
- Option to add an npm script to create the …
> chore: add build command to renovate

- packages/picker/stories/picker.stories.ts
There's a flaky test in picker where the first menu item should be selected but sometimes the `value="1"` from picker hasn't updated the nested `menu-item` before a snapshot is taken. To address this and reduce flakiness, this update adds the selected state to the first item to prevent this instability.
-   [ ] _Picker iconsNone_: Expect this test case to pass consistently …
> test(picker): force menu-item selected

- .changeset/brave-crews-win.md
- .changeset/cool-emus-appear.md
- .changeset/cute-peas-chew.md
- .changeset/good-lizards-brake.md
- .changeset/itchy-dots-draw.md
- .changeset/lazy-rivers-camp.md
- .changeset/public-steaks-juggle.md
- .changeset/sharp-dodos-start.md
- .changeset/tidy-oranges-agree.md
- .changeset/warm-ducks-dig.md
Update changesets to collate duplicate messages into 1 changeset. Also adds the missing color-handle update.
- Expect to see 1 changeset and the deletion of all other changesets with the same messaging.
-   [n/a] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [n/a] I have added tests to cover my changes.
-   [ ] All new and existing …
> chore: align and update changesets

- .github/workflows/browser-tests.yml
When pull requests are opened by tools or utilities, [example](https://github.com/adobe/spectrum-web-components/actions/runs/13961757174), pull request comments cannot be written.
The best way to validate this fix is to merge this update into main and then see if the comment step of the tachometer passes when dependabot opens another pull request. …
> chore: update tachometer reporting to stabilize ci [SWC-767] 

- .changeset/curvy-boxes-poke.md
- .circleci/config.yml
- packages/button/package.json
- packages/button/src/button-overrides.css
- packages/button/src/spectrum-button.css
- tools/styles/tokens-v2/system-theme-bridge.css
- tools/styles/tokens/express/system-theme-bridge.css
- tools/styles/tokens/spectrum/system-theme-bridge.css
- yarn.lock
This update aims to simplify `--mod-*` access by ensuring local variants and states aren't hooking into those custom properties for overrides. This updates all local variants and states to override the `--spectrum-button-*` properties instead and adjusts the specificity to ensure no regressions in rendered results.
This also involves pulling in the fixes from the previous 2 releases as well:
From [@spectrum-css/button v14.1.3](https://www.npmjs.com/package/@spectrum-css/button/v/14.1.3): [#3613](https://github.com/adobe/spectrum-css/pull/3613)
Adjusts static color buttons to more closely resemble the S2 specifications. There are no expected changes to non-static button variants in S2, and no expected changes to other themes.
This PR includes changes to:
-   Static white primary button …
> fix(button): hoisted modifier access 

- packages/field-label/README.md
- SWC-380
Review [field label docs](https://caseyisonit-swc-380-field-label-docs--spectrum-wc.netlify.app/components/field-label/)
-  [ ] Do the docs examples give enough context to test for accessibility?
-  [ ] Do the docs examples and text provide information on how to use the component accessibly?
-  [ ] If the component is to be used in the context of another component, do the examples include how that component is used accessibly in that context?
-  [ ] Are the docs headings logical and consistent across these components? ([1](#wave))
<a id="wave">1.</a> You can use the [WAVE browser …
> docs: field-label accessibility docs

- .changeset/stale-candies-camp.md
Package name was mistyped in the changes: https://github.com/adobe/spectrum-web-components/actions/runs/14597650232/job/40947560598
-   [x] I have reviewed at the Accessibility Practices for this …
> chore: correct package name in changeset

- projects/documentation/content/guides/adding-component.md
- projects/templates/plop-templates/README.md.hbs
- Updating contributor docs to include "States" section heading.
- Updating readme template to include recommended heading structure.
- SWC-91
Review the recommended [documentation structure](https://nikkimk-update-docs-structure--spectrum-wc.netlify.app/guides/adding-component/#documentation-structure)
-   [x] I have signed the [Adobe Open …
> docs: updated docs heading structure

- CHANGELOG.md
Add in the changelog notes to global changelog for 1.6.0
-   [ ] I …
> chore: add 1.6.0 changelog notes

- .changeset/tricky-fans-drive.md
- packages/tabs/package.json
- yarn.lock
This PR adds the `@spectrum-web-components/action-button` dependency to the `sp-tabs` component to maintain consistency with other components in the library. TabsOverflow uses `sp-action-button` as its direct dependency.
- N/A
The TabsOverflow component was missing the `@spectrum-web-components/action-button` dependency that other components utilize, which could lead to inconsistencies when implementing shared features. Adding this dependency ensures that the TabsOverflow component follows the same patterns as the rest of the library and can leverage common functionality.
> fix(tabs): added missing direct dependency of action-button in TabsOverflow component

- packages/overlay/README.md
- packages/overlay/imperative-api.md
- packages/overlay/overlay-trigger.md
- packages/overlay/slottable-request.md
- packages/overlay/src/Overlay.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/trigger-directive.md
- SWC-390
Review [overlay docs](https://ttomar-docs-overlay-a11y--spectrum-wc.netlify.app/components/overlay/)
-  [x] Do the docs examples give enough context to test for accessibility?
-  [x] Do the docs examples and text provide information on how to use the component accessibly?
-  [x] If the component is to be used in the context of another component, do the examples include how that component is used accessibly in that context?
-  [x] Are the docs headings logical and consistent across these components? You can use the [WAVE browser extension's](https://wave.webaim.org/extension/) **Structure** tab to review …
> docs(overlay): a11y docs update

- packages/dialog/README.md
- packages/dialog/dialog-base.md
- packages/dialog/dialog-wrapper.md
- projects/documentation/content/guides/adding-component.md
- projects/documentation/scripts/build-search-index.js
- Improving the accessibility documentation of dialog components.
- SWC-374
- SWC-375
- SWC-376
Review [dialog docs](https://nikkimk-dialog-docs--spectrum-wc.netlify.app/components/dialog/)
-  [ ] Do the docs examples give enough context to test for accessibility?
-  [ ] Do the docs examples and text provide information on how to use the component accessibly?
-  [ ] If the component is to be used in the context of another component, do the examples include how that component is used accessibly in that context?
-  [ ] Are the docs headings logical and consistent across these components? You can use the [WAVE browser extension's](https://wave.webaim.org/extension/) …
> docs(dialog): updated dialog docs for accessbility

- packages/toast/README.md
Improving the accessibility documentation of the toast component.
-   SWC-834
---
-   [x] I have added automated tests to cover my changes. _(N/A this is a docs PR)_
-   [x] I have included updated documentation if my …
> docs(toast): updated toast docs for accessibility

- .github/workflows/preview-release.yml
This adds a conditional check to the `preview-release` workflow to only run on commit types `feat`,`fix`, or `!:`. The `!:` will capture any breaking change.
- Reduce the number of preview releases published
- Only release functional testable code 
-   relates to PR #5365
-   [x] I have added automated tests to cover my changes.
- …
> chore: add conditional check to preview release

- .changeset/cuddly-lands-work.md
- package.json
- packages/card/package.json
- yarn.lock
`sp-card` has a direct import of `import '@spectrum-web-components/popover/sp-popover.js';` as its direct dependency but it is missed as import in its dependency tree in `package.json.
Added missing `sp-popover` dependency in `sp-card`
-   fixes SWC - 868
---
-   [ ] I have …
> fix(card): added missing sp-popover dependency

- tools/shared/src/focusable-selectors.ts
Extend the focusable selector to avoid retrieving elements with attribute `focusable="false"` , see: #5431 
- fixes #5431
SVGs with `focusable="false"` should not be detected. …
> fix: skip elements with focusable="false" attribute

- .changeset/happy-cycles-check.md
- packages/overlay/src/OverlayStack.ts
- packages/picker/test/index.ts
This PR addresses an issue where overlays (particularly pickers and action menus) were incorrectly closing when scrolling occurred within a component, rather than only closing on document/body scrolling.
Previously, the `handleScroll` method in the OverlayStack class would trigger for all scroll events, including those that occurred within components. This caused overlays to close unexpectedly when users scrolled within menus, lists, or other scrollable content inside components.
The fix is straightforward - we now check the scroll event target at the beginning of the handleScroll method to determine if it's a document-level scroll or a component-level scroll:
```ts
if (event.target !== document && 
event.target !== document.documentElement && 
event.target !== document.body) {
return;
} …
```
> fix(overlay): scroll jitter due to layout thrashing in safari and safari

- .changeset/word-break-updates.md
- packages/sidenav/src/spectrum-sidenav-item.css
- packages/textfield/src/textfield.css
- packages/tooltip/src/spectrum-tooltip.css
Replace deprecated `word-break: break-word` with `overflow-wrap: break-word` to align with modern CSS standards and improve cross-browser compatibility. This property was deprecated in Chrome 44 (July 2015) in favor of the standardized `overflow-wrap` property.
I've been seeing a lot of stylelint warnings about this property-value pairing and after doing a little research, found a non-deprecated alternative to accomplish the same results.
-   fixes [CSS-1223]
--- …
> fix(tooltip,textfield,sidenav): update deprecated css [CSS-1223]

- .circleci/config.yml
- .eslintrc.json
- .github/workflows/lint.yml
- .gitignore
- .stylelintrc.json
- package.json
- yarn.lock
This migrates linting from CircleCI to GitHub Actions.
The current linting in CI is more-or-less boolean (did it pass or not) but requires pulling down the branch locally and linting to fix things. This update moves our linting work into a GitHub Action that uses ReviewDog to lint and report back to the pull request what the linter identified.
---
---
-   [ ] Includes a Github Issue with appropriate flag or Jira ticket …
> chore: migrate linting from circleci to github actions

- .github/workflows/lint.yml
Identified a bug in this [run](https://github.com/adobe/spectrum-web-components/actions/runs/15588961722/job/43902673269) requiring the checkout action to be run before the changed files can be identified.
This is only an issue when run from a push event and not from a pull request.
> chore: checkout before fetching changed files to have a baseline to run against

- .changeset/grumpy-forks-bathe.md
- packages/switch/src/switch.css
This work builds off of the `spectrum-two` fix for this in https://github.com/adobe/spectrum-css/pull/3767, but addressing the same bug in the S1 context for SWC components. The switch in either context should now respond appropriately to the active state, with the active styles taking precedence over any hover styles. When a user now activates the active/down state, a visual difference can be noted, and that visual difference is no longer dependent on mouse movement (where it was incorrect before).
**New behavior**
https://github.com/user-attachments/assets/f1b8306c-6001-4d54-a733-5b160bd7f620
It was brought up in a Slack bug report that the switch may have some specificity issues between the hover and active states. The original message noted how to reproduce what they were seeing: 
> …
> fix(switch): down state styles take precedence over hover

- .changeset/fair-carrots-kiss.md
- tools/styles/tokens-v2/global-vars.css
- tools/styles/tokens-v2/index.css
- tools/styles/tokens-v2/spectrum/custom-vars.css
- tools/styles/tokens/index.css
- tools/styles/tokens/spectrum/custom-vars.css
- tools/styles/tokens/spectrum/global-vars.css
- tools/styles/tokens/spectrum/index.css
A contributor identified that one of our alias tokens for CJK font was pointing to the code font-family stack instead of the appropriate (and expected) CJK font-family stack.
-  Fix brought over from CSS contribution https://github.com/adobe/spectrum-css/pull/3936
-   [n/a] I have added automated tests to cover my changes.
-   [n/a] I …
> fix(styles): cjk alias mapping fixed

- .github/ISSUE_TEMPLATE/bug_report.yaml
Added a new field to the GitHub bug report template prompting users to include the version of @spectrum-web-components they’re using when filing issues.
While triaging recent bugs, I noticed that many reports were missing the library version. This information is often crucial for reproducing and resolving issues, especially when version-specific regressions or changes are involved
-   [ ] I have added automated tests …
> chore: add library version input field in bug report template

- .cursor/README.md
- .cursor/config.json
- .cursor/rules/branch-naming.mdc
- .cursor/rules/jira-ticket.mdc
- .cursor/rules/styles.mdc
- .cursor/rules/text-formatting.mdc
Added structured rules configuration for Cursor to enforce consistent formatting in documentation and Jira tickets. This includes:
- JSON configuration for enforcing text formatting rules
- Standardized templates for Jira tickets
- Automated validation of ticket structure and labels
- Documentation for rule usage and maintenance
This change provides automated enforcement of our documentation standards and Jira ticket formatting, ensuring consistency across the project. It helps team members create well-structured tickets and maintain consistent documentation formatting without manual oversight.
-   fixes CSS-1222
---
---
-   [x] Includes a Github Issue with appropriate flag or Jira ticket number without a link
-   [ ] Includes thoughtfully written changeset if changes suggested include …
> chore: cursor utilities [CSS-1222]

- tools/styles/fonts.css
- tools/styles/src/spectrum-detail.css
- tools/styles/src/spectrum-heading.css
- tools/styles/typography.css
Removes  `--spectrum-detail-margin-start` and `--spectrum-detail-margin-end` definitions from `.spectrum-Detail` and `.spectrum-Heading` ensuring margin custom properties are scoped only to .spectrum-Typography .spectrum-Heading and .spectrum-Typography .spectrum-Detail. 
We recently made a change in the Typography CSS that unintentionally scoped margin custom properties more broadly than intended. Typography margin custom properties should only be scoped to .spectrum-Typography
-   fixes [CSS-1248](https://jira.corp.adobe.com/browse/CSS-1248)
-   [x] I …
> fix(typography): unintended typography element margins

- packages/tabs/README.md
`SWC-412`
---
-   [x] Includes a Github Issue with appropriate flag or Jira ticket number without a link
-   [ ] Includes thoughtfully written …
> docs(tabs): update a11y docs

- packages/overlay/test/overlay-testing-helpers.ts
- packages/overlay/test/overlay-trigger-extended.test.ts
`SWC-1016`
`oneEvent(overlay, 'sp-opened')` returned a promise which is always truthy, meaning `(overlay && oneEvent(overlay, 'sp-opened'))` evaluates to a truthy promise and `waitUntil` returns immediately and never waits.
Now, we return early if the overlay's in the desired state, wait for the state change or event to occur and properly await the overlay transition.
This was causing test failures in CI for unrelated changes.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria …
> fix(overlay-testing-helpers): resolve race condition that lead to flaky test results

- packages/number-field/test/number-field.test.ts
Test failure identified during `yarn test:focus no-memory-ci` run
Test fails on Webkit with AssertionError: name is the label text: expected { Object (role, name) } to be null
After a deeper investigation with @nikkimk, the fix for this test to pass the way its set up would require work to the component which is out of scope for this task and has been flagged with a TODO so we know why this test is getting skipped in WebKit
> NOTE: other VRT and tests WILL fail and be resolved in future tasks, this is going in to the WTR feature branch which will have passing tests before merge to main.
The accessibility model test "increment and decrement buttons cannot receive keyboard focus" should pass
-   fixes [SWC-1006] …
> chore: disable flaky number field test in webkit

- .changeset/seven-yaks-open.md
- packages/number-field/test/number-field.test.ts
**Overview**
This PR addresses test flakiness in the number-field component's stepper UI pointer interaction test by adding proper element update awaits.
**Changes Made**
- Test Stability Improvements
- Added await elementUpdated(el) after mouse move operations to ensure DOM updates complete
- Added await elementUpdated(el) after input events to ensure value changes are reflected
- Added await elementUpdated(el) after frame waiting loops to ensure all pending updates complete
**Specific Fixes**
After moving to step-down button: Added await to ensure the element processes the pointer movement
After moving outside the buttons: Added await to ensure continuous input processing completes
After input events: Added await to ensure value updates are applied to the DOM
After frame waiting: Added …
> test(number-field): ensure element updates after input events

- packages/color-wheel/README.md
This PR reorganizes the color-wheel README.md to follow the established documentation standards structure, improving accessibility and consistency with other components.
**### Changes Made**
**Structure Reorganization**
- Overview: Replaced "Description" with "Overview" section and expanded component description
- Usage: Updated import code blocks with proper language syntax highlighting (bash, javascript)
- Anatomy: Added new section describing the component's key parts, basic usage, and custom gradient slot
- Options: Created comprehensive properties documentation including:
- Value (Hue) control
- Color format examples
- Step size configuration
- Label customization
- Direction support
- Custom sizing (moved from Variants section)
- States: Reorganized disabled state and added focused …
> docs(color-wheel): enhance README 

- packages/avatar/README.md
`SWC-358`
---
-   [x] Includes a Github Issue with appropriate flag or Jira ticket number without a link
-   [ ] Includes thoughtfully written …
> docs(avatar): update a11y docs

- netlify.toml
We no longer deploy to Netlify, so we don't need a `netlify.toml`.
> chore(netlify): remove netlify.toml now that Azure is used for deployments

- tools/opacity-checkerboard/README.md
This PR reorganizes the opacity-checkerboard README.md to follow the established documentation standards structure, improving accessibility and consistency with other components.
**Structure Reorganization**
* **Overview**: Replaced "Description" with "Overview" section to align with documentation standards
* **Usage**: Updated import code blocks with proper language syntax highlighting (`bash`, `javascript`)
* **Integration**: Added new section with clear guidance on how to integrate the CSS utility into components
* **Examples**: Created comprehensive examples section with:
* Basic usage with accessibility attributes
* Overlaid content demonstration showing transparency effects
* **Accessibility**: Added comprehensive new section including:
* Screen reader support with proper ARIA …
> docs(opacity-checkerboard): enhance README with detailed usage

- .changeset/eight-parts-begin.md
- .circleci/config.yml
- packages/alert-dialog/src/alert-dialog-overrides.css
- tools/styles/tokens-v2/system-theme-bridge.css
- tools/styles/tokens/express/system-theme-bridge.css
- tools/styles/tokens/spectrum/system-theme-bridge.css
This PR improves the Alert dialog component in spectrum-two theme.
The divider color should be transparent for S2 theme.
Fix the regressions found after changing from the express theme to the spectrum-two theme.
SWC-1077 (original)
CCEX-230905
Spectrum 1
Spectrum 2
Express
---
- …
> fix(sp-alert-dialog): Make the divider color transparent for S2 theme

- .circleci/config.yml
- packages/picker/src/Picker.ts
- packages/picker/src/picker.css
- packages/picker/stories/picker.stories.ts
- packages/popover/src/popover.css
This PR adds styles to the `popover.css` to enforce a fixed width when the popover is used within the picker component. This aligns with the design documentation and the picker component styles.
Without this change the rendered picker options will grow in width without wrapping for longer labeld.
-   fixes SWC-562
-   [ ] I have included a well-written changeset …
> fix(picker): add picker attribute to nested popover and styles to constrain to picker width

- first-gen/packages/progress-circle/src/ProgressCircle.ts
- second-gen/packages/core/components/progress-circle/ProgressCircle.base.ts
- second-gen/packages/swc/components/progress-circle/ProgressCircle.ts
- second-gen/packages/swc/components/progress-circle/progress-circle.css
- second-gen/packages/swc/components/progress-circle/stories/progress-circle.stories.ts
Updates the 2nd-gen Progress Circle component to the latest CSS styles from Spectrum CSS `spectrum-two` branch. This updates Progress Circle for the barebones milestone components with more complete S2 functionality including determinate/indeterminate states, sizing variants, and static color options.
**Note**: there are known rendering issues with the SVG being cut off at the bottom but it has been approved to move forward and resolve that issue at a later time.
- fixes SWC-1270
1. Go to Storybook Progress Circle stories
2. Test determinate progress values (0-100%)
3. Expect smooth visual progress indication
1. Toggle indeterminate property in Storybook
2. Observe animated loading indicator
3. Expect continuous rotation animation
1. Review small (s), medium (m), and large (l) sizes
2. …
> feat(progress-circle): migrate progress circle component to second-generation architecture
