- packages/shared/src/index.ts
Make an actual entry point for the `shared` package.
We should be able to see the package statistics at https://bundlephobia.com/result?p=@spectrum-web-components/shared, and when we can't it bungles getting statistics for the whole library.
> fix(shared): include an actual entry point for bundlephobia

- packages/overlay-root/src/active-overlay.ts
This is a fix for issue #104. Overlays were opening in the wrong place on Edge because Edge had not yet done the DOM layout when the position computation was done. The overlay DOM element had a size of zero in both dimensions.
#104 
Any kind of overlay looks busted on Edge
Manual testing of Storybook cases.
> Make overlays open in correct position on Edge

- .circleci/config.yml
Let's publish the documentation on a regular basis! How's every time we merge to master?
fixes #77 
Up-to-date docs are great.
> ci: publish docs when merging to master

- .circleci/config.yml
- documentation/src/components/side-nav.ts
- package.json
- yarn.lock
Linking to `/` does not perform as expected when a site lives in a subfolder. Use `#` instead, because the `<base>` tag allows it. Update publication step in CI to use `gh-pages`.
Everyone wants to go home again. And publishing!
> docs: update publication and link home correctly

- documentation/src/components/component.ts
- documentation/src/components/home.ts
Use headers more consistently.
fixes #330
Things should be accessible.
Visual comparison between current site and updates.
> docs: use headers for accessibility

- test/visual/screenshots-baseline/regenerate.js
- test/visual/visual.js
Speed up visual tests by using cacheing... who knew?
Faster feedback, better code!
Ran the CI a couple of times and regularly rated >2 minutes _faster_ that before 🎉 You're better off not questioning my statistical process here...
> test: use cache when visual testing

- package.json
- packages/styles/fonts.css
- packages/styles/package.json
- scripts/spectrum-vars.js
- yarn.lock
Added the @spectrum-css/commons package since we need to source our
fonts.css from 2 file to get what we need. Also updated the generation
script to allow building from multiple source files.
Fixes #308
Let's get rid of manual changes needed to update spectrum css.
I ran the visual tests locally, and also did some testing on the local doc site (including a bit of manual inspection to make sure the styles I expected to see were there).
I haven't done a deep inspection though, since I'm still not sure how much this affects.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I …
> fix: font.css not auto-generated from spectrum-css

- packages/checkbox/src/checkbox-base.ts
- packages/checkbox/src/checkbox.ts
- packages/switch/src/switch.ts
This pr applies `...super.styles` to `checkbox-base`, such that the disabled state can become more stable. Accordingly, `...super.styles` is also applied to `checkbox` and `switch`. 
In `crisp-component`, the redgreen switch is extended from `sp-switch`. During the implementation, I found that the disabled state of the switch didn't disable pointer events. In SWC, the style of `focusable` already has a rule to disable pointer events in disabled state. This style should be applied to the extended components such as `checkbox-base` (and then `switch`).
> fix: focusable style

- packages/button/src/action-button.ts
- packages/button/src/button-base.css
- packages/button/src/button-base.ts
- packages/button/src/button.ts
- packages/button/src/clear-button.ts
- packages/dropdown/src/dropdown.ts
- packages/shared/src/focusable.css
Removing selected outline on focusable components (checkbox, button, dropdown) when clicking on components.
[#318](https://github.com/adobe/spectrum-web-components/issues/318)
Clicking on components should select the component and not show tab focus.
Manual interaction in storybook.
> Tab selection focus on focusable components

- packages/link/src/link.ts
- packages/radio/src/radio.ts
- packages/shared/README.md
- packages/slider/src/slider.ts
- packages/textfield/src/textfield.css
- packages/textfield/src/textfield.ts
Use `super.styles` in all `Focusable` extensions that don't already have it available. This allows for `click` events on non-`focusElement` covered areas to occur without errantly focusing the element root.
fixes #318
@cdvu1 did a great job fixing this in the elements her team is actively using, but as I was about to release those updates I realized that the change would bump the version of the element included herein anyway, so I wanted to ensure that they include these updates, too.
Manually in storybook
> fix: apply Focuable styles in class extensions

- documentation/index.html
- documentation/src/components/home.css
- documentation/src/components/layout.css
- documentation/src/components/layout.ts
- documentation/src/components/side-nav.css
- documentation/src/components/side-nav.ts
Introduce mobile delivery of the documentation site.
- add collapsable left-hand drawer
- add a header with toggle button
- update the main content area to switch column breakdown by available space.
Make this more accessible on mobile
Visually
> docs: update to support responsive documentation delivery

- packages/overlay-root/src/active-overlay.ts
- packages/overlay-root/stories/overlay-root.stories.ts
- update `active-overlay` to position itself after the RAF _always_ so that it is measured after styles are applied and that it's not placed twice where it can cancel the mouse over event and hide errantly.
Delivery UI fidelity and hover interactions as expected.
Manually in Storybook, see below...
> Tooltip/Overlay Updates

- packages/radio-group/src/radio-group.ts
- packages/radio-group/test/radio-group.test.ts
https://github.com/adobe/spectrum-web-components/issues/364
I've tested this fix by extending the Radio-Group component in my project, and don't see anything bad. However, in this pull request, I'm not testing because I don't have the local environment set up
Simply wrapped the offending selector in quotes.
Radio Button Group breaks when radio value is an integer Issue #364
https://github.com/adobe/spectrum-web-components/issues/364
Radio Button Groups could not contain radio buttons with a value of type integer previously. The Radio Group, when set selected would throw an error due to query selection
Have not tested this fix at all, other than extending Radio Button Group on my project to patch this issue temporarily
> Fix for Radio Button Group breaks when radio value is an integer Issue #364

- __snapshots__/Slider.md
- packages/slider/src/slider.ts
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider.test.ts
Adds a new property `getAriaValueText` which accepts a function converting a value number argument into a string to be displayed.
#381 
Need to be able to control how the value of the slider is presented, both in aria presentation and in our visual presentation above the slider.
* Unit testing has been updated to test that the aria text value is updated correctly.
> feat(slider): adds getAriaValueText property, fixes #381

- documentation/webpack.config.js
Include the webcomponents polyfill for Edge (until Edgium is out)
#376 
It lets us load the site on Edge
Ran docs site locally and looked at it on Edge
> fix: for docs, add webcomponent polyfill for Edge

- documentation/src/components/side-nav.ts
- packages/sidenav/src/sidenav-item.ts
- packages/sidenav/test/sidenav-item.test.ts
Fix it so that an `sp-sidenav-item` that has no value can be expanded. Also, make the top level sidenav items in the docs expanded by default.
fixes #410 
We need the docs to be navigable
By running the docs locally.
> fix: allow expanding a sidenav item that has no value

- .circleci/config.yml
- documentation/404.html
Add inserting the 404 page into the documentation site into the CircleCI process.
fixes #357 
The doc site should work from all entry URLs.
Visit: https://opensource.adobe.com/spectrum-web-components/components/dropdown
> docs: add 404 processing for github pages

- packages/textfield/src/textfield.ts
- packages/textfield/test/textfield.test.ts
- packages/toast/src/toast.ts
For text fields, allow the passing through of the [`autocomplete`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute
#314 
I need this feature to stop the search field from autocompleting when I am implementing my own autocomplete.
I tested this in my branch where I am adding a search field to the documentation.
> feat: pass through autocomplete attribute to text inputs

- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay-trigger.test.ts
CircleCI ran into some non-deterministic test coverage results:
https://app.circleci.com/jobs/github/adobe/spectrum-web-components/1874/parallel-runs/0/steps/0-108
https://app.circleci.com/jobs/github/adobe/spectrum-web-components/1873/parallel-runs/0/steps/0-110
I tracked the root to:
The line in question is part of some `async` activity leading me to believe there's an unload timing issue at play, so I've ignored that line for coverage and added another test while I was there.
Coverage results should be predictable
CI
> test(overlay): clean up coverage for async disparities

- .circleci/config.yml
Make CI faster by leveraging workspace caching
The CI should be faster!
The following screen shot shows a build that started a minute later than the previous build and made it through the docs publish process about 3.5 minutes faster 😱
> ci: persist build assets to workspace

- packages/shared/src/focusable.ts
- packages/tab-list/src/tab-list.ts
The fix herein roughly follows the suggestion in https://github.com/adobe/spectrum-web-components/issues/318#issuecomment-566861628 except it uses `mousedown` rather than `click` because on further investigation the `focus` state starts that early in the interaction 😱 
It feels like a bit of a hack, which I guess it is being the `Focusable` base class is a workaround for not having `delegates-focus` functionality x-browser. If it feels like too much of a hack, I'm happy to review further.
The associated `tab-list` update isn't explicitly related, but I ran into it while confirming this fix. As such, I can break it out if anyone is worried about cleanliness or what not.
fixes #318 maybe?
Focusing the things is the path to them being accessible.
Manually. Focus and the shadow DOM is hard to …
> fix(shared): prevent focusing focusable root on second click

- packages/action-menu/README.md
- packages/action-menu/src/action-menu.css
- packages/action-menu/src/action-menu.ts
- packages/dropdown/src/dropdown.ts
Responding to design feedback from Spectrum team.
Ensure the `action-button` inside of `action-menu` doesn't apply `field-button` styles.
Spectrum specification adherence.
Manually.
> fix(action-menu): spectrum adherence update

- .storybook/preview-head.html
- .storybook/preview.js
- packages/overlay/src/active-overlay.ts
- packages/overlay/src/overlay-trigger.ts
- packages/theme/src/index.ts
- packages/theme/src/scale-large.css
- packages/theme/src/scale-large.ts
- packages/theme/src/scale-medium.css
- packages/theme/src/scale-medium.ts
- packages/theme/src/theme-dark.css
- packages/theme/src/theme-lightest.css
- packages/theme/src/theme.ts
- packages/theme/test/themes.test.ts
- Adds support for `scale=large` in `sp-theme`
- Add support for `theme` knobs system wide in Storybook
fixes #432 
We're currently using a local instance of the `large` theme in our application, but everyone should be able to use it, too!
Manually.
> Expand theme support, display options in Storybook

- packages/shared/src/focusable.ts
A prior change prevented default mousedown event behavior, this change prevented focusable input elements like search from functioning correctly. This PR fixes this issue by allowing the mousedown event to do its default behavior if the event is targeting the focus element.
#463 
Search input does not work when clicked today.
Storybook testing.
> fix(shared): fixes search input - fixes #463

- .circleci/config.yml
- __snapshots__/card.md
- packages/card/README.md
- packages/card/src/card.ts
- packages/card/stories/card.stories.ts
- packages/card/test/card.test.ts
- test/visual/stories.js
Previously, we were only allowing card titles to be passed in as pure text string, meaning that they could not use html. This pr allows support for slotted titles, meaning they can be text fields, headers, strong, italicized, etc. It also continues to support the old implementation, where if a title attribute is supplied and a slot is not provided, it falls back to using the old pure text string title.
This PR adds a new renderTitle property to card, which all variant render functions use. It includes a slot named `title` which by default contains the title attribute as it's text content
Improves flexibility of the card component, and consolidates some discrepancies between variants
- unit tests
- tested manually
- works in storybook
> feat(card): Allow slotted html title

- .storybook/preview.js
- packages/overlay/src/popper-arrow-rotate.ts
- Reliance on `margin-left` in the Spectrum CSS rules for `#tip` would cause its placement to be slightly off when managed by `popper.js`
- `es-dev-server` isn't used in `storybook-build` so the output JS would error on `process.env`: https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/overlay--default
After the work in #468 is complete, and possibly in #157, I'd like to revisit how regressions get listed so that we can more easily put "open" states, etc into that pipeline to catch things like this in the future.
Design adherence.
Manually
> fix(overlay): override SpectrumCSS tip rules and process usage in popper

- packages/link/src/spectrum-config-utils.js
- packages/link/src/spectrum-config.js
- packages/link/src/spectrum-link.css
Update the Spectrum Config for the link element to process the CSS without mangling the specificity. I didn't know this was a thing until @cuberoot did it for the [Overlay work](https://github.com/adobe/spectrum-web-components/pull/452/files#diff-326ffef068d4c7c520f1332940a2684d), and I'm not sure if it's really better than #431 or not, but it seems cool.
fixes #85 
closes #431 
The `focus` states were previously being overwritten.
Manually in storybook.
> fix(link): process Spectrum CSS without overwriting specificity

- __snapshots__/Action menu.md
- __snapshots__/Dropdown.md
- karma.conf.js
- packages/action-menu/README.md
- packages/action-menu/src/action-menu.ts
- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/stories/index.ts
- packages/action-menu/test/action-menu.test.ts
- packages/dropdown/README.md
- packages/dropdown/package.json
- packages/dropdown/src/dropdown.ts
- packages/dropdown/stories/dropdown.stories.ts
- packages/dropdown/test/dropdown.test.ts
- packages/dropdown/tsconfig.json
- packages/menu-item/stories/menu-item.stories.ts
- packages/overlay/src/active-overlay.ts
Tie `sp-dropdown` and it's derivatives into the new `Overlay` system.
- ensures content is "over" other content
- ensures that the content breaks any overflow rules
- ensures that the content respects the browser edges
- moves the content to ensure event listeners are maintained
- uses the widths of the `sp-dropdown` for the menu content in Standard variants and allows content to size itself in the Quiet variant
- New PR as a number of the implementation details, tests, etc have changed from #486 
- This is a breaking change!
- There's lots of room for additional documentation if people like the new DOM and attribute APIs.
- continue to require an `sp-menu` in the light DOM even though it's a small leak of our implementation details as it falls closer to the API found in [React Spectrum's …
> feat(dropdown): open menu UI with overlay system

- .circleci/config.yml
- packages/button/package.json
- packages/button/src/spectrum-action-button.css
- packages/button/src/spectrum-button.css
- packages/button/src/spectrum-clear-button.css
- packages/button/src/spectrum-fieldbutton.css
- packages/checkbox/package.json
- packages/icon/package.json
- packages/link/package.json
- packages/menu/package.json
- packages/slider/package.json
- packages/styles/core-global.css
- packages/styles/package.json
- packages/styles/scale-large.css
- packages/styles/scale-medium.css
- packages/styles/typography.css
- packages/textfield/package.json
- packages/textfield/src/spectrum-textfield.css
- yarn.lock
Update to the latest Spectrum CSS dependencies. This is separate from the "general update" as there should be (and is) actual changes to the golden images in this update, and it makes them easier to review.
fixes #496 
fixes #497 
fixes #498 
fixes #499 
fixes #500
fixes #501 
fixes #502 
fixes #503 
fixes #504  
Keeping us up-to-date with Spectrum CSS/DNA changes.
Visual regressions confirmed and updated in the golden images cache.
> chore: update spectrum CSS dependencies

- packages/search/src/search.ts
- packages/search/test/search.test.ts
Manual dispatch `input` and `change` events from the `input` element in the `Search` component so that an appropriate response can be made in implementing applications.
fixes #313
Tighter interaction loop.
- unit test
> fix(search): ensure "reset" surfaces "input" and "change" events

- packages/tab-list/src/tab-list.css
- packages/tab-list/src/tab-list.ts
- packages/tab/stories/tabs.stories.ts
Add support for a "vertical-right" variant in the `sp-tab-list` component.
It's possible that this requires further documentation, and could benefit from some cleaned up CSS, but I wanted to leave that until I get feedback from Spectrum CSS as to whether this variant could be included at some point in the future in their specification. [This issue](https://github.com/adobe/spectrum-css/issues/637) tracks the possible addition of this pattern in their project.
Product design requirement
Manually
> fix(tab-list): add support for "vertical-right"

- documentation/src/components/layout.ts
- documentation/src/components/page.ts
Ensures that the navigation closes when moving between pages in the documentation.
Less clicks for content
Manually
> docs: close nav when resetting scroll

- .circleci/config.yml
- packages/tab-list/src/tab-list.css
- packages/tab/stories/tabs.stories.ts
- test/visual/stories.js
Adds support for the following type of styles on `sp-tab-list`...
```
height: 75vh;
flex-direction: column;
justify-content: center;
```
fixes #537
It makes application styling easier.
- added a visual regression.
> fix(tab-list): position the indicator correctly when sized

- packages/icon/README.md
Ensure that the linking in the icons docs is correct no matter the value of the `<base/>` tag.
Links should work.
Manually.
> docs(icon): correct link pathing for base tag usage

- packages/overlay/src/active-overlay.ts
- packages/theme/src/index.ts
- packages/theme/src/theme.ts
Support manually configuring what theme fragments to load in an application by dynamically acquiring the "default" fragment for each theme "type".
fixes #532 
We shouldn't HAVE to load all the themes ALL the time.
- probably needs more tests if we agree on this path forward.
> fix(theme): track default theme values dynamically

- packages/textfield/src/textfield.ts
- packages/textfield/stories/textfield.stories.ts
- packages/textfield/test/textfield.test.ts
`required` means that a value _must_ be present.
`pattern` will verify that a value (when present) matches that pattern
`allowed-keys` will populate a regex to prevent input when the value is incorrect.
fixes #476
fixes #211
Don't always want validation UI.
- new tests!
> fix(textfield): update validation path, add "allowed-keys"

- packages/slider/src/slider.ts
- packages/slider/stories/slider.stories.ts
- Use the `input` element internal to the slider to sanitize values to avoid JS quirks in rounding values to match `step` management.
- Reduce the number of calls to `this.getBoundingClientRect()` as it can cause unnecessary layouts.
fixes #481 
Because `12.120000000000001` doesn't conform to `step="0.01"`...
Tests run just fine.
> fix(slider): use internal "input" for value sanitation

- packages/tab-list/src/tab-list.css
- packages/tab-list/src/tab-list.ts
Apply "width" via `scaleX` or `scaleY` so that it, too, can be animated when changing tabs. This is particularly apparent when the tab names have widely varying lengths.
Transitions should be smooth as butter.
Visually.
> fix(tab-list): transition indicator "width" as well as position

- packages/button/action-button.md
- packages/button/src/action-button.ts
- packages/button/stories/action-button.stories.ts
- packages/button/test/action-button.test.ts
Encapsulate dynamic management of the `selected` attribute via the presence of a `toggles` attribute.
To do: confirm with the accessibility team whether the `aria-pressed` attribute should always be managed on this element.
fixes #483
a11y and functionality should be componentized too!
- added unit tests
> fix(button): add "toggles" attribute to action button

- documentation/scripts/buildSearchIndex.js
- gulpfile.js
Get the docs to build correctly with the new globby version.
> docs: use the "new" glob syntax

- documentation/src/components/home.ts
- packages/link/src/link.ts
- packages/styles/fonts.css
> fix(link): correct white space in template/docs site

- .circleci/config.yml
- .stylelintrc.json
- packages/status-light/README.md
- packages/status-light/src/status-light.css
- packages/status-light/src/status-light.ts
- packages/tab/src/tab.css
- tweak Stylelint to that we can copy overrides straight out of processed Spectrum CSS output
- document `disabled` delivery
- manually correct cascade of `[disabled]` styles
Adherence to the Spectrum spec.
Visual regressions are updated to support the corrected delivery.
> Update Status Light as per Spectrum Specification

- .circleci/config.yml
- packages/tab-list/README.md
- packages/tab-list/src/tab-list.css
- packages/tab/README.md
Correct the display of `<sp-tab-list quiet>` and the size of icons in both the `<sp-tab-list>` and `<sp-tab>` README.md, as per feedback from the Spectrum team.
Quality adherence of the Spectrum specification.
Visual regressions are updated to support the corrected delivery.
> Update Tabs Delivery as per Spectrum Specification

- packages/slider/src/slider.ts
Fixes an issue where the ordering of `pointerdown` and `input` events was incorrect when the track was interacted with.
```
<sp-slider @pointerdown=${this.onPointerDown}  @input=${this.onInput}></sp-slider>
```
When the track is moused down in the above example, `onInput` will execute before `onPointerDown`.
**onTrackPointerDown()** 
- stop the propagation of the original pointer event
- Before the slider value is set, dispatch a syntethic event with the same properties as the original event
[Issue 576](https://github.com/adobe/spectrum-web-components/issues/576)
For `<input type="range"/>` elements, the ordering of `pointerdown` and `input` is swapped. We want our `sp-sliders` to reflect this behavior.
Unfortunately, testing the ordering of events is a difficult challenge.
We are …
> Ensure that pointer events fire before input events for Sliders

- packages/icon/README.md
- packages/iconset/README.md
- packages/search/src/search.ts
- packages/textfield/src/textfield.ts
- switch private images to base64
- ensure `"`s match with each other
- remove errant `slot` inclusion in documentation
Documentation should be as correct as possible
> docs: correct slot content, HTML text and private images

- packages/button/src/button-base.ts
- packages/link/src/link.ts
- packages/shared/src/like-anchor.ts
- packages/sidenav/src/sidenav-item.ts
Add the `LikeAnchor` mixin with a relatively general purpose `renderAnchor` method knowing that in some cases the elements that this is mixed into will leverage their own rendering to define the DOM of the anchor.
fixes #595 please see this issue for further discussion
- Less bumpy API
- Support for early adopters
Refactor passes current tests.
> refactor: use mixin to manage shared anchor like properties

- .circleci/config.yml
- packages/tab-list/src/tab-list.ts
- packages/tab-list/test/tab-list.test.ts
- packages/tab/src/tab.ts
- packages/tab/stories/tabs.stories.ts
- test/visual/stories.js
- support reassuring the `indicator` after `document.fonts` has completed loading so that any font metrics that may have changed between the fallback and the new font are reflected in the indicator UI
- clarify the difference between a click being the first interaction with the `tab-list` and a click being an interaction _after_ a keyboard interaction when deciding whether to apply `focus-visible` styling
- allow `tabs` to display without visible labels.
- correct visual delivery
- better accessibility support
- more flexibility
- added unit tests
- added visual regressions
- updated visual regressions
> fix(tabs, tab-list): various additions and expansions

- packages/overlay/package.json
- yarn.lock
Use the latest version of popper.js so that scrolling will be tracked through slots.
fixes #604
The docs were broke.
Manually
> fix(overlay): new popper version tracks scroll through assigned slots

- packages/popover/README.md
Ensure the documentation for Popover displays the most correct application of the currently available attributes/code.
fixes #584 
Manually
> docs: use appropriate attributes in examples

- packages/tab-list/src/tab-list.ts
- hide the indicator when there isn't an active selection using `scaleX(0) scaleY(0)`
- listen for resize events to ensure indicator is sized/located appropriately before/after them
I was pretty interested in doing something like the following:
```
if (TabList.resizeObserver) TabList.resizeObserver.observe(this);
else window.addEventListener('resize', this.updateSelectionIndicator);
```
However, it looks like Typescript doesn't have support for `window.ResizeObserver` as a constructor yet. So...next time.
fixes #610 
fixes #624 
UI consistancy.
Manually
> fix(tab-list): hide indicator without selection, listen to resize events

- packages/button/src/action-button.css
- packages/button/src/button-base.css
- packages/button/src/button-base.ts
- packages/button/src/button.css
- packages/button/src/button.ts
- packages/button/src/clear-button.css
- packages/button/src/spectrum-action-button.css
- packages/button/src/spectrum-button-base.css
- packages/button/src/spectrum-button.css
- packages/button/src/spectrum-clear-button.css
- packages/button/src/spectrum-config.js
- packages/button/src/spectrum-fieldbutton.css
- packages/dropdown/src/dropdown.ts
- scripts/process-spectrum-postcss-plugin.js
Add `excludeSourceSelector` to `process-spectrum-postcss-plugin.js` to allow greater control as to the styles that are included or excluded from a final CSS conversion. Lever this in the `button` package to structure a `button-base.css` output that contains all of the styles shared across all buttons, and prepare the rest of the packages leveraging those styles to accept this deduplicated CSS.
Elements should be as light as possible.
Visual regressions.
> fix(button): add excludeSourceSelector to reduce duplication of styles

- documentation/src/components/page.ts
Make the sidenav component links work in pre-chromium Edge.
fixes #628 
I want to debug some issues in our components in pre-chromium Edge using the doc site, but I can't even navigate to the component pages
Manual testing in Edge
> fix: click on docs sidenav links in Edge

- .circleci/config.yml
- packages/tab/src/tab.css
- packages/tab/stories/tabs.stories.ts
- test/visual/stories.js
Ensure local customization is based as close as possible on Spectrum CSS based custom properties. Add a new visual regression to manage.
fixes #123 
Maintainability.
Visually and with regression tests.
> fix(tab): use Spectrum CSS relative values for overrides

- .circleci/config.yml
- __snapshots__/card.md
- packages/card/package.json
- packages/card/src/card.css
- packages/card/src/card.ts
- packages/card/src/spectrum-card.css
- packages/card/src/spectrum-config.js
- packages/switch/src/spectrum-switch.css
- scripts/process-spectrum-postcss-plugin.js
- correctly process `.spectrum-Card--gallery.focus-ring` to `:host([variant='gallery']:focus-visible)` instead of `:host([variant='gallery']) :focus-visible`
- style slot wrappers instead of slots so we can accurate styles `:before` elements
- apply `tabindex` and `role` for more accurate accessibility
refs #279 
- better adherence to the Spectrum specification.
- higher quality accessibility
Visually.
*Corrected hover styles for quiet switches*
was
> fix(card): correctly apply :focus-visible styling to variants

- package.json
- packages/icons-ui/package.json
- packages/icons-workflow/package.json
- packages/iconset/package.json
`type: "module"` forces Node@12+ to think everything should be a module and blocks development. This removes those properties where local scripting is required.
Get things working in Node 12.
- locally it installs build and tests in Node@12.16.3
- `yarn` (which includes all of the build steps by default)
- `yarn test`
- `yarn storybook`
- `yarn docs:start`
> fix: remove "type: "module"" in package.json for node 12

- packages/textfield/src/textfield.ts
Add `maxlength` and `minlength` attributes to the `<sp-textfield>` element.
- tidy up the `checkValidity()` method
fixes #654 
A more complete `<input/>` like API.
- unit tests/visual regressions pass
> fix(textfield): add maxlength and minlength attributes

- packages/overlay/package.json
- packages/overlay/src/active-overlay.css
- packages/overlay/src/active-overlay.ts
- packages/overlay/src/apply-max-size.ts
- packages/overlay/src/popper.ts
- packages/popover/src/popover.css
- packages/popover/stories/popover.stories.ts
- yarn.lock
Add the `maxSize` and `applyMaxSize` modifiers to the Popper instance in the overlay system to that the contents in an overlaid element are contained to the browser window.
fixes #645 
- unit tests pass
- visual regressions pass
Type of Change
> fix: constrain overlay

- packages/dialog/src/dialog-wrapper.ts
- packages/dialog/src/spectrum-config.js
- packages/dialog/src/spectrum-dialog-wrapper.css
- scripts/process-spectrum-postcss-plugin.js
Adds support for processing selectors like `.spectrum-Dialog .spectrum-Button--cta` -> `[variant='cta']`, previously attribute selectors could only be applied to `:host()`
Leverage this and the addition of the `responsive` attribute processing to `sp-dialog`.
Previously the process pushed errors into the output without causing a hard failure.
- by reading the output.
> feat(dialog): descendent attribute support, responsive attribute added

- packages/slider/README.md
Add `label="x"` and `disabled` usage to documentation for the `sp-slider` element.
fixes #585
Documentation coverage.
> docs(slider): add usage of labeled and disabled variants

- documentation/src/components/code-example.css
- documentation/src/components/code-example.ts
- documentation/src/components/layout.css
Reduce padding at smaller widths for both the `html demo` blocks,
as well as the overall left/right padding for the docs.
Fixes #686 
The docs should look better on mobile. There are still issues on some pages, but this should give us a big boost in the right direction.
I've reviewed several of the doc pages in the chrome mobile/responsive dev tool. I want some feedback on the breakpoints before I do a complete review.
- [ x ] All new and …
> chore: improve documentation responsiveness

- custom-elements.json
- package.json
- packages/icons-ui/package.json
- packages/icons-workflow/package.json
- packages/sidenav/README.md
- packages/sidenav/src/sidenav-item.ts
- packages/sidenav/src/spectrum-config.js
- packages/sidenav/src/spectrum-sidenav-item.css
- packages/sidenav/test/sidenav-item.test.ts
- yarn.lock
- add support for icons in sidenav-items
- document the above and the previously existing heading elements
- clean up dependencies so that "Prettier" doesn't look like a component we ship
fixes #588 
Clearer and more complete support for Spectrum CSS source and compliance with Spectrum design review.
Available in documentation
> Complete Sidenav Documentation and Remove Prettier from Docs

- packages/menu-group/src/menu-group.ts
- packages/menu-item/src/menu-item.ts
- packages/menu/src/menu.ts
- packages/menu/test/menu.test.ts
Adds the ability for `sp-menu` to observe deep changes to its menu-item list to support the use of `sp-menu-group` elements as are found in the search interface of the documentation site.
A menu should be able to understand what items are inside of it.
- new unit tests
> fix(menu): support menu item list change in deep decendents

- packages/dropdown/src/dropdown.ts
- packages/dropdown/test/dropdown.test.ts
- allows `sp-dropdown` to lazy load the `Overlay` and `sp-popover` code
- wraps that laziness into the `updateComplete` lifecycle promise, so that timing-based interactions with the element can be managed with the appropriate fidelity
- users should be able to prevent unused code from being downloaded by their applications
- when doing so, those same users should be able to time interactions based on the availability of that code
- updated unit tests
- manually build/test in `westbrook/11ty`
> refactor(dropdown): extend updateComplete timing for overlay oven/close

- .circleci/config.yml
- documentation/src/main.css
- packages/sidenav/src/sidenav-item.css
- packages/sidenav/src/sidenav.css
Help our docs match the Spectrum CSS docs, while ensuring a more correct delivery of `sp-sidnav-item` elements.
fixes #587
Spectrum CSS adherence.
- visual regressions updated
> sp-sidenav-item spacing and docs delivery

- packages/overlay/src/active-overlay.ts
Clean up the possibility of passing `undefined` into `color` or `scale` values in a `sp-theme` element.
Lazily defined root themes might not always supply full themes to the overlay system.
Manually while developing on `westbrook/11ty`.
> fix(overlay): ensure undefined data is not passed into theme

- packages/theme/src/theme.ts
- packages/theme/test/theme-lazy.test.ts
- packages/theme/test/themes.test.ts
Through experiments around reducing the initial load of the documentation site, it became clear that `sp-theme` wasn't fully delivering the flexibility of load currently outlined in its [documentation](https://opensource.adobe.com/spectrum-web-components/components/theme). The ability to load only the style fragments you need, when you need them, is particularly important for the `scale` fragments which top out around 28kb parsed, but the `color` fragments also use up about 6kb of parsed JS, so having more than you need of either is wasteful.
- better structure `Theme` for use with lazily loaded theme fragments
- use the `scale` and `color` attributes before falling back to the fragment "defaults" when establishing the current themes
- always require the presence of a fragment for each of …
> fix(theme): support lazily loading theme fragments

- packages/theme/src/theme.ts
#714 did the work of creating lazily loadable fragments, however, while it worked in the browser and passed all of its tests, it also created a stack overflow in the console. This corrects the code path and gating to prevent this from happening while continuing to deliver on the lazy features.
A clean console.
Manually in https://westbrook-11ty--spectrum-web-components.netlify.app/ vs https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper
> fix(theme): prevent property sets attribute set property stack overflow

- packages/shared/src/focus-visible.ts
I initially placed this load behind a dynamic import so that it wouldn't block initial load. However, after working to optimize the documentation site I've learned that the benefits aren't what I'd hoped. By the nature of it being so small (just 1KB gzipped + minified), and being unrelated to other imports together with which it could multiple the late load benefits, any possible gains to load time are outweighed by the additional request, and the need to wait for what would otherwise be a required piece of code for something the had `autofocus` and this polyfill applied. As such, I think we should move it back to the static dependency graph.
> refactor(shared): remove lazy import of focus-visible polyfill

- .circleci/config.yml
- .github/dependabot.yml
With the demise of Greenkeeper, I had turned on Snyk for a little bit, but it wasn't quite to same functionality. It seems that Dependabot _is_ and that we can get back to managing version floors and ceilings by adding this config and relying on it being a part of github now to make this work.
Dependency management.
> ci: configure dependabot

- packages/tags/src/tag.ts
- packages/tags/test/tag.test.ts
Workaround provided color contrast in `<sp-tag disabled>` element by ensuring that `aria-disabled="true"` is also available in this context.
fixes #741
Accessible elements.
- unit test added
> feat(tags): manage aria-disabled from disabled attribute

- packages/banner/README.md
- packages/dropzone/README.md
- packages/status-light/src/status-light.ts
- packages/status-light/test/status-light.test.ts
- let `disabeld` manage `aria-disabled` in `<sp-status-light>`
- remove inline styles from Dropzone documentation
- remove `type="warning"` Banners from the Docs as they are not currently accessible. This pattern is "deprecated" and the Spectrum CSS level and we should find a path to do so as well here, separately.
Comes from the deque review of the Docs site.
> Contrast Updates in the Docs Site

- packages/bundle/package.json
Include elements.ts in the side effects for the bundle so that indirectly included elements would be included in the documentation site build.
> fix: include element is bundle side effects

- .circleci/config.yml
- packages/sidenav/src/Sidenav.ts
- packages/sidenav/src/SidenavItem.ts
- packages/sidenav/stories/sidenav.stories.ts
- packages/sidenav/test/sidenav-item.test.ts
- packages/sidenav/test/sidenav.test.ts
- projects/templates/plop-templates/benchmark.ts.hbs
blocked by #683 
- correctly handle the `tabindex` value of the "selected" item when navigating through the items with the keyboard
- leverage `aria-current="page"` in an item when conditions warrant
- expand stories and testing
fixes #733 
Better keyboard accessibility
Better accessibility tree.
- unit tests
- update visual regressions
> fix(sidenav): expand aria support and keyboard accesibility

- packages/tabs/src/Tabs.ts
- packages/tabs/test/tabs.test.ts
blocked by #683
Ensure that an `<sp-tabs>` element only has one active tab stop while navigating through its children via the keyboard.
This also removes the (seemingly) completely unused `value` attribute from `<sp-tabs>`.
fixes #740 
Better keyboard accessibility. 
- new unit tests!
> fix(tabs): ensure only one active tab stop in the tabs

- .circleci/config.yml
- .storybook/theme.js
- __snapshots__/Dropdown.md
- documentation/src/components/layout.css
- documentation/src/components/side-nav-search.ts
- documentation/src/main.css
- karma.conf.js
- package.json
- packages/dialog/src/Dialog.ts
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/test/dialog-wrapper.test.ts
- packages/dropdown/src/Dropdown.ts
- packages/dropdown/stories/dropdown.stories.ts
- packages/dropdown/test/dropdown.test.ts
- packages/icon/test/icon.test.ts
- packages/menu/src/Menu.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/active-overlay.css
- packages/overlay/src/overlay-stack.ts
- packages/overlay/src/overlay-types.ts
- packages/overlay/src/overlay.ts
- packages/overlay/src/popper-arrow-rotate.ts
- packages/overlay/stories/overlay-story-components.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-trigger.test.ts
- packages/overlay/test/overlay.test.ts
- packages/radio/src/RadioGroup.ts
- packages/radio/test/radio-group.test.ts
- adds inline and modal style overlays as described in https://github.com/adobe/spectrum-web-components/issues/710#issuecomment-643331874
- adds focus throwing via `receivedFocus`
- adds tab trapping via composed shadow DOM
- leverages new API in `sp-dropdown` and extension
- updates timing to not include arbitrary `requestAnimationFrame` calls
- adds stories and tests to the functionality
- sets overlay story element to "submit" on `enter` press
- updates `sp-radio-group` to appropriately manage keyboard interactions
Demo available at: https://westbrook-overlay-focus--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-menu--icon-only
fixes #709 
fixes #710 
fixes #723 
fixes #727
- increase the keyboard accessibility of our components and UI powered by our APIs
- …
> Manage tab order and focus placement with Overlay

- packages/circle-loader/package.json
- packages/circle-loader/test/benchmark/test-basic.ts
Some missed renamings from the `circleloader`=>`circle-loader` conversion.
> chore: cleanup missed circle-loader conversions

- packages/dropdown/README.md
Add `sp-dropdow[quiet]` listings to the README.
fixes #663
Users should have an easy time understanding what they get out of our packages.
Manually
> docs(dropdown): include [quiet] examples in README

- .circleci/config.yml
- packages/dropzone/README.md
- packages/illustrated-message/src/IllustratedMessage.ts
- packages/illustrated-message/src/illustrated-message.css
- use `h1` and `p` elements in the content of `sp-illustrated-message`
- ensure `sp-dropzone` documentation can be accessed via keyboard only interactions
fixes #732
fixes #765
Our elements should be accessible to everyone.
Manually
> Accessibility review updates

- packages/checkbox/test/checkbox.test.ts
- packages/shared/src/focusable.ts
- packages/tabs/src/Tabs.ts
Revisiting #318 this change prevent Firefox and Safari on MacOS (various testing points to this not occurring in Window to begin with, but I cannot confirm) from allowing the `:host()` element of a component extended from `Focuable` to take "focus". This is particularly important in checkbox-like element where maintaining focus is needed to allow for keyboard alterations to the state of the element.
- when `focusout` throws on the `focusElement`, but not on the `:host()` (which occurs when focus is leaving the element all together) call `this.focus()` so that focus is applied appropriately.
- extends `focus`/`blur` passing to the `click` method as well
- correct the focus entry element in `sp-tabs` elements
fixes #770
fixes #516 
Keyboard accessibility is important.
- unit tests
> Focus management fixes for elements extended `focusable`

- .circleci/config.yml
- packages/asset/README.md
- packages/asset/package.json
- packages/asset/sp-asset.ts
- packages/asset/src/Asset.ts
- packages/asset/src/asset.css
- packages/asset/src/index.ts
- packages/asset/src/spectrum-asset.css
- packages/asset/src/spectrum-config.js
- packages/asset/stories/asset.stories.ts
- packages/asset/test/asset.test.ts
- packages/asset/test/benchmark/basic-test.ts
- packages/asset/tsconfig.json
- packages/bundle/elements.ts
- packages/bundle/package.json
- packages/bundle/src/index.ts
- packages/bundle/tsconfig.json
- test/visual/stories.js
- yarn.lock
Implements the `<sp-asset>` pattern.
- leverages Spectrum CSS `^3.0.0`
- doesn't leverage `[dir="rtl|ltr"]`, so no need for `@spectrum-web-components/base`
refs #279 
Pattern availability
- Accessibility tests
- Screenshot tests
> feat(asset): add the asset pattern

- .circleci/config.yml
- packages/card/package.json
- packages/card/src/Card.ts
Something about recent changes to the CSS had caused the Visual Regression suite to become unstable regarding the testing of the Card component across the various themes. This change is a small step in the larger work to catch the Card component fully up to the Spectrum CSS output as listed in #279 AND it seems to stabilize the test suite.
refs #279 
If tests are flaky, ain't nobody happy!
Visual Regressions.
> Stabilize Visual Regressions of the Card Components

- __snapshots__/Checkbox.md
- __snapshots__/Dropdown.md
- __snapshots__/Search.md
- packages/actionbar/package.json
- packages/actionbar/src/Actionbar.ts
- packages/actionbar/src/spectrum-actionbar.css
- packages/base/README.md
- packages/base/package.json
- packages/base/src/Base.ts
- packages/base/src/index.ts
- packages/base/tsconfig.json
- packages/checkbox/package.json
- packages/checkbox/src/Checkbox.ts
- packages/checkbox/src/spectrum-checkbox.css
- packages/checkbox/src/spectrum-config.js
- packages/checkbox/test/checkbox.test.ts
- packages/shared/package.json
- packages/shared/src/focusable.ts
- scripts/process-spectrum-postcss-plugin.js
- yarn.lock
Spectrum CSS is getting close to a v3.0.0 release of all of its components and this branch should be able to serve as a base for testing out individual package upgrades.
- add a "base" package that vends `SpectrumMixin` and `SpectrumElement`, very open to alternate naming conventions if you have them.
- adds `public shadowRoot!: ShadowRoot;` to the element as we currently use shadow DOM in all of our elements and it's a pain to test for it in TS _all_ the time
- add a `connectedCallback()` that queries document direction and then applies it to the element tag so that elements extending from his can have an `[dir="rtl|ltr"]` selector to leverage in their styles
- extends the Spectrum CSS processing to include `[dir="rtl|ltr"]` selectors in the output by appending them to the host selector …
> [rfc|feature branch] Spectrum CSS 3.0.0 releases and '[dir="rtl|ltr"]'

- packages/link/test/link.test.ts
- packages/shared/src/like-anchor.ts
Add support for the `rel` attribute to the `LikeAnchor` (and thus `sp-link`) component
- fixes #791
- support `pwa-helpers` router behavior for handling links with `rel="external"`:
https://github.com/Polymer/pwa-helpers/blob/ce6be1a18655350c33b0f8949a1a16371d2caaa6/src/router.ts#L56
```ts
if (!anchor || anchor.target ||
anchor.hasAttribute('download') ||
anchor.getAttribute('rel') === 'external') return;
```
- unit test added
- n/a
> feat(link): support rel attribute

- README.md
- packages/overlay/src/overlay-stack.ts
Simple fix for #803 -- hopefully without unforeseen consequences.
#803 
Tests/visual regression passed.
- [ x ] All new and existing tests passed.
> Use height: 100% to avoid layout breaks with the shadow dom added to 

- .circleci/config.yml
- __snapshots__/Search.md
- packages/search/package.json
- packages/search/src/Search.ts
- packages/search/src/spectrum-config.js
- packages/search/src/spectrum-search.css
- packages/textfield/package.json
- packages/textfield/src/Textfield.ts
- packages/textfield/src/spectrum-config.js
- packages/textfield/src/spectrum-textfield.css
- packages/textfield/src/textfield.css
- packages/textfield/stories/textarea.stories.ts
- packages/textfield/stories/textfield.stories.ts
- scripts/process-spectrum-postcss-plugin.js
- yarn.lock
Directly (or as close to directly as possible) port the `textfield` and `search` patterns to `^3.0.0`.
Separately, we should review whether the `sp-textfield` pattern needs to be updated to some form of a light dom `<input/>` element in order to appropriately pair with `label` elements and extend to patterns like the `stepper` #477. 
fixes #513 
fixes #543 
fixes #750
Keeping up with Spectrum CSS, making customization easier.
- continues to pass unit tests
- visual regressions have been slightly updated
> Move `sp-textfiield` and `sp-search` to Spectrum CSS ^3.0.0

- packages/dropdown/test/dropdown.test.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay-trigger.test.ts
When an overlay is open when another is triggered, if the previous element isn't closed before the new overlay has opened, then the wrong overlay will be closed returning to the first overlay.
The dynamic import timing by default (and in builds _not_ made by webpack) seems to have managed this fine in the past, this update ensures the timing is correct in all cases and closer to the same between contexts.
fixes #809
We expect to be able to open successive overlays without issue.
- added new unit tests, passes old ones.
> fix(overlay): ensure overlay addition occurs after closing previous

- .circleci/config.yml
- .storybook/preview-head.html
- .storybook/preview.js
- documentation/src/components/code-example.ts
- documentation/src/components/layout.ts
- packages/base/README.md
- packages/base/src/Base.ts
- packages/base/test/base.test.ts
- packages/menu/src/Menu.ts
- packages/radio/src/RadioGroup.ts
- packages/slider/src/Slider.ts
- packages/tabs/src/Tabs.ts
- packages/tags/src/Tags.ts
- packages/theme/README.md
- packages/theme/src/Theme.ts
- packages/theme/stories/theme.stories.ts
Use `sp-theme` elements to supply a content direction "scope" in order to support multiple content directions on the same page.
- refactor `isDefaultDir` to `isLTR` for confusion around what "default" is in this case
- add `dir` documentation to `@spectrum-web-components/base`
- add `dir` documentation to `@spectrum-web-compoentns/theme`
Multiple content directions on the same page
- visual regressions updated
> feat: allow dir management by sp-theme elements

- packages/button/test/button.test.ts
- packages/dropdown/test/dropdown.test.ts
- packages/menu/test/menu.test.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay.test.ts
- packages/radio/test/radio-group.test.ts
- packages/sidenav/test/sidenav.test.ts
- packages/tabs/src/Tabs.ts
- packages/tabs/test/tabs.test.ts
- packages/tags/test/tag.test.ts
- packages/tags/test/tags.test.ts
- test/testing-helpers.ts
Centralizes the keyboard helper code into a single place so we don't need to copy/paste the code into another test file.
fixes #789
Shared codes is happier code!
- it is tests
> test: refactor keyboard input testing to shared tooling

- .circleci/config.yml
- package.json
- test/visual/screenshots-baseline/regenerate.js
- test/visual/visual.js
- yarn.lock
This catches the tooling there up to #837 where we're also moving unit testing to a Playwright driven workflow with the help of web-test-runner. It's looking like we get a little speed bump this way, too, 🤞, though I feel like this is something I initially saw with some other changes in the past that later dissolved.
One or both of Puppeteer and/or Chrome went crazy yesterday and will no longer load for the visual regression suite.
It _is_ tests.
> ci: use playwright for visual regression testing

- packages/dropdown/src/Dropdown.ts
- packages/dropdown/test/dropdown.test.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/overlay-stack.ts
Orders the `sp-overlay-close`, `change`, etc events and work appropriately for a user to be able to respond to `change` with their own `focus()` commands without them being overwritten.
fixes #843
Fix an issue, get a cookie...can I have a cookie?
- with unit tests
> fix: correct overlay closure order or operations for manual override

- packages/dropzone/README.md
- packages/dropzone/stories/dropzone.stories.ts
Spectrum CSS expects `sp-dropzone` elements to have a tab index so that they can be focused. I'm not sure the functional implications of this, so rather than apply this to the element itself, I've updated the stories to match the manual application of this in the docs site.
fixes #280
Spectrum adherence.
> docs: match tab index between site and stories

- documentation/src/app.ts
- documentation/src/components/layout.css
- documentation/src/components/layout.ts
- packages/button/README.md
- packages/checkbox/README.md
- packages/dialog/dialog-wrapper.md
- packages/radio/README.md
- packages/switch/README.md
- packages/toast/src/Toast.ts
Use `<sp-toast>` instead of `alert()` in JS notifications in the documentation site.
- catches a scoping change in `<sp-toast>` for the `rel=alert` and associated screen reader interaction. (Reader will no longer say "close" when the alert opens.)
- creates a `window.spAlert()` method for use in the documentation site.
- begins the conversation around what sort of glue code we might want to vend for consumers to be able to leverage this sort of functionality when using `<sp-toast>`
fixes #825
This dog food is delicious.
https://5f4e825a1305eb00070d9fbc--spectrum-web-components.netlify.app/
- click the "Use Spectrum Web Component buttons" button
- click the "Click me" button
- experience the toastiness...
> docs(toast): use "sp-toast" in the docs site insted of alert

- documentation/webpack.config.js
`html-loader` chose to minify HTML by default when it [moved to v1.0](https://github.com/webpack-contrib/html-loader/blob/master/CHANGELOG.md#-breaking-changes) and it started breaking the examples in the docs site. This reduces the amount of processing therein.
fixes #844 
It should be easy to read out examples.
Visually, locally, with `yarn docs:ci && npx servor documentation/dist` and the base updated, as this wasn't happening in the `yarn docs:start` context, because `development` vs `production`.
- [c] Bug fix (non-breaking change which fixes an issue)
> build: allow whitespace in documentation examples

- package.json
Allow for continuous development with CSS and TS watching while running the docs site locally.
fixes #834
@adixon-adobe can you confirm that this acts as you expect? It's not the _fastest_ live reload as we're doing `gulp css` + `tsc packages` + `webpack site`, but I was able to "live" add a `:host:before { content: 'Hello' }` style as per your issue and it updated.
> chore: add css/ts watch to docs:start

- .circleci/config.yml
- package.json
- yarn.lock
The Docker image we updated to in order to leverage `web-test-runner` was missing a couple of packages to support publishing the docs site from CI. This has now been corrected, and this PR points to that release. We should be able to move back to `bionic` the main line at some point in the next week or two, but this will allow us to avoid manually publishing the docs site in the interim.
> ci: use next docker release

- .circleci/config.yml
- packages/split-button/src/SplitButton.ts
- packages/split-button/test/split-button.test.ts
Realized there was a very quiet "warning" in our testing output that was pointing to not having `await`ed the accessibility testing in `<sp-split-button>`. Fixing that catches an issue, this corrects that issue by giving the "More" button a label...
The tests pass now.
> fix(split-button): test a11y correctly, find issues, fix them

- packages/shared/src/observe-slot-text.ts
Flatten observed slot assigned nodes to handle nested slots.
fixes #868 
This allows wrapping components with optional slots in other components, while still providing access to the slots as desired.
Tested scenario from issue locally.
n/a
> fix: flatten assigned nodes to observe text of nested slots

- documentation/src/components/component.ts
- packages/top-nav/README.md
Adds `top-nav` definitions to documentation site provisionally so that they don't need to go into `bundle`, yet.
> docs(top-nav): provisionally include top-nav JS in docs site

- packages/overlay/src/overlay-stack.ts
Safari has issues with WebGL canvas in association with out tab trapping solution. This mitigated the issue by initializing the tab trapping approach _only_ when tab trapping is being used by an element.
I have another idea that is low touch that I want to try, but all of my other ideas in this area haven't been working, so having something proposed as a possible path forward feels nice...
refs #848 
You should be able to have WebGL canvas AND use SWC.
- exiting tests pass.
> fix(overlay): only "tab trap" when you mean to

- packages/tabs/src/Tabs.ts
When removing the selected attribute on tabs, a typeError was thrown since the passed value was null 
This is fixed by checking if the value exists before checking for length via optional chaining
fixes #877 
* This removes the typeError
* It seems tabs behavior worked despite the typeError since the if-condition throwing the error was only relevant for selection, not removal of selection
* This has been tested in storybook.
* No additional unit tests were created since there's no functional changes
> fix(tabs): check if current selected value exists before setting selected attr

- .circleci/config.yml
- packages/slider/src/Slider.ts
- packages/slider/src/slider.css
- packages/slider/stories/slider.stories.ts
- test/visual/stories.js
Simplify the application of gradients by addressing `#track-left` and `#track-right` more uniformly and applying a `clip-path` rather than enforcing width via `left` and `right` properties.
fixes #455 
*Pros*
- requires only one deviation from Spectrum CSS `width: 100%`, which should be both easy to convince the application of and resilient to upstream change if not.
- much simpler
- doesn't rely on `variant=filled` so that you can have a fill and a gradient and that the addition of `fill-start` at a later date should be unblocked
*Cons*
- needs checking in Edge/IE 11 as `clip-path` is listed as "only supporting `url()`" in those browsers depending on which Can I Use you rely on: https://caniuse.com/#search=clip-path
Manually
> fix(slider): simplify application of the gradient backgrounds

- packages/icons-workflow/README.md
- packages/icons-workflow/package.json
- yarn.lock
Catch up to the source Workflow Icons dependency.
Correct `slot` usage in the docs.
Checkout the Storybook from the preview build to see the new icons that are included: https://5f6a8be1e17efa165a73b0f1--spectrum-web-components.netlify.app/storybook/?path=/story/icons--workflow
Keep up with the source and don't teach mistakes.
> chore(icons-workflow): update icon dependency and docs

- packages/base/src/Base.ts
Simple fix to the fallback for `dir`
#894 
For frameworks that re-use elements, this is pretty necessary!
Using the steps in the issue.
> fix: dir should never fall back to null

- documentation/guides/developing-components.md
- documentation/guides/generating-components.md
- documentation/guides/spectrum-config.md
- documentation/src/components/side-nav.ts
Adds documentation on working with the component package generation script and getting started from the Spectrum CSS source CSS/HTML.
- updates some spelling/linking on existing "Guides" pages
fixes #590
Help external contributors contribute to the project from scratch
Available for live review at https://5f6fbe59b444f53141be1701--spectrum-web-components.netlify.app/
> docs: add component generation documenation

- .circleci/config.yml
- .storybook/preview-head.html
- documentation/index.html
Chrome allows you to edit these styles in DevTools now, let's revel in the performance boost even at dev time!
fixes #722
Faster is better!
> docs: remove adoptedStyleSheet dev time workarounds

- .circleci/config.yml
Replace the GH integration with commitlint with a CircleCI workflow. Checkout:
https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/4050/workflows/3f03ce31-823e-4c5a-af2f-686f7236781d/jobs/21246
https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/4056/workflows/38f7a208-7866-4a29-9691-5c997e810770/jobs/21253
https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/4058/workflows/57370172-e67b-40f9-9fd5-9b9db0768163/jobs/21341
> ci: run commitlint in ci

- packages/bar-loader/src/BarLoader.ts
- packages/circle-loader/src/CircleLoader.ts
Ensure the correct visibility of `role=progress` elements in the accessibility tree through passing their `label` property into the `aria-label` attribute.
fixes #882
Components should be more accessible.
In https://5f6fca092785764a46d086a8--spectrum-web-components.netlify.app/
> fix: improve accessibility through aria-label attribute usage

- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/test/overlay-trigger.test.ts
Ensure that an `overlay-trigger` will close its overlays when it is given the `disabled` attribute/property.
fixes #278
State changes at the broader application level should be able to effect lower level UI offering.
- new unit test
> fix(overlay): close when overlay-trigger becomes [disabled]

- .circleci/config.yml
- packages/radio/src/RadioGroup.ts
- packages/radio/test/radio-group.test.ts
Update selection mechanism so that swipes in iOS Safari with voice over do not change selection. This also updates the response to the `autofocus` attribute to match what we see in native elements, as seen in the visual regression update.
fixes #766 
Deliver accessibility features on pair with native elements.
Manually in iOS Safari with VO
> fix(radio): select in response to arrow keys not focus

- package.json
- test/visual/screenshots-baseline/regenerate.js
- test/visual/visual.js
- yarn.lock
The process to generate visual regression was getting a little less than stable, see: https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/4239/workflows/18ff4246-da97-4e1a-b2aa-35c0c726e194. This updates to the "newer" version of `es-dev-server` called `@web/dev-server` and some newer timing mechanisms in the screenshot collecting code to help ensure the process is stable enough to capture actual regressions.
Stability.
The CI is stable in this branch and `westbrook/spectrum-css` where this solution came about.
> ci: update visual regressions to use @web/dev-server

- .circleci/config.yml
- packages/card/README.md
- packages/card/src/Card.ts
- packages/card/src/card.css
- packages/card/src/spectrum-config.js
- packages/card/stories/card.stories.ts
- packages/card/test/benchmark/test-basic.ts
- packages/card/test/card.test.ts
- test/visual/stories.js
The spectrum css variables are still title/subtitle, but I tried to
change what I could.
BREAKING CHANGE: renamed title/subtitle attributes and slot.
fixes #938 - title attribute causes browser tooltip to show,
Unittests plus review of storybook/docs. Oh, and cmd+f 😁 
- [ x ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x ] All new and existing tests passed.
> fix: switch to heading/subheading instead of title

- documentation/guides/generating-components.md
- documentation/guides/getting-started.md
- documentation/src/components/guide.ts
- documentation/src/components/side-nav.ts
- documentation/src/router.ts
Add "Getting Started" documentation with information around using Spectrum Web Components via CDN providers.
See: https://5f87af06d161ad3dbd013599--spectrum-web-components.netlify.app/ and the initial sidenav item `Getting Started`
fixes #878 
Not everything should require the commandline, NPM, or a build.
See preview.
> docs: add "getting started" content

- packages/dropdown/README.md
- packages/menu/README.md
- packages/menu/menu-group.md
- packages/menu/menu-item.md
Expand `sp-menu-item` documentation to reference usage of the `value` attribute:
- add page listing `sp-menu-group` directly.
- add page listing `sp-menu-item` directly.
fixes #664
Begin recovering the various elements batch delivered in a single package.
@adixon-adobe checked it out.
> docs(menu): split the various elements into individual docs pages

- packages/slider/src/slider.css
Make touch interactions with `sp-slider` more predictable by preventing "scroll/pan" actions from causing `pointercancel`.
fixes #519
Lots of people touch our sliders.
Manually in iOS via: https://5f8cdd6d084e2f8cbea81c82--spectrum-web-components.netlify.app
> fix(slider): prevent pointercancel events by container touch-action

- packages/checkbox/test/checkbox.test.ts
- packages/radio/test/radio.test.ts
- packages/shared/src/focus-visible.ts
- packages/shared/src/focusable.ts
- packages/sidenav/src/SidenavItem.ts
- packages/sidenav/stories/sidenav.stories.ts
- packages/sidenav/test/sidenav.test.ts
- packages/tabs/test/tabs.test.ts
- clean up duplicate code in `<sp-sidenav>`
- simplify logic in `focusable`
- make application of the `focus-visble` polyfill lazy. This means that "autofocus" functionality is delayed by a frame, see update to timing in tests.
refs #815 
Lazy polyfilling leads to perf trends like the following (note: `Remote` is the currently published version):
*Accordion*
*ActionMenu*
*Button*
*Link*
*Menu*
*Radio*
*Checkbox*
*Search*
*Sidenav*
*Slider*
*Switch*
*Textfield*
*Dropdown*
See above. See asynchrony changes to unit tests.
> Various updates to performance based off of better `tachometer` results.

- package.json
- packages/shared/src/focus-visible.ts
- scripts/css-processing.js
Conditionally apply the `focus-visible` polyfill only where it is needed:
While it would be interesting to also support `:-moz-focusring`, I'm not sure it 100% has the same heuristics as `:focus-visible`, so it's not included herein.
This approach builds on #980 where we make the polyfill lazy. While the results below tend to show a small amount of performance win, there seems to be less than I expected. Due to this, it may be too early to take on this change as it is generally powered by the a change in the way we process/deliver CSS for packages.
Previously, the following CSS `a:focus-visible { ... }` would be converted directly to `a.focus-visible { ... }` keeping the support process non-negative. To support both polyfill and no polyfill delivery it is required that the previous sample …
> feat(shared): conditionally apply focus-visible polyfill

- packages/textfield/src/Textfield.ts
- packages/textfield/src/spectrum-config.js
- packages/textfield/src/spectrum-textfield.css
Ensure correct focus+hover styles by processing `.is-focused` and `.is-keyboardFocused` styles. Note the polyfill that we leverage does not disambiguated between a mouse and a keyboard focus for inputs, so those styles are merged into the `[focused]` attribute rule.
fixes #988 
Adherence to Spectrum
Manually in storybook. None of our visual regressions have "interactive steps" before capture, so while we could add an "autofocus" story to Textfield it wouldn't technically cover this additions and "autofocus" is something I'd like to remove from other stories at some point as it's back for accessibility.
> fix(textfield): process ".is-focused" and ".is-keyboardFocused" styles

- .eslintrc.json
- documentation/src/components/home.ts
- documentation/src/router.ts
- package.json
- yarn.lock
Adds import linting to ensure correct usage of file extensions, and discourage anyone from adding any `export default` code to the library. Only one of two situations outside of the `wtr` context that had been catching most of this up-until-now.
Clearer direction on code structure.
The lint processes caught a couple of missed extensions in the documentation site.
> build: use import linting

- .gitignore
- .storybook/preview.js
- packages/overlay/local.d.ts
- packages/overlay/src/popper.ts
- projects/example-project-rollup/src/example-app.ts
Move to the ESM build from Popper so as to remove the need to `process.env` workarounds in no build contexts.
I wish that https://github.com/popperjs/popper-core/issues/1188 and https://github.com/popperjs/popper-core/issues/1188 and https://github.com/popperjs/popper-core/issues/933 would have gotten us a better solution. Needing to use an off main entry point build while hand managing the connectivity to the types is not my favorite thing in the world.
refs 963
`process.env` should be removed from production facing code.
Works locally and in CI
> fix(overlay): use esm build from popper and point through to types

- .circleci/config.yml
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/test/dialog-wrapper.test.ts
- test/visual/stories.js
- pass `error` attribute between `sp-dialog-wrapper` and `sp-dialog`
- prevent closing on `sp-underlay` when `sp-dialog:not([dismissable])`
fixes #992 
Expected delivery of attributes
New unit test.
New visual regression.
> fix(dialog): support "error" in wrapper, prevent underlay closure when not dismissable

- packages/accordion/src/Accordion.ts
- packages/accordion/src/AccordionItem.ts
- packages/accordion/test/accordion.test.ts
Allow `sp-accordion-item` elements to close.
- allow `sp-accordion-item-toggle` events to be cancelled
fixes #920 
More broadly usable accordion interactions.
New and updated unit testing
> feat(accordion): allow accordion items to close

- packages/menu/src/Menu.ts
- packages/menu/test/menu.test.ts
Make sure there are active menu items available when focusing items within an `<sp-menu>` element.
fixes #1009 
Prevent infinite loops.
Unit tests.
> fix(menu): prevent infinite loop when focus()

- .circleci/config.yml
- packages/top-nav/src/TopNav.ts
Set the `selected` value in `sp-top-nav` to `undefined` by default so that it doesn't require two renders passes to apply the correct indicator position.
Stabilize out visual regression suite.
Ran it a bunch in CI to make sure things weren't flaky anymore.
> fix(top-nav): initialize nav with an undefined selection

- .circleci/config.yml
- packages/slider/src/Slider.ts
- packages/slider/src/slider.css
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider.test.ts
- test/visual/stories.js
- allow for ticks to be placed along the track without fitting exactly to the value: e.g. `<sp-slider max=92 tick-step=5>`
- correct a value calculation error in RTL sliders with `max` other than 100
fixes #726 
Components shouldn't crash, even in edge case usage 
Added visual regression.
> fix(slider): allow irregular tick spacing and correct RTL value application

- packages/toast/README.md
- packages/toast/src/Toast.ts
- packages/toast/test/toast.test.ts
Support easier consumption of `<sp-toast>` elements by:
- not `open`ing them by default
- always dispatching `close` events when they close
fixes #935 
Ease of use and clarity of purpose.
Updated and added testing.
> feat(toast): default to "open === false", always dispatch "close" event

- .circleci/config.yml
- packages/bar-loader/src/spectrum-bar-loader.css
- packages/button/src/spectrum-clear-button.css
- packages/button/src/spectrum-config.js
- packages/checkbox/src/spectrum-checkbox.css
- packages/circle-loader/src/spectrum-circle-loader.css
- packages/dialog/src/spectrum-dialog.css
- packages/meter/src/spectrum-meter.css
- packages/modal/src/spectrum-modal-wrapper.css
- packages/modal/src/spectrum-modal.css
- packages/styles/src/spectrum-base.css
- packages/styles/src/spectrum-body.css
- packages/styles/src/spectrum-code.css
- packages/styles/src/spectrum-detail.css
- packages/styles/src/spectrum-heading.css
- scripts/process-spectrum-postcss-plugin.js
Include `atrule`s in the processing of Spectrum CSS output.
- ensure that it falls in order of the original CSS
- ensure the excluded classes are followed as appropriate
fixes #593 
We should be delivering CSS correctly to our users.
Visual regression found the output to be the same except for the color of the focus ring on Checkboxes which was adopting the unscoped `atrule` coloring for WHCM.
> build: process @media queries in source CSS

- .circleci/config.yml
- packages/card/README.md
- packages/card/src/card.css
- packages/card/stories/card.stories.ts
Temporary fix until https://github.com/adobe/spectrum-css/issues/1054 is
addressed.
Just override the unwanted css in SpectrumCSS.
#959 
This is the only issue blocking a clean integration of sp-card on our site.
Looked at the storybook & doc examples (and made extra sure my css was taking effect).
> fix: override and clear text-transform: uppercase

- packages/asset/src/Asset.ts
Add `aria-label` and `role` attributes to the SVGs representing the `folder` and `file` `variants`.
fixes #881
More accessible.
- unit tests
- accessible template linting.
> fix(asset): include alternative text for the file/folder versions

- .circleci/config.yml
- packages/action-group/src/action-group.css
- packages/action-menu/package.json
- packages/action-menu/src/ActionMenu.ts
- packages/button/sp-field-button.ts
- packages/button/src/ButtonBase.ts
- packages/button/src/FieldButton.ts
- packages/button/src/button-base.css
- packages/button/src/spectrum-action-button.css
- packages/button/src/spectrum-button-base.css
- packages/button/src/spectrum-button.css
- packages/button/src/spectrum-clear-button.css
- packages/button/src/spectrum-config.js
- packages/button/src/spectrum-fieldbutton.css
- packages/button/test/action-button.test.ts
- packages/button/test/button.test.ts
- packages/card/src/Card.ts
- packages/dropdown/src/Dropdown.ts
- packages/dropdown/src/dropdown.css
- packages/search/src/Search.ts
- packages/search/test/search.test.ts
- packages/shared/src/focusable.ts
- packages/split-button/src/SplitButton.ts
- packages/split-button/test/split-button.test.ts
- packages/tags/src/spectrum-config.js
- packages/tags/src/spectrum-tag.css
- scripts/process-spectrum-postcss-plugin.js
Move the accessible "button" node up from a `<button>` element in the shadow DOM to the a synthetic button at the host.
This _prepares_ both for work on a few existing issues and for an update to `elementInternals` in the future. There's been some coalescence around a polypill, so we might want to move in that direction at some point in the near future.
- synthesize button
- apply aria attributes
- apply click and keyboard handling
- update CSS processing for selector correctness
- process `active` styles correctly and broadly
- cascade changes across all button derivative and possessing patterns.
This will collide with #1051, so there will be much hand holding of one of these PRs to get them over the line.
refs #998 
refs #1042 
Accessibility can be achieved in many ways, but some of …
> feat(button): use synthetic button instead of native

- packages/action-menu/README.md
Spelling mistake. Called a `button` and `botton`
Documentation spell correct.
Just a readme change, no code change.
Readme doc change.
> Correct button spelling mistake in readme for button

- packages/slider/README.md
- packages/slider/src/Slider.ts
- packages/slider/stories/slider.stories.ts
- remove unlabelled slider expamples
- allow slider label through slot
fixed #739
Support users in ensuring a11y.
Prep for `:not(:defined)` style usage from the outside.
Unit test.
> Allow slider label via slot

- packages/button/src/ButtonBase.ts
- packages/button/src/button-base.css
- packages/button/test/button.test.ts
- packages/shared/src/focusable.ts
- packages/textfield/test/textfield.test.ts
Use proxy clicking to manage the anchor option of the `ButtonBase` class so that focus/hover/click/etc are managed correctly.
Buttons should still support `likeAnchor` functionality.
Added new unit tests.
> fix(button): relate to this.href correctly

- .circleci/config.yml
- .gitignore
- .storybook/preview.js
- package.json
- packages/base/src/Base.ts
- packages/overlay/stories/overlay.stories.ts
- projects/story-decorator/README.md
- projects/story-decorator/decorator.ts
- projects/story-decorator/package.json
- projects/story-decorator/sp-story-decorator.ts
- projects/story-decorator/src/StoryDecorator.ts
- projects/story-decorator/src/index.ts
- projects/story-decorator/tsconfig.json
- test/visual/screenshots-baseline/regenerate.js
- test/visual/visual.js
Working towards being able to leverage https://modern-web.dev/docs/dev-server/plugins/storybook/ as per #999 this PR investigates the usage of a Storybook decorator to apply in story persistent theme data for use both in our Storybook instance, as well as in other projects, e.g. https://webcomponents.dev/edit/HnzByTTgk9ahQ0S29zWi
fixes #970 
Make Storybook easier for consuming application contexts, prep for use of Storybook v6.
Runs in CI!
And: https://5fb6be4821cd18292cf464c1--spectrum-web-components.netlify.app/storybook/?path=/story/accordion--default
> feat(story-decorator): add story decorator to replace knobs for theme application

- .circleci/config.yml
- packages/action-button/src/ActionButton.ts
- packages/action-button/stories/action-button.stories.ts
- packages/action-group/README.md
- packages/action-group/package.json
- packages/action-group/src/ActionGroup.ts
- packages/action-group/stories/action-group.stories.ts
- packages/action-group/test/action-group.test.ts
- packages/action-group/tsconfig.json
- packages/actionbar/README.md
- packages/actionbar/stories/actionbar.stories.ts
- packages/button/src/button-base.css
- packages/menu/src/MenuItem.ts
- test/visual/stories.js
This extends the functionality of the `<sp-action-group>` to support the `selects` attribute that manages the collection of `sp-action-button`s internal to the group as either a radio group (`[selects="single"]`) which maintains a single selection or a checkbox group (`[selects="multiple"]`) which can maintain a selection of multiple items in the group.
Additions that support centrally managing `emphasized` and `quiet` delivery to the entire group of buttons have also been made.
This change is negatively effected by the following bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1158144 Currently, it is targeted for fixed in M89, which would be < 12 weeks from now, but with no actual progress in the issue so far, it's hard to fully rely on that.
fixes #998 
fixes #1043 …
> feat(action-group): manage "one" and "multiple" selections

- .circleci/config.yml
- test/visual/ci.js
- test/visual/local.js
- test/visual/screenshots-baseline/ci.js
- test/visual/screenshots-baseline/local.js
- test/visual/screenshots-baseline/regenerate.js
- test/visual/stories.js
- test/visual/visual.js
Make visual regression tests run concurrently.
```
yarn test:visual:baseline:local --concurrency=50
yarn test:visual:local --concurrency=10
yarn test:visual:ci --concurrency=5
```
Testing locally can surface the most performant settings for you system.
While variances exist, this update shortens the VRT passes to 2 - 4 minutes each from 4 - 6 minutes each in CI. Locally, you have more cores and can run an entire pass in about 1 minute, making that usage actually reasonable for the first time.
Things should be faster!
In CI.
Before:
After:
> test: queue page queue to accelerate visual regressions

- packages/dropdown/src/Dropdown.ts
- packages/dropdown/test/dropdown.test.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/src/overlay-types.ts
- packages/overlay/src/overlay.ts
- packages/overlay/test/overlay-trigger.test.ts
#1055
I have hit a couple of use cases where it is important to know when an overlay-trigger or a dropdown-related component (e.g. sp-action-menu) opens and closes.
Use cases include:
* Changing the styling of parent control when overlay is open
* Updating menu content on demand
I have added tests to accompany the changes
> Add open close events to dropdowns and overlay-triggers

- packages/accordion/src/Accordion.ts
- packages/accordion/test/accordion.test.ts
- packages/menu/src/Menu.ts
- packages/menu/test/menu.test.ts
- packages/sidenav/src/Sidenav.ts
- packages/sidenav/test/sidenav.test.ts
- prevent child searching loops from going infinite by keeping track of available vs disabled item counts
- prevent `sp-menu` from getting stuck on the first item (when `[disabled]`) when focusing programattically
- test these additions.
ref #1060 
Brought up in Slack
Infinite loops are bad.
- unit tests
> fix: prevent infinite loops when all children are [disabled]

- packages/icon/README.md
- packages/icon/src/IconBase.ts
- packages/icons-ui/stories/icons-ui.stories.ts
- packages/icons-workflow/stories/icons-workflow.stories.ts
Correct documentation re: `sp-icon` sizes.
- docs site
- workflow/ui icon stories
Incude `xxl` type for `size` property.
fixes #1086
Documentation correctness.
Docs.
> fix(icon): clean up docs and types for available size values

- packages/dialog/package.json
- packages/dialog/src/Dialog.ts
Ensure that `sp-button-group` and `sp-rule` are appropriately included in the `@spectrum-web-components/dialog` package and module files.
fixes #1087
Things works more better.
> fix(dialog): include all dependencies

- packages/slider/README.md
Document usage of `input` and `change` events in `sp-slider`.
Should revisit the content here when we ship the `steamingListener` directive as part of the Color elements work, as it encapsulates the vanilla pattern outlined herein for use in `lit-html`.
fixes #482
Clarify usage.
> docs(slider): expand event documentation

- packages/styles/package.json
The dependency is added by the build, so you won't find it in the code.
Fixes #1103
Yarn 2 has strict dependency checks, so this will fix errors with that.
It's not really testable until we release.
> fix: missing dependency

- packages/toast/src/Toast.ts
- packages/toast/test/toast.test.ts
Prevent `close` event from being dispatched when `open===true`.
refs #935
`close` when `open===true` is...weird.
- unit tests
> fix(toast): ensure "close" event only triggers when open===false

- packages/dialog/README.md
- packages/dialog/src/Dialog.ts
- packages/dialog/stories/dialog.stories.ts
Early response from the design team is that these two features do not mix, so I've prepped this PR. If anything changes, we might revisit, but in the currently available CSS this delivery won't work anyways
fixes #1088
Prevent bad visual delivery.
Added `dismissable` to the "fullscreen" story so we can be sure that the pattern delivers as expected going forward.
> fix(dialog): prevent "fullscreen*" dialogs from being "dissmisable"

- .circleci/config.yml
- packages/button/src/ButtonBase.ts
- packages/button/src/button.css
- packages/button/stories/button-cta.stories.ts
- packages/button/stories/button-overBackground.stories.ts
- packages/button/stories/button-primary.stories.ts
- packages/button/stories/button-secondary.stories.ts
- packages/button/stories/button-warning.stories.ts
- packages/button/stories/index.ts
- packages/button/test/button.test.ts
As per https://github.com/adobe/spectrum-css/issues/1086 the removal of icon after label styling in Spectrum CSS was not a regression but a conscious deprecation at the Spectrum design level. This aligns our offering with this decision.
fixes #1095 
Alignment with Spectrum specification
removed tests
> feat: deprecate "icon-right" in buttons as per Spectrum

- packages/action-button/src/action-button.css
- packages/button/src/button-base.css
Correct the specificity of the webkit appearance work around selector.
I'll look at advancing the reality of x-browser visual regression to help prevent things like this in the future.
fixes #1125
Correct x-browser style delivery
Manually.
> fix: correct specificity of webkit appearance work around

- documentation/src/components/code-example.ts
- documentation/src/components/component.ts
- packages/bar-loader/test/bar-loader.test.ts
- packages/circle-loader/test/circleloader.test.ts
- packages/menu/src/MenuGroup.ts
- packages/menu/test/menu-group.test.ts
- packages/meter/test/meter.test.ts
- packages/modal/src/spectrum-modal-wrapper.css
- yarn.lock
When updating out a11y and linting dependencies a couple of changes/issues arose. This addresses them separate of the broader work in which they were discovered.
The `sp-menu-group` change is not what I would want here, but in that it's being targeted for focused work in things like #715 and #350 that it made sense to get the tests passing here and address more holistic changes the accessibility model there later.
Test how we're supposed to use things!
It is tests.
> fix: address a11y/linting issues raised by updating our dependencies

- packages/card/src/Card.ts
- packages/card/test/card.test.ts
- add `change` event dispatches to interactions with the checkbox.
fixes #1126
Smooth API delivery as currently documented.
- unit tests
> fix: ensure that all paths to user change of selected trigger a change event

- README.md
The link to the documentation to start a new component is broken (linked to localhost instead of actual documentation site).
* Helps our contributors actually navigate to the proper place! 
- [ x ] Bug fix (non-breaking change which fixes an issue)
> fix(README): broken link to documentation site

- test/visual/visual.js
`testFileName` was in the wrong scope and would throw a reference error when attempting to report specifics around a testing error...
> test: use correct scope for vrt variable

- packages/slider/src/Slider.ts
- packages/slider/test/slider.test.ts
Previously throwing focus into the `<input>` element of a majority of interactions left the browser a difficult task of discerning whether a focus event was "focus visible" (keyboard triggered) or not. This meant that if the slider was interacted with (focused) via a pointing device and the the browser tab was blurred/focused again the "focus" would be applied to the slide as "focus visible", igniting the blue focus ring. This throws the focus to the `<label>` element via an imperative `click` event, which under the browser covers throws focus to the `<input>` without directly assigning additional event origin information. This leads to the "focus visible" check being more natural and the focus when returning to the tab active more like an `<input type="range">` element.
fixes #517 
We …
> fix(slider): manage focus more like a native rage input

- projects/story-decorator/package.json
- projects/story-decorator/src/StoryDecorator.ts
"Reduced Motion" in the story decorator currently applies to the main `sp-theme` provider, however when content is overlaid we're not resolving the "reduced motion" setting for that content. This monkey patches the `ActiveOverlay` render in this context to allow for the overlay content to accept "reduced motion" as well. In the future, when a Spectrum-wide approach to "reduced motion" is outlined, we can promote this to a first class feature of the `sp-theme` ecosystem.
Flakey tests.
> fix(story-decorator): ensure reduce motion application in overlays

- packages/dialog/dialog-wrapper.md
- packages/overlay/README.md
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/active-overlay.css
- packages/overlay/src/overlay-stack.ts
- packages/overlay/src/overlay-trigger.css
- packages/overlay/stories/overlay-story-components.ts
- packages/popover/src/Popover.ts
- packages/tooltip/src/Tooltip.ts
- ensure `[focusable]` can be passed focus
- remove focus outline on `ActiveOverlay`
- use `aria-hidden="true"` on content that prevents tab access
- have `overlay-stack` set `content.open = true` rather than rely on implementor
- allow "hover" content to be trigged via `focusin/out`
fixes #1133
Accessibility, predictability, simplicity, correctness.
Manually at https://60108127101bb4010c2b6208--spectrum-web-components.netlify.app/components/dialog-wrapper
> Overlay review updates.

- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay.test.ts
- place return focus element on demand
- as a short lived element it no longer needs to be cached on the `ActiveOverlay` element
fixes #1094
Functional elements should not reposition visual elements
Manually
> fix(overlay): place return focus element on demand

- packages/base/package.json
Looks like this was the only thing that cycled and then _everything_ cycled. We had removed the use of this dependency a while back for TS cycles and forgot to remove the JS dependency.
Actual cycles are bad.
`yarn lerna changed` no longer warns of cycles
> fix: reduce cycles

- .circleci/config.yml
- packages/action-button/test/action-button.test.ts
- packages/base/src/sizedMixin.ts
- packages/divider/src/Divider.ts
- packages/link/src/Link.ts
- packages/link/test/link.test.ts
- support "sized" element without a _default_ size
- support forcing element back to a _default_ size when the `size` attribute is removed
Allow links and other sized element to be used more easily.
Unit tests!
See the `sp-link` elements displaying appropriately below...
> fix: expand sized functionality to support no default and returning to default values

- documentation/src/utils/posthtml-spectrum-typography.js
Make sure links in the documentation site are delivered as `sp-link` elements
This doesn't look awesome: 
In the local build via the screenshot below...
> docs: process anchor tags in markdown as sp-link elements

- packages/bundle/package.json
- packages/split-button/package.json
- yarn.lock
One of these was missed, another seems like it merged weird, but the `dropdown` pattern is no longer part of the library.
> fix: correct dependency graph

- packages/icons-workflow/bin/build.js
Prevent ad blocking extensions from blocking unbuilt SWC code by renaming `AdPrint` to `PrintAdvert` and `AdDisplay` to `DisplayAdvert`. 
This is a "breaking" change, and I'm also unsure whether it goes far enough for ALL ad blockers and would appreciate feedback on whether there's a better name to use, whether it matters, whether we should do something else...
fixes #1160
Unbuilt apps should not be blocked by ad blockers.
Locally with adblockplus.org installed in my browser.
> [rfc] fix(icons-workflow): rename icons/files to avoid ad blocking

- packages/banner/README.md
- packages/card/README.md
- packages/popover/README.md
- packages/radio/README.md
- uses `max-width` et al to support responsive delivery of the banner, card, and popover patterns
- fixes typo in radio
- prefers #1207 for tabs pattern
- radio group seems to have fixed itself with some better wrapping from upstream
fixes #694
Docs should make us look good.
Manually in the docs: https://6035833901788b0b1983fe8a--spectrum-web-components.netlify.app/components/banner
> docs: make more responsive

- documentation/src/components/component.ts
- documentation/src/components/side-nav-search.ts
- packages/overlay/README.md
- packages/overlay/overlay-trigger.md
Clarify the usage of both the `Overlay` api and it's `open()` method and the `overlay-trigger` element by disambiguating them in the documentation site.
This might change a bit with @adixon-adobe's changes/additions of a reparenting API, so I wanted to get this out there to help the development there.
fixes #866 
More, clearer docs are best.
By you, here: https://603591a4ba119117846bd34f--spectrum-web-components.netlify.app/components/overlay and, here: https://603591a4ba119117846bd34f--spectrum-web-components.netlify.app/components/overlay-trigger
> docs(overlay): separate overlay and overlay-trigger APIs

- documentation/src/components/component.css
Sizes the `sp-dialog` element appropriately within the usage context of our documentation site in small screen contexts.
- we specifically place this element in a parent with padding so that it's `min-width` does not apply well to the layout, so use the `--spectrum-dialog-confirm-min-width` CSS Custom Property to correct.
- don't directly address `mode="fullscreenTakeover"` or `mode="fullscreen"` as it needs input from Spectrum CSS, scoped by only apply the size to content inside a `code-example` element.
fixes #671
refs #1041
Our documentation should look good.
Manually in the docs site: https://603578357fc48b00d8e7122e--spectrum-web-components.netlify.app/components/dialog
> docs(dialog): clean up responsive delivery

- packages/button/src/ButtonBase.ts
Add `pointerleave` (`pointercancel` requires capturing the pointer which then requires additional work to make the "click away" not actually click the button) to the events that manage the removal of the `active` state of buttons.
fix #1219
Correct UI.
Manually, and you can too: https://6037c9264f9c270bfa8db70a--spectrum-web-components.netlify.app/storybook/?path=/story/action-button--toggles
> fix(button): include "pointerleave" in management of the "active" state

- packages/styles/package.json
Compiled files like [spectrum-base.css.js](https://unpkg.com/browse/@spectrum-web-components/styles@0.8.0/src/spectrum-base.css.js) reference the `css` directive from the `@spectrum-web-components/base` package at runtime, so needs to be in `dependencies` section of the `package.json` (not `devDependencies`.)
Package managers like yarn in strict mode will complain about not explicitly declaring all of your dependencies.
> fix(styles): move `@spectrum-web-components/base` from devDependencies to dependencies

- packages/accordion/src/AccordionItem.ts
- packages/action-button/src/ActionButton.ts
- packages/action-menu/src/action-menu.css
- packages/base/src/sizedMixin.ts
- packages/button/src/ClearButton.ts
- packages/checkbox/src/Checkbox.ts
- packages/dialog/src/Dialog.ts
- packages/field-label/src/FieldLabel.ts
- packages/field-label/stories/field-label.stories.ts
- packages/menu/src/MenuItem.ts
- packages/picker/src/Picker.ts
- packages/search/src/Search.ts
- packages/split-button/src/SplitButton.ts
- packages/textfield/src/Textfield.ts
- packages/toast/src/Toast.ts
Prefer the tested performance benefits of `<sp-icon-*>` elements over `<sp-icon>${Icon()}></sp-icon>` benefits.
This approach also allows for module based as opposed to tree shake based bundling for smaller builds.
Smaller, faster, easier.
Passes the visual regression!
> refactor: use registered icons elements for performance and bundling benefits

- packages/picker/src/Picker.ts
- packages/picker/test/picker.test.ts
- packages/split-button/src/SplitButton.ts
- packages/split-button/test/split-button.test.ts
Add support for making a "quick selection" when an `sp-picker` element is focused via the right and left arrow keys.
Uses a cached `selectedItem` property to reduce work across the various interactions.
Check it out at: https://6037cd0dd41f080c0b2563ad--spectrum-web-components.netlify.app/components/picker
fixes #254
refs #1187
Make users lives easier and parity with other Spectrum component offerings.
Manually and unit tests.
> fix(picker): add "quick select" action to right/left arrow keys

- packages/split-view/package.json
- packages/split-view/src/SplitView.ts
This PR fix the calculation of initial height of primary panel when using primary-size="auto".
It replaces the parseInt function by parseFloat and rounding it up to the next full pixel value to prevent shrinking the initial height of the primary panel.
https://github.com/adobe/spectrum-web-components/issues/1243
it solves the problem of current client experiencing a shrink of initial height when adding a second panel and using the attribute `primary-size="auto"`. It leads to display scrollbars where in that use case it shouldn't be displayed of the first panel content. 
Visual testing, correct behavior already in local installation of the package to verify correct solution.
> [SplitView] Correct calculation of height when using primary-size='auto'

- .circleci/config.yml
- packages/menu/src/Menu.ts
- packages/modal/src/spectrum-modal.css
- packages/picker/src/picker.css
- packages/picker/src/spectrum-picker.css
- packages/picker/stories/picker.stories.ts
- packages/picker/stories/states.ts
- packages/styles/fonts.css
- scripts/process-spectrum-postcss-plugin.js
- scripts/spectrum-vars.js
When we point component root style to a `shadowSelector` in `spectrum-config.js` it is possible that CSS Custom Properties meant for the root of an element get pointed to a child element making it impossible to customize or override them from the outside. This alters our process scripts to ensure that those definitions get moved to the actual `:host` allowing for customization. Here I've added an `sp-picker[style="width: 400px;"]` element to the storybook/visual regression suite to ensure this stays possible going foward.
fixes #1155
Style customization should be addressable without heroic intervention.
- manually
- storybook
- VRT
> build: hoist CSS Custom Properties from hostShadowSelector to :host

- .circleci/config.yml
- packages/modal/src/modal.css
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/active-overlay.css
- packages/overlay/src/overlay-stack.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-trigger.test.ts
- take `body { margin: X }` into account when calculating the size of content in not the top layer of the overlay stack
- add a visual regression test for this
- realize that any one `type="modal"` overlay creates a sub-group in the stack that must be handled similarly
- add a unit test for this 
fixes #1234
The overlay stack should be resilient to many application contexts.
- manuall
- visual regression additions
- unit test additions
> Expand overlay stack support of sizing and modal "groups"

- .circleci/config.yml
- packages/action-bar/stories/action-bar.stories.ts
- packages/action-group/src/ActionGroup.ts
- packages/action-group/stories/action-group.stories.ts
- packages/action-group/test/action-group.test.ts
Ensure the `sp-action-group` supports `sp-action-button`s that are not direct children so that buttons with tooltips driven by `overlay-trigger` elements can be leveraged.
fixes #1230
JS errors are bad. Complex element usage is good.
Unit tests and manually in Storybook
> fix(action-group): support ActionButtons that are not direct children

- packages/bundle/package.json
The updated `exports` syntax allows bundlers to be more strict with their processing leading to https://cdn.skypack.dev/error/build:@spectrum-web-components/bundle@v0.19.0-7h0wI9m3AxFBcDNYHbyx which is a solid point being `bundle` doesn't actual export any of it's own custom elements and won't ever include this file.
> fix(bundle): bundle does not export its own custom-elements.json

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/test/action-menu.test.ts
- refactor one last `<sp-icon>` usage to `<sp-icon-*>` for perf and tree shaking simplicity
- prevent `sp-action-menu` from _accidentally_ resolving its accessible content from the default icon and clarify labelling story in demos
Not having to tree shake is a win for no/low-build situations.
- visual regressions
- a11y units
> refactor: remove sp-icon usage in shipped elements

- .circleci/config.yml
- packages/action-button/src/action-button.css
- packages/action-button/stories/action-button.stories.ts
- packages/button/src/ButtonBase.ts
- packages/button/src/button-base.css
- packages/menu/src/MenuItem.ts
- packages/menu/src/menu-item.css
- packages/menu/stories/menu-item.stories.ts
- Relocate handling for likeAnchor content in `ButtonBase` so all of it's derivatives receive the support for this style of delivery
- Enable appropriate right click response in this context
- Add visual regressions to support maintaining this going forward
Buttons with links should look correct, while still working like links.
Manual and visual regressions.
> fix: correctly delivery visuals and mouse interactions for likeAnchor and extensions

- packages/base/src/streaming-listener.ts
- packages/color-area/src/ColorArea.ts
- packages/color-area/test/color-area.test.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/test/color-slider.test.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/color-wheel/test/color-wheel.test.ts
- packages/slider/src/Slider.ts
- packages/slider/test/slider.test.ts
- remove right click value setting from `sp-color-area`, `sp-color-slider`, `sp-color-wheel`, and `sp-slider`
- normalize `sp-slider` to the use of `streamingListener` and remove support for mouse event fallbacks
fixes #1291
- setting value from right click means you can't inspect
- normalized code is easier to maintain
- enough safari supports `pointerEvents` now
Unit tests and manually.
> fix: remove right click value setting

- documentation/src/components/code-example.css
- documentation/src/components/code-example.ts
- documentation/src/components/copy-to-clipboard.ts
Add copy to clipboard functionality to code examples
See it live: https://605005b0ee00f311996ffce8--spectrum-web-components.netlify.app/
Easier code use.
Manually
> docs: add copy to clipboard functionality

- .circleci/config.yml
- packages/color-area/src/spectrum-color-area.css
- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-trigger-click.test.ts
- packages/overlay/test/overlay-trigger-hover.test.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
- packages/tooltip/stories/tooltip.stories.ts
Add an `open` attribute to the `<overlay-trigger>` element to declaratively outline which overlay content is open.
- open = 'click' | 'hover' | 'longpress'
- refactor existing stories to leverage
- simplify open/close workflow
fixes #424 
Elements should be usable in a declarative fashion.
New unit tests and VRTs.
- [c] New feature (non-breaking change which adds functionality)
> fix(overlay): allow overlay-trigger to declaratively open overlay content

- .circleci/config.yml
- packages/checkbox/src/CheckboxBase.ts
- packages/checkbox/stories/checkbox.stories.ts
- packages/checkbox/test/checkbox.test.ts
- packages/picker/src/Picker.ts
- packages/picker/src/picker.css
- packages/picker/stories/picker.stories.ts
- packages/picker/test/picker.test.ts
- packages/radio/src/Radio.ts
- packages/radio/stories/radio.stories.ts
- packages/radio/test/radio.test.ts
- packages/switch/stories/switch.stories.ts
- packages/switch/test/switch.test.ts
- packages/tags/src/Tag.ts
- packages/tags/stories/tags.stories.ts
- packages/tags/test/tag.test.ts
- packages/textfield/src/Textfield.ts
- packages/textfield/stories/textarea.stories.ts
- packages/textfield/stories/textfield.stories.ts
Currently fails in CI as I'm waiting for #1287 to land before managing the visual regressions added here.
Add `readonly` attribute to:
- [checkbox](https://605204763582c4ac55114e9b--spectrum-web-components.netlify.app/storybook/index.html?path=/story/checkbox--readonly) 
- [picker](https://605204763582c4ac55114e9b--spectrum-web-components.netlify.app/storybook/index.html?path=/story/picker--readonly)
- [radio](https://605204763582c4ac55114e9b--spectrum-web-components.netlify.app/storybook/index.html?path=/story/radio--readonly)
- [switch](https://605204763582c4ac55114e9b--spectrum-web-components.netlify.app/storybook/index.html?path=/story/switch--readonly)
- [tag](https://605204763582c4ac55114e9b--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tags--readonly)
- …
> fix: add support for "readonly" attribute

- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-trigger-hover.test.ts
- packages/overlay/test/overlay-trigger.test.ts
"hover-content" in an `<overlay-trigger>` will not persist through click events on the trigger element when there is not "click-content" the needs to be shown in response to that interaction. Further content centric events, `longpress`, `mouseout`, `blur`, etc. will cause the hover content to be closed. This is particularly useful in cases where clicking the trigger toggles its state and that state is represented in the hover content that has been projected.
fixes #277
Better tooltips for triggers that toggle.
New unit tests. https://westbrook-persist-hover-overlay--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--overlaid-top
> fix(overlay): persist hover overlay when there is not click content

- .circleci/config.yml
- packages/field-label/src/FieldLabel.ts
- packages/menu/menu-item.md
- packages/overlay/stories/overlay.stories.ts
- packages/picker/README.md
- packages/picker/src/Picker.ts
- packages/picker/stories/picker-sizes.stories.ts
- packages/picker/stories/picker.stories.ts
- packages/picker/test/picker.test.ts
- packages/shared/src/focusable.ts
- projects/example-project-rollup/index.html
- projects/example-project-rollup/package.json
- projects/example-project-rollup/src/example-app.ts
- projects/example-project-webpack/package.json
- projects/example-project-webpack/src/index.html
- projects/example-project-webpack/src/index.js
- test/a11y-snapshot-plugin.ts
- test/testing-helpers.ts
- test/tsconfig-plugins.json
- web-test-runner.config.js
- ensure that both the `field-label` content and the current `value` are represented in the accessibility tree of the picker
- prevent element errors in the "quick select" functionality
- label all of the pickers
- add accessibility snapshot tool for Playwright
fixes #1077
refs #1269
Screen reader users should have a clear representation of the content otherwise made available when seeing the UI.
- manual review with the accessibility team
- unit tests
- visual regressions
> feat(picker): process field-label content for more accurate a11y tree

- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/src/overlay-types.ts
- packages/overlay/src/overlay.ts
- packages/overlay/test/overlay-trigger-click.test.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
- add state (rather than a workaround) to handle whether a `longpress` overlay has been opened via the mouse or via the keyboard
- correct the management of whether an `sp-closed` event should close ALL overlays or not
- update/add tests to support maintaining this long term
fixes #1313
Non-hover/longpress (mouse only) overlays wouldn't open a second time.
- manually
- new tests
- updated tests
https://westbrook-overlay-trigger--spectrum-web-components.netlify.app/components/dialog-wrapper
> fix(overlay): handle hover/longpress more directly via the "open" attribute

- .circleci/config.yml
- packages/slider/src/Slider.ts
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider.test.ts
- change the default `max` value to 100 to more closely match that of a native `<input type="range" />` element
- move from `div[ole="textbox"]` to `output` for the value label
- remove superfluous `aria-*` attributes
- update story to demonstrate the use of `Intl.NumberFormat` for managing the value label
fixes #1308
fixes #1285
Increase predictability, accessibility, and usability of the pattern.
- Manually in the DOM inspector and mac voice over
- Updated some unit tests
> fix(slider): update a11y tree and default max value

- packages/overlay/src/ActiveOverlay.ts
- packages/picker/src/Picker.ts
- packages/shared/src/reparent-children.ts
Use the `reparentChildren` helper in `overlay-trigger`.
fixes #1249
Simplify code by leveraging helper.
CI.
> refactor(overlay): leverage "reparentChildren" helper

- packages/color-area/src/ColorArea.ts
- packages/color-area/test/color-area.test.ts
The up and down arrow keys were reported to be stuck in the Colour Area, which is a pretty serious usability issue. Luckily, it is now resolved. 
Fixes https://github.com/adobe/spectrum-web-components/issues/1255
Requested by our users. Also, it's just not great to have something that doesn't work.
Manual testing
> fix(color-area): Fix stuck up and down arrow keys 

- packages/dialog/src/Dialog.ts
Add slot documentation to the the Dialog listing.
fixes #1247 
We should inform users how to use out element.
> docs(dialog): add documentation for the slot API

- .circleci/config.yml
- packages/picker/stories/picker.stories.ts
- packages/popover/src/popover.css
Ensure maintaining the size of an `active-overlay` element is passed down to descendants.
fixes #1323 
Size management is important to surfacing this functionality.
Manually
New visual regression
> fix: correct max size calculation for overlays

- scripts/process-spectrum-css.js
- scripts/process-spectrum-postcss-plugin.js
Ensure that `yarn process-spectrum` still works post the postcss upgrade.
fixes #1347 
Things should work.
Manually to local changes that I reverted before committing.
> chore: update postcss usage

- packages/color-slider/test/color-slider.test.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/color-wheel/test/color-wheel.test.ts
Ensure color management with the `sp-color-wheel` element works like that in `sp-color-slider` and does not apply opinions as to what the saturation and value of a color it manages should be.
fixes #1257
Make https://webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/m5lUgBAAejgIkESwRvEs/src/index.ts?branch=master et al perform more as expected.
New unit test expectations in both wheel and slider to prevent regression in the future.\
> fix: ensure color wheel in not opinionated about saturation and lightness

- packages/color-area/stories/color-area.stories.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-wheel/src/ColorWheel.ts
- pass a hue normalized color to handles in slider/wheel elements so that when they area associated with saturation/lightness modifying interfaces they do not display that in their handle
- add "focus management" to pointer === mouse controls so that the handle is made larger during interaction
Preview: https://wesbtrook-handle--spectrum-web-components.netlify.app/storybook/index.html?path=/story/color-area--joint
fixes #1257 
Composed UIs should appear more as expected by default.
Manually as it's a primarily visual change.
> fix: use hue normalized color in handle and allow focus

- packages/progress-bar/README.md
- packages/progress-circle/README.md
Expand and correct documentation of `sp-progress-bar` and `sp-progress-cirlce` to include and outline when/how labels should be applied to the elements.
fixes #1271
fixes #1274
Accessibility!
https://westbrook-progress-bar--spectrum-web-components.netlify.app/components/progress-bar
https://westbrook-progress-bar--spectrum-web-components.netlify.app/components/progress-circle
> docs: clarify label usage in regards to role="progressbar" uis

- packages/picker/src/Picker.ts
- packages/picker/test/picker.test.ts
Ensures that the available options are as up-to-date as possible before validating a change to the picker's `value`.
refs #1331 maybe fixes, if we chose to follow up on the conversation there with a more specific issue
Users shouldn't have to be precious with our elements.
Unit test added.
> fix(picker): accept new "value" and new option post first render

- packages/overlay/src/ActiveOverlay.ts
- packages/shared/src/reparent-children.ts
- packages/shared/test/reparent-children.test.ts
@adixon-adobe I'm not 100% sure it's required, just yet, but if we were to expand on #1290 with the callback pattern to manage extended interaction with the reparented elements, it might look like this.
> refactor: use a callback to handle extended reparenting management

- packages/styles/package.json
Make JSPM happy about our exports listing.
Now: https://jspm.dev/@spectrum-web-components/styles@0.9.5-alpha.1/body.js
Previously: https://jspm.dev/@spectrum-web-components/styles@0.9.4/body.js
Upon thinking this all the way through I can understand why they would choose not to support the `'./*': './*'` listing that we were using, as it cuts off the ability to easily map "entry points" to not root directory sources. It does make me think that maybe we want to move things out of the root directory at some point in the future and rely on exports to map to the right file... something to think about in the future.
fixes #1190 🤞🏼 
At least one CDN needs to be happy with out bundle package so we can use it on the Getting Started page.
See above links.
> fix(styles): update exports listing

- packages/menu/src/Menu.ts
- packages/menu/src/MenuItem.ts
- packages/menu/test/menu.test.ts
- prevent `sp-menu-item` elements from having `tabindex="0"`
- do `focus()` work even when tabbing into the menu
- allows users to tab both into and _past_ the `sp-menu` element.
fixes #1040
Accessibility and correctness.
Manually and with an updated unit test
https://westbrook-menu-keys--spectrum-web-components.netlify.app/components/menu
> fix(menu): manage tabindex and focus entry correctly

- packages/accordion/src/Accordion.ts
- packages/field-label/src/FieldLabel.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/src/overlay-timer.ts
- packages/popover/src/Popover.ts
- packages/sidenav/src/Sidenav.ts
- packages/textfield/test/textfield.test.ts
- packages/tooltip/src/Tooltip.ts
Replace `isSameNode` with `===`.
When the webcomponentsjs polyfills are applied, Node.isSameNode may fail if the argument is not a Node. This failure is not in the spec and is browser-specific. This change removes isSameNode and replaces it with direct comparison, which is equivalent.
fixes #1369 1367
https://github.com/webcomponents/polyfills/issues/436
Though spectrum-web-components does not officially support old browsers, this change may be a reasonable and low-impact change to make.
I ran `yarn test`.
N/A
> Avoid use of Node.isSameNode

- documentation/index.html
This probably deserve better docs somewhere, but wanted to get this fixed first...
> docs: do not use margin on body with position: absolute root

- package.json
- packages/menu/src/Menu.ts
- packages/picker/test/picker.test.ts
The `scrollIntoView()` functionality to support keyboard interactions actually moves the `sp-menu-item` when scrolling is possible making the `click` event not trigger correctly. This sequester the `scrollIntoView()` call to _only_ the keyboard workflow to support this.
TODO:
fixes #1361 
Works as expected.
Manually
https://westbrook-menu--spectrum-web-components.netlify.app/storybook/?path=/story/picker--custom
> fix(menu): only scrollIntoView when keyboard navigating

- packages/button/src/ButtonBase.ts
Commit to one version of surfacing the anchor element in `sp-button href` and derivative elements.
- the single placement of an invisible link over the entire button element prevents the need to proxy a click _unless_ the implementing developer uses `button.click()`
- gate the click event listening to proxy `sp-button type="submit"` on the availability of an `href` value
fixes #1376 
Should only click once.
Manually in Firefox and with the existing unit tests.
> fix(button): no double link clicks

- packages/overlay/README.md
A first iteration of event documentation in non-element docs pages. All info, no style... so, happy to take notes if there was something easily attainable that was more informative here. We need to expand on our ability to document non-element content, but I'm not sure where to take this right now. This hopefully gets the information into the world, and we can revisit this page (and bundle/base/styles/etc.) soon.
fixes #1360
Ensure users know the capabilities made available to them by our APIs.
https://westbrook-overlay-events--spectrum-web-components.netlify.app/components/overlay
> docs(overlay): include event lisings

- packages/radio/src/Radio.ts
- packages/radio/src/RadioGroup.ts
- packages/radio/stories/radio.stories.ts
- packages/radio/test/radio-group.test.ts
Ensure correct management of bindings on both the `selected` attribute of an `sp-radio-group` element and the `value` attribute of its `sp-radio` children.
Using this pattern in app with enums or similar currently drops the first `selected` value for lack of access to the children at run time.
Updated units and demos.
> fix(radio): ensure radio-group first selected value is followed

- packages/tags/README.md
- packages/tags/src/Tag.ts
- packages/tags/src/Tags.ts
- packages/tags/test/tags.test.ts
The tabs are now only included in the tab order if they can be actioned (ie deleted). 
fixes https://github.com/adobe/spectrum-web-components/issues/769 
Our tags could be tab indexed regardless of their ability to be changed by the user. They're not actionable elements, so they shouldn't be included in the tab order. 
Manually and with added tests
> Fix(tags): tags should only be focusable if they can be actioned (deleted / selected)

- packages/slider/src/Slider.ts
- packages/slider/test/slider.test.ts
- test/send-mouse-plugin.ts
- test/tsconfig-plugins.json
- web-test-runner.config.js
- bind event handlers correctly so that `dragging` is released and track based value setting associated to drag based value setting
- add `sendMouse` plugin so that we can appropriately line up our test interactions with the slider with the expectations of the `focus-visible` polyfill when testing interaction state
fixes #1404 
Correct a bug.
- unit tests with new `sendMouse` plugin.
https://westbrook-slider--spectrum-web-components.netlify.app/components/slider
> fix(slider): ensure pointer events on the track and handle act the same

- documentation/webpack.config.js
- scripts/add-custom-properties.js
- scripts/css-processing.cjs
- scripts/process-spectrum-css.js
- scripts/spectrum-vars.js
Correct the usage of `postcssCustomProperties` so that CSS Custom Properties are published to the documentation site again.
Easier to use.
https://westbrook-custom-props--spectrum-web-components.netlify.app/components/action-button/api
> fix: correctly apply CSS Custom Props to docs site

- packages/button/src/ButtonBase.ts
- packages/shared/src/like-anchor.ts
Prevent content placed in the proxy link element from being read by screen readers.
Continually expanding use cases
Manually
> fix: allow rendered anchors to be aria-hidden

- packages/sidenav/src/Sidenav.ts
- packages/sidenav/src/SidenavItem.ts
- packages/sidenav/src/sidenav-item.css
- packages/sidenav/stories/sidenav.stories.ts
- packages/sidenav/test/benchmark/test-basic.ts
- packages/sidenav/test/sidenav.test.ts
Contain the `sidenav-select` within the `sp-sidenav` element, and re-dispatch this update as a `change` event on the root, so that it can be tracked more like a form element. The `sidenav-select` event can still be heard on individual `sp-sidenav-item` elements, which are available in the light DOM (see the documentation site build for continued usage of this).
There was some more in depth event management that was going on with `sidenav-select` and `manage-tab-index` that made sense to centralize on a single interface as part of this update. The most recent build shows a statistically significant preference for the new version.
```
┌─────────────┬────────────────────┐
│   Benchmark │ sidenav:test-basic │
├─────────────┼────────────────────┤
│     Browser │ chrome-headless    │
│ …
```
> feat(sidenav): add a "change" event to track the "value" property

- packages/slider/src/Slider.ts
- packages/slider/test/slider.test.ts
Make sure the `value` is set _after_ `min`, `max`, and `step` in the rendered template and that validation of the `value` happens after the `<input>` element is update, instead of before.
fixes #1308
Easier, less error prone element usage.
- unit tests updated and passing
- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
> fix(slider): ensure min/max/value application order

- packages/menu/src/Menu.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/picker/src/Picker.ts
- packages/picker/test/picker.test.ts
- packages/shared/src/reparent-children.ts
- web-test-runner.config.js
Afford the current `:focus-visible` context from the `<sp-menu>` element to its `<sp-menu-item>` children when navigating through them.
- only show the blue edge highlighting when the `:focus-visible` heuristic has been triggered.
- persist selected and hovered visual states without alteration
fixes #1136 
Clearer interface delivery.
New unit tests for both sides of the workflow, including some _special_ Firefox conciderations.
https://westbrook-menu--spectrum-web-components.netlify.app/components/picker
> fix(menu): pass current focus visibility to menu items

- .circleci/config.yml
- packages/overlay/src/active-overlay.css
- packages/overlay/stories/overlay.stories.ts
- don't force any overlay to have a specific height
- allow content in non-animating overlays to take pointer events
- add story to outline usage of "manually prepares" overlay content
fixes #1289 
Not everyone is going to use "expected" content in their overlays
Manually in storybook.
https://westbrook-active-overlay--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--modal-loose
https://westbrook-active-overlay--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--modal-managed
> fix(overlay): reduce the control active-overlay places on its content

- packages/action-group/src/ActionGroup.ts
- packages/action-group/test/action-group.test.ts
- packages/overlay/test/overlay-trigger.test.ts
- default child role is now `button` when `selects` is not set
- do not allow unset `label` attributes to overwrite the `aria-label` attribute on first render
refs #1419
refs #1418
Content appearance in the screen reader.
Expanded unit tests
> Update Action Group accessibility

- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/src/overlay-types.ts
- packages/overlay/src/overlay.ts
- packages/overlay/test/overlay-lifecycle.test.ts
- packages/tooltip/src/Tooltip.ts
- create "Overlay Lifecycle" methods that call into the overlaid element at open and close time:
- `overlayWillOpenCallback` marks the beginning of the open cycle. by default this is followed in a few short frames with the actual opening of the overlay and in this way can be seen as equivalent to an `overlayOpenedCallback` for most concerns)
- `overlayOpenCancelledCallback` takes into account overlay content that is `delayed` (usually tooltips) and could have their open process cancelled.
- `overlayCloseCallback` handles when the entire cycle is complete and only can occur for overlays that had not previously called `overlayOpenCancelledCallback`.
- each method accept an `options` argument with `{ trigger: HTMLElement }` (to support expanding to more options as needed in the future) and …
> fix(overlay): add overlay lifecycle methods to stack management

- .circleci/config.yml
- documentation/src/components/layout.css
- packages/bundle/elements.ts
- packages/bundle/package.json
- packages/bundle/src/index.ts
- packages/bundle/tsconfig.json
- packages/overlay/src/ActiveOverlay.ts
- packages/tray/README.md
- packages/tray/package.json
- packages/tray/sp-tray.ts
- packages/tray/src/Tray.ts
- packages/tray/src/index.ts
- packages/tray/src/spectrum-config.js
- packages/tray/src/spectrum-tray.css
- packages/tray/src/tray.css
- packages/tray/stories/tray.stories.ts
- packages/tray/test/benchmark/basic-test.ts
- packages/tray/test/tray.test.ts
- packages/tray/tsconfig.json
- test/visual/story-imports.ts
- yarn.lock
Add the `sp-tray` element.
- update docs so they don't double scroll bar
- simplify the storybook config for easier pattern additions
- tweak the Active Overlay entry process to reduce unneeded focus loops.
- The "mobile" implementation of the stepper UI has yet to be implemented at the Spectrum CSS level and as such in not included in this PR.
fixes #1461
Better coverage of Spectrum CSS patterns.
Prep for expanded coverage of the Picker pattern in mobile.
- unit tests
- VRTs
- https://westbrook-tray--spectrum-web-components.netlify.app/components/tray
- https://westbrook-tray--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tray--default
> fix(tray): add tray pattern

- documentation/src/components/code-example.css
- packages/checkbox/src/checkbox.css
- packages/color-slider/src/color-slider.css
- packages/color-wheel/src/color-wheel.css
- packages/link/src/link.css
- packages/radio/src/RadioGroup.ts
- packages/radio/test/radio-group.test.ts
- packages/shared/README.md
- packages/shared/src/focusable.ts
- packages/sidenav/test/sidenav.test.ts
- packages/slider/src/slider.css
- packages/textfield/src/textfield.css
- prevent the presence of a focus outline on element hosts in Safari where the `focusElement` child isn't a "focusable" element
- Safari doesn't not by default support focusing `input[type="radio"]`, `input[type="checkbox"]`, `input[type="range"]`, or `a` elements, so while "focus" will sometimes resolve to their host the focus outline has been remove from these sorts of elements
- prevent focusing the host when interacting with elements that contain "focusable" children
- correct the time as which `tabindex` is manages for children of a `sp-radio-group` element so that it performs more predictably
fixes #1426 
fixes #1038
- correct visual delivery in Safari
- correct keyboard interaction when `input[type=radio]` is "focusable"
- unit tests
- manually …
> fix: prevent tabindex=-1 elements from placing focus on their host

- packages/shared/src/focusable.ts
Go here: https://opensource.adobe.com/spectrum-web-components/components/tags
- scroll the nav down a bit
- attempt to navigate to another component
- see the scroll update but not the page
Go here: https://westbrook-focus-options--spectrum-web-components.netlify.app/components/tabs
- do the same
- see it work
Yay!
Links should work.
Manually in the docs site
> fix: no scroll update when managing elements outside of the tab order

- packages/tabs/README.md
Typo in the documentation for Tabs had the incorrect import for sp-tab-panel. This was corrected to prevent copy-paste errors or other confusion.
updated documentation saying
import '@spectrum-web-components/tabs/sp-panel.js';
to
import '@spectrum-web-components/tabs/sp-tab-panel.js';
https://github.com/adobe/spectrum-web-components/issues/1490
I copy-pasted the incorrect value and wanted to save others the same misfortune.
Using the "grip" tool to serve and render Github markdown on local server. Also looked correct in the github fork for this fix.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the …
> docs(tabs): fixed path to sp-tab-panel in import code block

- packages/textfield/src/Textfield.ts
- packages/textfield/test/textfield.test.ts
Pass the `select()` method from `sp-textfield` hosts to their `input` children in the shadow DOM.
fixes #1377 
Enable advanced interactions with the textfield.
- unit tests
> fix(textfield): add select() API mapping to shadow DOM element

- .circleci/config.yml
- packages/overlay/local.d.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/VirtualTrigger.ts
- packages/overlay/src/index.ts
- packages/overlay/src/overlay-types.ts
- packages/overlay/src/overlay.ts
- packages/overlay/src/popper.ts
- packages/overlay/stories/overlay.stories.ts
Add a `virtualTrigger` option to the overlay process that will supersede the element trigger, when available, as part of interaction directly with PopperJS.
`new VirtualTrigger(x, y)` will now provide a `VirtualElement` that can be passed an option to the `openOverlay` methods for use as the "trigger" in calls to PopperJS. The element makes public both a `getBoundingClientRect()` method for position the overlay and a `updateBoundingClientRect(x, y)` method for moving the "trigger" of the overlay. `updateBoundingClientRect()` also calls `Overlay.update()` internally to reduce the amount of manual interaction required to update overlays opened with the virtual trigger context.
fixes #1437 
Attempt to simplify from #1445 
Manually in Storybook. If this approach makes sense, some unit tests …
> Virtual Trigger as additional option to split what's send to Popper and SWC

- packages/meter/package.json
- packages/meter/src/Meter.ts
- packages/meter/test/benchmark/basic-test.ts
- packages/slider/src/Slider.ts
- packages/tabs/src/Tab.ts
Using an attribute fallback value for a default `slot` element can produce unexpected results when there is a text node with whitespace in side of the host element. The `ObserveSlotText` mixin allows us to apply the attribute in a non-replacing location when there is no content in the slotted text node.
fixes #1113
Labels should be easy.
Passes VRTs and unit tests.
> fix: use ObserveSlotText mixin to prevent white space from overriding label attribute

- .circleci/config.yml
- packages/color-area/README.md
- packages/color-area/src/ColorArea.ts
- packages/color-area/stories/color-area.stories.ts
- packages/color-area/test/color-area.test.ts
TinyColor has a problem where it, upon using HSL/HSV colour models, does not preserve the value of `hue` if the saturation is set to 0. By extracting the `hue` in the `set color()` method, as is done in `sp-color-slider` and `sp-color-wheel`, we can preserve the hue when it's given by the user. In the `get color()` method, we use a RegEx to remove the incorrect `hue` value and replace it with the `hue` property when the colour format is a string. When it is an object, we simply inject the `hue` property into an object and return that. 
fixes https://github.com/adobe/spectrum-web-components/issues/1470
Getting rid of a long-standing bug. Thanks, TinyColor.
Manually and with unit tests
> [Color Area] Prevent TinyColor from overriding hue value on HSV/HSL colour formats

- .circleci/config.yml
- packages/menu/src/Menu.ts
- packages/menu/stories/menu.stories.ts
- packages/picker/stories/picker.stories.ts
Previously we were `scrollIntoView`ing an `sp-menu-item[selected]` every time the `sp-menu` was connected to the DOM. This causes some inadvertent page scrolling when the `sp-menu` in not the featured content or is in, say, an `sp-popover` that is not `[open]` and also not `display: none;`.
This update correctly leverages the `preventScroll` option in the `focus({preventScroll}: FocusOptions)` method to ensure that internal focus management does not move the scroll which allows us to rely only on direct focus calls without this option to `scrollIntoView`, removing the need to do so at connect time.
Oh, linting also get excited about the touched files...
fixes #1473
Not all usage is contained in our library and we need to be prepared for unexpected usage.
- this is tested in two new VRT …
> fix(menu): clarify menu internal focus management via preventScroll option

- .eslintrc.json
- .husky/pre-commit
- package.json
- packages/.eslintrc.json
- packages/color-area/src/ColorArea.ts
- packages/iconset/stories/icons-demo.ts
- packages/radio/src/RadioGroup.ts
- packages/top-nav/src/TopNav.ts
Update linting to catch more thing at commit and CI time, including `debugger` statements.
Remove errant `debugger` statement and a couple of other lint fixes.
fixes #1510 
It shouldn't `debugger` in production.
> fix: lint away debugger statements

- projects/story-decorator/src/StoryDecorator.ts
`event.stopPropagation()` on `keydown` events in the story decorator that pass through an `<input>` element so that it's easier to experience the full glory of documented elements.
fixes #1513
Storybook can be greedy about its use of keyboard interactions.
> docs: stop keydown propagation when on an input element

- packages/button/src/ButtonBase.ts
- packages/button/test/button.test.ts
- packages/menu/test/menu.test.ts
Prevent `ButtonBase` from being cavalier with the role of elements that might be managed outside of its knowledge.
- allows `sp-menu-item[href="#"]` and tests it
- updates role related tests in button
fixes #1508
Removing the `role` is unexpected and endangers the accessibility of delivered content.
- unit tests
> fix: update role application logic to not overwrite menu* roles

- packages/overlay/test/overlay-trigger.test.ts
- normalize test language across the file
- better leverage `oneEvent` when timing has proven flaky
- update cleanup code for stability/timing
Tests should be reliable
It is tests.
> test: normalize overlay-trigger testing and use oneEvent() to manage timing

- packages/accordion/README.md
- packages/accordion/accordion-item.md
Expand docs to include `sp-accordion-item` examples entry.
fixes #1487
The API page was "available" but only if you knew the URL.
https://westbrook-accordion-item--spectrum-web-components.netlify.app/components/accordion-item
> docs: expand accordion documentation to include its child item page

- packages/sidenav/README.md
- packages/sidenav/sidenav-item.md
Expand docs to include `sp-sidenav-item` examples entry.
fixes #1486
The API page was "available" but only if you knew the URL.
https://westbrook-sidenav-item--spectrum-web-components.netlify.app/components/accordion-item
> docs: expand sidenav documentation to include child element pages

- packages/number-field/README.md
- packages/number-field/package.json
- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/overlay.ts
- packages/overlay/test/overlay-trigger.test.ts
- packages/shared/src/focusable.ts
- packages/slider/README.md
- packages/slider/package.json
- packages/slider/src/HandleController.ts
- packages/slider/src/Slider.ts
- packages/slider/src/SliderHandle.ts
- packages/slider/test/slider.test.ts
- packages/theme/README.md
- packages/theme/src/Theme.ts
- projects/story-decorator/src/StoryDecorator.ts
- yarn.lock
- provide `language` as a context container on `sp-theme`
- leverage this context in `sp-number-field` and `sp-slider`
- add NumberFormatter and NumberParser caching to `sp-number-field`
- expand `updateComplete` processing for `sp-slider` to include `handles`
- tests!
One last to-do, but I wanted to allow others to get eyes on the implementation as desired:
- https://westbrook-lang-context--spectrum-web-components.netlify.app/components/theme
- https://westbrook-lang-context--spectrum-web-components.netlify.app/components/number-field
- https://westbrook-lang-context--spectrum-web-components.netlify.app/components/slider 
```
┌─────────────┬───────────────────┐
│   Benchmark │ slider:test-basic │
├─────────────┼───────────────────┤
│     Browser │ chrome-headless   │
│             │ …
```
> fix: manage "lang" via context provided by "sp-theme"

- .circleci/config.yml
- packages/textfield/src/textfield.css
- packages/textfield/stories/textarea.stories.ts
- correct visual delivery of `sp-textfield[multiline][grows]`
- add story to VRT to prevent future regressions
fixes #1568
Should work as expected!
VRTs
> fix: correct sp-textfield[multiline][grows] styling and add story for regression testing

- .circleci/config.yml
- packages/menu/menu-item.md
- packages/menu/src/MenuItem.ts
- packages/menu/src/menu-item.css
- packages/menu/stories/menu-item.stories.ts
Add the `slot="value"` interface for including content at the end of the Menu Item, e.g. keyboard shortcuts, etc.
Preview available at:
- https://westbrook-menu-item--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu-item--value-slot
- https://westbrook-menu-item--spectrum-web-components.netlify.app/components/menu-item
fixes #1515
Menu Items should be more customizable
VRTs
> fix: add "value" slot to sp-menu-item

- .circleci/config.yml
- packages/dialog/src/dialog.css
Ensure text color styling is actively applied to footer content in a dialog.
Fixes #1149
VRTs on https://westbrook-dialog-footer--spectrum-web-components.netlify.app/components/dialog-wrapper
> fix: match footer default color to content

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
Use wheel directionally rather than based on "distance" for more predictable input.
fixes #1531
Users should not be surprised.
Unit tests.
https://westbrook-numberfield-wheel-step--spectrum-web-components.netlify.app/components/number-field
> fix: normalize wheel input directionally for more predictable input

- packages/radio/src/Radio.ts
- packages/radio/src/RadioGroup.ts
- packages/radio/src/radio.css
- packages/radio/src/spectrum-config.js
- packages/radio/src/spectrum-radio.css
- packages/radio/test/radio-group.test.ts
- packages/radio/test/radio.test.ts
While still tracking https://bugs.chromium.org/p/chromium/issues/detail?id=1158144#c_ts1615261031, this update allows both Firefox and Safari to show the posinset and setsize data automatically through appropriately preparing the "radiogroup" root and associating it correctly with child "radio" elements. Once the linked bug in Chrome is addressed, these updated should automatically be available in that context.
Note in the Chrome issue that the grouping issue also effects the naming in certain contexts. If this doesn't get addressed directly by the issue, we'll start a new issue to track further fixes in the browser.
fixes #1278
Accessibility!
Manually, unit tests, etc.
> fix: correct a11y representation of a radio group

- .circleci/config.yml
- packages/color-area/src/ColorArea.ts
- packages/color-area/stories/color-area.stories.ts
- packages/color-area/test/color-area.test.ts
- packages/color-handle/src/ColorHandle.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/test/color-slider.test.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/color-wheel/test/color-wheel.test.ts
- update the regex for extracting and setting hue/saturation values on hsl/hsla/hsv/hsva colors
- update focus management so that arrow keys can be accepted immediately after drag interactions on the same color control
RegExp adoption of hue and saturation values should be robust.
- expanded unit tests
- updated VRTs
https://westbrook-hue-and-saturation--spectrum-web-components.netlify.app/storybook/index.html?path=/story/color-area--joint
> fix: expand support for maintaining hue and saturation across customization

- .circleci/config.yml
- package.json
- packages/menu/menu-item.md
- packages/menu/src/MenuItem.ts
- packages/menu/src/menu-item.css
- packages/picker/README.md
- packages/picker/src/Picker.ts
- packages/picker/src/picker.css
- packages/picker/src/spectrum-config.js
- packages/picker/src/spectrum-picker.css
- packages/picker/stories/picker.stories.ts
- packages/picker/test/benchmark/basic-test.ts
- packages/picker/test/picker.test.ts
- add icon passing from `<sp-menu-item>` to `<sp-picker>`
- add `icons-only` attribute to the `<sp-picker>` element which allows it to display only the icon from the selected element while consuming the content into the accessibility tree
fixes #1569
Spectrum coverage. Product team support. Feature completeness.
- unit test
- screenshots
https://westbrook-icon-picker--spectrum-web-components.netlify.app/storybook/index.html?path=/story/picker--icons
> fix: add icon present and icon-only support to Picker

- packages/action-button/README.md
Update and expand the `<sp-action-button>` documentation to align more closely with the Spectrum CSS documentation and more fully cover the surfaced element API.
fixes #962
fixed #1052 
Better documentation means less issues, and more diverse applications!
https://westbrook-action-button-docs--spectrum-web-components.netlify.app/components/action-button
> docs(action-button): expand sp-action-button documentation

- .circleci/config.yml
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay.test.ts
- packages/shared/src/reparent-children.ts
- allow detached elements (e.g. `document.createElement('div')`) to be used as "content" in an overlay
fixes #1540
Alternatives to rendering into a document fragment when you don't want the overlay content to exist in the DOM when closed should be available.
- unit test
- story
> fix: allow detached elements to be used as content for an overlay

- .circleci/config.yml
- .storybook/preview.js
- package.json
- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/stories/index.ts
- packages/action-menu/test/action-menu.test.ts
- packages/button/src/button-base.css
- packages/button/stories/button-overBackground.stories.ts
- packages/button/stories/button-primary.stories.ts
- packages/button/stories/button-secondary.stories.ts
- packages/button/stories/button-warning.stories.ts
- packages/card/stories/card.stories.ts
- packages/card/test/card.test.ts
- packages/tooltip/stories/tooltip.stories.ts
- packages/top-nav/stories/top-nav.stories.ts
- projects/story-decorator/decorator.ts
- projects/story-decorator/src/StoryDecorator.ts
- yarn.lock
- use @web/dev-server-storybook version with pre and post `lit@2.0` support
- ensure that icon elements are used throughout the storybook system
- add story source support
https://westbrook-storybook--spectrum-web-components.netlify.app/storybook/?path=/docs/accordion--default
> chore: use pre-release @web/dev-server-storybook for easier upgrade to lit@2.0

- packages/split-view/src/SplitView.ts
- packages/split-view/stories/split-view.stories.ts
- packages/split-view/test/split-view.test.ts
This change automatically updates the splitter position when `primarySize` property changes.
https://github.com/adobe/spectrum-web-components/issues/1610
According to docs `primarySize` can be set with the `primary-size` attribute. Right now that applies only to the initial state. This change allows (us) to use the split view component as some kind of sidebar which is opened/closed automatically based on some user action.
* Added test
* Added `primarySize` control to storybook (just to the first example)
* By using this change with patch-package in the thing I'm working on
> feat(split-view): redraw when primary-size change

- packages/radio/src/Radio.ts
- yarn.lock
Updating `axe-core` to support ongoing changes to `sp-menu` surfaces a new test failure in `sp-radio`, this updates Radio out of band so that it doesn't collide with the menu work.
#accessibility
It failed tests, suddenly, so we fixed it.
https://westbrook-axe--spectrum-web-components.netlify.app/storybook/index.html?path=/story/radio--group-example
> refactor: use latest axe-core and update sp-radio as instructed

- .circleci/config.yml
- packages/tabs/README.md
- packages/tabs/src/Tab.ts
- packages/tabs/src/Tabs.ts
- packages/tabs/src/tab.css
- packages/tabs/src/tabs.css
- packages/tabs/stories/tabs.stories.ts
- packages/tabs/tab.md
- packages/tabs/test/tabs.test.ts
- give tabs layout by default
- correct VRT for sized vertical tabs
- visually and functionally support `[disabled]` on `sp-tabs` and `sp-tab` elements
fixes #1612
fixes #1471 
Correctness. Ease of use.
VRT, manually.
https://westbrook-tabs--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tabs--vertical-sized
> fix(tabs): ensure tabs has layout

- .circleci/config.yml
- packages/overlay/README.md
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/stories/overlay.stories.ts
- projects/story-decorator/src/StoryDecorator.ts
- surface `theme` part for external customization of the CSS Custom Properties hung off of the `sp-theme` element in an `active-overlay` 
cc: @ejez 
fixes #1586
Easier to customize your content.
VRT
https://westbrook-theme--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--customized-click-content
> fix(overlay): allow external style access to "sp-theme" elemenets in overlays as a CSS part

- .github/workflows/test.yml
- .gitignore
- package.json
- packages/overlay/test/overlay-trigger.test.ts
- tasks/build-tachometer-comment.cjs
- tasks/test-changes.js
- test/benchmark/cli.ts
- yarn.lock
Use Github Actions to report Tachometer results for the packages that Lerna outlines as having changes from `origin/main` in to pull requests as a self updating comment.
The time this takes scales up with the number of packages changed, which also influences the benefit of making smaller changes.
fixes #137 (our oldest open issue!!)
Easier to tell that our changes are for the greater good of the library.
You'll see below. I'll also create a couple of other demo PRs with active branches and list them here for review as well.
Draft PR of the changes for `lit-next` including this code: https://github.com/adobe/spectrum-web-components/pull/1636
Draft PR of the changes for `westbrook/menu-selects` including this code: https://github.com/adobe/spectrum-web-components/pull/1637
> ci: comment tachometer results for changed files to PRs

- package.json
- packages/color-area/src/ColorArea.ts
- packages/color-area/stories/color-area.stories.ts
- packages/color-area/test/color-area.test.ts
Similar to the other colour elements, ColorArea was not correctly dispatching change events when using the keyboard. That is now fixed. Hooray. Also, altering other tests that were previously incorrect/not optimal.
fixes https://github.com/adobe/spectrum-web-components/issues/1469 by extension
Matching functionality with other colour elements and providing accessibility for users 
Manually and with tests
> [Color Area] Dispatch change event when using keyboard

- .circleci/config.yml
- test/visual/test.ts
- prevent VRT retry from placing a _second_ instance of the test
- update code order to prevent runtime side effects in the tests from happening too early
Test stability
It is tests.
https://60fc81e1bf892e67cbfba04d--spectrum-web-components.netlify.app/review/
> test: clean up before retesting VRTs

- .circleci/config.yml
- .vscode/settings.json
- packages/action-menu/README.md
- packages/action-menu/package.json
- packages/action-menu/sync/sp-action-menu.ts
- packages/action-menu/test/action-menu-sync.test.ts
- packages/action-menu/tsconfig.json
- packages/menu/src/menu-item.css
- packages/overlay/overlay-trigger.md
- packages/overlay/test/overlay-trigger-sync.test.ts
- packages/picker/package.json
- packages/picker/sync/index.ts
- packages/picker/test/picker-sync.test.ts
- packages/split-button/README.md
- packages/split-button/package.json
- packages/split-button/src/SplitButton.ts
- packages/split-button/sync/sp-split-button.ts
- packages/split-button/test/benchmark/basic-test.ts
- packages/split-button/test/split-button-sync.test.ts
- packages/split-button/test/split-button.test.ts
- packages/split-button/tsconfig.json
- correct delivery of `sp-split-button` variants
- surface sync imports for Action Menu and Split Button patterns
fixes #1642
fixes #1456
Correctness, options.
VRT
https://westbrook-split-button--spectrum-web-components.netlify.app/storybook/index.html?path=/story/split-button--more-cta
> fix(split-button): hide "selected" item from menu

- packages/bundle/elements.ts
- packages/bundle/package.json
- packages/bundle/src/index.ts
- packages/bundle/tsconfig.json
- packages/icon/src/Icon.ts
- packages/icon/test/benchmark/test-basic.ts
- packages/iconset/stories/icons-demo.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/picker/src/Picker.ts
- packages/tabs/src/Tabs.ts
- test/benchmark/cli.ts
`LitElement` returns a boolean from its `updateComplete` promise to outline that there is another render pending.. In a number of cases we've extended that promise to include extra work, but not returned the boolean. Without returning the `boolean` at the end of the `Promise` consumers won't know whether another update has been queued. This corrects that.
Simplify acquiring the completeness of the render.
> fix: allow "updateComplete" to resolve to a boolean like the LitElement default

- packages/action-button/src/ActionButton.ts
Correct the associated element name in ActionButton.ts.
> docs: use correct component name

- .circleci/config.yml
- packages/textfield/src/textfield.css
- packages/textfield/stories/textarea.stories.ts
This PR introduces some small changes to the styling of the Textarea's sizer element, changes that will force very long words to break and wrap in order to properly resize the Textarea.
fixes https://github.com/adobe/spectrum-web-components/issues/1664
This change is necessary to fix the functionality of the `grows` variant of the Textarea component. Whithout these changes, the Textarea does not resize as expected when containing long words.
- manual testing
- added a new story to render the problematic use case for future observability
> fix(textfield): break very long within the Textarea's sizer element

- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/benchmark/basic-test.ts
Only listen for overlay events when an overlay is actually open.
fixes #1512
Allow for inclusion of the code before the `<body>` tag. Make the code more performant to boot up.
- tests all pass
> fix: update when events are added to manage overlays

- .circleci/config.yml
- packages/slider/README.md
- packages/slider/src/Slider.ts
- packages/slider/src/slider.css
- packages/slider/stories/slider.stories.ts
Allow control over the labelling that is surfaced by the `<sp-slider>` element while not requiring developers to leverage accessibility focused features to do so.
fixes #1159
Be accessible _and_ flexible.
VRTs
> feat(slider): support customizing visible label delivery 

- packages/color-area/src/ColorArea.ts
- packages/color-area/test/color-area.test.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/test/color-slider.test.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/color-wheel/test/color-wheel.test.ts
- ensure the `<sp-color-area>` and `<sp-color-sldier>` have a single tab stop and the the tab order does not get trapped within these elements
fixes #1692 
Color application interfaces should be keyboard accessible.
- unit tests
- manual test
> fix: key interaction handling no longer prevents "tab" presses

- packages/sidenav/README.md
- packages/sidenav/src/Sidenav.ts
- packages/sidenav/src/SidenavHeading.ts
- packages/sidenav/src/SidenavItem.ts
- packages/sidenav/src/sidenav-item.css
- packages/sidenav/stories/sidenav.stories.ts
- packages/sidenav/test/sidenav-item.test.ts
Update `<sp-sidenav>` API to accept `label` content as HTML via the default `<slot>` element.
fixes #1485
Easier customization of content.
- needs VRTs
- needs unit tests
> fix: update slotting in "sp-sidenav-item" to allow for labelling in HTML

- packages/action-group/test/action-group.test.ts
- packages/menu/src/Menu.ts
- packages/menu/src/MenuItem.ts
- packages/menu/src/menu-item.css
- packages/menu/src/spectrum-config.js
- packages/menu/src/spectrum-menu-item.css
- packages/menu/stories/menu-item.stories.ts
- packages/menu/test/menu-item.test.ts
- packages/picker/test/benchmark/basic-test.ts
`<sp-menu-item>` is built with _many_ but not _all_ of the pieces of `<sp-action-button>`. The parts that it does't use are the least performant. Re-structure the `MenuItem` class with the used parts and increase its overall performance by removing the parts that are not used. 
fixes #815 🙀 
I feel the need, the need for speed. 
- new tests
- VRTs
- the below perf tests.
> perf: reorganize inheritance and composition in Menu Items

- packages/card/README.md
- packages/card/src/Card.ts
- packages/card/src/spectrum-card.css
- packages/card/src/spectrum-config.js
- packages/card/stories/card.stories.ts
- packages/card/test/card.test.ts
- packages/dialog/README.md
- packages/dialog/src/Dialog.ts
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/src/spectrum-config.js
- packages/dialog/src/spectrum-dialog.css
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/stories/dialog.stories.ts
- packages/tray/stories/tray.stories.ts
Normalize sizing attributes across packages not currently leveraging t-shirt sizing to make required breaking changes pre-1.0.
- `<sp-card small>` becomes `<sp-card size="s">`
- `<sp-dialog size="small|medium|large">` becomes `<sp-dialog size="s|m|l">`
- `<sp-dialog-wrapper size="small|medium|large">` becomes `<sp-dialog-wrapper size="s|m|l">`
https://normalize-size--spectrum-web-components.netlify.app/components/card
https://normalize-size--spectrum-web-components.netlify.app/components/dialog
refs #865 
Introduce expected breaking changes in our pre-1.0 environment.
VRTs
> Normalize size attribute usage pre-1.0

- .circleci/config.yml
- packages/field-label/src/FieldLabel.ts
- packages/number-field/src/NumberField.ts
- packages/slider/README.md
- packages/slider/package.json
- packages/slider/src/HandleController.ts
- packages/slider/src/Slider.ts
- packages/slider/src/SliderHandle.ts
- packages/slider/src/slider.css
- packages/slider/stories/slider.stories.ts
- packages/slider/sync/sp-slider.ts
- packages/slider/test/slider-editable-sync.test.ts
- packages/slider/test/slider-editable.test.ts
- packages/slider/test/slider.test.ts
- packages/slider/tsconfig.json
Add editable slider delivery binding an `<sp-number-field>` into the UI of the `<sp-slider editable>` element through dynamic importing the element registration.
- also adds a synchronous entry point into the functionality as desired.
fixes #1572 
Spectrum compliance and application flexibility.
- VRT
- unit tests.
> fix: add "editable" option to "sp-slider"

- packages/action-bar/src/ActionBar.ts
fixes #1417 
propogates open attribute from sp-action-bar to the child sp-popover
#1417
the sp-popover was always rendered as open which made it visible to the accessibility tree as it was being rendered with visibility:visible which will expose content in the tree even if a child of visibility:hidden
Running in the docs and ensuring that the content is only rendered in the a11y tree when the action-bar is open
> Propogate open to child sp-popover 

- .github/workflows/test.yml
- tasks/build-preview-urls-comment.cjs
- tasks/build-tachometer-comment.cjs
- tasks/test-changes.js
Post simpler comments into GH when there are no changes to packges.
- Why post at all? Having the comment placeholder set means that _if_ there are package changes later on the the development lifecycle that it is still as close to the first one in the PR as possible.
Things should be _less_.
In this PR!
> ci: no VRT urls when packages have not changed

- packages/overlay/src/overlay-stack.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay.test.ts
When in an overlay of type `modal` allow `contextmenu` events on non-overlaid content to both close the overlay _AND_ interact with the content that had been previously made "inert". This will allow for synthetic context menus to trap the tab order while still affording the user to open a context menu on another piece of content.
fixes #1559 
Better support for synthetic context menu overlays.
1. Visit https://overlay-context-menu--spectrum-web-components.netlify.app/storybook/index.html?path=/story/overlay--virtual-element
2. Use a right click to open a "context menu" in the Story frame
3. Right click somewhere else on the Story frame to close to first "context menu" and open a new one.
-   [x] I …
> fix: close modal overlays with contextmenu events and pass those to the underlying page

- packages/color-area/src/ColorArea.ts
- packages/color-area/stories/color-area.stories.ts
- packages/color-area/test/color-area.test.ts
- packages/color-handle/src/ColorHandle.ts
- packages/color-handle/src/color-handle.css
- packages/color-slider/src/ColorSlider.ts
- packages/color-slider/test/color-slider.test.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/color-wheel/test/color-wheel.test.ts
- prevent `:focus` delivery on `sp-color-handle` both at the Handle level in CSS and in the usage level by removing `tabindex=-1`.
- ensure `Arrow*` keypresses activate `focused` delivery
- remove `modifier` support for `Meta` key as it prevent `keyup` events
fixes #1701
fixes #1698
- correct visual delivery of the current focus state
- prevent functional incongruities when keydown states can't be ended
1. Go to https://color-handle--spectrum-web-components.netlify.app/storybook/?path=/story/color-area--default
2. Click the label for the `Theme` picker along the bottom
3. Press `Shift + Tab`
4. Ensure that the handle has enlarged.
5. Press any of the `Arrow*` keys
6. Ensure that the handle/value has moved/been updated
7. Press `Shift + Tab`
8. Ensure that after …
> Color controls focus management updates.

- packages/color-area/test/color-area.test.ts
- packages/slider/src/Slider.ts
- packages/slider/test/slider.test.ts
- replace `elementUpdate` with `nextFrame`, which seems more reliable, in intermittently failing tests
- fix visibility of `ariaValueText` in Slider to be compatible with its type signature
- https://github.com/adobe/spectrum-web-components/issues/1772
While developing https://github.com/adobe/spectrum-web-components/pull/1771, I noticed that these tests would intermittently fail. The failures were rare and non-deterministic, which makes it difficult to know whether or not your work created a regression.
Experimentation (by running `yarn test` repeatedly) suggests that this PR will more-reliably `await` the state changes that the tests are confirming.
-   [ ] …
> fix: flappy Slider/Color Area tests

- .circleci/config.yml
- package.json
- packages/menu/src/Menu.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
Reduce the work done when focusing a Menu Item so that iOS + Voice Over doesn't thing you've left the interface by the time a Menu Item has fully received focus.
- refrain from cycles focus calls
- focus first selected, instead of last, upon Menu entry
- show `:focus-visible` styling on `Tab` key entry
- while leveraging `activedescendent` pattern surface only one tab stop per Menu root
- manage `aria-activedescendent` on Menu root
- fixes #1766
- fixes #1767 
Accessibly surfacing this functionality in Safari for iOS with Voice Over.
1. Go to https://picker-a11y--spectrum-web-components.netlify.app/components/menu
2. Use the `Tab` key until you should focus a Menu
3. See that the first item (or first selected item) is visibly focused
1. Go to …
> fix: simplify focus application in Menu

- .circleci/config.yml
- packages/shared/src/focusable.ts
- packages/slider/src/Slider.ts
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider-editable-sync.test.ts
- packages/slider/test/slider-editable.test.ts
When `disabled` and `editable` a Slider element attempts to blur a grand child element that has yet to be rendered causing a crash. Number Fields in `sp-slider[editable]` elements are the first to be loaded lazily but will likely not be the last, this adds affordances for this. Additional, testing and demos are added as well.
- #1775 
Elements shouldn't crash.
- unit tests
- VRTs
1. Go to https://slider-editable-disabled--spectrum-web-components.netlify.app/storybook/?path=/story/slider--editable-disabled
2. Ensure there are no errors in the console.
-   [ ] If my …
> fix: ensure lazily loaded focusElements do not crash

- packages/picker/src/Picker.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
Safari skips `button` elements in the tab order, so we need to provide a synthetic target with a tabindex to receive and then throw focus onto the Picker's button.
Resolves https://github.com/adobe/spectrum-web-components/issues/1770
Fixes a bug.
`yarn test` and manual testing in Chrome & Safari.
-   [X ] Bug fix (non-breaking change which fixes an issue)
-   [ X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ X] My code follows the code style of this project.
-   [ X] If my …
> fix: give Picker a focus helper to enable tab navigation in Safari

- packages/table/.npmignore
- packages/table/README.md
- packages/table/package.json
- packages/table/sp-cell.ts
- packages/table/sp-head-cell.ts
- packages/table/sp-row.ts
- packages/table/sp-table.ts
- packages/table/src/Cell.ts
- packages/table/src/HeadCell.ts
- packages/table/src/Row.ts
- packages/table/src/Table.ts
- packages/table/src/index.ts
- packages/table/src/spectrum-config.js
- packages/table/src/spectrum-table.css
- packages/table/src/table.css
- packages/table/stories/table.stories.ts
- packages/table/test/benchmark/basic-test.ts
- packages/table/test/table.test.ts
- packages/table/tsconfig.json
This is a basic and really naive implementation of the [table](https://opensource.adobe.com/spectrum-css/table.html) pattern.
I think that it could be better if someone with more experience actually implemented the table pattern given how table components are complicated. But even if someone else was to implement it, this PR could still be used as an inspiration (maybe).
Here is a list of things that are missing (and probably many more I missed):
* Only div style tables, no `<table>` tables
* No multi-select, column dividers, and other variants
* No tests
* Position of icons in header cells is off
* I'm not sure if I used the slots correctly (I don't think I did)
* I didn't check anything related to accessibility
* I'm not sure about the names of the elements
* No documentation
* …
> [RFC] feat(table): add table pattern

- .circleci/config.yml
- packages/number-field/README.md
- packages/number-field/src/NumberField.ts
- packages/number-field/stories/number-field.stories.ts
- packages/number-field/test/inputs.test.ts
- packages/number-field/test/number-field.test.ts
- packages/slider/README.md
- packages/slider/src/Slider.ts
- packages/slider/src/SliderHandle.ts
- packages/slider/stories/slider.stories.ts
- add support for non-native `unit` values in `formatOptions` object supplied to Number Field and Slider elements
- test it
- demo it
- document it
- fixes #1715 
We work with a lot of graphics software that needs extended unit support.
1. Visit https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/slider--px, https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/slider--two-handles-pt&args=variant:range;tickStep:10;labelVisibility:!undefined, or https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/slider--three-handles-pc
2. Move around the handles
3. Ensure that the `pc`, `pt`, or `px` string is included appropriately in the value labeling
1. Visit …
> Support "px" and other non-native units in Number Field and Slider

- packages/overlay/src/overlay-stack.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay.test.ts
Walk down shadow roots to ensure that `contextmenu` events passed to the underlying page actually hit the element at the point where the pointer interacted with the page regardless of what shadow tree it might exist in.
Thanks @OpportunityLiu for pointing this out!
- fixes #1790
Full power `contextmenu` passing.
1. Go to https://contextmenu-piercing--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--virtual-element&args=placement:right-end;offset:0;colorStop:light
2. Make a "context" click (right button) on the left half of the page.
3. Ensure that the overlay says "Menu Source: Start"
4. **While still open**, make a "context" click on the right half of the page.
5. Ensure that the overlay says "Menu Source: End"
-   [x] New feature (non-breaking …
> fix: allow contextmenu event passing to pierce shadow roots

- packages/slider/slider-handle.md
Document the limitation discovered in https://github.com/adobe/spectrum-web-components/issues/1781
https://github.com/adobe/spectrum-web-components/issues/1781
It's not currently clear that `<sp-slider-handle>` must be added to `<sp-slider>` in groups of two or more.
1. visit https://add-single-slider-handle-warning--spectrum-web-components.netlify.app/components/slider-handle
-   [X] I have signed the [Adobe Open Source …
> chore: warn about slotting in a single sp-slider-handle

- packages/color-area/README.md
- packages/color-area/src/ColorArea.ts
- packages/color-area/test/color-area.test.ts
This provides distinct aria labels for the X and Y inputs so that accessibility tools can expose them as `${saturation}, saturation` and `${luminosity}, luminosity` instead of `${saturation_or_luminosity}, saturation and luminosity`.
To ensure backwards-compatibility, so that this can be shipped as a non-breaking change, if the developer specifies a `label` attribute, it will override the `label-x` and `label-y` attributes, maintaining previous behavior.
resolves https://github.com/adobe/spectrum-web-components/issues/1768
This makes the Color Area component accessible to users who cannot use its visual representation on a 2D graphic.
1. go to https://separate-color-area-labels--spectrum-web-components.netlify.app/components/color-area
2. activate VoiceOver
3. ensure that you can …
> feat(color-area): separate X and Y aria labels to improve accessibility

- packages/button/src/ButtonBase.ts
- packages/button/test/button.test.ts
Listen for `NumpadEnter` keypresses, too.
- fixes #1799 
Full keyboard support!
1. Go https://numpad-enter--spectrum-web-components.netlify.app/components/button
2. Keyboard focus the "Handling events" button that says "Click me"
3. Press the `Enter` key
4. See a click registered in the toast
5. Press the `NumpadEnter` key (`fn + Enter` on a Mac keyboard)
6. See a click registered in the toast …
> fix: ensure "click" on "NumpadEnter" key press

- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay.test.ts
Close the hole that exists between adding and removing overlay events due to events being added at the beginning of an asynchronous process and them being removed at the end of another which could prevent users from being able to close overlays after interactions of a specific timing.
Overlays should be closable.
-   See unit test, it's difficult to recreate the context that causes this without a fairly complex user interface …
> fix: correct add/remove timing of overlay events

- packages/action-group/README.md
Include documentation around labelling Action Group elements.
- fixes #1419
Content should be accessible!
1. Go to https://action-group-label--spectrum-web-components.netlify.app/components/action-group
2. Consumer new label delivery documentation
1. Go to  https://action-group-label--spectrum-web-components.netlify.app/components/action-group
2. Visit the two `selects` demos with a screen reader
3. Experience the label `Single Selection Demo Group` and `Multiple Selection Demo Group` being associated to the two groups.
-   [x] My code …
> docs: extend accessible content guidance

- package.json
- packages/checkbox/stories/checkbox-sizes.stories.ts
- packages/color-area/stories/color-area.stories.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/test/dialog-wrapper.test.ts
- packages/picker/stories/picker-sizes.stories.ts
- packages/picker/stories/picker.stories.ts
- packages/sidenav/stories/sidenav.stories.ts
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider-editable-sync.test.ts
- packages/split-button/stories/split-button.stories.ts
- yarn.lock
Less `console.log()` and more built in features of Storybook makes testing simpler.
`console.log()` leaks into shared contexts where the CSF exports are leveraged, like tests.
1. Go to https://storybook--spectrum-web-components.netlify.app/storybook/index.html?path=/story/checkbox-sizes--s
2. Toggle the checkbox
3. See `change` and `click` reports in the "Actions" tab
1. Go to https://storybook--spectrum-web-components.netlify.app/storybook/index.html?path=/story/color-area--default
2. Drag the color handle around
3. See `input` repots in the "Actions" tab
- Etc. …
> docs: use latest Storybook Prebuilt and leverage the actions addon

- documentation/src/components/side-nav-search.ts
- packages/search/src/Search.ts
- packages/search/src/search.css
Ensure that attributes are applied correctly to deliver the "Search" button in a mobile virtual keyboard.
- add `type="search"`
- apply `action` attribute to the `<form>` even when unavailable
- fixes #1752 
Easier use of the element in mobile.
1. Go to https://type-search--spectrum-web-components.netlify.app/ in mobile
2. Open the nav drawer
3. Type into the search field `Test`
4. See a modified "Go"/"Submit" button
5. Press it
6. See that the focus has been moved into the search results on "submit"
1. Go to https://type-search--spectrum-web-components.netlify.app/components/search
2. Tap into one of the search fields
3. See that the virtual keyboard surfaces a "Search" button
- …
> fix: use type="search" for nicer virtual keyboards

- packages/slider/sp-slider.ts
- packages/slider/test/slider-handle-upgrade.test.ts
`<sp-slider>` depends on `<sp-slider-handle>`. Since that dependency is only implicit, it's possible to create a document that upgrades `<sp-slider-handle>` _after_ `<sp-slider>`, breaking the Slider's functionality.
This change specifies the dependency and ensures that `<sp-slider-handle>`s will exist before `<sp-slider>` tries to use them.
Fixes https://github.com/adobe/spectrum-web-components/issues/1803
Sliders can currently throw and crash if the document upgrades them out-of-order.
1. Added `slider-handle-upgrade.test.ts` (run with `yarn test`)
2. Manually verified that https://fix-slider-handle-upgrade-order--spectrum-web-components.netlify.app/components/slider-handle continues to work as expected
-   [ ] New feature …
> fix(slider): make implicit dependency on sp-slider-handle explicit

- .circleci/config.yml
- packages/textfield/src/textfield.css
- packages/textfield/stories/textarea.stories.ts
- packages/textfield/test/textfield.test.ts
Allow users to specify `<sp-textfield style="resize: none|both|horizontal|vertical;">`.
Resolves https://github.com/adobe/spectrum-web-components/issues/1700
Otherwise, all multiline textfields are resizable.
1. go to https://support-textfield-resize-none--spectrum-web-components.netlify.app/storybook/?path=/story/textarea--default
2. ensure that your browser does show resize controls
3. go to https://support-textfield-resize-none--spectrum-web-components.netlify.app/storybook/?path=/story/textarea--resize-controls
4. ensure that your browser doesn't show resize controls for the first textfield
5. `yarn test`
-   [ ] Breaking change (fix or feature that would cause …
> fix(textfield): respect resize styling

- packages/action-menu/package.json
- packages/icons-workflow/package.json
Associate `action-menu` and `icons-workflow` with upstream Spectrum CSS dependencies so that they can be versioned along with the reset of the library in response to updates there.
I was about to push the latest release and saw that these two packages were versioning differently that the others. `action-menu` is bumped by `picker`, but internal to Lerna that association only counts as a "fix" and not a "feature" and the same with `icons-workflow` which is bumped by `icon`.
Now, all of the packages will be prepped for a "feature" bump, other than `bundle`, a change to which changes everything so it's less important that it receive a specific bump.
> feat: track the associated Spectrum CSS package

- package.json
- packages/icons-ui/README.md
- packages/icons-workflow/README.md
- packages/iconset/stories/icons-demo.ts
- projects/documentation/package.json
- projects/documentation/scripts/component-template-parts.js
- projects/documentation/scripts/copy-component-docs.js
- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/side-nav-search.ts
- projects/documentation/src/components/styles.css
- projects/documentation/src/utils/posthtml-spectrum-docs-markdown.js
- yarn.lock
- correct API table DOM
- add some missed API tables
- update "Usage" for `icons-ui` and `icons-workflow`
- add Search UI for both
- include `IconBase` API table for both
- fixes #1421
Make it easier to consume the icon packages and their various offerings.
1. Go to https://docs-icons--spectrum-web-components.netlify.app/components/icons-workflow/#find-an-icon
2. Search for `flag`
3. Click the `<sp-icon-flag-exclude>` icon
4. See the "copied to clipboard" message
5. Paste `import '@spectrum-web-components/icons-workflow/icons/sp-icon-flag-exclude.js';` somewhere.
1. Go to https://docs-icons--spectrum-web-components.netlify.app/components/icons-ui/#find-an-icon
2. Search for `dash`
3. Click the `<sp-icon-dash400>` icon
4. See the "copied to …
> docs: add icon search UIs to documentation site

- packages/overlay/src/overlay-stack.ts
- projects/documentation/src/components/side-nav.css
- Prevent `touch-action` on content hidden by a modal overlay.
- Prevent `touch-action` on the `Underlay` below the mobile navigation in the docs.
The modals don't move, why should anything else?
1. Go to https://modal-touch--spectrum-web-components.netlify.app/index.html on a mobile device
2. Open one of the theme pickers
3. Attempt to scroll the page behind while the option menu is open
4. Profit.
1. Go to https://modal-touch--spectrum-web-components.netlify.app/index.html on a mobile device
2. Open the side navigation
3. Attempt to scroll the page behind the Underlay
4. Profit.
-   [x] My code …
> fix: prevent touch scolling on non-modal content

- package.json
- projects/documentation/content/guides/migration-guide.11tydata.cjs
- projects/documentation/content/guides/migration-guide.md
- projects/documentation/package.json
Add migration instructions for the pending `lit@2.0` release!
Docs are great.
1. Go to https://lit-migration--spectrum-web-components.netlify.app/guides/migration-guide/
2. Read the page. …
> docs: add migration instructions to the first lit@2.0 releases

- packages/action-menu/src/ActionMenu.ts
- packages/action-menu/test/action-menu-sync.test.ts
- packages/action-menu/test/action-menu.test.ts
- packages/base/src/Base.ts
- packages/color-area/src/ColorArea.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/menu/src/Menu.ts
- packages/overlay/package.json
- packages/picker/src/Picker.ts
- packages/split-button/src/SplitButton.ts
- packages/split-button/test/split-button-sync.test.ts
- packages/split-button/test/split-button.test.ts
- yarn.lock
- correct extension from Picker so that both `<sp-action-menu>` and `<sp-split-button>` can now toggle
- abstract "hasVisibleFocusInTree" functionality to base with extra protection
- update `focusElement` on `sp-split-button[left]` elements
- fixes #1894
Was broken
1. Go to https://splitter-toggle--spectrum-web-components.netlify.app/components/action-menu/#sizes
2. Toggle the menu open/closed a few times
1. Go to https://splitter-toggle--spectrum-web-components.netlify.app/components/split-button/#sizes
2. Toggle the menu open/closed a few times
-   [x] My code follows the code style of this …
> fix: abstract "hasVisibleFocusInTree" functionality and return trigger focus after close

- package.json
- packages/menu/src/MenuItem.ts
- packages/picker/src/Picker.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
- web-test-runner.config.js
Move `selectedItemContent` caching down into `sp-menu-item` where we can more accurately react to mutations. Leverage `sp-menu-item-added-or-updated` and `sp-menu-item-removed` events to allow for reactivity in `sp-picker`:
- accepts new selected item content
- accepts new selected item content when open
- unsets value when children removed
- fixes #1893
Lifecycle flexibility of the `sp-picker` element.
1. Go to https://selected-item-cache--spectrum-web-components.netlify.app/components/picker/#value
2. Select the `[value="item-3"]` element
3. See that its text content is applied to the Picker button
4. Use devTools to update the text content of the `[value="item-3"]` element
5. See that the new text is applied to the Picker button
6. Remove the `[value="item-3"]` …
> fix(picker): allow menu items to be added, updated, and removed

- packages/tabs/src/Tab.ts
- packages/tabs/src/Tabs.ts
- packages/tabs/test/tabs.test.ts
Allow `sp-tab` to accept DOM elements when its `label` is slotted into it.
Allow `sp-tab` to notify `sp-tabs` when it has has its `label` updated so it can update the Selection Indicator
- fixes #1867
- fixes #1920
Allow usage without edge case issues.
1. Go to https://tabs-updates--spectrum-web-components.netlify.app/components/tabs/#sizes
2. Take a reference of the selected `Tab 1``sp-tab` in the "Medium" size demo
3. Update its `el.textContent` to be much longer or shoter
4. See that the Selection Indicator is updated
1. Go to https://tabs-updates--spectrum-web-components.netlify.app/components/tabs/#sizes
2. Take a reference of the `Tab 13``sp-tab` in the "Medium" size demo
3. Update its `el.innerHTML` to be `<span>Some other thing</span>` …
> Tabs updates

- packages/slider/src/HandleController.ts
- packages/slider/src/Slider.ts
- packages/slider/src/slider.css
- packages/slider/test/slider-editable-sync.test.ts
- packages/slider/test/slider-editable.test.ts
- packages/slider/test/slider.test.ts
- remeasure bounding box when the screen orientation changes
- refactor `pointer*` listeners to listed directly of the `#track` element
- reduce scope creation by not needing to bind models into the template
- maintain a single pointer event path rather than one for handles and one for the track
- tweak CSS and pointer capture to maintain touch in more cases on mobile
- fixes #1881
Things should work great in mobile.
1. On iOS Safari or a simulator
2. Go to https://slider-updates--spectrum-web-components.netlify.app/components/slider#tick
3. Manually update the slider value. Drag the handle, touch the track, etc.
4. Ensure the value updates as expected
5. Change the orientation of the iOS device
6. Manually update the slider value. Drag the handle, touch the track, …
> Slider updates

- packages/number-field/src/NumberField.ts
- packages/number-field/test/number-field.test.ts
Prevent interaction with stepper buttons when disabled
- fixes #1928
Visitors shouldn't be allowed to interact with the number field in this state.
1. Go to https://numberfield-disabled--spectrum-web-components.netlify.app/storybook/index.html?path=/story/number-field--disabled
2. Attempt to interact with the up or down arrow buttons
3. You can't.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRI …
> fix(number-field): prevent interaction with stepper buttons when disabled

- packages/dropzone/README.md
This clarifies the use of `tabindex` while not commenting on the ability to use an `<sp-dropzone>` element without text, as this process isn't fully documented by Spectrum CSS.
- fixes #1275
More accessible default examples of our elements.
1. Go to https://a11y-dropzone--spectrum-web-components.netlify.app/components/dropzone/
2. See that the Dropzone elements themselves are no longer in the tab order
1. Go to https://a11y-dropzone--spectrum-web-components.netlify.app/components/dropzone/#accessibility
2. And learn about using `tabindex` responsibly with an `<sp-dropdown>` element. …
> docs(dropzone): clarify usage of "tabindex" and remove it from available examples

- packages/action-button/src/ActionButton.ts
- packages/action-button/test/action-button.test.ts
- yarn.lock
Apply `aria-pressed="true"` to all Action Buttons that `role="button"`. Avoid adding this attribute when other roles are applied as they are not part of the expected accessibility tree in that case.
- fixes #756
More accessibility by default.
1. Go to https://action-button-selected--spectrum-web-components.netlify.app/components/action-button/#sizes
2. Add the `selected` attribute to one of the Action Buttons there
3. See that the `aria-pressed=true` attribute is also applied.
1. Go to https://action-button-selected--spectrum-web-components.netlify.app/components/action-group/#single
2. See that the Action Button there with the `selected` attribute does not have `aria-pressed=true`
1. Go to …
> fix(action-button): all "selected" Action Buttons should be "aria-pressed=true"

- package.json
- packages/popover/src/Popover.ts
Expand documentation in the API table.
- fixes #1277 
Packages should be understandable.
1. Go to https://a11y-popover--spectrum-web-components.netlify.app/components/popover/api/
2. Read entry on `dialog` and `open`
3. Be better prepared to consume this element
- …
> docs(popover): expand dialog/open documentation

- packages/card/test/card.test.ts
- packages/menu/test/menu-item.test.ts
- packages/menu/test/menu-selects.test.ts
- packages/number-field/test/helpers.ts
- packages/number-field/test/number-field.test.ts
- packages/overlay/test/overlay-trigger-hover-click.test.ts
- packages/overlay/test/overlay.test.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
- packages/radio/test/radio-group.test.ts
- packages/radio/test/radio.test.ts
- packages/sidenav/test/sidenav.test.ts
- packages/slider/test/slider.test.ts
- packages/textfield/test/textfield.test.ts
- test/plugins/browser.ts
- test/plugins/send-mouse-plugin.ts
Create a `sendMouse` helper method that enacts the command while also submitting a clean up call to run after the test.
- apply this helper to all `send-mouse` plugin usage locations
- fixes #1784 
Less likely to have surprising test errors based on mouse context and location.
1. Tests ran in CI
2. Feel free to try them locally. …
> Update send mouse usage

- packages/color-area/README.md
- packages/color-area/src/ColorArea.ts
- packages/color-area/test/color-area.test.ts
BREAKING CHANGE: set labels via the label-x/label-y attributes or labelX/labelY properties
Remove deprecated `label` attribute/property in favor of the `label-x`/`labelX` and `label-y`/labelY` attribute/properties.
- #1802
Clean API.
1. Go to https://color-area-label--spectrum-web-components.netlify.app/components/color-area/
2. Add a `label` attribute to an `sp-color-area` element
3. See that this value isn't propagated to the internal `<input>` elements' `aria-label` attributes. …
> fix(color-area): remove deprecated "label" attribute/property

- test/testing-helpers-a11y.ts
These tests were flaking, and need a little extra time being the snapshot can't be taken until after the async update cycle and the async slotchange event timing is completed. The browser also needs a little time to register the new accessibility tree, so this seems like the right call...
Tests were flaky.
1. Go to https://app.circleci.com/pipelines/github/adobe/spectrum-web-components?branch=help-text-timing
2. See that all of the flaky test failures agains this branch have been _other_ flaky tests...
-   [ …
> test: add time before querying accessibility tree

- .circleci/config.yml
- package.json
- packages/tooltip/src/Tooltip.ts
- packages/tooltip/src/tooltip.css
- packages/tooltip/stories/tooltip.stories.ts
- packages/tooltip/test/tooltip.test.ts
- patches/@popperjs+core+2.10.2.patch
- apply a `slot` attribute whenever `self-managed` to ensure it is hidden _until_ overlaid
- support adding proxy to where `sp-tooltip` was for more predicable styling
- patch-package `@popperjs/core` to support sub-pixel fix in https://github.com/popperjs/popper-core/pull/1418
- add `tooltip-proxy` element to support knowing when an `sp-tooptip` trigger has been removed from the DOM
- reorganize code path to leverage a single proxy element
- add unit test for cleanup
- add storybook rules to confirm proxy placement in DOM
Nicer to use tooltips
1. Go to https://tooltip-delay--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--self-managed&args=placement:top;offset:6;delayed:false
2. Without interacting with the Tooltip story, navigate to a second …
> Support `self-managed` Tooltip elements with `delay`

- packages/action-group/stories/action-group-tooltip.stories.ts
- packages/action-group/stories/action-group.stories.ts
- packages/action-group/test/action-group.test.ts
- packages/overlay/overlay-trigger.md
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay-lifecycle.test.ts
- packages/overlay/test/overlay-trigger-hover-click.test.ts
- packages/tooltip/README.md
- packages/tooltip/src/Tooltip.ts
- packages/tooltip/stories/tooltip.stories.ts
- packages/tooltip/test/benchmark/test-basic.ts
- packages/tooltip/test/tooltip.test.ts
- projects/vrt-compare/src/OnionSkinner.ts
BREAKING CHANGE: Self management will now be the default when using an "<sp-tooltip>".
Update `<sp-tooltip>` to self manage by default and allow the `managed` attribute to turn off this management.
- fixes #1885
Simpler API, better defaults.
1. Tests pass.
1. Go to https://tooltip-managed--spectrum-web-components.netlify.app/storybook/?path=/story/tooltip--self-managed&args=placement:top;offset:6;delayed:true
2. See the tooltip open in a delayed manner
3. Review some tooltips (all the other in the Storybook) with `managed`.
-   [x] My code follows the code style of …
> fix(tooltip): exchange "self-managed" attribute for "managed" with opposite effect

- packages/accordion/src/AccordionItem.ts
- packages/color-area/src/ColorArea.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/number-field/src/NumberField.ts
- packages/radio/src/Radio.ts
- packages/radio/src/RadioGroup.ts
- packages/search/src/Search.ts
- packages/slider/src/SliderHandle.ts
- packages/tabs/src/Tab.ts
- packages/tabs/src/Tabs.ts
- packages/textfield/src/Textfield.ts
- packages/toast/src/Toast.ts
- packages/tray/src/Tray.ts
- projects/documentation/scripts/component-template-parts.js
- projects/documentation/scripts/copy-component-docs.js
Ensure that all events have both a description and type in our docs site.
- fixes #1176
Easier to consume docs.
1. Go to https://events-docs--spectrum-web-components.netlify.app/components/search/api/#events
2. See that the docs have a nice description and type for each event
3. See that other elements have the similar niceties...
vs …
> docs: include description and type for all event listing in the docs

- .circleci/config.yml
- packages/accordion/src/AccordionItem.ts
- packages/color-area/src/ColorArea.ts
- packages/color-slider/src/ColorSlider.ts
- packages/color-wheel/src/ColorWheel.ts
- packages/number-field/src/NumberField.ts
- packages/radio/src/Radio.ts
- packages/radio/src/RadioGroup.ts
- packages/search/src/Search.ts
- packages/slider/src/SliderHandle.ts
- packages/slider/test/slider.test.ts
- packages/tabs/src/Tab.ts
- packages/tabs/src/Tabs.ts
- packages/textfield/src/Textfield.ts
- packages/toast/src/Toast.ts
- packages/tray/src/Tray.ts
- projects/documentation/scripts/component-template-parts.js
- projects/documentation/scripts/copy-component-docs.js
BREAKING CHANGE: When not supplied value will now be set to halfway between min and max.
Update default `value` when no applied by the application. Update tests to match.
- fixes #1788
Be more like native elements.
1. With unit tests...
-   [x] …
> fix(slider): update "value" default to match browser native range input

- package.json
- packages/overlay/src/ActiveOverlay.ts
- packages/tabs/src/Tabs.ts
- packages/theme/src/Theme.ts
- packages/top-nav/src/TopNav.ts
- projects/story-decorator/src/types.ts
- yarn.lock
- use "natively" provided `doncument.fonts.ready` and `document.fonts.addEventListener` types
- make `ShadowRoot.adoptedStyleSheets` a local type
supersedes #1984
Cleaner types
1. `yarn build:ts:clean`
1. manually inspected `.d.ts` files to verify that the newly defined types are not exported.
- …
> [ALT] Stop emitting local types into the global scope

- package.json
- packages/iconset/stories/icons-demo.ts
- projects/documentation/scripts/component-template-parts.js
- projects/documentation/src/components.ts
- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/styles.css
Allow all `tr`s to be anchors in the API docs section.
Allow all `tr` to copy content into a users clipboard related to the API that it is outlining.
Is baking both of these into the same action "too much"?
Make the docs easier to share and communicate with.
1. Go [here](https://link-api-docs--spectrum-web-components.netlify.app/components/accordion/api/)
2. Click a row in the table
3. See that the URL updates to that anchor
4. Paste the content that is now in your clipboard.
-   [x] If my change required a …
> docs: support anchor linking and copying individual API table names

- INVENTORY.md
- package.json
- tasks/build-component-inventory.js
- yarn.lock
This adds a left column to the component inventory that lists all of the spectrum design tokens from `@adobe/spectrum-tokens`.
A more complete understanding of upstream projects & dependencies.
- Check out [the generated table](https://github.com/adobe/spectrum-web-components/blob/add-spectrum-tokens-to-inventory/INVENTORY.md)
-   [X] My code follows the code style of …
> docs: add spectrum design tokens to component inventory

- .circleci/config.yml
- package.json
- packages/action-menu/src/ActionMenu.ts
- packages/menu/src/Menu.ts
- packages/overlay/package.json
- packages/overlay/src/overlay-stack.ts
- packages/picker/src/Picker.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
- packages/split-button/stories/split-button.stories.ts
- packages/split-button/test/benchmark/basic-test.ts
- patches/@popperjs+core+2.11.0.patch
- test/benchmark/bench-runner.html
- test/benchmark/helpers.ts
- yarn.lock
- correct application of theme and remove body margin in benchmarking
- expand `<sp-split-button>` benchmark to include 5 open/close actions on one element rather than init on 100
- update `<sp-picker>` and derivatives to gather menu items on a document fragment rather than in the DOM before projecting into an overlay
- reorder and conditionalize work within the overlay process to reduce unneeded work
- update CSS to reduce paints when opening overlay
We get a small, but clear, perf benefit in our automated benchmarking. Locally, under stress, I'm seeing even better perf benefits to this change. On the order of 2 - 3 frames (32 - 48ms) during open or close actions, and I expect to see that further scale up as this is leveraged in busier and busier code paths.
- fixes #1910
Faster is …
> refactor(overlay): reduce paint/render work when opening a modal

- packages/textfield/src/Textfield.ts
Prevent Safari from placing the input carat before the initial hiragana character when IME opens to resolve the implied kanji.
The removed functionality was originally applied when we moved to WTR and started testing in Safari with local failures. No tests fail when removed, so it seems that somewhere in the dependency/browser change the issue in question has been resolved outside of our input.
I can't think of a way to test IME in an automated manner, and would take input in this area if anyone had ideas.
- fixes #2018
Internationalization
https://user-images.githubusercontent.com/1156657/148085390-ff9819ab-b993-4b04-bf2a-a05fb9af0539.mov
- …
> fix(textfield): prevent IME selection misalignment in Safari when using hiragana input modality

- packages/toast/src/Toast.ts
- packages/toast/stories/toast.stories.ts
- packages/toast/test/toast.test.ts
Reorder code path so that internal moves to `open=false` and external ones can be managed separately. This allows for the Toast to be delivered as a controlled element.
More flexible consumption in applications.
1. Go [here](https://toast-controlled--spectrum-web-components.netlify.app/components/toast/#example)
2. Put an event listed on the `close` event of an `sp-toast` element
3. Manual switch `open` to `false`
4. Notice that no `close` event is dispatched …
> refactor(toast): allow for using Toast in a controlled context

- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/src/overlay-trigger.css
We'd originally moved to wrapped slots in a number of places due to support with polyfills, but as we don't specifically support polyfilled delivery anymore we can move away from this practice, especially when there are bugs that come out of doing so.
As per https://bugs.chromium.org/p/chromium/issues/detail?id=1278446 the use of `display: contents` here seems to confusing the accessibility tree starting in Chrome 96, this removed the need for such usage by pushing the events down onto the `<slot>`.
Accessibility. Also running perf tests to see if this counts as more performant.
1. Go [here](https://a11y-overlay-trigger--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-group-tooltips--selects-single)
2. Interact the the buttons in the demo …
> fix(overlay): reduce DOM and use of "display: contents" for simplicity and accessibility

- .circleci/config.yml
- packages/number-field/src/NumberField.ts
- packages/number-field/src/number-field.css
- packages/number-field/src/spectrum-config.js
- packages/number-field/src/spectrum-number-field.css
- packages/number-field/stories/number-field.stories.ts
Correct style delivery and add VRT coverage to prevent regression.
Supports more complex color pickers.
1. Go [here](https://numberfield-quiet--spectrum-web-components.netlify.app/storybook/index.html?path=/story/number-field--quiet)
2. See that the bottom border is straight.
1. Go [here](https://numberfield-quiet--spectrum-web-components.netlify.app/storybook/index.html?path=/story/number-field--hide-stepper-quiet)
2. See that the bottom border is straight. …
> Make sure Numberfield quiet has "square" corners

- packages/color-slider/src/color-slider.css
- packages/slider/src/slider.css
Normalize touch interactions in Sliders between mobile Safari and Chrome.
Allow handle focus to be changes with multi-handle Sliders.
- fixes #2034
Mobile is all the rage...
1. Go [here](https://touch-action--spectrum-web-components.netlify.app/components/slider-handle/)
2. Turn on mobile emulation in Chrome DevTools 
3. See that both of the handles in the example slider are accessible via touch.
1. In Mobile Safari
2. Go [here](https://touch-action--spectrum-web-components.netlify.app/components/slider-handle/)
3. See that both of the handles in the example slider are accessible via touch.
-   [x] …
> fix: simplify touch-action application

- package.json
- packages/thumbnail/package.json
- packages/thumbnail/src/Thumbnail.ts
- packages/thumbnail/src/spectrum-config.js
- packages/thumbnail/src/spectrum-thumbnail.css
- packages/thumbnail/src/thumbnail.css
- yarn.lock
Upgrade Spectrum CSS dependency for Thumbnail to unblock https://github.com/adobe/spectrum-web-components/pull/2004#issuecomment-1005894971
> fix: use latest @spectrum-css/thumbnail with built in "cover" support

- packages/tabs/src/Tabs.ts
- packages/tabs/test/tabs.test.ts
A click inside sp-tabs throws if outside of a sp-tab.
- fixes #2000 
Bugfix
Manually
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md) …
> fix(tabs): error on click - undefined tab target

- packages/styles/scale-large.css
- packages/styles/scale-medium.css
- packages/styles/stories/styles.stories.ts
Use CSS Custom Property Name name that can be replaced by upstream tooling when ready without disrupting consumers.
> fix: use CSS Custom Property name supplied by Spectrum for dividers

- packages/overlay/src/OverlayTrigger.ts
- packages/overlay/test/overlay-lifecycle.test.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
- packages/shared/src/platform.ts
- packages/tooltip/src/Tooltip.ts
So, this ended up not being so much an action-button accessibility issue... Moreso an Overlay/Tooltip issue.
This PR fixes the following issues:
- Having a tooltip on a long-press button no longer forces the `aria-describedby` attribute to be reset or removed. Multiple descriptor attributes can be added. 
- Buttons with hold affordance/long press now alert users to the secondary action in the screen reader via an `aria-describedby` attribute programatically added in `OverlayTrigger.ts`. The text of the secondary action changes depending on whether the trigger has visible focus or not. 
fixes https://github.com/adobe/spectrum-web-components/issues/1418 
write later
Manually and with written tests in `overlay-trigger.test.js`
Manually with screenreader in storybook, and via written tests 
- …
> action button a11y

- projects/story-decorator/src/StoryDecorator.ts
I found a duplicate box-sizing property and this teensy PR removes that.
-
-   [x] _Open storybook_
1. Check for regressions in how components fit into the container
-   [N/A] I have …
> fix: remove duplicate box-sizing style from storybook-decorator

- packages/picker/src/Picker.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
Make sure `change` event in Picker bubbles and is composed like `change` events on a native `<select>` element.
- fixes #2002
- closes #2003 
Match native element patterns.
1. Go [here](https://picker-event--spectrum-web-components.netlify.app/components/picker/#sizes)
2. Add an event listener for the `change` event on an element ancestor of a Picker
3. Change the Picker and see the event bubble. …
> fix(picker): make "change" event bubbling and composed

- packages/accordion/test/accordion-item.test.ts
- packages/accordion/test/accordion.test.ts
- packages/action-group/test/action-group.test.ts
- packages/button/test/button.test.ts
- packages/card/test/card.test.ts
- packages/color-slider/test/color-slider.test.ts
- packages/color-wheel/test/color-wheel.test.ts
- packages/menu/test/menu.test.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
- packages/radio/test/radio-group.test.ts
- packages/search/test/search.test.ts
- packages/sidenav/test/sidenav.test.ts
- packages/split-view/test/split-view.test.ts
- packages/tabs/test/tabs.test.ts
- packages/tags/test/tag.test.ts
- packages/tags/test/tags.test.ts
- test/testing-helpers.ts
Found in #2017 that the non-factory approach to keyboard events in the test suite caused us to recycle events that might already have `defaultPrevented` confusing test results. This wraps all of our helpers in factory methods so we work with a new event each time.
CI ran.
-   [ ] I …
> test: use factory methods for keyboard events to prevent reusing cancelled events

- packages/number-field/src/NumberField.ts
- packages/number-field/stories/number-field.stories.ts
- packages/number-field/test/inputs.test.ts
- packages/textfield/src/Textfield.ts
Convert input of 2 byte characters to their single byte cousins as follows:
```
{
'１': '1',
'２': '2',
'３': '3',
'４': '4',
'５': '5',
'６': '6',
'７': '7',
'８': '8',
'９': '9',
'０': '0',
'、': ',',
'，': ',',
'。': '.',
'．': '.',
'％': '%',
'＋': '+',
ー: '-',
}
```
- fixes #1953
Easier use of Number Field with international keyboards, specifically Chinese, Japanese and Korean.
1. Go [here](https://two-byte-chars--spectrum-web-components.netlify.app/components/number-field/#example)
2. Paste `１、２３４，５６７。８９｀ into the Number Field
3. See that it is processed as `1,234,567.89`
1. Go [here](https://two-byte-chars--spectrum-web-components.netlify.app/components/number-field/#decimals)
2. Paste `＋９。８７` into the Number Field
3. See that it is processed as `+9.87` …
> fix(number-field): process 2 byte characters as their single byte cousins

- .circleci/config.yml
- packages/top-nav/src/top-nav-item.css
- packages/top-nav/stories/top-nav.stories.ts
Focus visible for Top Nav Items was overly reliant on the Focus Visible polyfill which is needed less and less. Update the CSS so that it can exist in DOM trees where the polyfill hasn't been registered and still delivery focus states.
- fixes #2071 
Accessibility
1. Go [here](https://top-nav--spectrum-web-components.netlify.app/storybook/?path=/story/top-nav--autofocus)
2. See that the shadow DOM wrapped Top Nav demo has an autofocus child with visible focus. …
> [Top Nav] Correct application of focus state

- packages/number-field/src/NumberField.ts
- packages/number-field/stories/number-field.stories.ts
- packages/number-field/test/number-field.test.ts
Validate `value` before dispatching `change` so that restraints like `min` and `max` are followed before announcing a new `value`.
Correctness.
1. Go [here](https://number-field-change--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--default)
2. Apply a value for `max` in the "Controls" panel
3. Switch to the "Actions" panel
4. Type a value larger than what you applied for `max`
5. Press `Enter`
6. See that the final `input` and the `change` event immediately there after are bound by the value you applied to `max`.
-   [ ] If my change …
> fix(number-field): validate value before dispatching "change" event

- package.json
- packages/popover/README.md
Correct relative link.
- fixes #2083
1. Go [here](https://popover-docs--spectrum-web-components.netlify.app/components/popover/)
2. Click the "Overlay system" link
3. See that you go to the Overlay component page.
- …
> docs(popover): correct link URL

- packages/tabs/src/Tabs.ts
- packages/tabs/test/tabs.test.ts
Without a test to confirm the `auto` functionality it regressed during the key handling update when we moved to the `RovingTabindex` controller. This adds it back and a test for the future.
- fixes #2095
Because we broke it.
1. Go [here](https://tabs-auto--spectrum-web-components.netlify.app/components/tabs/#sizes)
2. Click "Large"
3. See the content switch to "Large"
4. Press `ArrowLeft`
5. See the content switch to "Medium"
6. Etc. …
> fix(tabs): ensure that "auto" attribute is respected

- .circleci/config.yml
- package.json
- packages/textfield/src/Textfield.ts
- packages/textfield/src/textfield.css
- packages/textfield/stories/textarea.stories.ts
- packages/textfield/stories/textfield.stories.ts
- projects/story-decorator/src/StoryDecorator.ts
- prevent `<sp-textfield multiline grows>` with no `value` from collapsing
- ensure that `<sp-textfield multiline grows>` expands with newline white space
- ensure the the focus ring follow the actual `<textarea>` in `<sp-textfield multiline>`
- fixes #2107
- fixes #2108
1. Go [here](https://textfield-multiline--spectrum-web-components.netlify.app/storybook/?path=/story/textarea--quiet)
2. Make sure the focus state looks correct
1. Go [here](https://textfield-multiline--spectrum-web-components.netlify.app/storybook/?path=/story/textarea--grows-empty)
2. See that there's only one border
1. Go [here](https://textfield-multiline--spectrum-web-components.netlify.app/storybook/?path=/story/textarea--sized)
2. See that the …
> fix(textfield): correct "multiline" and "grows" delivery

- .circleci/config.yml
- packages/base/package.json
- packages/base/src/condition-attribute-with-id.ts
- packages/dialog/dialog-wrapper.md
- packages/dialog/src/Dialog.ts
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/dialog/test/benchmark/basic-test.ts
- packages/dialog/test/dialog-wrapper.test.ts
- packages/dialog/test/dialog.test.ts
- packages/help-text/src/HelpTextManager.ts
- packages/modal/src/modal.css
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/active-overlay.css
- packages/overlay/src/overlay-stack.ts
- packages/overlay/stories/overlay.stories.ts
- packages/shared/src/focusable.ts
- ensure the use of `role="dialog"` on the `<sp-dialog>` element
- relate the `[slot="heading"]` content to the `<sp-dialog>` via `aria-labelledby`
- when three or less elements are supplied to the default slot, related that content to the `<sp-dialog>` via `aria-describedby`
- allow `[autofocus]` content to receive focus when not sending focus to the `<sp-dialog>` itself
- fixes #1283
Content should inform screen readers of itself appropriately.
1. Turn on your screen reader
2. Go [here](https://a11y-dialog--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-wrapped--form)
3. Close the dialog.
4. Open the dialog.
5. See that the screen reader is directed to the "Street" input automatically
1. Turn on your screen reader
2. Go …
> 'sp-dialog': Accessibility Updates

- packages/overlay/src/ActiveOverlay.ts
Measure initial overlay data off screen such that even when resource constrained we can position the overlay without it appearing in an incorrect location during janked frames.
> fix(overlay): measure initial overlay data offscreen

- packages/tray/README.md
Wrap &lt;sp-tray&gt; usage with &lt;overlay-trigger&gt; so documentation content won't be blocked from start.
- fixes #2120 
Restores sp-tray doc page interactivity.
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] If my change required a change to the documentation, I …
> fix: blocked content on sp-tray doc page

- package.json
- packages/icons-ui/README.md
- packages/icons-workflow/README.md
- projects/documentation/package.json
- projects/documentation/rollup.config.js
- yarn.lock
Alias content into the docs build scope so dev time assets can be used there.
- fixes #2116
Try not to add to the public API?
1. Go [here](https://icons3--spectrum-web-components.netlify.app/components/icons-workflow/#find-an-icon)
2. See the icon search UI load.
1. Go [here](https://icons3--spectrum-web-components.netlify.app/components/icons-ui/#find-an-icon)
2. See the icon search UI load. …
> docs: use @swc-packages-internal alias to surface dev time assets in the docs build

- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/src/active-overlay.css
- move overlays onto the GPU and do some extra work to get overlays off the screen for the first measurement.
Some resource constrained contexts may place the overlay at 0, 0 for a visible number of frames, and then glitch while animating the overlay into place.
-   [x] refactor (new code that does the same thing but better) …
> refactor: position overlays on the GPU

- .circleci/config.yml
- packages/overlay/src/overlay-trigger.css
- packages/overlay/test/overlay-trigger-extended.test.ts
- packages/overlay/test/overlay-trigger-hover-click.test.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
- packages/shared/src/focus-visible.ts
- yarn.lock
- normalize the direct and indirect versions of Playwright to the latest version
- update VRTs for latest Chrome
- update tests for new browser versions
- Chrome complained about the styling/content availability in `overlay-trigger` with hover content, the CSS there has been updated
- remove duplicate `focus-visible` import
- refactor Picker test to reduce flakiness
Keeping up with the v100+ browsers.
Reducing flakiness in tests.
Prepare for changes in other branches.
1. Go [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/11248/workflows/9af7a905-493d-44cc-bb4c-050efe3b0eaa)
2. See that tests passed
1. Go [here](https://playwright--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--longpress)
2. …
> Use latest Playwright and latest test browsers.

- tools/grid/src/Grid.ts
- tools/grid/src/GridController.ts
- tools/grid/src/LitVirtualizer.ts
- tools/grid/test/grid.test.ts
Avoid registering `lit-virtualizer` in the global custom elements namespace.
Grid depends on `LitVirtualizer`, but not on `<lit-virtualizer>`. Since other components may use the virtualizer at different versions, let's avoid registering in the global namespace which can create collisions.
- Added unit tests
-   [X] …
> fix: avoid registering lit-virtualizer globally

- packages/radio/src/Radio.ts
- packages/radio/src/RadioGroup.ts
- packages/radio/test/radio-group.test.ts
Stop propagation of `sp-radio` "change" events at the `sp-radio-group` boundary.
Prevent "change" event when `sp-radio` is already checked.
- fixes #2199
- related #2094
- related #829
Make it easier to consume the `sp-radio-group` element in applications.
https://webcomponents.dev/edit/jVMbK8MN5IAJnJHsJ0pL/src/index.ts?p=stories has been added to the unit test suite.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main …
> fix: stop propagation of sp-radio "change" events at sp-radio-group boundary

- .circleci/config.yml
- packages/overlay/src/active-overlay.css
- packages/popover/src/popover.css
Allow popovers that are not restricted by the size of the browser to take up enough width or height to not truncate or line break their content in unexpected places.
- fixes #2150
Uniformity of delivery.
1. Go [here](https://popover-size--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
2. See that `Ft. Greene` and `S. Portland Ave` are displayed on single lines like the [VRT results](https://026cce46f8e420c49c8bcc48f25b51ca--spectrum-web-components.netlify.app/review/#SubmenuStories/submenu.png)
-   [ ] If my change required a change …
> Popover size

- packages/checkbox/test/checkbox.test.ts
- packages/menu/test/menu-selects.test.ts
- packages/menu/test/menu.test.ts
- packages/picker/test/picker-responsive.test.ts
- packages/picker/test/picker-sync.test.ts
- packages/picker/test/picker.test.ts
- packages/search/test/search.test.ts
- packages/shared/src/focus-visible.ts
- packages/shared/tsconfig.json
Test perf benefits of only loading the polyfill when needed.
- use dynamic import and capability test to prevent polyfill use in Chrome and Firefox
- ungated usage can cause edge case situations like in #2071 
Perf
1. Go [here](https://focus-visible--spectrum-web-components.netlify.app/)
2. Navigate the site with the keyboard and see that focus visible states are triggered. …
> feat: conditionally load focus-visible polyfill

- package.json
- projects/documentation/src/components/search-index.ts
- projects/documentation/src/components/side-nav-search.ts
Correct the applied layout of the search completion overlay.
Update the search index path to allow results in the main docs site.
- fixes #2215 
Things should be search able
Still works in development sites but the difference between spectrum-web-components.netlify.app and opensource.adobe.com/spectrum-web-components is difficult to fully test until in production.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTIN …
> docs: update docs search paths and layout

- packages/overlay/test/overlay-trigger-extended.test.ts
Skip the test for now... for the good of the game.
> test: xit test that no longer works as expected

- packages/menu/src/MenuItem.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/picker/src/Picker.ts
- packages/shared/src/reparent-children.ts
- packages/shared/test/reparent-children.test.ts
`reparentChildren()` can now receive a position argument (just like in insertAdjacentElement).
This is a non-breakable change, the default position if not specified is `beforeend` (append).
- fixes #2140  …
> feat: reparentChildren - insertAdjacentElement style API

- .circleci/config.yml
- RELEASE_PROCESS.md
- reduce CI time by building before the approval step
- prevent mismatch between docs and current `latest` by gating docs publication on a manual approval step
- fixes #1305
Easier to consume components when the documentation site is more tightly coupled to the published code.
Ran CI, and approved the publication: https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/11505/workflows/45e4e35b-1f8d-4e85-b600-a000d9338757
-   [ ] If my change required a change to the documentation, I have updated the documentation …
> ci: use approval workflow for docs publication

- .circleci/config.yml
- package.json
- packages/search/src/spectrum-config.js
- packages/search/src/spectrum-search.css
- packages/search/stories/search.stories.ts
- ensure CSS processing manages class conversion correctly to receive search specific textfield updates.
Who doesn't like rounded corners?
1. Go [here](https://ccx-search--spectrum-web-components.netlify.app/)
2. Switch to the "Express" theme
3. See the search field get fully rounded corners.
-   [x] I have added tests to …
> Correct "sp-search" delivery when "express"

- .circleci/config.yml
- packages/slider/src/Slider.ts
- packages/slider/stories/slider.stories.ts
Have the tick labels in a Slider count up from `min` rather than `0`.
- fixes #2246
Correctness.
1. Go [here](https://slider-tick-labels--spectrum-web-components.netlify.app/storybook/?path=/story/slider--tick-labels)
2. See that the tick labels count from 50 - 75 and not 1 - 25
-   [x] I have added tests to cover my …
> Slider tick labels

- .circleci/config.yml
> ci: only lint/analyze in webkit, which takes the least time to test

- package.json
- packages/action-group/src/ActionGroup.ts
- packages/action-group/test/action-group.test.ts
Allow `sp-action-group` to receive the value of `selected` more than once from the parent application context.
- fixes #2163
Empowers controlled components.
1. Go [here](https://action-group-selected--spectrum-web-components.netlify.app/components/action-group/#multiple)
2. Focus the `sp-action-group` element in the DevTools
3. Paste `$0.selected = ['Longer Button 2']` into the console
4. See the selection update correctly in the UI. …
> fix: ensure that "selected" can be set more than once from the outside

- packages/slider/src/Slider.ts
Prevent `slot="handle"` from triggering `no-unknown-slot` warnings in `lit-analyze
- fixes #2148
Easier consumptions of patterns with `lit-analyzer`
1. Go [here](https://slider-docs--spectrum-web-components.netlify.app/components/slider/api/#slots)
2. See the inclusion of the `handle` slot.
-   [x] docs …
> docs: include slot listing for "handle"

- projects/documentation/src/components/layout.css
- projects/documentation/src/components/layout.ts
Ensure that the docs site can use the various scales and color themes for the Spectrum Theme.
1. Go [here](https://docs-themes--spectrum-web-components.netlify.app/index.html)
2. Try the color themes and scales.
-   [x] docs
> docs: ensure presence of theme fragments

- package.json
- packages/slider/src/HandleController.ts
- packages/slider/src/Slider.ts
- packages/slider/test/slider.test.ts
Prevent further pointer events when the Slider moves to `disabled` while a pointer event is active.
- fixes #2268
1. Go [here](https://slider-disabled--spectrum-web-components.netlify.app/components/slider/)
2. Select a Slider element in DevTools
3. Run: `const test = $0; setTimeout(() => test.disabled = true, 3000);` in the Console.
4. Start dragging the Slider
5. See the drag interaction end after 3 seconds. …
> fix: prevent active pointer events when slider toggles to [disabled]

- packages/accordion/src/AccordionItem.ts
- packages/accordion/stories/accordion.stories.ts
- packages/accordion/test/accordion-item.test.ts
Prevent `Space` and `Enter` interactions in the Accordion Item content area from causing the Accordion Item to toggle.
- fixes #1816
- related to #2278 
Accessibility of the content.
-   [ ] _Test case 1_ **Updated**
1. Go [here](https://accordion-activation--spectrum-web-components.netlify.app/storybook/?path=/story/accordion--default)
2. Open the Accordion Item with the title "Heading 3"
3. Tab into the `<sp-link>` in the expanded content area
4. Use the `Space` key to no effect (or possibly page scroll depending on window size)
5. Use the `Enter` key to open the link in a new tab
6. Ensure neither interaction toggled the Accordion Item
- …
> fix: contain activation to header content

- packages/accordion/package.json
- packages/accordion/src/Accordion.ts
- packages/accordion/test/accordion.test.ts
- removed Roving Tab Index management of Accordion Items
- expanded testing of natural Tab Order access of Accordion Items
- fixes #2273
Appropriate accessibility models.
1. Go [here](https://accordion-keys--spectrum-web-components.netlify.app/components/accordion/#example)
2. Tab into the example.
3. See that you can only access Accordion Items via `Tab` and not `ArrowUp/Down` …
> fix: correctly apply tab order to Accordion Items

- packages/.eslintrc.json
- packages/accordion/src/Accordion.ts
- tools/.eslintrc.json
- tools/reactive-controllers/src/FocusGroup.ts
- tools/reactive-controllers/src/RovingTabindex.ts
Split up "Focus Group" and "Roving Tabindex" functionality to support a wider number of use cases.
Apply the "Focus Group" functionality to the Accordion pattern so that the Items in the Accordion can be accessed as expected.
- referencing https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html the Accordion Items are not navigable by ArrowUp/Down keys, but as per this conversation with @jnurthen https://github.com/adobe/spectrum-web-components/pull/2278#discussion_r868588706 maintaining the _initial_ (though not current) implementation of this pattern in SWC is acceptable.
- fixes #2273
Apply the correct accessibility model to Accordion Items and make leveraging the accessibility model elsewhere less complicated.
1. Go …
> refactor: separate Focus Group and Roving Tabindex into class extensions

- packages/toast/src/Toast.ts
- projects/documentation/content/getting-started.md
- correct link in Getting Started page
- add documentation for unexpected accessibility features in `<sp-toast>`
- refs #2291
- refs #351
Easier to get started.
1. Go [here](https://docs-updates--spectrum-web-components.netlify.app/getting-started/#what-you-can-do)
2. See that "Read about the full range of style customization provided by @spectrum-web-components/theme." links to the Theme page.
1. Go [here](https://docs-updates--spectrum-web-components.netlify.app/components/toast/api/#attributes-and-properties)
2. See that `toast` is documented
-   [x] Docs …
> docs: update docs content

- .circleci/config.yml
- packages/overlay/src/ActiveOverlay.ts
- packages/overlay/stories/overlay.stories.ts
- packages/overlay/test/overlay.test.ts
- packages/popover/src/popover.css
Allow content opened from a "virtual trigger" to "flip" on both axises when looking for a place to position itself.
- don't use `auto` because it's not predictable enough for closely related content like Pickers
- update `size` usage to always fallback to the initial size when measuring
- moves the Picker Menu location to above the Picker button in some Large VRTs due to their not being enough space below the picker for the content
- fixes #2198
1. Go [here](https://overlay-fallbacks--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--virtual-element)
2. Squeeze the preview window down to 400px wide or so
3. Try opening the "context menu" from various places on the screen.
- top left
- top right
- bottom left
- bottom right
4. See they the "context …
> Overlay fallbacks

- packages/button/test/button.test.ts
- packages/split-button/src/spectrum-config.js
- packages/theme/README.md
- projects/documentation/content/guides/adding-component.md
- projects/documentation/content/guides/spectrum-config.md
- projects/documentation/content/index.md
- scripts/process-spectrum-postcss-plugin.js
Remove usage of `cta` variant in favor of `accent` across docs and comments.
- fixes #2290
Clearer documentation.
-   [x] Documentation
> docs: cleanup usage of <sp-button variant="cta">

- .circleci/config.yml
- packages/badge/.npmignore
- packages/badge/README.md
- packages/badge/package.json
- packages/badge/sp-badge.ts
- packages/badge/src/Badge.ts
- packages/badge/src/badge.css
- packages/badge/src/index.ts
- packages/badge/src/spectrum-badge.css
- packages/badge/src/spectrum-config.js
- packages/badge/stories/badge.stories.ts
- packages/badge/test/badge.test.ts
- packages/badge/test/benchmark/basic-test.ts
- packages/badge/tsconfig.json
- packages/bundle/elements.ts
- packages/bundle/package.json
- packages/bundle/src/index.ts
- packages/bundle/tsconfig.json
- yarn.lock
Implements the [Badge](https://spectrum.adobe.com/page/badge/) component.
https://github.com/adobe/spectrum-web-components/issues/1643
Expanding component coverage
1. Go to [the preview storybook](https://hunterloftis-badge--spectrum-web-components.netlify.app/storybook/?path=/story/badge--default)
2. Check out the various examples of badge usage
3. Go to [the preview docs site](https://hunterloftis-badge--spectrum-web-components.netlify.app/components/badge/)
4. Check out the documentation
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, …
> feat: add badge component

- packages/badge/README.md
Was tempted to commit directly to main (any thoughts around that @Westbrook?)
> docs(badge): typo in readme

- packages/menu/src/MenuItem.ts
- packages/menu/src/menu-item.css
- packages/menu/test/submenu.test.ts
Disabled menu item should not open submenu.
@Westbrook 
There are some issues with the tests on Chrome,
I suspect the cleanup doesn't properly work because the html is reused (on the next two tests) in a buggy way (keeping the disabled attribute).
Moving the test to the end of list resolves the issue.
This doesn't happen on Firefox or WebKit, only on Chrome.
Did this happened before? I don't want to "solve" this just by changing the test position.
- #2218 
- …
> fix(menu): disabled menu-item should not open submenu

- packages/overlay/overlay-trigger.md
- packages/tray/README.md
- packages/tray/test/benchmark/basic-test.ts
- packages/underlay/README.md
Correct consumption of `<sp-dialog>` across documentation site.
- fixes #2303
1. Go [here](https://tray-docs--spectrum-web-components.netlify.app/components/tray/#dialog)
2. Click "toggle tray"
3. See that the dialog fills the width of the tray.
-   [x] Docs update
> docs: ensure that sp-dialog is given a valid "size" attribute

- package.json
- projects/documentation/src/components.ts
Lazily load the bundle package on component pages. Reduce blocking time by up to 50%:
Before: https://www.webpagetest.org/result/220601_AiDcCE_R4/
After: https://www.webpagetest.org/result/220601_AiDc98_R3/
1. Go [here](https://lazy-docs--spectrum-web-components.netlify.app/components/action-button/)
2. Confirm the pages loads the same as [this one](https://opensource.adobe.com/spectrum-web-components/components/action-button/) but faster...
-   [x] Optimization …
> docs: try lazy loading the non-page content

- .circleci/config.yml
- package.json
- packages/menu/stories/menu-group.stories.ts
- yarn.lock
Use the latest version of playwright
- get latest version of playwright browsers
- prep for https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/11955/workflows/a8656306-6d07-4a37-b4ad-ca4bcbf87c65 which sneaks the latest version of playwright into the project
- move away from `monotype` in the mixed menu group demo as it has some weird rendering issue and isn't part of our actual components at test time
1. Go [here](https://3f33f9f9425cdf8137e61ab507bcdd0f--spectrum-web-components.netlify.app/review/)
2. See what changes were accepted.
-   [x] …
> chore: use latest version of playwright

- tsconfig-all.json
- yarn.lock
Badge was left out of the paster `tsconfig.json` and didn't get built before publication last week. This fixes that so we can make a new release.
refs #2162 
1. checkout branch
2. `rm -rf packages`
3. `yarn`
4. see that `packages/badge/sp-badge.js` exists. …
> fix(badge): ensure built assets as publish time

- packages/badge/README.md
Add link for webcomponents.dev demo to README.md:
https://studio.webcomponents.dev/edit/qxPsOTrGAPB92LzPfk4P/src/index.ts?p=stories
- fixes #2319
1. Go [here](https://badge-demo--spectrum-web-components.netlify.app/components/badge/)
2. Click on "Try it on WebComponents.dev" link
3. See the demo
-   [x] Docs
> docs: add webcomponents.dev demo link

- packages/dialog/src/DialogWrapper.ts
- packages/dialog/test/dialog-wrapper.test.ts
Use a specific transition property to trigger the `close` event so that it doesn't trigger multiple times.
- fixes #2346
1. Go [here](https://dialog-close--spectrum-web-components.netlify.app/components/dialog-wrapper/#small)
2. Open a dialog
3. Bind an event lister to `close` with a console log
4. Close the dialog
5. See that it logs only once
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUT …
> fix: prevent Dialog Wrapper from dispatching two "close" events

- .circleci/config.yml
- packages/textfield/src/textfield.css
- projects/story-decorator/src/StoryDecorator.ts
HCM doesn't allow you to `caret-color: transparent`, which means that the blinking carat can cause issues in VRTs. This works around it by making all focused Text Fields appear without `forced-color-adjust` so that we can hide the caret as expected in that context. It's a bit of a hack, but it allows us to have stable VRTs in HCM and the values that go changed in that context are tested in non-focused Text Fields to balance it out.
1. Go [here](https://c2935d10de0a6e2731722869d4d51953--spectrum-web-components.netlify.app/review/#SearchStories/autofocus.png)
2. Review the contexts where the delivery of the Text Field is updated in the VRT pass.
- …
> Stabilize HCM VRT passes

- packages/action-group/package.json
- packages/action-group/src/ActionGroup.ts
- packages/menu/package.json
- packages/menu/src/MenuItem.ts
- packages/picker/test/index.ts
- packages/shared/package.json
- packages/shared/src/observe-slot-presence.ts
- packages/shared/src/observe-slot-text.ts
- packages/slider/package.json
- packages/slider/src/HandleController.ts
- packages/theme/src/Theme.ts
Update Menu Item to leverage a Mutation Observer as opposed to `slotchange` events when updating its content to work around https://github.com/lit/lit/issues/2629
- apply Mutation Observe with mutation controller
- update other usages of Mutation Observer to leverage mutation controller
- fixes #2158
Components should "just work ™️" regardless of the tools you leverage them in.
1. Go [here](https://picker-label--spectrum-web-components.netlify.app/components/picker/#matching-value)
2. Find the `sp-menu-item` element in the inspector with "Select inverse" as its text content
3. Select the *Text Node* that represents that content
4. In the console use `$0.textContent = 'Something else'` to update the active label of the Picker
5. See that the "label" is updated
6. Open …
> Ensure the Picker label is managed by its Menu Item children

- packages/menu/src/MenuItem.ts
- packages/menu/test/submenu.test.ts
- packages/overlay/src/overlay-events.ts
- packages/overlay/src/overlay-stack.ts
Submenus should be closed based off of any `pointerenter` event on Menu Items that are siblings to the root of the submenu regardless of whether that Menu Item has a submenu itself.
1. Go [here](https://close-overlays-by-root--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--submenu)
2. Once all three menus have opened, move you mouse into the Menu Item that says "Williamsburg"
3. See that the submenu related to the "Ft. Greene" Menu Item is closed.
-   [ ] If my change required a change to the documentation, I have updated the documentation …
> fix: ensure that entering an ancestor Menu Item without a submenu closes related submenus

- .circleci/config.yml
- packages/dialog/package.json
- packages/dialog/src/Dialog.ts
Update the close UI in `sp-dialog` to leverage am `sp-close-button` element instead of an `sp-action-button` with custom icon.
1. Go [here](https://42ba5b12c6c1ecbd84d280bc613b2aaa--spectrum-web-components.netlify.app/review/#DialogWrapperStories/wrapperDismissableUnderlayError.png)
2. See how this changed the delivery.
-   [x]  Refactor
-   [ ] I have added tests to cover my …
> Use Close Button in Dialog pattern

- packages/number-field/src/NumberField.ts
- packages/number-field/stories/number-field.stories.ts
This PR will explicitly set the focused NumberField `wheel` event handler as `passive`, since we do not want the browser to also scroll the page when changing the field value via mouse wheel.
- fixes #2323
With this change, we mark the wheel event handler as being explicitly not passive, as we are preventing the default behavior of the browser when the NumberField is active.
-   [ ] I have signed the [Adobe Open Source …
> fix(number-field): explicitly setting NumberField wheel event handler as not passive

- packages/slider/src/slider.css
Remove local CSS overrides.
- fixes #1527
1. VRTs exhibited no change in visual delivery.
> refactor: remove local work around for Slider positioning

- .circleci/config.yml
- packages/icons-ui/package.json
- packages/icons-workflow/package.json
- yarn.lock
Make sure the latest versions of icons like "Invite" are available in the library:
1. Go [here](https://icons--spectrum-web-components.netlify.app/storybook/?path=/story/icons-workflow--elements)
2. See that the "Invite" icon is available.
-   [ ] I have added …
> chore: use latest icon assets

- packages/action-menu/src/ActionMenu.ts
- packages/color-area/src/ColorArea.ts
- packages/number-field/src/NumberField.ts
- packages/overlay/src/ActiveOverlay.ts
- packages/picker/src/Picker.ts
- packages/radio/src/RadioGroup.ts
- packages/search/src/Search.ts
- packages/shared/src/observe-slot-presence.ts
- packages/shared/src/observe-slot-text.ts
- packages/slider/src/SliderHandle.ts
- packages/split-button/src/SplitButton.ts
- packages/split-view/src/SplitView.ts
- packages/tabs/src/Tabs.ts
- packages/textfield/src/Textfield.ts
- test/benchmark/helpers.ts
- yarn.lock
- general: clean up multiple `lit-html` usage in local tooling
- shared: move initial Observer Slot Text work into `update`, as a mixin having it there will ensure calls to `super` as the same is required by `LitElement`
- color-area: use private properties when validating state from form elements in the UI so there's not additional render required
- use `willUpdate`
- Tabs
- Active Overlay
- Split View
- Radio Group
- Number Field
- Search
- Update Benchmarking to register perf only once there are no additional renders queued
- use `update`
- Picker
- Action Menu
- Split Button
- Slider Handle
- Textfield
- Track changes in Observe Slot Presence
- refs #2257 
Clearing out upstream warnings make room for #2308 
1. Everything works as it did before... 😏 
-   [x] …
> Address various warnings raised in Lit Dev Mode.

- projects/documentation/content/_data/site.cjs
- projects/documentation/content/_includes/layout.njk
- projects/documentation/src/components/layout.ts
- projects/documentation/src/components/styles.css
Load the docs site at the "large" scale by default in "mobile" contexts.
- align more appropriately with Spectrum standards
- really remove the Service Worker during development
- correct a duplicated ID
- ensure reduced Cumulative Layout Shift in the updated delivery
-   [ ] I have …
> docs: deliver mobile docs as "large" scale by default

- .husky/pre-commit
Capture more information on staged files & run linting commands on them in a more targeted way. Ensure commands are run only if files are present in stage.
- Prevent stray *.css linting errors from being included if the PR in-question didn't touch the file.
- Auto-fix where possible and commit that update
-   [x] _Remove a copyright header from a *.js and *.css file_
1. Commit to the branch 
2. Check that auto-fix corrects the *.js and the *.css file in question
-   [x] If my change required a change to the documentation, I have …
> chore: focus pre-commit cmds on staged assets

- packages/theme/src/Theme.ts
- projects/documentation/scripts/component-template-parts.js
Expand JSDocs usage in `theme.ts` for better API table population in the docs site.
- refs #2291
Easier to get started with the API.
1. Go [here](https://theme-docs--spectrum-web-components.netlify.app/components/theme/api/)
2. See that there is more information than there way before.
Before:
After:
-   [x] Documentation
-   [x] All …
> docs: make Theme API table more useful

- packages/overlay/overlay-trigger.md
This PR fixes a typo in the documentation for overlay-trigger, specifically the import statement provided for statically importing transitive dependencies.
- 
Fixes incorrect documentation
Added the existing import statement to a project bundled with rollup: 
- the overaly did not work,
- saw the following error at build time
```bash
(!) Unresolved dependencies
@spectrum-web-components/overlay-trigger/sync/overlay-trigger.js 
```
Using the updated import statement, 
- the overlay trigger works 
- no complaints from rollup
-   [x] Chore (minor updates related to the tooling or …
> docs: fix overlay trigger static import statement

- .circleci/config.yml
- packages/slider/README.md
- packages/slider/src/HandleController.ts
- packages/slider/src/Slider.ts
- packages/slider/stories/slider.stories.ts
- packages/slider/test/slider-editable.test.ts
Add `quiet` and `indeterminate` attributes, for slider edit mode.
- fixes https://github.com/adobe/spectrum-web-components/issues/2399
Expose more properties already available for the numeric input, used when slider can be edited by user input.
1. Go here
2. Do this
1. Go here
2. Do this
-   [x] My code follows the code style of …
> fix(slider): add quiet and indeterminate

- packages/checkbox/src/CheckboxBase.ts
The change event for checkboxes doesn't include the `composed` property. I included it as mentioned here in this comment: https://github.com/adobe/spectrum-web-components/pull/2365#discussion_r902022875
Keeping things consistent across different components. 
Ran existing test suite to make sure they behave the same.  …
> fix(checkbox): add composed EventInit to CheckboxBase's change event

- packages/shared/src/observe-slot-presence.ts
- packages/shared/src/observe-slot-text.ts
Reduces multiple render passes in patterns leveraging the ObserverSlotPresence mixin, specifically `sp-dialog`.
Reduce multiple render passes in patterns leveraging the ObserveSlotText mixin, e.g. Action Button, Tab, Meter.
1. Run the test
2. See that the Lit Dev Mode warnings for these components are not triggered. …
> refactor: move update request to after active update

- packages/slider/src/HandleController.ts
Prevent requesting an update before the first update. Prevent Lit Dev Mode warnings.
1. Run the tests
2. See that the `sp-slider` doesn't generate warning from LIt.
-   [ ] I have reviewed at the Accessibility Practices for this …
> refactor(slider): prefent requesting another update until after the first update has been made

- packages/number-field/src/NumberField.ts
Leverage internal state rather than DOM state so we can validate before the first render and prevent multiple renders when the value needs to change due to constraints.
1. See that tests pass
1. Run tests
2. See that no Lit Dev Mode warnings are generated for `sp-number-field`
-   [x] All new …
> refactor(number-field): use internal state rather than DOM values for validation

- packages/card/src/Card.ts
- packages/checkbox/src/CheckboxBase.ts
- packages/checkbox/test/checkbox.test.ts
Events weren't cancellable, bubbling, OR composed by default!! So I changed all of that and added a test to make sure they're doing what they're supposed to do. 
-
Affects related components/components using checkbox
Wrote tests. 
1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/checkbox--default
2. Select the `<sp-checkbox>` in the console
3. Paste `$0.addEventListener('change', (event) => event.preventDefault());` into the console
4. Click the checkbox and see that the event is not prevented. 
1. Go [here](https://halsema-cancellable-checkbox--spectrum-web-components.netlify.app/storybook/?path=/story/checkbox--default)
2. Select the `<sp-checkbox>` in the console
3. Paste …
> fix(checkbox): allow events to be cancelled on CheckboxBase

- .circleci/config.yml
- .github/workflows/publish.yml
- RELEASE_PROCESS.md
- package.json
This PR creates a workflow_dispatch trigger for the site deploy commands. This allows the site to be deployed manually via the GitHub Actions UI.
CircleCI shows a failed status on most builds on the main branch because the approval to build the site is only "passed" on release branches.  This approach will clean up the status reporting for the main branch, making it easier to identify true failures.
-   [ ] _gh workflow run publish.yml --ref chore-ci-build-site-on-release_
- [docs](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-using-github-cli)
Note: Cannot be run from the UI until the workflow exists on main.  Once on main you can use the UI or use gh cli or trigger it using a REST API call.
-   [x] Chore (minor updates related …
> chore: create site-build UI in GitHub Actions; remove from CircleCI

- .github/workflows/publish.yml
Syntax error being thrown on the new publish workflow.
This repository uses conventional commit syntax …
> chore: repair quotes on publish workflow

- packages/dialog/src/Dialog.ts
- packages/dialog/test/dialog.test.ts
Enable template extensibility for the Dialog class by pulling out sections into separate rendering methods.
This will allow UEC to create different "flavors" of a Dialog by extending the class and customizing an individual section of the template.
-   [x] _Check dialog for regressions: should be no change_
-   [x] Add new tests.
-   [x] All new …
> fix: pull out rendering for Dialog into individual methods

- package.json
Adding an alias for the `yarn storybook` command: `yarn start`
A `start` command is a nice feature because it describes what the developer is doing rather than the tool they are using.  We are using storybook for viewing development but the task we are performing is development. Just a personal preference but hoping it makes it easier to standardize commands across projects when different development tools might be in use.
-   [x] _yarn start_
1. Calls & runs `yarn storybook`
-   [n/a] If my change required a change to the …
> chore: alias storybook command to 'start'

- package.json
- yarn.lock
Bump dependency resolution to _close_ to the latest version of Playwright. The newest version surfaces a weird Firefox issue that I don't even understand enough, yet, to open an issue on their side.
Trying to see if this helps stabilize the VRTs for the table work...
- refs #2365
1. CI passes
-   [x] Guess …
> chore: use latest Playwright dependency

- custom-elements-manifest.config.js
- package.json
- yarn.lock
Leverage a Custom Elements Manifest Analyzer plugin to ensure that the `.ts` source is listed as its `.js` in the delivered manifests.
- fixes #2104
1. run `yarn custom-element-json` locally
2. see that the output manifest in the package directories does not have `.ts` listing.
-   [ ] I have added tests to cover my …
> build: ensure CEM output features *.js files

- .circleci/config.yml
- packages/help-text/package.json
- packages/help-text/src/spectrum-help-text.css
- packages/styles/express/spectrum-scale-large.css
- packages/styles/express/spectrum-scale-medium.css
- packages/styles/spectrum-scale-large.css
- packages/styles/spectrum-scale-medium.css
- scripts/spectrum-tokens.js
- yarn.lock
Leverage Core Tokens in the Help Text pattern.
Uses `beta` release, hold for full release.
1. Go [here](https://2ca598f7cc125086fc950534fe9be893--spectrum-web-components.netlify.app/review/)
2. Review the changes.
> refactor(help-text): use core tokens

- scripts/spectrum-tokens.js
The Action Button usage of core tokens implied that there would be no longer a need for CSS Custom Properties with component names in them. The Radio Button usage disproved that. This prepares for Radio Button (which is on hold) and other patterns that may do this as well to apply Custom Properties with component names in the `tokens` directory.
1. See #2458 …
> fix: prepare for future core token consumption that leverages component names

- packages/styles/package.json
- packages/styles/tokens/dark-vars.css
- packages/styles/tokens/darkest-vars.css
- packages/styles/tokens/express/custom-large-vars.css
- packages/styles/tokens/express/custom-medium-vars.css
- packages/styles/tokens/express/custom-vars.css
- packages/styles/tokens/express/global-vars.css
- packages/styles/tokens/express/large-vars.css
- packages/styles/tokens/express/medium-vars.css
- packages/styles/tokens/global-vars.css
- packages/styles/tokens/large-vars.css
- packages/styles/tokens/light-vars.css
- packages/styles/tokens/medium-vars.css
- packages/styles/tokens/spectrum/custom-large-vars.css
- packages/styles/tokens/spectrum/custom-medium-vars.css
- packages/styles/tokens/spectrum/custom-vars.css
- packages/styles/tokens/spectrum/global-vars.css
- packages/styles/tokens/spectrum/large-vars.css
- packages/styles/tokens/spectrum/medium-vars.css
- projects/documentation/src/components/styles.css
- scripts/spectrum-tokens.js
Ensure that `:root` is available as a selector on all Core Tokens rules so that they can be used on the document as well as on an element's shadow root.
Leverage them at an updated Media Query in the documentation site.
1. Go [here](https://tokens-selectors--spectrum-web-components.netlify.app/)
2. See that the Action Button in the code sample doesn't have a white outline like [here](https://opensource.adobe.com/spectrum-web-components/index.html)
1. Go [here](https://tokens-selectors--spectrum-web-components.netlify.app/)
2. Resize only one side of the browser to less than 700px and ensure [this](https://opensource.adobe.com/spectrum-web-components/index.html) doesn't happen
Fail state: …
> fix: include the ":root" selector in tokens CSS for use in the docs site

- .circleci/config.yml
- packages/tabs/src/Tabs.ts
- packages/tabs/src/tabs.css
- packages/top-nav/src/TopNav.ts
Add a `tablist` part to the "tab list" container in the `<sp-tabs>` element.
Add this to the Custom Elements Manifest for future documentation and IED consumptions, but do not actively document this as we don't have a good path to documenting part _AND_ I'd like to keep parts sort of secret until they feel like a wholistic part of the library.
Comes with some slightly related updates to spacing, colors and WHCM delivery of the Tabs and Top Nav elements.
- fixes #2460
1. Go [here](https://tabs-list--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tabs--vertical-right)
2. Inspect the `<style>` tag in the story DOM
3. Add `sp-tabs::part(tablist) { background: red; }` to see that the part is available.
-   [x] New feature (non-breaking change which …
> fix(tabs): add "tablist" part to manage list styles

- packages/button/README.md
- projects/documentation/src/components/styles.css
Update and expand the Button API docs to feature the current API and all of it's capabilities.
- fixes #2462
Does not relate to #2289, that still requires additional work.
1. Go [here](https://button-docs--spectrum-web-components.netlify.app/components/button/#variants)
2. See documentation of `variant` and `treatment` attributes.
-   [x] Docs
-   [ ] I have added tests to cover …
> docs: ouline expanded Button API

- .circleci/config.yml
- packages/close-button/package.json
- packages/close-button/src/spectrum-close-button.css
- yarn.lock
Adopt Core Tokens based Spectrum CSS dependency for Close Button
Updated color delivery
1. Go [here](https://0c9ba506034bd6de4cc37917dd49adb4--spectrum-web-components.netlify.app/review/)
2. Review the diffs
1. CI Passes …
> feat(close-button): use core tokens

- .circleci/config.yml
- packages/action-menu/stories/action-menu.stories.ts
- packages/action-menu/test/action-menu.test.ts
- packages/picker/src/Picker.ts
- packages/picker/test/index.ts
New behavior: Omit `submenu` items from the `menuItems` list managed by `PickerBase`.
https://github.com/adobe/spectrum-web-components/issues/2480
A side-effect of the existing behavior (managing _all_ menu items) is that nested submenus have their selection states removed.
1. Go to [Storybook](https://62ec14b045349f19bd39b6b0--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--submenu)
2. Toggle the selections in the submenu
---
1. Regression test added to suite 
2. All existing tests pass …
> fix(action-menu): stop stripping selected state from submenu items

- .circleci/config.yml
Correct being on the wrong side of a rendering flake in the VRT system.
> ci: update golden image cache

- packages/overlay/README.md
Document an undocumented option that's necessary for overlays like [this](https://studio.webcomponents.dev/edit/MgVf7AvrGMoL7z2aeNhj/src/index.ts?p=stories).
-   [X] I have read the …
> docs(overlay): document notImmediatelyClosable

- packages/dialog/src/DialogWrapper.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
https://localhost:8000/?path=/story/dialog-wrapped--wrapper-dismissable-underlay-error This story would not reopen due to it having no previousElementSibling. Switched the order of the elements to fix. Also added JSDocs for `responsive` attribute.
Pointed out by SWC user in slack
1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/dialog-wrapped--wrapper-dismissable-underlay-error
2. Close the dialogue
3. See that it does not reopen when clicking "Toggle Dialog" button. Note console error.
1. Go here
2. Close dialogue
3. See that you can reopen dialogue with the button, unlike before.
-   [ ] New feature (non-breaking change which adds …
> docs(dialog): fix story and add doc for responsive attribute

- yarn.lock
The caniuse database has started throwing errors during builds in UEC so I thought I'd open this PR for SWC before you start seeing them too. …
> chore: update the caniuse database

- .circleci/config.yml
- packages/dialog/src/DialogWrapper.ts
The order of secondary and cancel button is wrong according to Spectrum spec.
Change the order of secondary and cancel button inside the render method.
fixes #2344
Manually tested. …
> fix(dialog): swap secondary and cancel button order

- packages/table/README.md
- packages/table/elements.ts
- packages/table/package.json
- packages/table/src/Table.ts
- packages/table/src/TableCheckboxCell.ts
- packages/table/src/TableHeadCell.ts
- packages/table/src/TableRow.ts
- packages/table/test/table-selects.test.ts
- packages/table/test/virtualized-table-selects.test.ts
- toggle selection on row clicks
- expose `elements.js` as an export
- expand docs
- bind the virtualized list in a way that doesn't create run away listeners
- test coverage and clean up post refactor
- refs #2456 
1. Go [here](https://table--spectrum-web-components.netlify.app/components/table/)
2. Read the docs
1. Go [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/12737/workflows/635f986d-8cd1-47d5-b47a-d9d58b38ea41)
2. See that the unit tests are passing
3. VRTs will come later
-   [x] Feature work
-   [x] If my change required a change to the documentation, I have …
> Table Phase 2 Additions

- .circleci/config.yml
- packages/dialog/src/DialogWrapper.ts
- packages/dialog/stories/dialog-wrapper.stories.ts
- packages/overlay/src/overlay-stack.ts
- packages/overlay/test/overlay-trigger-hover.test.ts
- packages/overlay/test/overlay-trigger-sync.test.ts
- packages/overlay/test/overlay-trigger.test.ts
- "hover" content doesn't take focus, it shouldn't move focus when closing
- returned focus shouldn't go to the "root" of a parent modal but to the "trigger" of the recently closed modal
- fixes #2483
1. Go [here](https://returns-focus--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-wrapped--tooltips)
2. Tab through the modal
3. See that the focus stays on the expected button …
> Update focus return from overlays to modal parents

- packages/action-button/src/ActionButton.ts
- packages/action-button/test/action-button.test.ts
- packages/overlay/test/overlay-trigger-longpress.test.ts
Context menu interaction no longer trigger the `longpress` event.
- fixes #2517
1. Added new unit test
1. Go [here](https://longpress-conextmenu--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--longpress)
2. Right click the Action Button, see that it doesn't open the `longpress` menu. …
> fix: prevent longpress when interacting with context menu

- tools/grid/src/Grid.ts
- tools/grid/src/GridController.ts
- tools/grid/src/grid.css
- tools/grid/test/grid.test.ts
While the Grid element needs to manage the Roving Tab Index of its children during Tab presses and `focus()` calls it shouldn't steal focus (particularly when scrolled to some degree) when clicked. Remove `touch-events` to prevent this. Force the Grid to be a shadow DOM rendering custom element so that it can accept style rules in an encapsulated manner.
- fixes #2501
1. Go [here](https://grid-pointer-focus--spectrum-web-components.netlify.app/storybook/?path=/story/grid--sized)
2. Scroll down a good amount
3. Click BETWEEN the card elements
4. See that focus IS NOT thrown to the first Card element
-   [x] My code follows …
> fix: prevent Grid clicks from throwing focus unexpectedly
